create or replace PROCEDURE SP_ERLR_EMPLOYEE_CASE_DEL
(
	I_HHSID IN VARCHAR2,
    I_CASEID IN NUMBER
)
IS
    V_CNT NUMBER;
BEGIN

    -- DELETE ONLY MANUALLY ENTERED CASE
    DELETE ERLR_EMPLOYEE_CASE
     WHERE HHSID = I_HHSID
       AND CASEID = I_CASEID
       AND M_DT IS NOT NULL; 
    
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/

GRANT EXECUTE ON HHS_CMS_HR.SP_ERLR_EMPLOYEE_CASE_DEL TO HHS_CMS_HR_RW_ROLE;
/
