 CREATE OR REPLACE PROCEDURE SP_UPDATE_INCENTIVES_SAM_TABLE
(
	I_PROCID            IN      NUMBER
)
IS
BEGIN
	IF I_PROCID IS NOT NULL AND I_PROCID > 0 THEN
		DELETE INCENTIVES_SAM WHERE PROC_ID = I_PROCID;
		INSERT INTO INCENTIVES_SAM (PROC_ID, COC_NAME, COC_EMAIL, COC_ID, COC_TITLE, INIT_SALARY_GRADE, INIT_SALARY_STEP, INIT_SALARY_SALARY_PER_ANNUM , INIT_SALARY_LOCALITY_PAY_SCALE
			, SUPPORT_SAM, RCMD_SALARY_GRADE, RCMD_SALARY_STEP, RCMD_SALARY_SALARY_PER_ANNUM, RCMD_SALARY_LOCALITY_PAY_SCALE
			, SELECTEE_SALARY_PER_ANNUM, SELECTEE_SALARY_TYPE, SELECTEE_BONUS, SELECTEE_BENEFITS, SELECTEE_TOTAL_COMPENSATION
			, SUP_DOC_REQ_DATE, SUP_DOC_RCV_DATE, JUSTIFICATION_SUPER_QUAL_DESC, JUSTIFICATION_QUAL_COMP_DESC
			, JUSTIFICATION_PAY_EQUITY_DESC, JUSTIFICATION_EXIST_PKG_DESC, JUSTIFICATION_EXPLAIN_CONSID
			, SELECT_MEET_ELIGIBILITY, SELECT_MEET_CRITERIA, SUPERIOR_QUAL_REASON, OTHER_FACTORS, SPL_AGENCY_NEED_RSN, SPL_AGENCY_NEED_RSN_ESS
			, QUAL_REAPPT, OTHER_EXCEPTS
			, BASIC_PAY_RATE_FACTOR1 , BASIC_PAY_RATE_FACTOR2 , BASIC_PAY_RATE_FACTOR3 , BASIC_PAY_RATE_FACTOR4 , BASIC_PAY_RATE_FACTOR5
			, BASIC_PAY_RATE_FACTOR6 , BASIC_PAY_RATE_FACTOR7 , BASIC_PAY_RATE_FACTOR8 , BASIC_PAY_RATE_FACTOR9 , BASIC_PAY_RATE_FACTOR10
			, OTHER_RLVNT_FACTOR, OTHER_REQ_JUST_APVD, OTHER_REQ_SUFF_INFO_PRVD
			, OTHER_REQ_INCEN_REQD, OTHER_REQ_DOC_PRVD, HRS_RVW_CERT, HRS_NOT_SPT_RSN, RVW_HRS, HRS_RVW_DATE
			, RCMD_GRADE, RCMD_STEP, RCMD_SALARY_PER_ANNUM, RCMD_LOCALITY_PAY_SCALE, RCMD_INC_DEC_AMOUNT, RCMD_PERC_DIFF
			, OHC_APPRO_REQ, RCMD_APPRO_OHC_NAME, RCMD_APPRO_OHC_EMAIL, RCMD_APPRO_OHC_ID
			, RVW_REMARKS, APPROVAL_SO_VALUE, APPROVAL_SO_ACTING, APPROVAL_SO, APPROVAL_SO_RESP_DATE
			, APPROVAL_DGHO_VALUE, APPROVAL_DGHO_ACTING, APPROVAL_DGHO, APPROVAL_DGHO_RESP_DATE, APPROVAL_TABG_VALUE, APPROVAL_TABG_ACTING, APPROVAL_TABG, APPROVAL_TABG_RESP_DATE
			, APPROVAL_OHC_VALUE, APPROVAL_OHC_ACTING, APPROVAL_OHC, APPROVAL_OHC_RESP_DATE, APPROVER_NOTES)
			SELECT PROC_ID, COC_NAME, COC_EMAIL, COC_ID, COC_TITLE, INIT_SALARY_GRADE, INIT_SALARY_STEP, INIT_SALARY_SALARY_PER_ANNUM , INIT_SALARY_LOCALITY_PAY_SCALE
			, SUPPORT_SAM, RCMD_SALARY_GRADE, RCMD_SALARY_STEP, RCMD_SALARY_SALARY_PER_ANNUM, RCMD_SALARY_LOCALITY_PAY_SCALE
			, SELECTEE_SALARY_PER_ANNUM, SELECTEE_SALARY_TYPE, SELECTEE_BONUS, SELECTEE_BENEFITS, SELECTEE_TOTAL_COMPENSATION
			, SUP_DOC_REQ_DATE, SUP_DOC_RCV_DATE, JUSTIFICATION_SUPER_QUAL_DESC, JUSTIFICATION_QUAL_COMP_DESC
			, JUSTIFICATION_PAY_EQUITY_DESC, JUSTIFICATION_EXIST_PKG_DESC, JUSTIFICATION_EXPLAIN_CONSID
			, SELECT_MEET_ELIGIBILITY, SELECT_MEET_CRITERIA, SUPERIOR_QUAL_REASON, OTHER_FACTORS, SPL_AGENCY_NEED_RSN, SPL_AGENCY_NEED_RSN_ESS
			, QUAL_REAPPT, OTHER_EXCEPTS
			, BASIC_PAY_RATE_FACTOR1 , BASIC_PAY_RATE_FACTOR2 , BASIC_PAY_RATE_FACTOR3 , BASIC_PAY_RATE_FACTOR4 , BASIC_PAY_RATE_FACTOR5
			, BASIC_PAY_RATE_FACTOR6 , BASIC_PAY_RATE_FACTOR7 , BASIC_PAY_RATE_FACTOR8 , BASIC_PAY_RATE_FACTOR9 , BASIC_PAY_RATE_FACTOR10
			, OTHER_RLVNT_FACTOR, OTHER_REQ_JUST_APVD, OTHER_REQ_SUFF_INFO_PRVD
			, OTHER_REQ_INCEN_REQD, OTHER_REQ_DOC_PRVD, HRS_RVW_CERT, HRS_NOT_SPT_RSN, RVW_HRS, HRS_RVW_DATE
			, RCMD_GRADE, RCMD_STEP, RCMD_SALARY_PER_ANNUM, RCMD_LOCALITY_PAY_SCALE, RCMD_INC_DEC_AMOUNT, RCMD_PERC_DIFF
			, OHC_APPRO_REQ, RCMD_APPRO_OHC_NAME, RCMD_APPRO_OHC_EMAIL, RCMD_APPRO_OHC_ID
			, RVW_REMARKS, APPROVAL_SO_VALUE, APPROVAL_SO_ACTING, APPROVAL_SO, APPROVAL_SO_RESP_DATE
			, APPROVAL_DGHO_VALUE, APPROVAL_DGHO_ACTING, APPROVAL_DGHO, APPROVAL_DGHO_RESP_DATE, APPROVAL_TABG_VALUE, APPROVAL_TABG_ACTING, APPROVAL_TABG, APPROVAL_TABG_RESP_DATE
			, APPROVAL_OHC_VALUE, APPROVAL_OHC_ACTING, APPROVAL_OHC, APPROVAL_OHC_RESP_DATE, APPROVER_NOTES
			FROM VW_INCENTIVES_SAM WHERE PROC_ID = I_PROCID;
	END IF;

	EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/
