CREATE OR REPLACE VIEW VW_ERLR_GEN
AS
SELECT
    EG.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = EG.GEN_PRIMARY_SPECIALIST AND ROWNUM = 1)  AS GEN_PRIMARY_SPECIALIST_NAME	
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = EG.GEN_SECONDARY_SPECIALIST AND ROWNUM = 1)  AS GEN_SECONDARY_SPECIALIST_NAME
	, EG.GEN_CUSTOMER_NAME
	, EG.GEN_CUSTOMER_PHONE
	, EG.GEN_CUSTOMER_ADMIN_CD
	, EG.GEN_CUSTOMER_ADMIN_CD_DESC
	, EG.GEN_EMPLOYEE_NAME
	, EG.GEN_EMPLOYEE_PHONE
	, EG.GEN_EMPLOYEE_ADMIN_CD
	, EG.GEN_EMPLOYEE_ADMIN_CD_DESC
	, FN_GET_2ND_SUB_ORG(EG.GEN_EMPLOYEE_ADMIN_CD) AS GEN_EMPLOYEE_2ND_SUB_ORG
	, EG.GEN_CASE_DESC
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = EG.GEN_CASE_STATUS AND ROWNUM = 1) AS GEN_CASE_STATUS
	, EG.GEN_CUST_INIT_CONTACT_DT
	, EG.GEN_PRIMARY_REP_AFFILIATION
	, EG.GEN_CMS_PRIMARY_REP_ID AS GEN_CMS_PRIMARY_REP_NAME
	, EG.GEN_CMS_PRIMARY_REP_PHONE
	, EG.GEN_NON_CMS_PRIMARY_FNAME
	, EG.GEN_NON_CMS_PRIMARY_MNAME
	, EG.GEN_NON_CMS_PRIMARY_LNAME
	, EG.GEN_NON_CMS_PRIMARY_EMAIL
	, EG.GEN_NON_CMS_PRIMARY_PHONE
	, EG.GEN_NON_CMS_PRIMARY_ORG
	, EG.GEN_NON_CMS_PRIMARY_ADDR
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = EG.GEN_CASE_TYPE AND ROWNUM = 1) AS GEN_CASE_TYPE
	, FN_GET_CASE_CATEGORY(EG.GEN_CASE_CATEGORY) AS GEN_CASE_CATEGORY
	, EG.GEN_INVESTIGATION
	, EG.GEN_INVESTIGATE_START_DT
	, EG.GEN_INVESTIGATE_END_DT
	, EG.GEN_STD_CONDUCT
	, GEN_STD_CONDUCT_TYPE
	, CC_FINAL_ACTION
	, EG.CC_CASE_COMPLETE_DT
	, (SELECT STATE FROM BIZFLOW.PROCS P WHERE P.PROCID = EC.PROCID) AS BF_PROCS_STATE
	, ETPH.THRD_PRTY_APPEAL_TYPE
FROM
	ERLR_GEN EG
    LEFT OUTER JOIN ERLR_CASE EC ON EG.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
	LEFT OUTER JOIN ERLR_3RDPARTY_HEAR ETPH ON EG.ERLR_CASE_NUMBER = ETPH.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_GRIEVANCE
AS
SELECT
    G.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , GI_TYPE
	, GI_NEGOTIATED_GRIEVANCE_TYPE
	, GI_TIMELY_FILING_2
	, GI_IND_MANAGER
	, GI_FILING_DT_2
	, GI_TIMELY_FILING
	, GI_FILING_DT
	, GI_IND_MEETING_DT
	, GI_IND_STEP_1_DECISION_DT
    , GI_IND_STEP_1_DEADLINE
    , GI_IND_STEP_1_EXT_DUE_DT
    , GI_IND_STEP_1_EXT_DUE_REASON
	, GI_IND_DECISION_ISSUE_DT
	, GI_STEP_2_REQUEST
	, GI_IND_STEP_2_MTG_DT
	, GI_IND_STEP_2_DECISION_DUE_DT
	, GI_IND_STEP_2_DCSN_ISSUE_DT
	, GI_IND_STEP_2_DEADLINE
	, GI_IND_EXT_2_EXT_DUE_DT
	, GI_IND_STEP_2_EXT_DUE_REASON
	, GI_IND_THIRD_PARTY_APPEAL_DT
	, GI_IND_THIRD_APPEAL_REQUEST	
    , GI_UM_GRIEVABILITY
	, GI_MEETING_DT
	, GI_GRIEVANCE_STATUS
	, GI_ARBITRATION_DEADLINE_DT
	, GI_ARBITRATION_REQUEST
	, GI_ADMIN_OFFCL_1
	, GI_ADMIN_STG_1_DECISION_DT
	, GI_ADMIN_STG_1_ISSUE_DT
	, GI_ADMIN_STG_2_RESP
	, GI_ADMIN_OFFCL_2
	, GI_ADMIN_STG_2_DECISION_DT
	, GI_ADMIN_STG_2_ISSUE_DT
FROM
	ERLR_GRIEVANCE G
    LEFT OUTER JOIN ERLR_CASE EC ON G.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_PROB_ACTION
AS
SELECT
    PA.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , PPA_ACTION_TYPE
	, PPA_TERMINATION_TYPE
	, PPA_TERM_PROP_ACTION_DT
	, PPA_TERM_ORAL_PREZ_REQUESTED
	, PPA_TERM_ORAL_PREZ_DT
	, PPA_TERM_WRITTEN_RESP
	, PPA_TERM_WRITTEN_RESP_DUE_DT
	, PPA_TERM_WRITTEN_RESP_DT
	, PPA_TERM_AGENCY_DECISION	
    , PPA_TERM_DECIDING_OFFCL_NAME
	, PPA_TERM_DECISION_ISSUED_DT
	, PPA_TERM_EFFECTIVE_DECISION_DT
	, PPA_PROB_TERM_DCSN_ISSUED_DT
	, PPA_PROBATION_CONDUCT
	, PPA_PROBATION_PERFORMANCE
	, PPA_APPEAL_GRIEVANCE_DEADLINE
	, PPA_EMP_APPEAL_DECISION
	, PPA_PROP_ACTION_ISSUED_DT
	, PPA_ORAL_PREZ_REQUESTED
	, PPA_ORAL_PREZ_DT
	, PPA_ORAL_RESPONSE_SUBMITTED
	, PPA_RESPONSE_DUE_DT
	, PPA_WRITTEN_RESPONSE_SBMT_DT
	, PPA_POS_TITLE
	, PPA_PPLAN
	, PPA_SERIES
	, PPA_CURRENT_INFO_GRADE
	, PPA_CURRENT_INFO_STEP
	, PPA_PROPOSED_POS_TITLE
	, PPA_PROPOSED_PPLAN
	, PPA_PROPOSED_SERIES
	, PPA_PROPOSED_INFO_GRADE
	, PPA_PROPOSED_INFO_STEP
	, PPA_FINAL_POS_TITLE
	, PPA_FINAL_PPLAN
	, PPA_FINAL_SERIES
	, PPA_FINAL_INFO_GRADE
	, PPA_FINAL_INFO_STEP
	, PPA_NOTICE_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_DECISION
	, PPA_DECIDING_OFFCL
	, PPA_DECISION_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_EFF_DT
	, PPA_NUMB_DAYS
	, PPA_EFFECTIVE_DT
	, PPA_CURRENT_ADMIN_CODE
	, PPA_RE_ASSIGNMENT_CURR_ORG
	, PPA_FINAL_ADMIN_CODE
	, PPA_FINAL_ADMIN_CODE_FINAL_ORG
FROM
	ERLR_PROB_ACTION PA
    LEFT OUTER JOIN ERLR_CASE EC ON PA.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_PERF_ISSUE
AS
SELECT
    PI.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_ACTION_TYPE AND ROWNUM = 1) AS PI_ACTION_TYPE
	, PI_NEXT_WGI_DUE_DT
	, PI_PERF_COUNSEL_ISSUE_DT
	, PI_CNSL_GRV_DECISION
	, PI_DMTN_PRPS_ACTN_ISSUE_DT
	, PI_DMTN_ORAL_PRSNT_REQ
	, PI_DMTN_ORAL_PRSNT_DT
	, PI_DMTN_WRTN_RESP_SBMT
	, PI_DMTN_WRTN_RESP_DUE_DT
	, PI_DMTN_WRTN_RESP_SBMT_DT
	, PI_DMTN_CUR_POS_TITLE
	, PI_DMTN_CUR_PAY_PLAN
	, PI_DMTN_CUR_JOB_SERIES
	, PI_DMTN_CUR_GRADE
	, PI_DMTN_CUR_STEP
	, PI_DMTN_PRPS_POS_TITLE
	, PI_DMTN_PRPS_PAY_PLAN
	, PI_DMTN_PRPS_JOB_SERIES
	, PI_DMTN_PRPS_GRADE
	, PI_DMTN_PRP_STEP
	, PI_DMTN_FIN_POS_TITLE
	, PI_DMTN_FIN_PAY_PLAN
	, PI_DMTN_FIN_JOB_SERIES
	, PI_DMTN_FIN_GRADE
	, PI_DMTN_FIN_STEP
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_ACTION_TYPE AND ROWNUM = 1) AS PI_DMTN_FIN_AGCY_DECISION
	, PI_DMTN_FIN_DECIDING_OFC
	, PI_DMTN_FIN_DECISION_ISSUE_DT
	, PI_DMTN_DECISION_EFF_DT
	, PI_DMTN_APPEAL_DECISION
	, PI_PIP_RSNBL_ACMDTN
	, PI_PIP_EMPL_SBMT_MEDDOC
	, PI_PIP_DOC_SBMT_FOH_RVW
	, PI_PIP_WGI_WTHLD
	, PI_PIP_WGI_RVW_DT
	, PI_PIP_MEDDOC_RVW_OUTCOME
	, PI_PIP_START_DT
	, PI_PIP_END_DT
	, PI_PIP_EXT_END_DT
	, PI_PIP_EXT_END_REASON
	, PI_PIP_EXT_END_NOTIFY_DT	
	, PI_PIP_ACTUAL_DT
	, PI_PIP_END_PRIOR_TO_PLAN
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_END_PRIOR_TO_PLAN_RSN AND ROWNUM = 1) AS PI_PIP_END_PRIOR_TO_PLAN_RSN
	, PI_PIP_SUCCESS_CMPLT
	, PI_PIP_PMAP_RTNG_SIGN_DT
	, PI_PIP_PMAP_RVW_SIGN_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_PRPS_ACTN AND ROWNUM = 1) AS PI_PIP_PRPS_ACTN
	, PI_PIP_PRPS_ISSUE_DT
	, PI_PIP_ORAL_PRSNT_REQ
	, PI_PIP_ORAL_PRSNT_DT
	, PI_PIP_WRTN_RESP_SBMT
	, PI_PIP_WRTN_RESP_DUE_DT
	, PI_PIP_WRTN_SBMT_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_FIN_AGCY_DECISION AND ROWNUM = 1) AS PI_PIP_FIN_AGCY_DECISION
	, PI_PIP_DECIDING_OFFICAL
	, PI_PIP_FIN_AGCY_DECISION_DT
	, PI_PIP_DECISION_ISSUE_DT
	, PI_PIP_EFF_ACTN_DT
	, PI_PIP_EMPL_GRIEVANCE
	, PI_PIP_APPEAL_DECISION
	, PI_REASGN_NOTICE_DT
	, PI_REASGN_EFF_DT
	, PI_REASGN_CUR_ADMIN_CD
	, PI_REASGN_CUR_ORG_NM
	, PI_REASGN_FIN_ADMIN_CD
	, PI_REASGN_FIN_ORG_NM
	, PI_RMV_PRPS_ACTN_ISSUE_DT
	, PI_RMV_EMPL_NOTC_LEV
	, PI_RMV_NOTC_LEV_START_DT
	, PI_RMV_NOTC_LEV_END_DT
	, PI_RMV_ORAL_PRSNT_REQ
	, PI_RMV_ORAL_PRSNT_DT
	, PI_RMV_WRTN_RESP_DUE_DT
	, PI_RMV_WRTN_RESP_SBMT_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_RMV_FIN_AGCY_DECISION AND ROWNUM = 1) AS PI_RMV_FIN_AGCY_DECISION
	, PI_RMV_FIN_DECIDING_OFC
	, PI_RMV_DECISION_ISSUE_DT
	, PI_RMV_EFF_DT
	, PI_RMV_NUM_DAYS
	, PI_RMV_APPEAL_DECISION
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_WRTN_NRTV_RVW_TYPE AND ROWNUM = 1) AS PI_WRTN_NRTV_RVW_TYPE
	, PI_WNR_SPCLST_RVW_CMPLT_DT
	, PI_WNR_MGR_RVW_RTNG_DT
	, PI_WNR_CRITICAL_ELM
	, PI_WNR_FIN_RATING
	, PI_WNR_RVW_OFC_CONCUR_DT
	, PI_WNR_WGI_WTHLD
	, PI_WNR_WGI_RVW_DT

FROM
	ERLR_PERF_ISSUE PI
    LEFT OUTER JOIN ERLR_CASE EC ON PI.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_CNDT_ISSUE
AS
SELECT
    CI.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , CI_ACTION_TYPE
	, CASE WHEN CI.CI_ADMIN_INVESTIGATORY_LEAVE = '1'  THEN 'Yes' ELSE 'No' END AS CI_ADMIN_INVESTIGATORY_LEAVE	
	, CASE WHEN CI.CI_ADMIN_NOTICE_LEAVE = '1'  THEN 'Yes' ELSE 'No' END AS CI_ADMIN_NOTICE_LEAVE
	, CI.CI_LEAVE_START_DT
	, CI.CI_LEAVE_END_DT
	, CI.CI_APPROVAL_NAME
	, CI.CI_LEAVE_START_DT_2
	, CI.CI_LEAVE_END_DT_2
	, CI.CI_APPROVAL_NAME_2
	, CI.CI_PROP_ACTION_ISSUED_DT
	, CI.CI_ORAL_PREZ_REQUESTED
	, CI.CI_ORAL_PREZ_DT
	, CI.CI_ORAL_RESPONSE_SUBMITTED
	, CI.CI_RESPONSE_DUE_DT
	, CI.CI_WRITTEN_RESPONSE_SBMT_DT
	, CI.CI_POS_TITLE
	, CI.CI_PPLAN
	, CI.CI_SERIES
	, CI.CI_CURRENT_INFO_GRADE
	, CI.CI_CURRENT_INFO_STEP
	, CI.CI_PROPOSED_POS_TITLE
	, CI.CI_PROPOSED_PPLAN
	, CI.CI_PROPOSED_SERIES
	, CI.CI_PROPOSED_INFO_GRADE
	, CI.CI_PROPOSED_INFO_STEP
	, CI.CI_FINAL_POS_TITLE
	, CI.CI_FINAL_PPLAN
	, CI.CI_FINAL_SERIES
	, CI.CI_FINAL_INFO_GRADE
	, CI.CI_FINAL_INFO_STEP
	, CI.CI_DEMO_FINAL_AGNCY_DCSN
	, CI.CI_DECIDING_OFFCL
	, CI.CI_DECISION_ISSUED_DT
	, CI.CI_DEMO_FINAL_AGENCY_EFF_DT
	, CI.CI_NUMB_DAYS
	, CI_COUNSEL_TYPE
	, CI.CI_COUNSEL_ISSUED_DT
	, CI.CI_SICK_LEAVE_ISSUED_DT
	, CI.CI_RESTRICTION_ISSED_DT	
	, CI.CI_SL_WARN_ISSUE
	, CI.CI_NOTICE_ISSUED_DT
	, CI.CI_EFFECTIVE_DT
	, CI.CI_CURRENT_ADMIN_CODE
	, CI.CI_RE_ASSIGNMENT_CURR_ORG
	, CI.CI_FINAL_ADMIN_CODE
	, CI.CI_RE_ASSIGNMENT_FINAL_ORG
	, CI.CI_REMOVAL_PROP_ACTION_DT
	, CI.CI_EMP_NOTICE_LEAVE_PLACED
	, CI.CI_REMOVAL_NOTICE_START_DT
	, CI.CI_REMOVAL_NOTICE_END_DT
	, CI.CI_RMVL_ORAL_PREZ_RQSTED
	, CI.CI_REMOVAL_ORAL_PREZ_DT
	, CI.CI_RMVL_WRTN_RESPONSE
	, CI.CI_WRITTEN_RESPONSE_DUE_DT
	, CI.CI_WRITTEN_SUBMITTED_DT
	, CI_RMVL_FINAL_AGNCY_DCSN
	, CI.CI_DECIDING_OFFCL_NAME
	, CI.CI_RMVL_DATE_DCSN_ISSUED
	, CI.CI_REMOVAL_EFFECTIVE_DT
	, CI.CI_RMVL_NUMB_DAYS
	, CI_SUSPENTION_TYPE
	, CI.CI_SUSP_PROP_ACTION_DT
	, CI.CI_SUSP_ORAL_PREZ_REQUESTED
	, CI.CI_SUSP_ORAL_PREZ_DT
	, CI.CI_SUSP_WRITTEN_RESP
	, CI.CI_SUSP_WRITTEN_RESP_DUE_DT
	, CI.CI_SUSP_WRITTEN_RESP_DT
	, CI_SUSP_FINAL_AGNCY_DCSN
	, CI.CI_SUSP_DECIDING_OFFCL_NAME
	, CI.CI_SUSP_DECISION_ISSUED_DT
	, CI.CI_SUSP_EFFECTIVE_DECISION_DT
	, CI.CI_SUS_NUMB_DAYS
	, CI.CI_REPRIMAND_ISSUE_DT
	, CI.CI_EMP_APPEAL_DECISION
FROM
	ERLR_CNDT_ISSUE CI
    LEFT OUTER JOIN ERLR_CASE EC ON CI.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/