--------------------------------------------------------
--  DDL for View VW_LOOKUP
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HHS_CMS_HR"."VW_LOOKUP" AS 
  SELECT 
   TBL_ID ID
   , TBL_PARENT_ID PARENTID
   , TBL_LTYPE LTYPE
   , TBL_NAME NAME
   , TBL_LABEL LABEL
   , TBL_ACTIVE ACTIVE
   , TBL_DISP_ORDER DISPORDER
   , TBL_CATEGORY CATEGORY
FROM HHS_CMS_HR.TBL_LOOKUP 
ORDER BY TBL_PARENT_ID, TBL_LTYPE, DISPORDER, TBL_LABEL, TBL_NAME
;

GRANT SELECT ON HHS_CMS_HR.VW_LOOKUP TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_LOOKUP TO HHS_CMS_HR_DEV_ROLE;
