ALTER TABLE
    ERLR_GEN
MODIFY 
(    
   GEN_CUSTOMER_ADMIN_CD  NVARCHAR2(30),   
   GEN_CUSTOMER_ADMIN_CD_DESC	 NVARCHAR2(255),
   GEN_EMPLOYEE_ADMIN_CD NVARCHAR2(30),   
   GEN_EMPLOYEE_ADMIN_CD_DESC	 NVARCHAR2(255)
);

COMMIT;