--------------------------------------------------------
--  DDL for altering the tables INCENTIVES_LE
--------------------------------------------------------
ALTER TABLE INCENTIVES_LE ADD (
	JUSTIFICATION_VER	           NUMBER(10) DEFAULT 0,
	JUSTIFICATION_CRT_NAME         VARCHAR2(100),
	JUSTIFICATION_CRT_ID           VARCHAR2(10),
	JUSTIFICATION_CRT_DATE         VARCHAR2(20),
	JUSTIFICATION_LASTMOD_NAME     VARCHAR2(100),
	JUSTIFICATION_LASTMOD_ID       VARCHAR2(10),
	JUSTIFICATION_LASTMOD_DATE     VARCHAR2(20),
	JUSTIFICATION_MOD_REASON       VARCHAR2(100) NULL,
	JUSTIFICATION_MOD_SUMMARY      VARCHAR2(500) NULL,
	JUSTIFICATION_MODIFIER_NAME    VARCHAR2(100) NULL,
	JUSTIFICATION_MODIFIER_ID      VARCHAR2(10) NULL,
	JUSTIFICATION_MODIFIED_DATE    VARCHAR2(20) NULL
);
/


