Update ERLR_GEN SET GEN_CASE_STATUS = null;

ALTER TABLE 
   ERLR_GEN
MODIFY 
(    
   GEN_CASE_STATUS  NVARCHAR2(200)   
);

COMMENT ON COLUMN ERLR_GEN.GEN_CASE_STATUS IS 'Case status';

Update ERLR_CASE SET ERLR_CASE_STATUS_ID = null;

ALTER TABLE 
   ERLR_CASE
MODIFY 
(    
   ERLR_CASE_STATUS_ID  NVARCHAR2(200)   
);

COMMIT;