UPDATE ERLR_EMPLOYEE_CASE C
   SET (EMP_FIRST_NAME, EMP_LAST_NAME) = ( 
        SELECT FIRST_NAME, LAST_NAME 
        FROM HHS_HR.EMPLOYEE_LOOKUP           
        WHERE HHSID = (SELECT XMLQUERY('/formData/items/item[id="GEN_EMPLOYEE_ID"]/value/text()' PASSING FIELD_DATA RETURNING CONTENT).GETSTRINGVAL() 
          FROM TBL_FORM_DTL F JOIN BIZFLOW.RLVNTDATA P ON F.PROCID = P.PROCID AND P.RLVNTDATANAME='caseNumber'
         WHERE P.VALUE = TO_CHAR(C.CASEID)));
/
