CREATE OR REPLACE VIEW VW_ERLR_CNDT_ISSUE
AS
SELECT
    CI.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , CI_ACTION_TYPE
	, CASE WHEN CI.CI_ADMIN_INVESTIGATORY_LEAVE = '1'  THEN 'Yes' ELSE 'No' END AS CI_ADMIN_INVESTIGATORY_LEAVE	
	, CASE WHEN CI.CI_ADMIN_NOTICE_LEAVE = '1'  THEN 'Yes' ELSE 'No' END AS CI_ADMIN_NOTICE_LEAVE
	, CI.CI_LEAVE_START_DT
	, CI.CI_LEAVE_END_DT
	, CI.CI_APPROVAL_NAME
	, CI.CI_LEAVE_START_DT_2
	, CI.CI_LEAVE_END_DT_2
	, CI.CI_APPROVAL_NAME_2
	, CI.CI_PROP_ACTION_ISSUED_DT
	, CI.CI_ORAL_PREZ_REQUESTED
	, CI.CI_ORAL_PREZ_DT
	, CI.CI_ORAL_RESPONSE_SUBMITTED
	, CI.CI_RESPONSE_DUE_DT
	, CI.CI_WRITTEN_RESPONSE_SBMT_DT
	, CI.CI_POS_TITLE
	, CI.CI_PPLAN
	, CI.CI_SERIES
	, CI.CI_CURRENT_INFO_GRADE
	, CI.CI_CURRENT_INFO_STEP
	, CI.CI_PROPOSED_POS_TITLE
	, CI.CI_PROPOSED_PPLAN
	, CI.CI_PROPOSED_SERIES
	, CI.CI_PROPOSED_INFO_GRADE
	, CI.CI_PROPOSED_INFO_STEP
	, CI.CI_FINAL_POS_TITLE
	, CI.CI_FINAL_PPLAN
	, CI.CI_FINAL_SERIES
	, CI.CI_FINAL_INFO_GRADE
	, CI.CI_FINAL_INFO_STEP
	, CI.CI_DEMO_FINAL_AGNCY_DCSN
	, CI.CI_DECIDING_OFFCL
	, CI.CI_DECISION_ISSUED_DT
	, CI.CI_DEMO_FINAL_AGENCY_EFF_DT
	, CI.CI_NUMB_DAYS
	, CI_COUNSEL_TYPE
	, CI.CI_COUNSEL_ISSUED_DT
	, CI.CI_SICK_LEAVE_ISSUED_DT
	, CI.CI_RESTRICTION_ISSED_DT	
	, CI.CI_SL_WARN_ISSUE
	, CI.CI_NOTICE_ISSUED_DT
	, CI.CI_EFFECTIVE_DT
	, CI.CI_CURRENT_ADMIN_CODE
	, CI.CI_RE_ASSIGNMENT_CURR_ORG
	, CI.CI_FINAL_ADMIN_CODE
	, CI.CI_RE_ASSIGNMENT_FINAL_ORG
	, CI.CI_REMOVAL_PROP_ACTION_DT
	, CI.CI_EMP_NOTICE_LEAVE_PLACED
	, CI.CI_REMOVAL_NOTICE_START_DT
	, CI.CI_REMOVAL_NOTICE_END_DT
	, CI.CI_RMVL_ORAL_PREZ_RQSTED
	, CI.CI_REMOVAL_ORAL_PREZ_DT
	, CI.CI_RMVL_WRTN_RESPONSE
	, CI.CI_WRITTEN_RESPONSE_DUE_DT
	, CI.CI_WRITTEN_SUBMITTED_DT
	, CI_RMVL_FINAL_AGNCY_DCSN
	, CI.CI_DECIDING_OFFCL_NAME
	, CI.CI_RMVL_DATE_DCSN_ISSUED
	, CI.CI_REMOVAL_EFFECTIVE_DT
	, CI.CI_RMVL_NUMB_DAYS
	, CI_SUSPENTION_TYPE
	, CI.CI_SUSP_PROP_ACTION_DT
	, CI.CI_SUSP_ORAL_PREZ_REQUESTED
	, CI.CI_SUSP_ORAL_PREZ_DT
	, CI.CI_SUSP_WRITTEN_RESP
	, CI.CI_SUSP_WRITTEN_RESP_DUE_DT
	, CI.CI_SUSP_WRITTEN_RESP_DT
	, CI_SUSP_FINAL_AGNCY_DCSN
	, CI.CI_SUSP_DECIDING_OFFCL_NAME
	, CI.CI_SUSP_DECISION_ISSUED_DT
	, CI.CI_SUSP_EFFECTIVE_DECISION_DT
	, CI.CI_SUS_NUMB_DAYS
	, CI.CI_REPRIMAND_ISSUE_DT
	, CI.CI_EMP_APPEAL_DECISION
FROM
	ERLR_CNDT_ISSUE CI
    LEFT OUTER JOIN ERLR_CASE EC ON CI.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_PERF_ISSUE
AS
SELECT
    PI.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_ACTION_TYPE AND ROWNUM = 1) AS PI_ACTION_TYPE
	, PI_NEXT_WGI_DUE_DT
	, PI_PERF_COUNSEL_ISSUE_DT
	, PI_CNSL_GRV_DECISION
	, PI_DMTN_PRPS_ACTN_ISSUE_DT
	, PI_DMTN_ORAL_PRSNT_REQ
	, PI_DMTN_ORAL_PRSNT_DT
	, PI_DMTN_WRTN_RESP_SBMT
	, PI_DMTN_WRTN_RESP_DUE_DT
	, PI_DMTN_WRTN_RESP_SBMT_DT
	, PI_DMTN_CUR_POS_TITLE
	, PI_DMTN_CUR_PAY_PLAN
	, PI_DMTN_CUR_JOB_SERIES
	, PI_DMTN_CUR_GRADE
	, PI_DMTN_CUR_STEP
	, PI_DMTN_PRPS_POS_TITLE
	, PI_DMTN_PRPS_PAY_PLAN
	, PI_DMTN_PRPS_JOB_SERIES
	, PI_DMTN_PRPS_GRADE
	, PI_DMTN_PRP_STEP
	, PI_DMTN_FIN_POS_TITLE
	, PI_DMTN_FIN_PAY_PLAN
	, PI_DMTN_FIN_JOB_SERIES
	, PI_DMTN_FIN_GRADE
	, PI_DMTN_FIN_STEP
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_ACTION_TYPE AND ROWNUM = 1) AS PI_DMTN_FIN_AGCY_DECISION
	, PI_DMTN_FIN_DECIDING_OFC
	, PI_DMTN_FIN_DECISION_ISSUE_DT
	, PI_DMTN_DECISION_EFF_DT
	, PI_DMTN_APPEAL_DECISION
	, PI_PIP_RSNBL_ACMDTN
	, PI_PIP_EMPL_SBMT_MEDDOC
	, PI_PIP_DOC_SBMT_FOH_RVW
	, PI_PIP_WGI_WTHLD
	, PI_PIP_WGI_RVW_DT
	, PI_PIP_MEDDOC_RVW_OUTCOME
	, PI_PIP_START_DT
	, PI_PIP_END_DT
	, PI_PIP_EXT_END_DT
	, PI_PIP_EXT_END_REASON
	, PI_PIP_EXT_END_NOTIFY_DT	
	, PI_PIP_ACTUAL_DT
	, PI_PIP_END_PRIOR_TO_PLAN
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_END_PRIOR_TO_PLAN_RSN AND ROWNUM = 1) AS PI_PIP_END_PRIOR_TO_PLAN_RSN
	, PI_PIP_SUCCESS_CMPLT
	, PI_PIP_PMAP_RTNG_SIGN_DT
	, PI_PIP_PMAP_RVW_SIGN_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_PRPS_ACTN AND ROWNUM = 1) AS PI_PIP_PRPS_ACTN
	, PI_PIP_PRPS_ISSUE_DT
	, PI_PIP_ORAL_PRSNT_REQ
	, PI_PIP_ORAL_PRSNT_DT
	, PI_PIP_WRTN_RESP_SBMT
	, PI_PIP_WRTN_RESP_DUE_DT
	, PI_PIP_WRTN_SBMT_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_PIP_FIN_AGCY_DECISION AND ROWNUM = 1) AS PI_PIP_FIN_AGCY_DECISION
	, PI_PIP_DECIDING_OFFICAL
	, PI_PIP_FIN_AGCY_DECISION_DT
	, PI_PIP_DECISION_ISSUE_DT
	, PI_PIP_EFF_ACTN_DT
	, PI_PIP_EMPL_GRIEVANCE
	, PI_PIP_APPEAL_DECISION
	, PI_REASGN_NOTICE_DT
	, PI_REASGN_EFF_DT
	, PI_REASGN_CUR_ADMIN_CD
	, PI_REASGN_CUR_ORG_NM
	, PI_REASGN_FIN_ADMIN_CD
	, PI_REASGN_FIN_ORG_NM
	, PI_RMV_PRPS_ACTN_ISSUE_DT
	, PI_RMV_EMPL_NOTC_LEV
	, PI_RMV_NOTC_LEV_START_DT
	, PI_RMV_NOTC_LEV_END_DT
	, PI_RMV_ORAL_PRSNT_REQ
	, PI_RMV_ORAL_PRSNT_DT
	, PI_RMV_WRTN_RESP_DUE_DT
	, PI_RMV_WRTN_RESP_SBMT_DT
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_RMV_FIN_AGCY_DECISION AND ROWNUM = 1) AS PI_RMV_FIN_AGCY_DECISION
	, PI_RMV_FIN_DECIDING_OFC
	, PI_RMV_DECISION_ISSUE_DT
	, PI_RMV_EFF_DT
	, PI_RMV_NUM_DAYS
	, PI_RMV_APPEAL_DECISION
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = PI_WRTN_NRTV_RVW_TYPE AND ROWNUM = 1) AS PI_WRTN_NRTV_RVW_TYPE
	, PI_WNR_SPCLST_RVW_CMPLT_DT
	, PI_WNR_MGR_RVW_RTNG_DT
	, PI_WNR_CRITICAL_ELM
	, PI_WNR_FIN_RATING
	, PI_WNR_RVW_OFC_CONCUR_DT
	, PI_WNR_WGI_WTHLD
	, PI_WNR_WGI_RVW_DT

FROM
	ERLR_PERF_ISSUE PI
    LEFT OUTER JOIN ERLR_CASE EC ON PI.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_3RDPARTY_HEAR
AS
SELECT
    TPH.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , THRD_PRTY_APPEAL_TYPE
	, THRD_PRTY_APPEAL_FILE_DT
	, THRD_PRTY_ASSISTANCE_REQ_DT
	, THRD_PRTY_HEARING_TIMING
	, THRD_PRTY_HEARING_REQUESTED
	, THRD_PRTY_STEP_DECISION_DT
	, THRD_PRTY_ARBITRATION_INVOKED
	, THRD_PRTY_ARBIT_LNM_3
	, THRD_PRTY_ARBIT_FNM_3
	, THRD_PRTY_ARBIT_MNM_3
	, THRD_PRTY_ARBIT_EMAIL_3
	, THRD_ERLR_ARBIT_PHONE_NUM_3
	, THRD_PRTY_ARBIT_ORG_AFFIL_3
	, THRD_PRTY_ARBIT_MAILING_ADDR_3
	, THRD_PRTY_PREHEARING_DT_2
	, THRD_PRTY_HEARING_DT_2
	, THRD_PRTY_POSTHEAR_BRIEF_DUE_2
	, THRD_PRTY_FNL_ARBIT_DCSN_DT_2
	, THRD_PRTY_EXCEPTION_FILED_2
	, THRD_PRTY_EXCEPTION_FILE_DT_2
	, THRD_PRTY_RSPS_TO_EXCPT_DUE_2
	, THRD_PRTY_FNL_FLRA_DCSN_DT_2
	, THRD_PRTY_ARBIT_LNM
	, THRD_PRTY_ARBIT_FNM
	, THRD_PRTY_ARBIT_MNM
	, THRD_PRTY_ARBIT_EMAIL
	, THRD_ERLR_ARBIT_PHONE_NUM
	, THRD_PRTY_ARBIT_ORG_AFFIL
	, THRD_PRTY_ARBIT_MAILING_ADDR
	, THRD_PRTY_PREHEARING_DT
	, THRD_PRTY_HEARING_DT
	, THRD_PRTY_POSTHEAR_BRIEF_DUE
	, THRD_PRTY_FNL_ARBIT_DCSN_DT
	, THRD_PRTY_EXCEPTION_FILED
	, THRD_PRTY_EXCEPTION_FILE_DT
	, THRD_PRTY_RSPS_TO_EXCPT_DUE
	, THRD_PRTY_FNL_FLRA_DCSN_DT
	, THRD_PRTY_ARBIT_LNM_4
	, THRD_PRTY_ARBIT_FNM_4
	, THRD_PRTY_ARBIT_MNM_4
	, THRD_PRTY_ARBIT_EMAIL_4
	, THRD_ERLR_ARBIT_PHONE_NUM_4
	, THRD_PRTY_ARBIT_ORG_AFFIL_4
	, THRD_PRTY_ARBIT_MAILING_ADDR_4
	, THRD_PRTY_DT_STLMNT_DSCUSN
	, THRD_PRTY_DT_PREHEAR_DSCLS
	, THRD_PRTY_DT_AGNCY_RSP_DUE
	, THRD_PRTY_PREHEARING_DT_MSPB
	, THRD_PRTY_WAS_DSCVRY_INIT
	, THRD_PRTY_DT_DISCOVERY_DUE
	, THRD_PRTY_HEARING_DT_MSPB
	, THRD_PRTY_INIT_DCSN_DT_MSPB
	, THRD_PRTY_WAS_PETI_FILED_MSPB
	, THRD_PRTY_PETITION_RV_DT
	, THRD_PRTY_FNL_BRD_DCSN_DT_MSPB
	, THRD_PRTY_DT_STLMNT_DSCUSN_2
	, THRD_PRTY_DT_PREHEAR_DSCLS_2
	, THRD_PRTY_PREHEARING_CONF
	, THRD_PRTY_HEARING_DT_FLRA
	, THRD_PRTY_DECISION_DT_FLRA
	, THRD_PRTY_TIMELY_REQ
    , THRD_PRTY_PROC_ORDER
	, THRD_PRTY_PANEL_MEMBER_LNAME
	, THRD_PRTY_PANEL_MEMBER_FNAME
	, THRD_PRTY_PANEL_MEMBER_MNAME
	, THRD_PRTY_PANEL_MEMBER_EMAIL
	, THRD_PRTY_PANEL_MEMBER_PHONE
	, THRD_PRTY_PANEL_MEMBER_ORG
	, THRD_PRTY_PANEL_MEMBER_MAILING
	, THRD_PRTY_PANEL_DESCR
FROM
	ERLR_3RDPARTY_HEAR TPH
    LEFT OUTER JOIN ERLR_CASE EC ON TPH.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

CREATE OR REPLACE VIEW VW_ERLR_PROB_ACTION
AS
SELECT
    PA.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , PPA_ACTION_TYPE
	, PPA_TERMINATION_TYPE
	, PPA_TERM_PROP_ACTION_DT
	, PPA_TERM_ORAL_PREZ_REQUESTED
	, PPA_TERM_ORAL_PREZ_DT
	, PPA_TERM_WRITTEN_RESP
	, PPA_TERM_WRITTEN_RESP_DUE_DT
	, PPA_TERM_WRITTEN_RESP_DT
	, PPA_TERM_AGENCY_DECISION	
    , PPA_TERM_DECIDING_OFFCL_NAME
	, PPA_TERM_DECISION_ISSUED_DT
	, PPA_TERM_EFFECTIVE_DECISION_DT
	, PPA_PROB_TERM_DCSN_ISSUED_DT
	, PPA_PROBATION_CONDUCT
	, PPA_PROBATION_PERFORMANCE
	, PPA_APPEAL_GRIEVANCE_DEADLINE
	, PPA_EMP_APPEAL_DECISION
	, PPA_PROP_ACTION_ISSUED_DT
	, PPA_ORAL_PREZ_REQUESTED
	, PPA_ORAL_PREZ_DT
	, PPA_ORAL_RESPONSE_SUBMITTED
	, PPA_RESPONSE_DUE_DT
	, PPA_WRITTEN_RESPONSE_SBMT_DT
	, PPA_POS_TITLE
	, PPA_PPLAN
	, PPA_SERIES
	, PPA_CURRENT_INFO_GRADE
	, PPA_CURRENT_INFO_STEP
	, PPA_PROPOSED_POS_TITLE
	, PPA_PROPOSED_PPLAN
	, PPA_PROPOSED_SERIES
	, PPA_PROPOSED_INFO_GRADE
	, PPA_PROPOSED_INFO_STEP
	, PPA_FINAL_POS_TITLE
	, PPA_FINAL_PPLAN
	, PPA_FINAL_SERIES
	, PPA_FINAL_INFO_GRADE
	, PPA_FINAL_INFO_STEP
	, PPA_NOTICE_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_DECISION
	, PPA_DECIDING_OFFCL
	, PPA_DECISION_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_EFF_DT
	, PPA_NUMB_DAYS
	, PPA_EFFECTIVE_DT
	, PPA_CURRENT_ADMIN_CODE
	, PPA_RE_ASSIGNMENT_CURR_ORG
	, PPA_FINAL_ADMIN_CODE
	, PPA_FINAL_ADMIN_CODE_FINAL_ORG
FROM
	ERLR_PROB_ACTION PA
    LEFT OUTER JOIN ERLR_CASE EC ON PA.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;