-- DROP TABLE ELIG_QUAL;
-- DROP SEQUENCE ELIG_QUAL_SEQ; 

--------------------------------------------------------
--  DDL for Table ELIG_QUAL
--------------------------------------------------------
CREATE TABLE ELIG_QUAL
(
	ELIGQUAL_ID             NUMBER(20,0),
	ADMIN_CD                NVARCHAR2(8),
	RT_ID                   NUMBER(20,0),
	AT_ID                   NUMBER(20,0),
	VT_ID                   NUMBER(20,0),
	SAT_ID                  NUMBER(20,0),
	CT_ID                   NUMBER(20,0),
	SO_ID                   NVARCHAR2(10),
	SO_TITLE                NVARCHAR2(50),
	SO_ORG                  NVARCHAR2(50),
	XO_ID                   NVARCHAR2(10),
	XO_TITLE                NVARCHAR2(50),
	XO_ORG                  NVARCHAR2(50),
	POS_ID                  NUMBER(20,0),
	HRL_ID                  NVARCHAR2(10),
	HRL_TITLE               NVARCHAR2(100),
	HRL_ORG                 NVARCHAR2(100),
	SS_ID                   NVARCHAR2(10),
	CS_ID                   NVARCHAR2(10),
	SO_AGREE                CHAR(1 BYTE) DEFAULT '0',
	OTHER_CERT              NVARCHAR2(200),
	CNDT_LAST_NM            NVARCHAR2(50),
	CNDT_FIRST_NM           NVARCHAR2(50),
	CNDT_MIDDLE_NM          NVARCHAR2(50),
	BGT_APR_OFM             CHAR(1 BYTE),
	SPNSR_ORG_NM            NVARCHAR2(140),
	SPNSR_ORG_FUND_PC       NUMBER(3, 0),
	JOB_REQ_NUMBER          NVARCHAR2(16),
	JOB_REQ_CREATE_DT       DATE,
	POS_TITLE               NVARCHAR2(140),
	PAY_PLAN_ID             NUMBER(20,0),
	SERIES                  NUMBER(20,0),
	POS_DESC_NUMBER_1       NVARCHAR2(20),
	CLASSIFICATION_DT_1     DATE,
	GRADE_1                 NVARCHAR2(2),
	POS_DESC_NUMBER_2       NVARCHAR2(20),
	CLASSIFICATION_DT_2     DATE,
	GRADE_2                 NVARCHAR2(2),
	POS_DESC_NUMBER_3       NVARCHAR2(20),
	CLASSIFICATION_DT_3     DATE,
	GRADE_3                 NVARCHAR2(2),
	POS_DESC_NUMBER_4       NVARCHAR2(20),
	CLASSIFICATION_DT_4     DATE,
	GRADE_4                 NVARCHAR2(2),
	POS_DESC_NUMBER_5       NVARCHAR2(20),
	CLASSIFICATION_DT_5     DATE,
	GRADE_5                 NVARCHAR2(2),
	MED_OFFICERS_ID         NUMBER(20, 0),
	PERFORMANCE_LEVEL       NVARCHAR2(2),
	SUPERVISORY             NUMBER(20, 0),
	SKILL                   NVARCHAR2(200),
	GRADES_ADVERTISED       NVARCHAR2(100),
	LOCATION                NVARCHAR2(200),
	VACANCIES               NUMBER(9, 0),
	REPORT_SUPERVISOR       NVARCHAR2(10),
	CAN                     NVARCHAR2(8),
	VICE                    CHAR(1 BYTE) DEFAULT '0',
	VICE_NAME               NVARCHAR2(50),
	DAYS_ADVERTISED         NVARCHAR2(50),
	TA_ID                   NUMBER(20, 0),
	NTE                     NVARCHAR2(140),
	WORK_SCHED_ID           NUMBER(20, 0),
	HOURS_PER_WEEK          NVARCHAR2(50),
	DUAL_EMPLMT             NVARCHAR2(10),
	SEC_ID                  NUMBER(20, 0),
	CE_FINANCIAL_DISC       CHAR(1 BYTE) DEFAULT '0',
	CE_FINANCIAL_TYPE_ID    NUMBER(20, 0),
	CE_PE_PHYSICAL          CHAR(1 BYTE) DEFAULT '0',
	CE_DRUG_TEST            CHAR(1 BYTE) DEFAULT '0',
	CE_IMMUN                CHAR(1 BYTE) DEFAULT '0',
	CE_TRAVEL               CHAR(1 BYTE) DEFAULT '0',
	CE_TRAVEL_PER           NVARCHAR2(3),
	CE_LIC                  CHAR(1 BYTE) DEFAULT '0',
	CE_LIC_INFO             NVARCHAR2(140),
	REMARKS                 NVARCHAR2(500),
	PROC_REQ_TYPE           NUMBER(20, 0),
	RECRUIT_OFFICE_ID       NUMBER(20, 0),
	REQ_ID                  NUMBER(20, 0),
	REQ_CREATE_NOTIFY_DT    DATE,
	ASSOC_DESCR_NUMBERS     NVARCHAR2(100),
	PROMOTE_POTENTIAL       NUMBER(2, 0),
	VICE_EMPL_ID            NVARCHAR2(25),
	SR_ID                   NUMBER(20,0),
	GR_ID                   NUMBER(20,0),
	PROCID                  NUMBER(20,0),
	STATUS_ID               NUMBER(20,0),
	SC_REQUESTED            CHAR(1 BYTE) DEFAULT '0',
	SG_ID                   NUMBER(20,0),
	PD_ID                   NUMBER(20,0),
	GA_1                    CHAR(1 BYTE) DEFAULT '0',
	GA_2                    CHAR(1 BYTE) DEFAULT '0',
	GA_3                    CHAR(1 BYTE) DEFAULT '0',
	GA_4                    CHAR(1 BYTE) DEFAULT '0',
	GA_5                    CHAR(1 BYTE) DEFAULT '0',
	GA_6                    CHAR(1 BYTE) DEFAULT '0',
	GA_7                    CHAR(1 BYTE) DEFAULT '0',
	GA_8                    CHAR(1 BYTE) DEFAULT '0',
	GA_9                    CHAR(1 BYTE) DEFAULT '0',
	GA_10                   CHAR(1 BYTE) DEFAULT '0',
	GA_11                   CHAR(1 BYTE) DEFAULT '0',
	GA_12                   CHAR(1 BYTE) DEFAULT '0',
	GA_13                   CHAR(1 BYTE) DEFAULT '0',
	GA_14                   CHAR(1 BYTE) DEFAULT '0',
	GA_15                   CHAR(1 BYTE) DEFAULT '0',
	CNDT_ELIGIBLE           NVARCHAR2(10),
	INELIG_REASON           NUMBER(20,0),
	CNDT_QUALIFIED          NVARCHAR2(10),
	DISQUAL_REASON          NUMBER(20,0),
	SEL_DETERM              NUMBER(20,0),
	DCO_CERT                CHAR(1 BYTE) DEFAULT '0',
	DCO_NAME                NVARCHAR2(100),
	DCO_SIG                 NVARCHAR2(100),
	DCO_SIG_DT              DATE
);

COMMENT ON COLUMN ELIG_QUAL.ELIGQUAL_ID IS 'The unique ID on ELIG_QUAL';
COMMENT ON COLUMN ELIG_QUAL.ADMIN_CD IS 'Admin code';
COMMENT ON COLUMN ELIG_QUAL.RT_ID IS 'Request Type ID';
COMMENT ON COLUMN ELIG_QUAL.AT_ID IS 'Appointment Type ID';
COMMENT ON COLUMN ELIG_QUAL.VT_ID IS 'Volunteer Type ID';
COMMENT ON COLUMN ELIG_QUAL.SAT_ID IS 'Schedule A Type ID';
COMMENT ON COLUMN ELIG_QUAL.CT_ID IS 'ID to Lookup table ClassificationType';
COMMENT ON COLUMN ELIG_QUAL.SO_ID IS 'Selecting Officer ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.SO_TITLE IS 'Selecting Officer Title';
COMMENT ON COLUMN ELIG_QUAL.SO_ORG IS 'Selecting Officer''s organization';
COMMENT ON COLUMN ELIG_QUAL.XO_ID IS 'Executive Office ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.XO_TITLE IS 'Executive Officer''s title';
COMMENT ON COLUMN ELIG_QUAL.XO_ORG IS 'Executive Officer''s organization';
COMMENT ON COLUMN ELIG_QUAL.POS_ID IS 'Position ID';
COMMENT ON COLUMN ELIG_QUAL.HRL_ID IS 'HR Liaison ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.HRL_TITLE IS 'HR Liaison title';
COMMENT ON COLUMN ELIG_QUAL.HRL_ORG IS 'HR Liaison organization';
COMMENT ON COLUMN ELIG_QUAL.SS_ID IS 'Staffing Specialist ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.CS_ID IS 'Classification Specialist foriegn ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.SO_AGREE IS 'Checkbox for Selecting official concurrence 1=yes, 0=no';
COMMENT ON COLUMN ELIG_QUAL.OTHER_CERT IS 'Other certification';
COMMENT ON COLUMN ELIG_QUAL.CNDT_LAST_NM IS 'Candidate/Selectee Last Name';
COMMENT ON COLUMN ELIG_QUAL.CNDT_FIRST_NM IS 'Candidate/Selectee First Name';
COMMENT ON COLUMN ELIG_QUAL.CNDT_MIDDLE_NM IS 'Candidate/Selectee Middle Name';
COMMENT ON COLUMN ELIG_QUAL.BGT_APR_OFM IS 'Budget Approved by OFM?';
COMMENT ON COLUMN ELIG_QUAL.SPNSR_ORG_NM IS 'Name of Sponsoring Organization';
COMMENT ON COLUMN ELIG_QUAL.SPNSR_ORG_FUND_PC IS 'Sponsoring Organization Funding Percentage';
COMMENT ON COLUMN ELIG_QUAL.JOB_REQ_NUMBER IS 'Generated from current date + sequence number: yyyy-mm-ddnnnn';
COMMENT ON COLUMN ELIG_QUAL.JOB_REQ_CREATE_DT IS 'Date requested was made';
COMMENT ON COLUMN ELIG_QUAL.POS_TITLE IS 'Position title';
COMMENT ON COLUMN ELIG_QUAL.PAY_PLAN_ID IS 'Pay Plan ID from the Lookup table';
COMMENT ON COLUMN ELIG_QUAL.SERIES IS 'Organizational Series - 2 characters';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_1 IS 'PD Number 1';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_1 IS 'Classification date 1';
COMMENT ON COLUMN ELIG_QUAL.GRADE_1 IS 'Grade #1';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_2 IS 'PD Number 2';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_2 IS 'Classification date 2';
COMMENT ON COLUMN ELIG_QUAL.GRADE_2 IS 'Grade #2';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_3 IS 'PD Number 3';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_3 IS 'Classification date 3';
COMMENT ON COLUMN ELIG_QUAL.GRADE_3 IS 'Grade #3';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_4 IS 'PD Number 4';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_4 IS 'Classification date 4';
COMMENT ON COLUMN ELIG_QUAL.GRADE_4 IS 'Grade #4';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_5 IS 'PD Number 5';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_5 IS 'Classification date 5';
COMMENT ON COLUMN ELIG_QUAL.GRADE_5 IS 'Grade #5';
COMMENT ON COLUMN ELIG_QUAL.MED_OFFICERS_ID IS 'Medical Officers';
COMMENT ON COLUMN ELIG_QUAL.PERFORMANCE_LEVEL IS 'Full Performance Level';
COMMENT ON COLUMN ELIG_QUAL.SUPERVISORY IS 'Supervisory';
COMMENT ON COLUMN ELIG_QUAL.SKILL IS 'Primary skill';
COMMENT ON COLUMN ELIG_QUAL.GRADES_ADVERTISED IS 'List of grades advertised';
COMMENT ON COLUMN ELIG_QUAL.LOCATION IS 'Location';
COMMENT ON COLUMN ELIG_QUAL.VACANCIES IS 'Number of vacancies';
COMMENT ON COLUMN ELIG_QUAL.REPORT_SUPERVISOR IS 'Member ID of Report Supervisor';
COMMENT ON COLUMN ELIG_QUAL.CAN IS 'Common Accounting Number(CAN)';
COMMENT ON COLUMN ELIG_QUAL.VICE IS 'Replacing a position? 1=tru 0=false';
COMMENT ON COLUMN ELIG_QUAL.VICE_NAME IS 'Name of position being replaced';
COMMENT ON COLUMN ELIG_QUAL.DAYS_ADVERTISED IS 'Number of days position should be advertised';
COMMENT ON COLUMN ELIG_QUAL.TA_ID IS 'Type of Appointment';
COMMENT ON COLUMN ELIG_QUAL.NTE IS 'Not To Exceed - temporary employment duration';
COMMENT ON COLUMN ELIG_QUAL.WORK_SCHED_ID IS 'Work schedule ID';
COMMENT ON COLUMN ELIG_QUAL.HOURS_PER_WEEK IS 'Hours per week';
COMMENT ON COLUMN ELIG_QUAL.DUAL_EMPLMT IS 'Dual Employment';
COMMENT ON COLUMN ELIG_QUAL.SEC_ID IS 'Security code - also Position Sensitivity code LTYPE=PositionSensitivity';
COMMENT ON COLUMN ELIG_QUAL.CE_FINANCIAL_DISC IS 'Financial dsclosure or Financial statement required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_FINANCIAL_TYPE_ID IS 'Financial type ID';
COMMENT ON COLUMN ELIG_QUAL.CE_PE_PHYSICAL IS 'Pre-employment physical required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_DRUG_TEST IS 'Drug test required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_IMMUN IS 'Immunization?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_TRAVEL IS 'Travel required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_TRAVEL_PER IS 'Percentage travel required: 0-100';
COMMENT ON COLUMN ELIG_QUAL.CE_LIC IS 'License required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_LIC_INFO IS 'License information';
COMMENT ON COLUMN ELIG_QUAL.REMARKS IS 'Remarks related to the position';
COMMENT ON COLUMN ELIG_QUAL.PROC_REQ_TYPE IS 'Process request type';
COMMENT ON COLUMN ELIG_QUAL.RECRUIT_OFFICE_ID IS 'Recruiting Office ID';
COMMENT ON COLUMN ELIG_QUAL.REQ_ID IS 'Request ID';
COMMENT ON COLUMN ELIG_QUAL.REQ_CREATE_NOTIFY_DT IS 'Date of request notification';
COMMENT ON COLUMN ELIG_QUAL.ASSOC_DESCR_NUMBERS IS 'List of additional PD numbers associated with this position';
COMMENT ON COLUMN ELIG_QUAL.PROMOTE_POTENTIAL IS 'Level of promotion';
COMMENT ON COLUMN ELIG_QUAL.VICE_EMPL_ID IS 'Vice employee ID';
COMMENT ON COLUMN ELIG_QUAL.SR_ID IS 'Lookup ID for Organizational Series';
COMMENT ON COLUMN ELIG_QUAL.GR_ID IS 'Lookup value for grade';
COMMENT ON COLUMN ELIG_QUAL.PROCID IS 'Process ID. Foreign key to BIZFLOW.PROCS table';
COMMENT ON COLUMN ELIG_QUAL.STATUS_ID IS 'Status of the request for all stages';
COMMENT ON COLUMN ELIG_QUAL.SC_REQUESTED IS '';
COMMENT ON COLUMN ELIG_QUAL.SG_ID IS 'ID from the STRATCON_GEN table';
COMMENT ON COLUMN ELIG_QUAL.PD_ID IS 'ID from the PD Coversheet table';
COMMENT ON COLUMN ELIG_QUAL.GA_1 IS 'Grade 1 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_2 IS 'Grade 2 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_3 IS 'Grade 3 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_4 IS 'Grade 4 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_5 IS 'Grade 5 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_6 IS 'Grade 6 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_7 IS 'Grade 7 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_8 IS 'Grade 8 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_9 IS 'Grade 9 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_10 IS 'Grade 10 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_11 IS 'Grade 11 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_12 IS 'Grade 12 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_13 IS 'Grade 13 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_14 IS 'Grade 14 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_15 IS 'Grade 15 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CNDT_ELIGIBLE IS 'Candidate/selectee eligible? Yes/No';
COMMENT ON COLUMN ELIG_QUAL.INELIG_REASON IS 'Reason for Ineligibility';
COMMENT ON COLUMN ELIG_QUAL.CNDT_QUALIFIED IS 'Candidate/selectee qualified? Yes/No';
COMMENT ON COLUMN ELIG_QUAL.DISQUAL_REASON IS 'Reason for Disqualification';
COMMENT ON COLUMN ELIG_QUAL.SEL_DETERM IS 'Selection Determination: Selected? 1=true, 0=false';
COMMENT ON COLUMN ELIG_QUAL.DCO_CERT IS 'DCO approved? 1=true, 0=false';
COMMENT ON COLUMN ELIG_QUAL.DCO_NAME IS 'DCO name';
COMMENT ON COLUMN ELIG_QUAL.DCO_SIG IS 'DCO signature';
COMMENT ON COLUMN ELIG_QUAL.DCO_SIG_DT IS 'DCO signature date';

--------------------------------------------------------
--  DDL for Index ELIG_QUAL_PK
--------------------------------------------------------
CREATE UNIQUE INDEX ELIG_QUAL_PK ON ELIG_QUAL (ELIGQUAL_ID);

--------------------------------------------------------
--  Constraints for Table ELIG_QUAL
--------------------------------------------------------
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_PK PRIMARY KEY (ELIGQUAL_ID);
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK1   CHECK ( SO_AGREE          IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK2   CHECK ( VICE              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK3   CHECK ( CE_FINANCIAL_DISC IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK4   CHECK ( CE_PE_PHYSICAL    IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK5   CHECK ( CE_DRUG_TEST      IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK6   CHECK ( CE_IMMUN          IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK7   CHECK ( CE_TRAVEL         IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK8   CHECK ( CE_LIC            IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK9   CHECK ( GA_1              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK10  CHECK ( GA_2              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK11  CHECK ( GA_3              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK12  CHECK ( GA_4              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK13  CHECK ( GA_5              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK14  CHECK ( GA_6              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK15  CHECK ( GA_7              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK16  CHECK ( GA_8              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK17  CHECK ( GA_9              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK18  CHECK ( GA_10             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK19  CHECK ( GA_11             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK20  CHECK ( GA_12             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK21  CHECK ( GA_13             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK22  CHECK ( GA_14             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK23  CHECK ( GA_15             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK24  CHECK ( SC_REQUESTED      IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK27  CHECK ( DCO_CERT          IN('0', '1')) ENABLE;

/



--------------------------------------------------------
--  DDL for Sequence ELIG_QUAL_SEQ
--------------------------------------------------------
CREATE SEQUENCE ELIG_QUAL_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/


--------------------------------------------------------
--  DDL for Trigger ELIG_QUAL_BIR
--------------------------------------------------------
CREATE OR REPLACE TRIGGER ELIG_QUAL_BIR
BEFORE INSERT ON ELIG_QUAL
FOR EACH ROW
BEGIN
	SELECT ELIG_QUAL_SEQ.NEXTVAL
	INTO :NEW.ELIGQUAL_ID
	FROM DUAL;
END;

/
