

-- data type change for ELIG_QUAL.DCO_CERT
ALTER TABLE ELIG_QUAL DROP CONSTRAINT ELIG_QUAL_CK27;

ALTER TABLE ELIG_QUAL ADD DCO_CERT_TEMP NVARCHAR2(10);

--UPDATE ELIG_QUAL SET DCO_CERT_TEMP = TO_CHAR(DCO_CERT);
UPDATE ELIG_QUAL SET DCO_CERT_TEMP = (CASE WHEN DCO_CERT = 1 THEN 'Yes' ELSE 'No' END);
COMMIT;

ALTER TABLE ELIG_QUAL DROP COLUMN DCO_CERT;

ALTER TABLE ELIG_QUAL RENAME COLUMN DCO_CERT_TEMP TO DCO_CERT;

COMMENT ON COLUMN ELIG_QUAL.DCO_CERT IS 'DCO approved? Yes/No';

