 CREATE OR REPLACE PROCEDURE SP_UPDATE_INCENTIVES_LE_TABLE
(
	I_PROCID            IN      NUMBER
)
IS
BEGIN
	IF I_PROCID IS NOT NULL AND I_PROCID > 0 THEN
		DELETE INCENTIVES_LE WHERE PROC_ID = I_PROCID;
		INSERT INTO INCENTIVES_LE (PROC_ID, COC_NAME, COC_EMAIL, COC_ID, COC_TITLE, INIT_ANN_LA_RATE, SUPPORT_LE, PROPS_ANN_LA_RATE
			, JUSTIFICATION_SKILL_EXP, JUSTIFICATION_AGENCY_GOAL, SELECTEE_ELIGIBILITY
			, HRS_RVW_CERT, HRS_NOT_SPT_RSN, RVW_HRS, HRS_RVW_DATE, RCMD_LA_RATE
			, APPROVAL_SO_VALUE, APPROVAL_SO_ACTING, APPROVAL_SO, APPROVAL_SO_RESP_DATE, APPROVAL_COC_VALUE, APPROVAL_COC_ACTING, APPROVAL_COC, APPROVAL_COC_RESP_DATE, APPROVAL_DGHO_VALUE, APPROVAL_DGHO_ACTING, APPROVAL_DGHO, APPROVAL_DGHO_RESP_DATE
			, APPROVAL_TABG_VALUE, APPROVAL_TABG_ACTING, APPROVAL_TABG, APPROVAL_TABG_RESP_DATE)
			SELECT PROC_ID, COC_NAME, COC_EMAIL, COC_ID, COC_TITLE, INIT_ANN_LA_RATE, SUPPORT_LE, PROPS_ANN_LA_RATE
			, JUSTIFICATION_SKILL_EXP, JUSTIFICATION_AGENCY_GOAL, SELECTEE_ELIGIBILITY
			, HRS_RVW_CERT, HRS_NOT_SPT_RSN, RVW_HRS, HRS_RVW_DATE, RCMD_LA_RATE
			, APPROVAL_SO_VALUE, APPROVAL_SO_ACTING, APPROVAL_SO, APPROVAL_SO_RESP_DATE, APPROVAL_COC_VALUE, APPROVAL_COC_ACTING, APPROVAL_COC, APPROVAL_COC_RESP_DATE, APPROVAL_DGHO_VALUE, APPROVAL_DGHO_ACTING, APPROVAL_DGHO, APPROVAL_DGHO_RESP_DATE
			, APPROVAL_TABG_VALUE, APPROVAL_TABG_ACTING, APPROVAL_TABG, APPROVAL_TABG_RESP_DATE
			FROM VW_INCENTIVES_LE WHERE PROC_ID = I_PROCID;
	END IF;

	EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/
