----------------------------------
-- grant for HHS_CMS_HR_RW_ROLE
----------------------------------
GRANT SELECT ON HHS_HR.DSS_CMS_TIME_TO_HIRE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON BIZFLOW.HHS_VW_CONSULTATION_PROC TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON BIZFLOW.HHS_FN_GET_BUSDAYSDIFF TO HHS_HR_RW_ROLE;
GRANT EXECUTE ON BIZFLOW.HHS_FN_SUBTRACT_BUSDAY TO HHS_HR_RW_ROLE;

----------------------------------
-- grant for HHS_CMS_HR_DEV_ROLE
----------------------------------
GRANT SELECT ON HHS_HR.DSS_CMS_TIME_TO_HIRE TO HHS_HR_DEV_ROLE;
GRANT SELECT ON BIZFLOW.HHS_VW_CONSULTATION_PROC TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON BIZFLOW.HHS_FN_GET_BUSDAYSDIFF TO HHS_HR_DEV_ROLE;
GRANT EXECUTE ON BIZFLOW.HHS_FN_SUBTRACT_BUSDAY TO HHS_HR_DEV_ROLE;

----------------------------------
-- grant for HHS_CMS_HR
----------------------------------
GRANT SELECT ON HHS_HR.DSS_CMS_TIME_TO_HIRE TO HHS_CMS_HR;
GRANT SELECT ON BIZFLOW.HHS_VW_CONSULTATION_PROC TO HHS_HR;
GRANT EXECUTE ON BIZFLOW.HHS_FN_GET_BUSDAYSDIFF TO HHS_HR;
GRANT EXECUTE ON BIZFLOW.HHS_FN_SUBTRACT_BUSDAY TO HHS_HR;


