
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1688, 0, 'ERLRDenialNoticeReason', 'Information Was Neither Reasonably Available Nor Necessary', 'Information Was Neither Reasonably Available Nor Necessary', '1', 2, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1689, 0, 'ERLRDenialNoticeReason', 'Information Is Protected from Disclosure by Law', 'Information Is Protected from Disclosure by Law', '1', 3, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1690, 0, 'ERLRDenialNoticeReason', 'Information Is Not Normally Maintained by the Agency', 'Information Is Not Normally Maintained by the Agency', '1', 4, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1691, 0, 'ERLRDenialNoticeReason', 'Information Is Protected as Intra-Management Guidance', 'Information Is Protected as Intra-Management Guidance', '1', 5, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1692, 0, 'ERLRDenialNoticeReason', 'Other', 'Other', '1', 6, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1693, 0, 'ERLRDenialNoticeReason', 'Failed to Meet Particularized Need Standard', 'Failed to Meet Particularized Need Standard', '1', 1, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1694, 0, 'ERLRULPDispositionType', 'Dismissal', 'Dismissal', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1695, 0, 'ERLRULPDispositionType', 'Withdrawal', 'Withdrawal', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1696, 0, 'ERLRULPDispositionType', 'Complaint', 'Complaint', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;

---
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1703,747,'ERLRCasesCompletedFinalAction','Information Provided','Information Provided','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1704,747,'ERLRCasesCompletedFinalAction','Information Request Denied','Information Request Denied','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1705,747,'ERLRCasesCompletedFinalAction','Information Provided in Part and Denied in Part','Information Provided in Part and Denied in Part','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1706,747,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1707,746,'ERLRCasesCompletedFinalAction','Documentation Provided','Documentation Provided','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1708,746,'ERLRCasesCompletedFinalAction','Documentation Not Provided','Documentation Not Provided','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1709,746,'ERLRCasesCompletedFinalAction','Documentation Accepted','Documentation Accepted','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1710,746,'ERLRCasesCompletedFinalAction','Documentation Not Accepted','Documentation Not Accepted','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1711,746,'ERLRCasesCompletedFinalAction','Documentation Request Rescinded','Documentation Request Rescinded','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1712,746,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

--
UPDATE HHS_CMS_HR.TBL_LOOKUP SET TBL_NAME = 'NoActionTaken', TBL_LABEL ='No Action Taken' WHERE TBL_ID IN(944,937);

--
INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1713, 0, 'ERLRMeddocReasonForRequest', 'Performance', 'Performance', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

--
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1714,809,'ERLRCasesCompletedFinalAction','WGI Denied','WGI Denied','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1715,809,'ERLRCasesCompletedFinalAction','WGI Granted','WGI Granted','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1716,809,'ERLRCasesCompletedFinalAction','WGI Delayed','WGI Delayed','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1717,809,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1725,754,'ERLRCasesCompletedFinalAction','ULP Dismissed','ULP Dismissed','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1726,754,'ERLRCasesCompletedFinalAction','ULP Upheld','ULP Upheld','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1727,754,'ERLRCasesCompletedFinalAction','ULP Dismissed in Part, Upheld in Part','ULP Dismissed in Part, Upheld in Part','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1728,754,'ERLRCasesCompletedFinalAction','Posting','Posting','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1729,754,'ERLRCasesCompletedFinalAction','ULP Withdrawn by Union','ULP Withdrawn by Union','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1731,754,'ERLRCasesCompletedFinalAction','ULP Withdrawn by Management','ULP Withdrawn by Management','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1732,754,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

--3rd party inserts starts
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1718,0,'ERLRCasesCompletedFinalAction','Grievance Granted','Grievance Granted','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1719,0,'ERLRCasesCompletedFinalAction','Grievance Denied','Grievance Denied','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1720,0,'ERLRCasesCompletedFinalAction','Grievance Granted in Part, Denied in Part','Grievance Granted in Part, Denied in Part','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1721,0,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1722,0,'ERLRCasesCompletedFinalAction','Grievance Withdrawn by Union','Grievance Withdrawn by Union','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1723,0,'ERLRCasesCompletedFinalAction','Grievance Withdrawn by Management','Grievance Withdrawn by Management','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1724,0,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1733,0,'ERLRCasesCompletedFinalAction','Arbitrator''s Decision Upheld','Arbitrator''s Decision Upheld','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1734,0,'ERLRCasesCompletedFinalAction','Arbitrator''s Decision Reversed','Arbitrator''s Decision Reversed','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1735,0,'ERLRCasesCompletedFinalAction','Arbitrator''s Decision Upheld in Part, Reversed in Part','Arbitrator''s Decision Upheld in Part, Reversed in Part','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1736,0,'ERLRCasesCompletedFinalAction','Case Remanded to Arbitrator for Revised Decision','Case Remanded to Arbitrator for Revised Decision','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1737,0,'ERLRCasesCompletedFinalAction','Case Remanded to Parties for New Hearing','Case Remanded to Parties for New Hearing','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1738,0,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1739,0,'ERLRCasesCompletedFinalAction','Case Withdrawn by Union','Case Withdrawn by Union','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1740,0,'ERLRCasesCompletedFinalAction','Case Withdrawn by Management','Case Withdrawn by Management','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1741,0,'ERLRCasesCompletedFinalAction','ULP Dismissed','ULP Dismissed','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1742,0,'ERLRCasesCompletedFinalAction','Posting Ordered','Posting Ordered','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1743,0,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));


Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1744,0,'ERLRCasesCompletedFinalAction','Med- Arb Agency Win','Med- Arb Agency Win','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1745,0,'ERLRCasesCompletedFinalAction','Med- Arb Union Win','Med- Arb Union Win','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1746,0,'ERLRCasesCompletedFinalAction','Med- Arb Split Decision','Med- Arb Split Decision','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1747,0,'ERLRCasesCompletedFinalAction','Agency''s Last Final Offer','Agency''s Last Final Offer','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1748,0,'ERLRCasesCompletedFinalAction','Union''s Last Final Offer','Union''s Last Final Offer','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1749,0,'ERLRCasesCompletedFinalAction','FSIP Developed Decision','FSIP Developed Decision','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1750,0,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));

Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1751,0,'ERLRCasesCompletedFinalAction','FSIP Developed Decision','FSIP Developed Decision','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1752,0,'ERLRCasesCompletedFinalAction','Appeal Granted','Appeal Granted','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1753,0,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1754,0,'ERLRCasesCompletedFinalAction','Appeal Granted in Part, Dismissed in Part','Appeal Granted in Part, Dismissed in Part','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1755,0,'ERLRCasesCompletedFinalAction','Appeal Withdrawn','Appeal Withdrawn','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1756,0,'ERLRCasesCompletedFinalAction','Other','Other','1',null,'N',null,'ERLR',to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));