-- CMS_HR_DB_UPD_20_alter_model_tables.sql

ALTER TABLE ELIG_QUAL
MODIFY XO_ID NVARCHAR2(32);

ALTER TABLE ELIG_QUAL
MODIFY XO_TITLE NVARCHAR2(200);

ALTER TABLE ELIG_QUAL
MODIFY XO_ORG NVARCHAR2(200);