CREATE OR REPLACE PROCEDURE SP_UPDATE_ERLR_TABLE
(
	I_PROCID            IN      NUMBER
)
IS
	V_CASE_NUMBER                NUMBER(20);
	V_JOB_REQ_NUM               NVARCHAR2(50);
    V_CASE_CREATION_DT          DATE;	
	V_VALUE                     NVARCHAR2(4000);
	V_VALUE_LOOKUP              NVARCHAR2(2000);
	V_REC_CNT                   NUMBER(10);
	V_XMLDOC                    XMLTYPE;
	V_XMLVALUE                  XMLTYPE;	
	V_ERRCODE                   NUMBER(10);
	V_ERRMSG                    VARCHAR2(512);
	E_INVALID_PROCID            EXCEPTION;
	E_INVALID_JOB_REQ_ID        EXCEPTION;
	PRAGMA EXCEPTION_INIT(E_INVALID_JOB_REQ_ID, -20902);
	E_INVALID_STRATCON_DATA     EXCEPTION;
	PRAGMA EXCEPTION_INIT(E_INVALID_STRATCON_DATA, -20905);
BEGIN
	--DBMS_OUTPUT.PUT_LINE('SP_UPDATE_ERLR_TABLE - BEGIN ============================');
	--DBMS_OUTPUT.PUT_LINE('PARAMETERS ----------------');
	--DBMS_OUTPUT.PUT_LINE('    I_PROCID IS NULL?  = ' || (CASE WHEN I_PROCID IS NULL THEN 'YES' ELSE 'NO' END));
	--DBMS_OUTPUT.PUT_LINE('    I_PROCID           = ' || TO_CHAR(I_PROCID));
	--DBMS_OUTPUT.PUT_LINE(' ----------------');



	IF I_PROCID IS NOT NULL AND I_PROCID > 0 THEN
		------------------------------------------------------
		-- Transfer XML data into operational table
		--
		-- 1. Get Case number and Job Request Number
		-- 1.1 Select it from data xml from TBL_FORM_DTL table.
		-- 1.2 If not found, select it from BIZFLOW.RLVNTDATA table.
		-- 2. If Case number /Job Request Number not found, issue error.
		-- 3. For each target table,
		-- 3.1. If record found for the CASE_NUMBER, update record.
		-- 3.2. If record not found for the CASE_NUMBER, insert record.
		------------------------------------------------------
		--DBMS_OUTPUT.PUT_LINE('Starting xml data retrieval and table update ----------');

		--------------------------------
		-- get Case number
		--------------------------------
		--DBMS_OUTPUT.PUT_LINE('    REQUEST table');
        BEGIN
			SELECT VALUE
			INTO V_CASE_NUMBER
			FROM BIZFLOW.RLVNTDATA
			WHERE PROCID = I_PROCID AND RLVNTDATANAME = 'caseNumber';
		EXCEPTION
			WHEN NO_DATA_FOUND THEN V_CASE_NUMBER := NULL;
		END;

		--DBMS_OUTPUT.PUT_LINE('    V_CASE_NUMBER = ' || V_CASE_NUMBER);
		IF V_CASE_NUMBER IS NULL THEN
			RAISE_APPLICATION_ERROR(-20902, 'SP_UPDATE_ERLR_TABLE: Case Number is invalid.  I_PROCID = '
				|| TO_CHAR(I_PROCID) || ' V_CASE_NUMBER = ' || V_CASE_NUMBER || '  V_CASE_NUMBER = ' || TO_CHAR(V_CASE_NUMBER));
		END IF;

        --------------------------------
		-- get Request number 
		--------------------------------
		BEGIN
			SELECT VALUE
			INTO V_JOB_REQ_NUM
			FROM BIZFLOW.RLVNTDATA
			WHERE PROCID = I_PROCID AND RLVNTDATANAME = 'requestNum';
		EXCEPTION
			WHEN NO_DATA_FOUND THEN V_JOB_REQ_NUM := NULL;
		END;

		--DBMS_OUTPUT.PUT_LINE('    V_JOB_REQ_NUM = ' || V_JOB_REQ_NUM);
		--IF V_JOB_REQ_NUM IS NULL THEN
		--	RAISE_APPLICATION_ERROR(-20902, 'SP_UPDATE_ERLR_TABLE: Request Number is invalid.  I_PROCID = '
		--		|| TO_CHAR(I_PROCID) || ' V_JOB_REQ_NUM = ' || V_JOB_REQ_NUM || '  V_JOB_REQ_NUM = ' || TO_CHAR(V_JOB_REQ_NUM));
		--END IF;

        --------------------------------
		-- get Case Creation Date
		--------------------------------
		--DBMS_OUTPUT.PUT_LINE('    Case Creation Date'');
        BEGIN
			SELECT CREATIONDTIME
			INTO V_CASE_CREATION_DT
			FROM BIZFLOW.PROCS
			WHERE PROCID = I_PROCID;
		EXCEPTION
			WHEN NO_DATA_FOUND THEN V_CASE_CREATION_DT := NULL;
		END;
		--------------------------------
		-- ERLR_CASE table
		--------------------------------
		BEGIN
            MERGE INTO  ERLR_CASE TRG
            USING
            (
                SELECT
                    V_CASE_NUMBER AS ERLR_CASE_NUMBER
                    , V_JOB_REQ_NUM AS ERLR_JOB_REQ_NUMBER
                    , I_PROCID AS PROCID
                    , X.GEN_CASE_STATUS AS ERLR_CASE_STATUS_ID
                    , V_CASE_CREATION_DT AS ERLR_CASE_CREATE_DT
                FROM TBL_FORM_DTL FD
                    , XMLTABLE('/formData/items'
						PASSING FD.FIELD_DATA
						COLUMNS
                            GEN_CASE_STATUS NUMBER(20,0) PATH './item[id="GEN_CASE_STATUS"]/value'
                ) X
			    WHERE FD.PROCID = I_PROCID
            )SRC ON (SRC.ERLR_CASE_NUMBER = TRG.ERLR_CASE_NUMBER)
            WHEN MATCHED THEN UPDATE SET
                TRG.ERLR_CASE_STATUS_ID = SRC.ERLR_CASE_STATUS_ID
				,TRG.ERLR_JOB_REQ_NUMBER = SRC.ERLR_JOB_REQ_NUMBER     
            WHEN NOT MATCHED THEN INSERT
            (
                TRG.ERLR_CASE_NUMBER
                , TRG.ERLR_JOB_REQ_NUMBER
	            , TRG.PROCID 
	            , TRG.ERLR_CASE_STATUS_ID
	            , TRG.ERLR_CASE_CREATE_DT
            )
            VALUES
            (
                SRC.ERLR_CASE_NUMBER
                , SRC.ERLR_JOB_REQ_NUMBER
	            , SRC.PROCID 
	            , SRC.ERLR_CASE_STATUS_ID
	            , SRC.ERLR_CASE_CREATE_DT
            );

		END;



		--------------------------------
		-- ERLR_GEN table
		--------------------------------
		BEGIN
			--DBMS_OUTPUT.PUT_LINE('    ERLR_GEN table');
			MERGE INTO ERLR_GEN TRG
			USING
			(
				SELECT
					V_CASE_NUMBER AS ERLR_CASE_NUMBER
					--X.ERLR_CASE_NUMBER
					, SUBSTR(X.GEN_PRIMARY_SPECIALIST, 4, 10) AS GEN_PRIMARY_SPECIALIST
                    , SUBSTR(X.GEN_SECONDARY_SPECIALIST, 4, 10) AS GEN_SECONDARY_SPECIALIST
                    , X.GEN_CUSTOMER_NAME
                    , X.GEN_CUSTOMER_PHONE
                    , X.GEN_CUSTOMER_ADMIN_CD
                    , X.GEN_CUSTOMER_ADMIN_CD_DESC
                    , X.GEN_EMPLOYEE_NAME
                    , X.GEN_EMPLOYEE_PHONE
                    , X.GEN_EMPLOYEE_ADMIN_CD
                    , X.GEN_EMPLOYEE_ADMIN_CD_DESC
                    , X.GEN_CASE_DESC
	                , X.GEN_CASE_STATUS
					, TO_DATE(X.GEN_CUST_INIT_CONTACT_DT,'MM/DD/YYYY HH24:MI:SS') AS GEN_CUST_INIT_CONTACT_DT            
	                , X.GEN_PRIMARY_REP_AFFILIATION
	                , X.GEN_CMS_PRIMARY_REP_ID
	                , X.GEN_CMS_PRIMARY_REP_PHONE
	                , X.GEN_NON_CMS_PRIMARY_FNAME
	                , X.GEN_NON_CMS_PRIMARY_MNAME
	                , X.GEN_NON_CMS_PRIMARY_LNAME
	                , X.GEN_NON_CMS_PRIMARY_EMAIL
	                , X.GEN_NON_CMS_PRIMARY_PHONE
	                , X.GEN_NON_CMS_PRIMARY_ORG
	                , X.GEN_NON_CMS_PRIMARY_ADDR
	                , X.GEN_CASE_TYPE
	                , X.GEN_CASE_CATEGORY
	                , X.GEN_INVESTIGATION
	                , X.GEN_INVESTIGATE_START_DT
	                , X.GEN_INVESTIGATE_END_DT
	                , X.GEN_STD_CONDUCT
	                , X.GEN_STD_CONDUCT_TYPE
	                , X.CC_FINAL_ACTION
	                , TO_DATE(X.CC_CASE_COMPLETE_DT,'MM/DD/YYYY HH24:MI:SS') AS CC_CASE_COMPLETE_DT          
				FROM TBL_FORM_DTL FD
					, XMLTABLE('/formData/items' PASSING FD.FIELD_DATA
						COLUMNS
							ERLR_CASE_NUMBER	NUMBER(20,0)	PATH './item[id="CASE_NUMBER"]/value'
							, GEN_PRIMARY_SPECIALIST VARCHAR2(13) PATH './item[id="GEN_PRIMARY_SPECIALIST"]/value'
                            , GEN_SECONDARY_SPECIALIST	VARCHAR2(13)   PATH './item[id="GEN_SECONDARY_SPECIALIST"]/value'
	                        , GEN_CUSTOMER_NAME 	NVARCHAR2(150)  PATH './item[id="GEN_CUSTOMER_NAME"]/value'
	                        , GEN_CUSTOMER_PHONE	NVARCHAR2(50)   PATH './item[id="GEN_CUSTOMER_PHONE"]/value'
	                        , GEN_CUSTOMER_ADMIN_CD	NVARCHAR2(8)    PATH './item[id="GEN_CUSTOMER_ADMIN_CD"]/value'
	                        , GEN_CUSTOMER_ADMIN_CD_DESC	NVARCHAR2(50)   PATH './item[id="GEN_CUSTOMER_ADMIN_CD_DESC"]/value'
	                        , GEN_EMPLOYEE_NAME	NVARCHAR2(150)  PATH './item[id="GEN_EMPLOYEE_NAME"]/value'
	                        , GEN_EMPLOYEE_PHONE	NVARCHAR2(50)   PATH './item[id="GEN_EMPLOYEE_PHONE"]/value'
	                        , GEN_EMPLOYEE_ADMIN_CD	NVARCHAR2(8)    PATH './item[id="GEN_EMPLOYEE_ADMIN_CD"]/value'
	                        , GEN_EMPLOYEE_ADMIN_CD_DESC	NVARCHAR2(50)   PATH './item[id="GEN_EMPLOYEE_ADMIN_CD_DESC"]/value'
	                        , GEN_CASE_DESC	NVARCHAR2(500)  PATH './item[id="GEN_CASE_DESC"]/value'
	                        , GEN_CASE_STATUS	 NUMBER(20,0)   PATH './item[id="GEN_CASE_STATUS"]/value'
	                        , GEN_CUST_INIT_CONTACT_DT	VARCHAR2(10)    PATH './item[id="GEN_CUST_INIT_CONTACT_DT"]/value'
	                        , GEN_PRIMARY_REP_AFFILIATION	 NVARCHAR2(20)  PATH './item[id="GEN_PRIMARY_REP"]/value'
	                        , GEN_CMS_PRIMARY_REP_ID VARCHAR2(10)  PATH './item[id="GEN_CMS_PRIMARY_REP"]/value/id'
	                        , GEN_CMS_PRIMARY_REP_PHONE	NVARCHAR2(50)   PATH './item[id="GEN_CMS_PRIMARY_REP_PHONE"]/value'
	                        , GEN_NON_CMS_PRIMARY_FNAME	NVARCHAR2(50)   PATH './item[id="GEN_NON_CMS_PRIMARY_FNAME"]/value'
	                        , GEN_NON_CMS_PRIMARY_MNAME	NVARCHAR2(50)   PATH './item[id="GEN_NON_CMS_PRIMARY_MNAME"]/value'
	                        , GEN_NON_CMS_PRIMARY_LNAME	NVARCHAR2(50)   PATH './item[id="GEN_NON_CMS_PRIMARY_LNAME"]/value'
	                        , GEN_NON_CMS_PRIMARY_EMAIL	NVARCHAR2(100)  PATH './item[id="GEN_NON_CMS_PRIMARY_EMAIL"]/value'
	                        , GEN_NON_CMS_PRIMARY_PHONE	NVARCHAR2(50)   PATH './item[id="GEN_NON_CMS_PRIMARY_PHONE"]/value'
	                        , GEN_NON_CMS_PRIMARY_ORG	NVARCHAR2(100)  PATH './item[id="GEN_NON_CMS_PRIMARY_ORG"]/value'
	                        , GEN_NON_CMS_PRIMARY_ADDR	NVARCHAR2(250)  PATH './item[id="GEN_NON_CMS_PRIMARY_ADDR"]/value'
	                        , GEN_CASE_TYPE	 NUMBER(20,0)   PATH './item[id="GEN_CASE_TYPE"]/value'
	                        , GEN_CASE_CATEGORY	NVARCHAR2(200)  PATH './item[id="GEN_CASE_CATEGORY"]/value'
	                        , GEN_INVESTIGATION	NVARCHAR2(3)    PATH './item[id="GEN_INVESTIGATION"]/value'
	                        , GEN_INVESTIGATE_START_DT	DATE    PATH './item[id="GEN_INVESTIGATE_START_DT"]/value'
	                        , GEN_INVESTIGATE_END_DT	DATE    PATH './item[id="GEN_INVESTIGATE_END_DT"]/value'
	                        , GEN_STD_CONDUCT	NVARCHAR2(3)    PATH './item[id="GEN_STD_CONDUCT"]/value'
	                        , GEN_STD_CONDUCT_TYPE	 NVARCHAR2(200) PATH './item[id="GEN_STD_CONDUCT_TYPE"]/value'
	                        , CC_FINAL_ACTION	NVARCHAR2(200)  PATH './item[id="CC_FINAL_ACTION"]/value'
	                        , CC_CASE_COMPLETE_DT	VARCHAR2(10)    PATH './item[id="CC_CASE_COMPLETE_DT"]/value'
					) X					
				WHERE FD.PROCID = I_PROCID
			) SRC ON (SRC.ERLR_CASE_NUMBER = TRG.ERLR_CASE_NUMBER)
			WHEN MATCHED THEN UPDATE SET
				TRG.GEN_PRIMARY_SPECIALIST                    = SRC.GEN_PRIMARY_SPECIALIST
				, TRG.GEN_SECONDARY_SPECIALIST            = SRC.GEN_SECONDARY_SPECIALIST
				, TRG.GEN_CUSTOMER_NAME                  = SRC.GEN_CUSTOMER_NAME
				, TRG.GEN_CUSTOMER_PHONE      = SRC.GEN_CUSTOMER_PHONE
				, TRG.GEN_CUSTOMER_ADMIN_CD    = SRC.GEN_CUSTOMER_ADMIN_CD
				, TRG.GEN_CUSTOMER_ADMIN_CD_DESC                = SRC.GEN_CUSTOMER_ADMIN_CD_DESC
				, TRG.GEN_EMPLOYEE_NAME       = SRC.GEN_EMPLOYEE_NAME
				, TRG.GEN_EMPLOYEE_PHONE      = SRC.GEN_EMPLOYEE_PHONE
				, TRG.GEN_EMPLOYEE_ADMIN_CD    = SRC.GEN_EMPLOYEE_ADMIN_CD
				, TRG.GEN_EMPLOYEE_ADMIN_CD_DESC                = SRC.GEN_EMPLOYEE_ADMIN_CD_DESC
				, TRG.GEN_CASE_DESC       = SRC.GEN_CASE_DESC
				, TRG.GEN_CASE_STATUS      = SRC.GEN_CASE_STATUS
				, TRG.GEN_CUST_INIT_CONTACT_DT    = SRC.GEN_CUST_INIT_CONTACT_DT
				, TRG.GEN_PRIMARY_REP_AFFILIATION                = SRC.GEN_PRIMARY_REP_AFFILIATION
				, TRG.GEN_CMS_PRIMARY_REP_ID       = SRC.GEN_CMS_PRIMARY_REP_ID
				, TRG.GEN_CMS_PRIMARY_REP_PHONE      = SRC.GEN_CMS_PRIMARY_REP_PHONE
				, TRG.GEN_NON_CMS_PRIMARY_FNAME    = SRC.GEN_NON_CMS_PRIMARY_FNAME
				, TRG.GEN_NON_CMS_PRIMARY_MNAME                = SRC.GEN_NON_CMS_PRIMARY_MNAME
				, TRG.GEN_NON_CMS_PRIMARY_LNAME       = SRC.GEN_NON_CMS_PRIMARY_LNAME
				, TRG.GEN_NON_CMS_PRIMARY_EMAIL      = SRC.GEN_NON_CMS_PRIMARY_EMAIL
				, TRG.GEN_NON_CMS_PRIMARY_PHONE    = SRC.GEN_NON_CMS_PRIMARY_PHONE
				, TRG.GEN_NON_CMS_PRIMARY_ORG                = SRC.GEN_NON_CMS_PRIMARY_ORG
				, TRG.GEN_NON_CMS_PRIMARY_ADDR       = SRC.GEN_NON_CMS_PRIMARY_ADDR
				, TRG.GEN_CASE_TYPE      = SRC.GEN_CASE_TYPE
				, TRG.GEN_CASE_CATEGORY            = SRC.GEN_CASE_CATEGORY
				, TRG.GEN_INVESTIGATION                  = SRC.GEN_INVESTIGATION
				, TRG.GEN_INVESTIGATE_START_DT               = SRC.GEN_INVESTIGATE_START_DT
				, TRG.GEN_INVESTIGATE_END_DT                     = SRC.GEN_INVESTIGATE_END_DT
				, TRG.GEN_STD_CONDUCT                  = SRC.GEN_STD_CONDUCT
				, TRG.GEN_STD_CONDUCT_TYPE                    = SRC.GEN_STD_CONDUCT_TYPE
				, TRG.CC_FINAL_ACTION                     = SRC.CC_FINAL_ACTION
				, TRG.CC_CASE_COMPLETE_DT                  = SRC.CC_CASE_COMPLETE_DT				
			WHEN NOT MATCHED THEN INSERT
			(
				TRG.ERLR_CASE_NUMBER
				, TRG.GEN_PRIMARY_SPECIALIST
				, TRG.GEN_SECONDARY_SPECIALIST
				, TRG.GEN_CUSTOMER_NAME     
				, TRG.GEN_CUSTOMER_PHONE  
				, TRG.GEN_CUSTOMER_ADMIN_CD
				, TRG.GEN_CUSTOMER_ADMIN_CD_DESC
				, TRG.GEN_EMPLOYEE_NAME
				, TRG.GEN_EMPLOYEE_PHONE
				, TRG.GEN_EMPLOYEE_ADMIN_CD
				, TRG.GEN_EMPLOYEE_ADMIN_CD_DESC
				, TRG.GEN_CASE_DESC
				, TRG.GEN_CASE_STATUS
				, TRG.GEN_CUST_INIT_CONTACT_DT
				, TRG.GEN_PRIMARY_REP_AFFILIATION
				, TRG.GEN_CMS_PRIMARY_REP_ID
				, TRG.GEN_CMS_PRIMARY_REP_PHONE
				, TRG.GEN_NON_CMS_PRIMARY_FNAME
				, TRG.GEN_NON_CMS_PRIMARY_MNAME
				, TRG.GEN_NON_CMS_PRIMARY_LNAME
				, TRG.GEN_NON_CMS_PRIMARY_EMAIL
				, TRG.GEN_NON_CMS_PRIMARY_PHONE
				, TRG.GEN_NON_CMS_PRIMARY_ORG
				, TRG.GEN_NON_CMS_PRIMARY_ADDR
				, TRG.GEN_CASE_TYPE
				, TRG.GEN_CASE_CATEGORY
				, TRG.GEN_INVESTIGATION
				, TRG.GEN_INVESTIGATE_START_DT
				, TRG.GEN_INVESTIGATE_END_DT
				, TRG.GEN_STD_CONDUCT
				, TRG.GEN_STD_CONDUCT_TYPE
				, TRG.CC_FINAL_ACTION
				, TRG.CC_CASE_COMPLETE_DT
			)
			VALUES
			(
				SRC.ERLR_CASE_NUMBER
				, SRC.GEN_PRIMARY_SPECIALIST
				, SRC.GEN_SECONDARY_SPECIALIST
				, SRC.GEN_CUSTOMER_NAME     
				, SRC.GEN_CUSTOMER_PHONE  
				, SRC.GEN_CUSTOMER_ADMIN_CD
				, SRC.GEN_CUSTOMER_ADMIN_CD_DESC
				, SRC.GEN_EMPLOYEE_NAME
				, SRC.GEN_EMPLOYEE_PHONE
				, SRC.GEN_EMPLOYEE_ADMIN_CD
				, SRC.GEN_EMPLOYEE_ADMIN_CD_DESC
				, SRC.GEN_CASE_DESC
				, SRC.GEN_CASE_STATUS
				, SRC.GEN_CUST_INIT_CONTACT_DT
				, SRC.GEN_PRIMARY_REP_AFFILIATION
				, SRC.GEN_CMS_PRIMARY_REP_ID
				, SRC.GEN_CMS_PRIMARY_REP_PHONE
				, SRC.GEN_NON_CMS_PRIMARY_FNAME
				, SRC.GEN_NON_CMS_PRIMARY_MNAME
				, SRC.GEN_NON_CMS_PRIMARY_LNAME
				, SRC.GEN_NON_CMS_PRIMARY_EMAIL
				, SRC.GEN_NON_CMS_PRIMARY_PHONE
				, SRC.GEN_NON_CMS_PRIMARY_ORG
				, SRC.GEN_NON_CMS_PRIMARY_ADDR
				, SRC.GEN_CASE_TYPE
				, SRC.GEN_CASE_CATEGORY
				, SRC.GEN_INVESTIGATION
				, SRC.GEN_INVESTIGATE_START_DT
				, SRC.GEN_INVESTIGATE_END_DT
				, SRC.GEN_STD_CONDUCT
				, SRC.GEN_STD_CONDUCT_TYPE
				, SRC.CC_FINAL_ACTION
				, SRC.CC_CASE_COMPLETE_DT
			)
			;
		END;

		--------------------------------
		-- ERLR_CNDT_ISSUE table
		--------------------------------
		BEGIN
            MERGE INTO  ERLR_CNDT_ISSUE TRG
            USING
            (
                SELECT
                    V_CASE_NUMBER AS ERLR_CASE_NUMBER
					, X.CI_ACTION_TYPE
					--, X.CI_ADMIN_INVESTIGATORY_LEAVE
					--, X.CI_ADMIN_NOTICE_LEAVE
					, TO_DATE(X.CI_LEAVE_START_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_LEAVE_START_DT
					, TO_DATE(X.CI_LEAVE_END_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_LEAVE_END_DT
					, X.CI_APPROVAL_NAME
					, TO_DATE(X.CI_LEAVE_START_DT_2,'MM/DD/YYYY HH24:MI:SS') AS CI_LEAVE_START_DT_2
					, TO_DATE(X.CI_LEAVE_END_DT_2,'MM/DD/YYYY HH24:MI:SS') AS CI_LEAVE_END_DT_2
					, X.CI_APPROVAL_NAME_2
					, TO_DATE(X.CI_PROP_ACTION_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_PROP_ACTION_ISSUED_DT
					, X.CI_ORAL_PREZ_REQUESTED
					, TO_DATE(X.CI_ORAL_PREZ_DT,'MM/DD/YYYY HH24:MI:SS') AS  CI_ORAL_PREZ_DT
					, X.CI_ORAL_RESPONSE_SUBMITTED
					, TO_DATE(X.CI_RESPONSE_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_RESPONSE_DUE_DT
					, TO_DATE(X.CI_WRITTEN_RESPONSE_SBMT_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_WRITTEN_RESPONSE_SBMT_DT
					, X.CI_POS_TITLE
					, X.CI_PPLAN
					, X.CI_SERIES
					, X.CI_CURRENT_INFO_GRADE
					, X.CI_CURRENT_INFO_STEP
					, X.CI_PROPOSED_POS_TITLE
					, X.CI_PROPOSED_PPLAN
					, X.CI_PROPOSED_SERIES
					, X.CI_PROPOSED_INFO_GRADE
					, X.CI_PROPOSED_INFO_STEP
					, X.CI_FINAL_POS_TITLE
					, X.CI_FINAL_PPLAN
					, X.CI_FINAL_SERIES
					, X.CI_FINAL_INFO_GRADE
					, X.CI_FINAL_INFO_STEP
					, X.CI_DEMO_FINAL_AGNCY_DCSN
					, X.CI_DECIDING_OFFCL
					, TO_DATE(X.CI_DECISION_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_DECISION_ISSUED_DT
					, TO_DATE(X.CI_DEMO_FINAL_AGENCY_EFF_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_DEMO_FINAL_AGENCY_EFF_DT
					, X.CI_NUMB_DAYS
					, X.CI_COUNSEL_TYPE
					, TO_DATE(X.CI_COUNSEL_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_COUNSEL_ISSUED_DT
					, TO_DATE(X.CI_SICK_LEAVE_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SICK_LEAVE_ISSUED_DT
					, TO_DATE(X.CI_RESTRICTION_ISSED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_RESTRICTION_ISSED_DT
					, X.CI_SL_REVIEWED_DT_LIST
					, X.CI_SL_WARNING_DISCUSS_DT_LIST
					, TO_DATE(X.CI_SL_WARN_ISSUE,'MM/DD/YYYY HH24:MI:SS') AS CI_SL_WARN_ISSUE
					, TO_DATE(X.CI_NOTICE_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_NOTICE_ISSUED_DT
					, TO_DATE(X.CI_EFFECTIVE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_EFFECTIVE_DT
					, X.CI_CURRENT_ADMIN_CODE
					, X.CI_RE_ASSIGNMENT_CURR_ORG
					, X.CI_FINAL_ADMIN_CODE
					, X.CI_RE_ASSIGNMENT_FINAL_ORG
					, TO_DATE(X.CI_REMOVAL_PROP_ACTION_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REMOVAL_PROP_ACTION_DT
					, X.CI_EMP_NOTICE_LEAVE_PLACED
					, TO_DATE(X.CI_REMOVAL_NOTICE_START_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REMOVAL_NOTICE_START_DT
					, TO_DATE(X.CI_REMOVAL_NOTICE_END_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REMOVAL_NOTICE_END_DT
					, X.CI_RMVL_ORAL_PREZ_RQSTED
					, TO_DATE(X.CI_REMOVAL_ORAL_PREZ_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REMOVAL_ORAL_PREZ_DT
					, X.CI_RMVL_WRTN_RESPONSE
					, TO_DATE(X.CI_WRITTEN_RESPONSE_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_WRITTEN_RESPONSE_DUE_DT
					, TO_DATE(X.CI_WRITTEN_SUBMITTED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_WRITTEN_SUBMITTED_DT
					, X.CI_RMVL_FINAL_AGNCY_DCSN
					, X.CI_DECIDING_OFFCL_NAME
					, TO_DATE(X.CI_RMVL_DATE_DCSN_ISSUED,'MM/DD/YYYY HH24:MI:SS') AS CI_RMVL_DATE_DCSN_ISSUED
					, TO_DATE(X.CI_REMOVAL_EFFECTIVE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REMOVAL_EFFECTIVE_DT
					, X.CI_RMVL_NUMB_DAYS
					, X.CI_SUSPENTION_TYPE
					, TO_DATE(X.CI_SUSP_PROP_ACTION_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_PROP_ACTION_DT
					, X.CI_SUSP_ORAL_PREZ_REQUESTED
					, TO_DATE(X.CI_SUSP_ORAL_PREZ_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_ORAL_PREZ_DT
					, X.CI_SUSP_WRITTEN_RESP
					, TO_DATE(X.CI_SUSP_WRITTEN_RESP_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_WRITTEN_RESP_DUE_DT
					, TO_DATE(X.CI_SUSP_WRITTEN_RESP_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_WRITTEN_RESP_DT
					, X.CI_SUSP_FINAL_AGNCY_DCSN
					, X.CI_SUSP_DECIDING_OFFCL_NAME
					, TO_DATE(X.CI_SUSP_DECISION_ISSUED_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_DECISION_ISSUED_DT
					, TO_DATE(X.CI_SUSP_EFFECTIVE_DECISION_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_SUSP_EFFECTIVE_DECISION_DT
					, X.CI_SUS_NUMB_DAYS
					, TO_DATE(X.CI_REPRIMAND_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS CI_REPRIMAND_ISSUE_DT
					, X.CI_EMP_APPEAL_DECISION                    
                FROM TBL_FORM_DTL FD
                    , XMLTABLE('/formData/items'
						PASSING FD.FIELD_DATA
						COLUMNS
                            CI_ACTION_TYPE	NVARCHAR2(200)	PATH './item[id="CI_ACTION_TYPE"]/value'
							--, CI_ADMIN_INVESTIGATORY_LEAVE	NVARCHAR2(3)	PATH './item[id="CI_ADMIN_INVESTIGATORY_LEAVE"]/value'
							--, CI_ADMIN_NOTICE_LEAVE	NVARCHAR2(3)	PATH './item[id="CI_ADMIN_NOTICE_LEAVE"]/value'
							, CI_LEAVE_START_DT	NVARCHAR2(10)	PATH './item[id="CI_LEAVE_START_DT"]/value'
							, CI_LEAVE_END_DT	NVARCHAR2(10)	PATH './item[id="CI_LEAVE_END_DT"]/value'
							, CI_APPROVAL_NAME	NVARCHAR2(10)	PATH './item[id="CI_APPROVAL_NAME"]/value/id'
							, CI_LEAVE_START_DT_2	NVARCHAR2(10)	PATH './item[id="CI_LEAVE_START_DT_2"]/value'
							, CI_LEAVE_END_DT_2	NVARCHAR2(10)	PATH './item[id="CI_LEAVE_END_DT_2"]/value'
							, CI_APPROVAL_NAME_2	NVARCHAR2(10)	PATH './item[id="CI_APPROVAL_NAME_2"]/value/id'
							, CI_PROP_ACTION_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_PROP_ACTION_ISSUED_DT"]/value'
							, CI_ORAL_PREZ_REQUESTED	NVARCHAR2(3)	PATH './item[id="CI_ORAL_PREZ_REQUESTED"]/value'
							, CI_ORAL_PREZ_DT	NVARCHAR2(10)	PATH './item[id="CI_ORAL_PREZ_DT"]/value'
							, CI_ORAL_RESPONSE_SUBMITTED	NVARCHAR2(3)	PATH './item[id="CI_ORAL_RESPONSE_SUBMITTED"]/value'
							, CI_RESPONSE_DUE_DT	NVARCHAR2(10)	PATH './item[id="CI_RESPONSE_DUE_DT"]/value'
							, CI_WRITTEN_RESPONSE_SBMT_DT	NVARCHAR2(10)	PATH './item[id="CI_WRITTEN_RESPONSE_SUBMITTED_DT"]/value'
							, CI_POS_TITLE	NVARCHAR2(50)	PATH './item[id="CI_POS_TITLE"]/value'
							, CI_PPLAN	NVARCHAR2(50)	PATH './item[id="CI_PPLAN"]/value'
							, CI_SERIES	NVARCHAR2(50)	PATH './item[id="CI_SERIES"]/value'
							, CI_CURRENT_INFO_GRADE	NVARCHAR2(50)	PATH './item[id="CI_CURRENT_INFO_GRADE"]/value'
							, CI_CURRENT_INFO_STEP	NVARCHAR2(50)	PATH './item[id="CI_CURRENT_INFO_STEP"]/value'
							, CI_PROPOSED_POS_TITLE	NVARCHAR2(50)	PATH './item[id="CI_PROPOSED_POS_TITLE"]/value'
							, CI_PROPOSED_PPLAN	NVARCHAR2(50)	PATH './item[id="CI_PROPOSED_PPLAN"]/value'
							, CI_PROPOSED_SERIES	NVARCHAR2(50)	PATH './item[id="CI_PROPOSED_SERIES"]/value'
							, CI_PROPOSED_INFO_GRADE	NVARCHAR2(50)	PATH './item[id="CI_PROPOSED_INFO_GRADE"]/value'
							, CI_PROPOSED_INFO_STEP	NVARCHAR2(50)	PATH './item[id="CI_PROPOSED_INFO_STEP"]/value'
							, CI_FINAL_POS_TITLE	NVARCHAR2(50)	PATH './item[id="CI_FINAL_POS_TITLE"]/value'
							, CI_FINAL_PPLAN	NVARCHAR2(50)	PATH './item[id="CI_FINAL_PPLAN"]/value'
							, CI_FINAL_SERIES	NVARCHAR2(50)	PATH './item[id="CI_FINAL_SERIES"]/value'
							, CI_FINAL_INFO_GRADE	NVARCHAR2(50)	PATH './item[id="CI_FINAL_INFO_GRADE"]/value'
							, CI_FINAL_INFO_STEP	NVARCHAR2(50)	PATH './item[id="CI_FINAL_INFO_STEP"]/value'
							, CI_DEMO_FINAL_AGNCY_DCSN	NVARCHAR2(200)	PATH './item[id="CI_DEMO_FINAL_AGENCY_DECISION"]/value'
							, CI_DECIDING_OFFCL	NVARCHAR2(10)	PATH './item[id="CI_DECIDING_OFFCL"]/value/id'
							, CI_DECISION_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_DECISION_ISSUED_DT"]/value'
							, CI_DEMO_FINAL_AGENCY_EFF_DT	NVARCHAR2(10)	PATH './item[id="CI_DEMO_FINAL_AGENCY_EFF_DT"]/value'
							, CI_NUMB_DAYS	NUMBER(20,0)	PATH './item[id="CI_NUMB_DAYS"]/value'
							, CI_COUNSEL_TYPE	NVARCHAR2(200)	PATH './item[id="CI_COUNSEL_TYPE"]/value'
							, CI_COUNSEL_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_COUNSEL_ISSUED_DT"]/value'
							, CI_SICK_LEAVE_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_SICK_LEAVE_ISSUED_DT"]/value'
							, CI_RESTRICTION_ISSED_DT	NVARCHAR2(10)	PATH './item[id="CI_RESTRICTION_ISSED_DT"]/value'
							, CI_SL_REVIEWED_DT_LIST	VARCHAR2(4000)	PATH './item[id="CI_SICK_LEAVE_REVIEWED_DT_LIST"]/value'
							, CI_SL_WARNING_DISCUSS_DT_LIST	VARCHAR2(4000)	PATH './item[id="CI_SL_WARNING_DISCUSSION_DT_LIST"]/value'
							, CI_SL_WARN_ISSUE	NVARCHAR2(10)	PATH './item[id="CI_SL_WARN_ISSUE"]/value'
							, CI_NOTICE_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_NOTICE_ISSUED_DT"]/value'
							, CI_EFFECTIVE_DT	NVARCHAR2(10)	PATH './item[id="CI_EFFECTIVE_DT"]/value'
							, CI_CURRENT_ADMIN_CODE	NVARCHAR2(8)	PATH './item[id="CI_CURRENT_ADMIN_CODE"]/value'
							, CI_RE_ASSIGNMENT_CURR_ORG	NVARCHAR2(50)	PATH './item[id="CI_RE_ASSIGNMENT_CURR_ORG"]/value'
							, CI_FINAL_ADMIN_CODE	NVARCHAR2(8)	PATH './item[id="CI_FINAL_ADMIN_CODE"]/value'
							, CI_RE_ASSIGNMENT_FINAL_ORG	NVARCHAR2(50)	PATH './item[id="CI_RE_ASSIGNMENT_FINAL_ORG"]/value'
							, CI_REMOVAL_PROP_ACTION_DT	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_PROP_ACTION_DT"]/value'
							, CI_EMP_NOTICE_LEAVE_PLACED	NVARCHAR2(3)	PATH './item[id="CI_EMP_NOTICE_LEAVE_PLACED"]/value'
							, CI_REMOVAL_NOTICE_START_DT	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_NOTICE_START_DT"]/value'
							, CI_REMOVAL_NOTICE_END_DT	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_NOTICE_END_DT"]/value'
							, CI_RMVL_ORAL_PREZ_RQSTED	NVARCHAR2(3)	PATH './item[id="CI_REMOVAL_ORAL_PREZ_REQUESTED"]/value'
							, CI_REMOVAL_ORAL_PREZ_DT	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_ORAL_PREZ_DT"]/value'
							, CI_RMVL_WRTN_RESPONSE	NVARCHAR2(3)	PATH './item[id="CI_REMOVAL_WRITTEN_RESPONSE"]/value'
							, CI_WRITTEN_RESPONSE_DUE_DT	NVARCHAR2(10)	PATH './item[id="CI_WRITTEN_RESPONSE_DUE_DT"]/value'
							, CI_WRITTEN_SUBMITTED_DT	NVARCHAR2(10)	PATH './item[id="CI_WRITTEN_SUBMITTED_DT"]/value'
							, CI_RMVL_FINAL_AGNCY_DCSN	NVARCHAR2(200)	PATH './item[id="CI_RMVL_FINAL_AGENCY_DECISION"]/value'
							, CI_DECIDING_OFFCL_NAME	NVARCHAR2(10)	PATH './item[id="CI_DECIDING_OFFCL_NAME"]/value/id'
							, CI_RMVL_DATE_DCSN_ISSUED	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_DATE_DECISION_ISSUED"]/value'
							, CI_REMOVAL_EFFECTIVE_DT	NVARCHAR2(10)	PATH './item[id="CI_REMOVAL_EFFECTIVE_DT"]/value'
							, CI_RMVL_NUMB_DAYS	NUMBER(20,0)	PATH './item[id="CI_RMVL_NUMB_DAYS"]/value'
							, CI_SUSPENTION_TYPE	NUMBER(20,0)	PATH './item[id="CI_SUSPENTION_TYPE"]/value'
							, CI_SUSP_PROP_ACTION_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_PROP_ACTION_DT"]/value'
							, CI_SUSP_ORAL_PREZ_REQUESTED	NVARCHAR2(3)	PATH './item[id="CI_SUSP_ORAL_PREZ_REQUESTED"]/value'
							, CI_SUSP_ORAL_PREZ_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_ORAL_PREZ_DT"]/value'
							, CI_SUSP_WRITTEN_RESP	NVARCHAR2(3)	PATH './item[id="CI_SUSP_WRITTEN_RESP"]/value'
							, CI_SUSP_WRITTEN_RESP_DUE_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_WRITTEN_RESP_DUE_DT"]/value'
							, CI_SUSP_WRITTEN_RESP_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_WRITTEN_RESP_DT"]/value'
							, CI_SUSP_FINAL_AGNCY_DCSN	NVARCHAR2(200)	PATH './item[id="CI_SUSP_FINAL_AGENCY_DECISION"]/value'
							, CI_SUSP_DECIDING_OFFCL_NAME	NVARCHAR2(10)	PATH './item[id="CI_SUSP_DECIDING_OFFCL_NAME"]/value/id'
							, CI_SUSP_DECISION_ISSUED_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_DECISION_ISSUED_DT"]/value'
							, CI_SUSP_EFFECTIVE_DECISION_DT	NVARCHAR2(10)	PATH './item[id="CI_SUSP_EFFECTIVE_DECISION_DT"]/value'
							, CI_SUS_NUMB_DAYS	NUMBER(20,0)	PATH './item[id="CI_SUS_NUMB_DAYS"]/value'
							, CI_REPRIMAND_ISSUE_DT	NVARCHAR2(10)	PATH './item[id="CI_REPRIMAND_ISSUE_DT"]/value'
							, CI_EMP_APPEAL_DECISION	NVARCHAR2(3)	PATH './item[id="CI_EMP_APPEAL_DECISION"]/value'
                ) X
			    WHERE FD.PROCID = I_PROCID
            )SRC ON (SRC.ERLR_CASE_NUMBER = TRG.ERLR_CASE_NUMBER)
            WHEN MATCHED THEN UPDATE SET
				--TRG.ERLR_CASE_NUMBER = SRC.ERLR_CASE_NUMBER
				TRG.CI_ACTION_TYPE = SRC.CI_ACTION_TYPE				
				, TRG.CI_LEAVE_START_DT = SRC.CI_LEAVE_START_DT
				, TRG.CI_LEAVE_END_DT = SRC.CI_LEAVE_END_DT
				, TRG.CI_APPROVAL_NAME = SRC.CI_APPROVAL_NAME
				, TRG.CI_LEAVE_START_DT_2 = SRC.CI_LEAVE_START_DT_2
				, TRG.CI_LEAVE_END_DT_2 = SRC.CI_LEAVE_END_DT_2
				, TRG.CI_APPROVAL_NAME_2 = SRC.CI_APPROVAL_NAME_2
				, TRG.CI_PROP_ACTION_ISSUED_DT = SRC.CI_PROP_ACTION_ISSUED_DT
				, TRG.CI_ORAL_PREZ_REQUESTED = SRC.CI_ORAL_PREZ_REQUESTED
				, TRG.CI_ORAL_PREZ_DT = SRC.CI_ORAL_PREZ_DT
				, TRG.CI_ORAL_RESPONSE_SUBMITTED = SRC.CI_ORAL_RESPONSE_SUBMITTED
				, TRG.CI_RESPONSE_DUE_DT = SRC.CI_RESPONSE_DUE_DT
				, TRG.CI_WRITTEN_RESPONSE_SBMT_DT = SRC.CI_WRITTEN_RESPONSE_SBMT_DT
				, TRG.CI_POS_TITLE = SRC.CI_POS_TITLE
				, TRG.CI_PPLAN = SRC.CI_PPLAN
				, TRG.CI_SERIES = SRC.CI_SERIES
				, TRG.CI_CURRENT_INFO_GRADE = SRC.CI_CURRENT_INFO_GRADE
				, TRG.CI_CURRENT_INFO_STEP = SRC.CI_CURRENT_INFO_STEP
				, TRG.CI_PROPOSED_POS_TITLE = SRC.CI_PROPOSED_POS_TITLE
				, TRG.CI_PROPOSED_PPLAN = SRC.CI_PROPOSED_PPLAN
				, TRG.CI_PROPOSED_SERIES = SRC.CI_PROPOSED_SERIES
				, TRG.CI_PROPOSED_INFO_GRADE = SRC.CI_PROPOSED_INFO_GRADE
				, TRG.CI_PROPOSED_INFO_STEP = SRC.CI_PROPOSED_INFO_STEP
				, TRG.CI_FINAL_POS_TITLE = SRC.CI_FINAL_POS_TITLE
				, TRG.CI_FINAL_PPLAN = SRC.CI_FINAL_PPLAN
				, TRG.CI_FINAL_SERIES = SRC.CI_FINAL_SERIES
				, TRG.CI_FINAL_INFO_GRADE = SRC.CI_FINAL_INFO_GRADE
				, TRG.CI_FINAL_INFO_STEP = SRC.CI_FINAL_INFO_STEP
				, TRG.CI_DEMO_FINAL_AGNCY_DCSN = SRC.CI_DEMO_FINAL_AGNCY_DCSN
				, TRG.CI_DECIDING_OFFCL = SRC.CI_DECIDING_OFFCL
				, TRG.CI_DECISION_ISSUED_DT = SRC.CI_DECISION_ISSUED_DT
				, TRG.CI_DEMO_FINAL_AGENCY_EFF_DT = SRC.CI_DEMO_FINAL_AGENCY_EFF_DT
				, TRG.CI_NUMB_DAYS = SRC.CI_NUMB_DAYS
				, TRG.CI_COUNSEL_TYPE = SRC.CI_COUNSEL_TYPE
				, TRG.CI_COUNSEL_ISSUED_DT = SRC.CI_COUNSEL_ISSUED_DT
				, TRG.CI_SICK_LEAVE_ISSUED_DT = SRC.CI_SICK_LEAVE_ISSUED_DT
				, TRG.CI_RESTRICTION_ISSED_DT = SRC.CI_RESTRICTION_ISSED_DT
				, TRG.CI_SL_REVIEWED_DT_LIST = SRC.CI_SL_REVIEWED_DT_LIST
				, TRG.CI_SL_WARNING_DISCUSS_DT_LIST = SRC.CI_SL_WARNING_DISCUSS_DT_LIST
				, TRG.CI_SL_WARN_ISSUE = SRC.CI_SL_WARN_ISSUE
				, TRG.CI_NOTICE_ISSUED_DT = SRC.CI_NOTICE_ISSUED_DT
				, TRG.CI_EFFECTIVE_DT = SRC.CI_EFFECTIVE_DT
				, TRG.CI_CURRENT_ADMIN_CODE = SRC.CI_CURRENT_ADMIN_CODE
				, TRG.CI_RE_ASSIGNMENT_CURR_ORG = SRC.CI_RE_ASSIGNMENT_CURR_ORG
				, TRG.CI_FINAL_ADMIN_CODE = SRC.CI_FINAL_ADMIN_CODE
				, TRG.CI_RE_ASSIGNMENT_FINAL_ORG = SRC.CI_RE_ASSIGNMENT_FINAL_ORG
				, TRG.CI_REMOVAL_PROP_ACTION_DT = SRC.CI_REMOVAL_PROP_ACTION_DT
				, TRG.CI_EMP_NOTICE_LEAVE_PLACED = SRC.CI_EMP_NOTICE_LEAVE_PLACED
				, TRG.CI_REMOVAL_NOTICE_START_DT = SRC.CI_REMOVAL_NOTICE_START_DT
				, TRG.CI_REMOVAL_NOTICE_END_DT = SRC.CI_REMOVAL_NOTICE_END_DT
				, TRG.CI_RMVL_ORAL_PREZ_RQSTED = SRC.CI_RMVL_ORAL_PREZ_RQSTED
				, TRG.CI_REMOVAL_ORAL_PREZ_DT = SRC.CI_REMOVAL_ORAL_PREZ_DT
				, TRG.CI_RMVL_WRTN_RESPONSE = SRC.CI_RMVL_WRTN_RESPONSE
				, TRG.CI_WRITTEN_RESPONSE_DUE_DT = SRC.CI_WRITTEN_RESPONSE_DUE_DT
				, TRG.CI_WRITTEN_SUBMITTED_DT = SRC.CI_WRITTEN_SUBMITTED_DT
				, TRG.CI_RMVL_FINAL_AGNCY_DCSN = SRC.CI_RMVL_FINAL_AGNCY_DCSN
				, TRG.CI_DECIDING_OFFCL_NAME = SRC.CI_DECIDING_OFFCL_NAME
				, TRG.CI_RMVL_DATE_DCSN_ISSUED = SRC.CI_RMVL_DATE_DCSN_ISSUED
				, TRG.CI_REMOVAL_EFFECTIVE_DT = SRC.CI_REMOVAL_EFFECTIVE_DT
				, TRG.CI_RMVL_NUMB_DAYS = SRC.CI_RMVL_NUMB_DAYS
				, TRG.CI_SUSPENTION_TYPE = SRC.CI_SUSPENTION_TYPE
				, TRG.CI_SUSP_PROP_ACTION_DT = SRC.CI_SUSP_PROP_ACTION_DT
				, TRG.CI_SUSP_ORAL_PREZ_REQUESTED = SRC.CI_SUSP_ORAL_PREZ_REQUESTED
				, TRG.CI_SUSP_ORAL_PREZ_DT = SRC.CI_SUSP_ORAL_PREZ_DT
				, TRG.CI_SUSP_WRITTEN_RESP = SRC.CI_SUSP_WRITTEN_RESP
				, TRG.CI_SUSP_WRITTEN_RESP_DUE_DT = SRC.CI_SUSP_WRITTEN_RESP_DUE_DT
				, TRG.CI_SUSP_WRITTEN_RESP_DT = SRC.CI_SUSP_WRITTEN_RESP_DT
				, TRG.CI_SUSP_FINAL_AGNCY_DCSN = SRC.CI_SUSP_FINAL_AGNCY_DCSN
				, TRG.CI_SUSP_DECIDING_OFFCL_NAME = SRC.CI_SUSP_DECIDING_OFFCL_NAME
				, TRG.CI_SUSP_DECISION_ISSUED_DT = SRC.CI_SUSP_DECISION_ISSUED_DT
				, TRG.CI_SUSP_EFFECTIVE_DECISION_DT = SRC.CI_SUSP_EFFECTIVE_DECISION_DT
				, TRG.CI_SUS_NUMB_DAYS = SRC.CI_SUS_NUMB_DAYS
				, TRG.CI_REPRIMAND_ISSUE_DT = SRC.CI_REPRIMAND_ISSUE_DT
				, TRG.CI_EMP_APPEAL_DECISION = SRC.CI_EMP_APPEAL_DECISION                    
            WHEN NOT MATCHED THEN INSERT
            (
                TRG.ERLR_CASE_NUMBER
				, TRG.CI_ACTION_TYPE				
				, TRG.CI_LEAVE_START_DT
				, TRG.CI_LEAVE_END_DT
				, TRG.CI_APPROVAL_NAME
				, TRG.CI_LEAVE_START_DT_2
				, TRG.CI_LEAVE_END_DT_2
				, TRG.CI_APPROVAL_NAME_2
				, TRG.CI_PROP_ACTION_ISSUED_DT
				, TRG.CI_ORAL_PREZ_REQUESTED
				, TRG.CI_ORAL_PREZ_DT
				, TRG.CI_ORAL_RESPONSE_SUBMITTED
				, TRG.CI_RESPONSE_DUE_DT
				, TRG.CI_WRITTEN_RESPONSE_SBMT_DT
				, TRG.CI_POS_TITLE
				, TRG.CI_PPLAN
				, TRG.CI_SERIES
				, TRG.CI_CURRENT_INFO_GRADE
				, TRG.CI_CURRENT_INFO_STEP
				, TRG.CI_PROPOSED_POS_TITLE
				, TRG.CI_PROPOSED_PPLAN
				, TRG.CI_PROPOSED_SERIES
				, TRG.CI_PROPOSED_INFO_GRADE
				, TRG.CI_PROPOSED_INFO_STEP
				, TRG.CI_FINAL_POS_TITLE
				, TRG.CI_FINAL_PPLAN
				, TRG.CI_FINAL_SERIES
				, TRG.CI_FINAL_INFO_GRADE
				, TRG.CI_FINAL_INFO_STEP
				, TRG.CI_DEMO_FINAL_AGNCY_DCSN
				, TRG.CI_DECIDING_OFFCL
				, TRG.CI_DECISION_ISSUED_DT
				, TRG.CI_DEMO_FINAL_AGENCY_EFF_DT
				, TRG.CI_NUMB_DAYS
				, TRG.CI_COUNSEL_TYPE
				, TRG.CI_COUNSEL_ISSUED_DT
				, TRG.CI_SICK_LEAVE_ISSUED_DT
				, TRG.CI_RESTRICTION_ISSED_DT
				, TRG.CI_SL_REVIEWED_DT_LIST
				, TRG.CI_SL_WARNING_DISCUSS_DT_LIST
				, TRG.CI_SL_WARN_ISSUE
				, TRG.CI_NOTICE_ISSUED_DT
				, TRG.CI_EFFECTIVE_DT
				, TRG.CI_CURRENT_ADMIN_CODE
				, TRG.CI_RE_ASSIGNMENT_CURR_ORG
				, TRG.CI_FINAL_ADMIN_CODE
				, TRG.CI_RE_ASSIGNMENT_FINAL_ORG
				, TRG.CI_REMOVAL_PROP_ACTION_DT
				, TRG.CI_EMP_NOTICE_LEAVE_PLACED
				, TRG.CI_REMOVAL_NOTICE_START_DT
				, TRG.CI_REMOVAL_NOTICE_END_DT
				, TRG.CI_RMVL_ORAL_PREZ_RQSTED
				, TRG.CI_REMOVAL_ORAL_PREZ_DT
				, TRG.CI_RMVL_WRTN_RESPONSE
				, TRG.CI_WRITTEN_RESPONSE_DUE_DT
				, TRG.CI_WRITTEN_SUBMITTED_DT
				, TRG.CI_RMVL_FINAL_AGNCY_DCSN
				, TRG.CI_DECIDING_OFFCL_NAME
				, TRG.CI_RMVL_DATE_DCSN_ISSUED
				, TRG.CI_REMOVAL_EFFECTIVE_DT
				, TRG.CI_RMVL_NUMB_DAYS
				, TRG.CI_SUSPENTION_TYPE
				, TRG.CI_SUSP_PROP_ACTION_DT
				, TRG.CI_SUSP_ORAL_PREZ_REQUESTED
				, TRG.CI_SUSP_ORAL_PREZ_DT
				, TRG.CI_SUSP_WRITTEN_RESP
				, TRG.CI_SUSP_WRITTEN_RESP_DUE_DT
				, TRG.CI_SUSP_WRITTEN_RESP_DT
				, TRG.CI_SUSP_FINAL_AGNCY_DCSN
				, TRG.CI_SUSP_DECIDING_OFFCL_NAME
				, TRG.CI_SUSP_DECISION_ISSUED_DT
				, TRG.CI_SUSP_EFFECTIVE_DECISION_DT
				, TRG.CI_SUS_NUMB_DAYS
				, TRG.CI_REPRIMAND_ISSUE_DT
				, TRG.CI_EMP_APPEAL_DECISION               
            )
            VALUES
            (
                SRC.ERLR_CASE_NUMBER
				, SRC.CI_ACTION_TYPE				
				, SRC.CI_LEAVE_START_DT
				, SRC.CI_LEAVE_END_DT
				, SRC.CI_APPROVAL_NAME
				, SRC.CI_LEAVE_START_DT_2
				, SRC.CI_LEAVE_END_DT_2
				, SRC.CI_APPROVAL_NAME_2
				, SRC.CI_PROP_ACTION_ISSUED_DT
				, SRC.CI_ORAL_PREZ_REQUESTED
				, SRC.CI_ORAL_PREZ_DT
				, SRC.CI_ORAL_RESPONSE_SUBMITTED
				, SRC.CI_RESPONSE_DUE_DT
				, SRC.CI_WRITTEN_RESPONSE_SBMT_DT
				, SRC.CI_POS_TITLE
				, SRC.CI_PPLAN
				, SRC.CI_SERIES
				, SRC.CI_CURRENT_INFO_GRADE
				, SRC.CI_CURRENT_INFO_STEP
				, SRC.CI_PROPOSED_POS_TITLE
				, SRC.CI_PROPOSED_PPLAN
				, SRC.CI_PROPOSED_SERIES
				, SRC.CI_PROPOSED_INFO_GRADE
				, SRC.CI_PROPOSED_INFO_STEP
				, SRC.CI_FINAL_POS_TITLE
				, SRC.CI_FINAL_PPLAN
				, SRC.CI_FINAL_SERIES
				, SRC.CI_FINAL_INFO_GRADE
				, SRC.CI_FINAL_INFO_STEP
				, SRC.CI_DEMO_FINAL_AGNCY_DCSN
				, SRC.CI_DECIDING_OFFCL
				, SRC.CI_DECISION_ISSUED_DT
				, SRC.CI_DEMO_FINAL_AGENCY_EFF_DT
				, SRC.CI_NUMB_DAYS
				, SRC.CI_COUNSEL_TYPE
				, SRC.CI_COUNSEL_ISSUED_DT
				, SRC.CI_SICK_LEAVE_ISSUED_DT
				, SRC.CI_RESTRICTION_ISSED_DT
				, SRC.CI_SL_REVIEWED_DT_LIST
				, SRC.CI_SL_WARNING_DISCUSS_DT_LIST
				, SRC.CI_SL_WARN_ISSUE
				, SRC.CI_NOTICE_ISSUED_DT
				, SRC.CI_EFFECTIVE_DT
				, SRC.CI_CURRENT_ADMIN_CODE
				, SRC.CI_RE_ASSIGNMENT_CURR_ORG
				, SRC.CI_FINAL_ADMIN_CODE
				, SRC.CI_RE_ASSIGNMENT_FINAL_ORG
				, SRC.CI_REMOVAL_PROP_ACTION_DT
				, SRC.CI_EMP_NOTICE_LEAVE_PLACED
				, SRC.CI_REMOVAL_NOTICE_START_DT
				, SRC.CI_REMOVAL_NOTICE_END_DT
				, SRC.CI_RMVL_ORAL_PREZ_RQSTED
				, SRC.CI_REMOVAL_ORAL_PREZ_DT
				, SRC.CI_RMVL_WRTN_RESPONSE
				, SRC.CI_WRITTEN_RESPONSE_DUE_DT
				, SRC.CI_WRITTEN_SUBMITTED_DT
				, SRC.CI_RMVL_FINAL_AGNCY_DCSN
				, SRC.CI_DECIDING_OFFCL_NAME
				, SRC.CI_RMVL_DATE_DCSN_ISSUED
				, SRC.CI_REMOVAL_EFFECTIVE_DT
				, SRC.CI_RMVL_NUMB_DAYS
				, SRC.CI_SUSPENTION_TYPE
				, SRC.CI_SUSP_PROP_ACTION_DT
				, SRC.CI_SUSP_ORAL_PREZ_REQUESTED
				, SRC.CI_SUSP_ORAL_PREZ_DT
				, SRC.CI_SUSP_WRITTEN_RESP
				, SRC.CI_SUSP_WRITTEN_RESP_DUE_DT
				, SRC.CI_SUSP_WRITTEN_RESP_DT
				, SRC.CI_SUSP_FINAL_AGNCY_DCSN
				, SRC.CI_SUSP_DECIDING_OFFCL_NAME
				, SRC.CI_SUSP_DECISION_ISSUED_DT
				, SRC.CI_SUSP_EFFECTIVE_DECISION_DT
				, SRC.CI_SUS_NUMB_DAYS
				, SRC.CI_REPRIMAND_ISSUE_DT
				, SRC.CI_EMP_APPEAL_DECISION               
            );

		END;

        --------------------------------
		-- ERLR_PERF_ISSUE table
		--------------------------------
		BEGIN
            MERGE INTO  ERLR_PERF_ISSUE TRG
            USING
            (
                SELECT
                    V_CASE_NUMBER AS ERLR_CASE_NUMBER
                    , X.PI_ACTION_TYPE
					, TO_DATE(X.PI_NEXT_WGI_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_NEXT_WGI_DUE_DT	
					, TO_DATE(X.PI_PERF_COUNSEL_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PERF_COUNSEL_ISSUE_DT	
					, X.PI_CNSL_GRV_DECISION
					, TO_DATE(X.PI_DMTN_PRPS_ACTN_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_PRPS_ACTN_ISSUE_DT	
					, X.PI_DMTN_ORAL_PRSNT_REQ
					, TO_DATE(X.PI_DMTN_ORAL_PRSNT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_ORAL_PRSNT_DT	
					, X.PI_DMTN_WRTN_RESP_SBMT
					, TO_DATE(X.PI_DMTN_WRTN_RESP_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_WRTN_RESP_DUE_DT	
					, TO_DATE(X.PI_DMTN_WRTN_RESP_SBMT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_WRTN_RESP_SBMT_DT	
					, X.PI_DMTN_CUR_POS_TITLE
					, X.PI_DMTN_CUR_PAY_PLAN
					, X.PI_DMTN_CUR_JOB_SERIES
					, X.PI_DMTN_CUR_GRADE
					, X.PI_DMTN_CUR_STEP
					, X.PI_DMTN_PRPS_POS_TITLE
					, X.PI_DMTN_PRPS_PAY_PLAN
					, X.PI_DMTN_PRPS_JOB_SERIES
					, X.PI_DMTN_PRPS_GRADE
					, X.PI_DMTN_PRP_STEP
					, X.PI_DMTN_FIN_POS_TITLE
					, X.PI_DMTN_FIN_PAY_PLAN
					, X.PI_DMTN_FIN_JOB_SERIES
					, X.PI_DMTN_FIN_GRADE
					, X.PI_DMTN_FIN_STEP
					, X.PI_DMTN_FIN_AGCY_DECISION
					, X.PI_DMTN_FIN_DECIDING_OFC
					, TO_DATE(X.PI_DMTN_FIN_DECISION_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_FIN_DECISION_ISSUE_DT	
					, TO_DATE(X.PI_DMTN_DECISION_EFF_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_DMTN_DECISION_EFF_DT	
					, X.PI_DMTN_APPEAL_DECISION
					, X.PI_PIP_RSNBL_ACMDTN
					, X.PI_PIP_EMPL_SBMT_MEDDOC
					, X.PI_PIP_DOC_SBMT_FOH_RVW
					, X.PI_PIP_WGI_WTHLD
					, TO_DATE(X.PI_PIP_WGI_RVW_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_WGI_RVW_DT	
					, X.PI_PIP_MEDDOC_RVW_OUTCOME
					, TO_DATE(X.PI_PIP_START_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_START_DT
					, TO_DATE(X.PI_PIP_END_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_END_DT	
					, TO_DATE(X.PI_PIP_EXT_END_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_EXT_END_DT	
					, X.PI_PIP_EXT_END_REASON
					, TO_DATE(X.PI_PIP_EXT_END_NOTIFY_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_EXT_END_NOTIFY_DT	
					, X.PI_PIP_EXT_DT_LIST	
					, TO_DATE(X.PI_PIP_ACTUAL_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_ACTUAL_DT	
					, X.PI_PIP_END_PRIOR_TO_PLAN
					, X.PI_PIP_END_PRIOR_TO_PLAN_RSN
					, X.PI_PIP_SUCCESS_CMPLT
					, TO_DATE(X.PI_PIP_PMAP_RTNG_SIGN_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_PMAP_RTNG_SIGN_DT	
					, TO_DATE(X.PI_PIP_PMAP_RVW_SIGN_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_PMAP_RVW_SIGN_DT	
					, X.PI_PIP_PRPS_ACTN	
					, TO_DATE(X.PI_PIP_PRPS_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_PRPS_ISSUE_DT	
					, X.PI_PIP_ORAL_PRSNT_REQ	
					, TO_DATE(X.PI_PIP_ORAL_PRSNT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_ORAL_PRSNT_DT	
					, X.PI_PIP_WRTN_RESP_SBMT	
					, TO_DATE(X.PI_PIP_WRTN_RESP_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_WRTN_RESP_DUE_DT	
					, TO_DATE(X.PI_PIP_WRTN_SBMT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_WRTN_SBMT_DT	
					, X.PI_PIP_FIN_AGCY_DECISION
					, X.PI_PIP_DECIDING_OFFICAL
					, TO_DATE(X.PI_PIP_FIN_AGCY_DECISION_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_FIN_AGCY_DECISION_DT	
					, TO_DATE(X.PI_PIP_DECISION_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_DECISION_ISSUE_DT	
					, TO_DATE(X.PI_PIP_EFF_ACTN_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_PIP_EFF_ACTN_DT	
					, X.PI_PIP_EMPL_GRIEVANCE	
					, X.PI_PIP_APPEAL_DECISION
					, TO_DATE(X.PI_REASGN_NOTICE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_REASGN_NOTICE_DT	
					, TO_DATE(X.PI_REASGN_EFF_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_REASGN_EFF_DT	
					, X.PI_REASGN_CUR_ADMIN_CD
					, X.PI_REASGN_CUR_ORG_NM	
					, X.PI_REASGN_FIN_ADMIN_CD
					, X.PI_REASGN_FIN_ORG_NM	
					, TO_DATE(X.PI_RMV_PRPS_ACTN_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_PRPS_ACTN_ISSUE_DT	
					, X.PI_RMV_EMPL_NOTC_LEV	
					, TO_DATE(X.PI_RMV_NOTC_LEV_START_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_NOTC_LEV_START_DT	
					, TO_DATE(X.PI_RMV_NOTC_LEV_END_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_NOTC_LEV_END_DT	
					, X.PI_RMV_ORAL_PRSNT_REQ	
					, TO_DATE(X.PI_RMV_ORAL_PRSNT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_ORAL_PRSNT_DT	
					, TO_DATE(X.PI_RMV_WRTN_RESP_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_WRTN_RESP_DUE_DT	
					, TO_DATE(X.PI_RMV_WRTN_RESP_SBMT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_WRTN_RESP_SBMT_DT	
					, X.PI_RMV_FIN_AGCY_DECISION	
					, X.PI_RMV_FIN_DECIDING_OFC	
					, TO_DATE(X.PI_RMV_DECISION_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_DECISION_ISSUE_DT	
					, TO_DATE(X.PI_RMV_EFF_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_RMV_EFF_DT	
					, X.PI_RMV_NUM_DAYS	
					, X.PI_RMV_APPEAL_DECISION	
					, X.PI_WRTN_NRTV_RVW_TYPE	
					, TO_DATE(X.PI_WNR_SPCLST_RVW_CMPLT_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_WNR_SPCLST_RVW_CMPLT_DT	
					, TO_DATE(X.PI_WNR_MGR_RVW_RTNG_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_WNR_MGR_RVW_RTNG_DT	
					, X.PI_WNR_CRITICAL_ELM	
					, X.PI_WNR_FIN_RATING
					, TO_DATE(X.PI_WNR_RVW_OFC_CONCUR_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_WNR_RVW_OFC_CONCUR_DT	
					, X.PI_WNR_WGI_WTHLD
					, TO_DATE(X.PI_WNR_WGI_RVW_DT,'MM/DD/YYYY HH24:MI:SS') AS PI_WNR_WGI_RVW_DT	
                FROM TBL_FORM_DTL FD
                    , XMLTABLE('/formData/items'
						PASSING FD.FIELD_DATA
						COLUMNS
                            PI_ACTION_TYPE	NUMBER(20,0)	PATH './item[id="PI_ACTION_TYPE"]/value'
							, PI_NEXT_WGI_DUE_DT	VARCHAR2(10)	PATH './item[id="PI_NEXT_WGI_DUE_DT"]/value'
							, PI_PERF_COUNSEL_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_PERF_COUNSEL_ISSUE_DT"]/value'
							, PI_CNSL_GRV_DECISION	VARCHAR2(3)	PATH './item[id="PI_CNSL_GRV_DECISION"]/value'
							, PI_DMTN_PRPS_ACTN_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_PRPS_ACTN_ISSUE_DT"]/value'
							, PI_DMTN_ORAL_PRSNT_REQ	VARCHAR2(3)	PATH './item[id="PI_DMTN_ORAL_PRSNT_REQ"]/value'
							, PI_DMTN_ORAL_PRSNT_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_ORAL_PRSNT_DT"]/value'
							, PI_DMTN_WRTN_RESP_SBMT	VARCHAR2(3)	PATH './item[id="PI_DMTN_WRTN_RESP_SBMT"]/value'
							, PI_DMTN_WRTN_RESP_DUE_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_WRTN_RESP_DUE_DT"]/value'
							, PI_DMTN_WRTN_RESP_SBMT_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_WRTN_RESP_SBMT_DT"]/value'
							, PI_DMTN_CUR_POS_TITLE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_CUR_POS_TITLE"]/value'
							, PI_DMTN_CUR_PAY_PLAN	NVARCHAR2(50)	PATH './item[id="PI_DMTN_CUR_PAY_PLAN"]/value'
							, PI_DMTN_CUR_JOB_SERIES	NVARCHAR2(50)	PATH './item[id="PI_DMTN_CUR_JOB_SERIES"]/value'
							, PI_DMTN_CUR_GRADE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_CUR_GRADE"]/value'
							, PI_DMTN_CUR_STEP	NVARCHAR2(50)	PATH './item[id="PI_DMTN_CUR_STEP"]/value'
							, PI_DMTN_PRPS_POS_TITLE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_PRPS_POS_TITLE"]/value'
							, PI_DMTN_PRPS_PAY_PLAN	NVARCHAR2(50)	PATH './item[id="PI_DMTN_PRPS_PAY_PLAN"]/value'
							, PI_DMTN_PRPS_JOB_SERIES	NVARCHAR2(50)	PATH './item[id="PI_DMTN_PRPS_JOB_SERIES"]/value'
							, PI_DMTN_PRPS_GRADE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_PRPS_GRADE"]/value'
							, PI_DMTN_PRP_STEP	NVARCHAR2(50)	PATH './item[id="PI_DMTN_PRP_STEP"]/value'
							, PI_DMTN_FIN_POS_TITLE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_FIN_POS_TITLE"]/value'
							, PI_DMTN_FIN_PAY_PLAN	NVARCHAR2(50)	PATH './item[id="PI_DMTN_FIN_PAY_PLAN"]/value'
							, PI_DMTN_FIN_JOB_SERIES	NVARCHAR2(50)	PATH './item[id="PI_DMTN_FIN_JOB_SERIES"]/value'
							, PI_DMTN_FIN_GRADE	NVARCHAR2(50)	PATH './item[id="PI_DMTN_FIN_GRADE"]/value'
							, PI_DMTN_FIN_STEP	NVARCHAR2(50)	PATH './item[id="PI_DMTN_FIN_STEP"]/value'
							, PI_DMTN_FIN_AGCY_DECISION	NUMBER(20,0)	PATH './item[id="PI_DMTN_FIN_AGCY_DECISION"]/value'
							, PI_DMTN_FIN_DECIDING_OFC NVARCHAR2(10)	PATH './item[id="PI_DMTN_FIN_DECIDING_OFC"]/value/id'
							, PI_DMTN_FIN_DECISION_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_FIN_DECISION_ISSUE_DT"]/value'
							, PI_DMTN_DECISION_EFF_DT	VARCHAR2(10)	PATH './item[id="PI_DMTN_DECISION_EFF_DT"]/value'
							, PI_DMTN_APPEAL_DECISION	VARCHAR2(3)	PATH './item[id="PI_DMTN_APPEAL_DECISION"]/value'
							, PI_PIP_RSNBL_ACMDTN	VARCHAR2(3)	PATH './item[id="PI_PIP_RSNBL_ACMDTN"]/value'
							, PI_PIP_EMPL_SBMT_MEDDOC	VARCHAR2(3)	PATH './item[id="PI_PIP_EMPL_SBMT_MEDDOC"]/value'
							, PI_PIP_DOC_SBMT_FOH_RVW	VARCHAR2(3)	PATH './item[id="PI_PIP_DOC_SBMT_FOH_RVW"]/value'
							, PI_PIP_WGI_WTHLD	VARCHAR2(3)	PATH './item[id="PI_PIP_WGI_WTHLD"]/value'
							, PI_PIP_WGI_RVW_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_WGI_RVW_DT"]/value'
							, PI_PIP_MEDDOC_RVW_OUTCOME	NVARCHAR2(140)	PATH './item[id="PI_PIP_MEDDOC_RVW_OUTCOME"]/value'
							, PI_PIP_START_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_START_DT"]/value'
							, PI_PIP_END_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_END_DT"]/value'
							, PI_PIP_EXT_END_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_EXT_END_DT"]/value'
							, PI_PIP_EXT_END_REASON	NVARCHAR2(200)	PATH './item[id="PI_PIP_EXT_END_REASON"]/value'
							, PI_PIP_EXT_END_NOTIFY_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_EXT_END_NOTIFY_DT"]/value'
							, PI_PIP_EXT_DT_LIST	VARCHAR2(4000)	PATH './item[id="PI_PIP_EXT_DT_LIST"]/value'
							, PI_PIP_ACTUAL_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_ACTUAL_DT"]/value'
							, PI_PIP_END_PRIOR_TO_PLAN	VARCHAR2(3)	PATH './item[id="PI_PIP_END_PRIOR_TO_PLAN"]/value'
							, PI_PIP_END_PRIOR_TO_PLAN_RSN	NUMBER(20,0)	PATH './item[id="PI_PIP_END_PRIOR_TO_PLAN_RSN"]/value'
							, PI_PIP_SUCCESS_CMPLT	VARCHAR2(3)	PATH './item[id="PI_PIP_SUCCESS_CMPLT"]/value'
							, PI_PIP_PMAP_RTNG_SIGN_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_PMAP_RTNG_SIGN_DT"]/value'
							, PI_PIP_PMAP_RVW_SIGN_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_PMAP_RVW_SIGN_DT"]/value'
							, PI_PIP_PRPS_ACTN	NUMBER(20,0)	PATH './item[id="PI_PIP_PRPS_ACTN"]/value'
							, PI_PIP_PRPS_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_PRPS_ISSUE_DT"]/value'
							, PI_PIP_ORAL_PRSNT_REQ	VARCHAR2(3)	PATH './item[id="PI_PIP_ORAL_PRSNT_REQ"]/value'
							, PI_PIP_ORAL_PRSNT_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_ORAL_PRSNT_DT"]/value'
							, PI_PIP_WRTN_RESP_SBMT	VARCHAR2(3)	PATH './item[id="PI_PIP_WRTN_RESP_SBMT"]/value'
							, PI_PIP_WRTN_RESP_DUE_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_WRTN_RESP_DUE_DT"]/value'
							, PI_PIP_WRTN_SBMT_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_WRTN_SBMT_DT"]/value'
							, PI_PIP_FIN_AGCY_DECISION	NUMBER(20,0)	PATH './item[id="PI_PIP_FIN_AGCY_DECISION"]/value'
							, PI_PIP_DECIDING_OFFICAL	NVARCHAR2(10)	PATH './item[id="PI_PIP_DECIDING_OFFICAL"]/value/id'
							, PI_PIP_FIN_AGCY_DECISION_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_FIN_AGCY_DECISION_DT"]/value'
							, PI_PIP_DECISION_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_DECISION_ISSUE_DT"]/value'
							, PI_PIP_EFF_ACTN_DT	VARCHAR2(10)	PATH './item[id="PI_PIP_EFF_ACTN_DT"]/value'
							, PI_PIP_EMPL_GRIEVANCE	VARCHAR2(3)	PATH './item[id="PI_PIP_EMPL_GRIEVANCE"]/value'
							, PI_PIP_APPEAL_DECISION	VARCHAR2(3)	PATH './item[id="PI_PIP_APPEAL_DECISION"]/value'
							, PI_REASGN_NOTICE_DT	VARCHAR2(10)	PATH './item[id="PI_REASGN_NOTICE_DT"]/value'
							, PI_REASGN_EFF_DT	VARCHAR2(10)	PATH './item[id="PI_REASGN_EFF_DT"]/value'
							, PI_REASGN_CUR_ADMIN_CD	NVARCHAR2(8)	PATH './item[id="PI_REASGN_CUR_ADMIN_CD"]/value'
							, PI_REASGN_CUR_ORG_NM	NVARCHAR2(50)	PATH './item[id="PI_REASGN_CUR_ORG_NM"]/value'
							, PI_REASGN_FIN_ADMIN_CD	NVARCHAR2(8)	PATH './item[id="PI_REASGN_FIN_ADMIN_CD"]/value'
							, PI_REASGN_FIN_ORG_NM	NVARCHAR2(50)	PATH './item[id="PI_REASGN_FIN_ORG_NM"]/value'
							, PI_RMV_PRPS_ACTN_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_PRPS_ACTN_ISSUE_DT"]/value'
							, PI_RMV_EMPL_NOTC_LEV	VARCHAR2(3)	PATH './item[id="PI_RMV_EMPL_NOTC_LEV"]/value'
							, PI_RMV_NOTC_LEV_START_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_NOTC_LEV_START_DT"]/value'
							, PI_RMV_NOTC_LEV_END_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_NOTC_LEV_END_DT"]/value'
							, PI_RMV_ORAL_PRSNT_REQ	VARCHAR2(3)	PATH './item[id="PI_RMV_ORAL_PRSNT_REQ"]/value'
							, PI_RMV_ORAL_PRSNT_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_ORAL_PRSNT_DT"]/value'
							, PI_RMV_WRTN_RESP_DUE_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_WRTN_RESP_DUE_DT"]/value'
							, PI_RMV_WRTN_RESP_SBMT_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_WRTN_RESP_SBMT_DT"]/value'
							, PI_RMV_FIN_AGCY_DECISION	NUMBER(20,0)	PATH './item[id="PI_RMV_FIN_AGCY_DECISION"]/value'
							, PI_RMV_FIN_DECIDING_OFC	NVARCHAR2(10)	PATH './item[id="PI_RMV_FIN_DECIDING_OFC"]/value/id'
							, PI_RMV_DECISION_ISSUE_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_DECISION_ISSUE_DT"]/value'
							, PI_RMV_EFF_DT	VARCHAR2(10)	PATH './item[id="PI_RMV_EFF_DT"]/value'
							, PI_RMV_NUM_DAYS	NUMBER(20,0)	PATH './item[id="PI_RMV_NUM_DAYS"]/value'
							, PI_RMV_APPEAL_DECISION	VARCHAR2(3)	PATH './item[id="PI_RMV_APPEAL_DECISION"]/value'
							, PI_WRTN_NRTV_RVW_TYPE	NUMBER(20,0)	PATH './item[id="PI_WRTN_NRTV_RVW_TYPE"]/value'
							, PI_WNR_SPCLST_RVW_CMPLT_DT	VARCHAR2(10)	PATH './item[id="PI_WNR_SPCLST_RVW_CMPLT_DT"]/value'
							, PI_WNR_MGR_RVW_RTNG_DT VARCHAR2(10)	PATH './item[id="PI_WNR_MGR_RVW_RTNG_DT"]/value'
							, PI_WNR_CRITICAL_ELM	NVARCHAR2(250)	PATH './item[id="PI_WNR_CRITICAL_ELM"]/value'
							, PI_WNR_FIN_RATING	NVARCHAR2(200)	PATH './item[id="PI_WNR_FIN_RATING"]/value'
							, PI_WNR_RVW_OFC_CONCUR_DT	VARCHAR2(10)	PATH './item[id="PI_WNR_RVW_OFC_CONCUR_DT"]/value'
							, PI_WNR_WGI_WTHLD	VARCHAR2(3)	PATH './item[id="PI_WNR_WGI_WTHLD"]/value'
							, PI_WNR_WGI_RVW_DT	VARCHAR2(10)	PATH './item[id="PI_WNR_WGI_RVW_DT"]/value'
                ) X
			    WHERE FD.PROCID = I_PROCID
            )SRC ON (SRC.ERLR_CASE_NUMBER = TRG.ERLR_CASE_NUMBER)
            WHEN MATCHED THEN UPDATE SET
				TRG.PI_ACTION_TYPE = SRC.PI_ACTION_TYPE
				, TRG.PI_NEXT_WGI_DUE_DT = SRC.PI_NEXT_WGI_DUE_DT 	
				, TRG.PI_PERF_COUNSEL_ISSUE_DT	= SRC.PI_PERF_COUNSEL_ISSUE_DT
				, TRG.PI_CNSL_GRV_DECISION = SRC.PI_CNSL_GRV_DECISION
				, TRG.PI_DMTN_PRPS_ACTN_ISSUE_DT = SRC.PI_DMTN_PRPS_ACTN_ISSUE_DT	
				, TRG.PI_DMTN_ORAL_PRSNT_REQ = SRC.PI_DMTN_ORAL_PRSNT_REQ
				, TRG.PI_DMTN_ORAL_PRSNT_DT	= SRC.PI_DMTN_ORAL_PRSNT_DT
				, TRG.PI_DMTN_WRTN_RESP_SBMT = SRC.PI_DMTN_WRTN_RESP_SBMT
				, TRG.PI_DMTN_WRTN_RESP_DUE_DT	= SRC.PI_DMTN_WRTN_RESP_DUE_DT
				, TRG.PI_DMTN_WRTN_RESP_SBMT_DT	= SRC.PI_DMTN_WRTN_RESP_SBMT_DT
				, TRG.PI_DMTN_CUR_POS_TITLE = SRC.PI_DMTN_CUR_POS_TITLE
				, TRG.PI_DMTN_CUR_PAY_PLAN = SRC.PI_DMTN_CUR_PAY_PLAN
				, TRG.PI_DMTN_CUR_JOB_SERIES = SRC.PI_DMTN_CUR_JOB_SERIES
				, TRG.PI_DMTN_CUR_GRADE = SRC.PI_DMTN_CUR_GRADE
				, TRG.PI_DMTN_CUR_STEP = SRC.PI_DMTN_CUR_STEP
				, TRG.PI_DMTN_PRPS_POS_TITLE = SRC.PI_DMTN_PRPS_POS_TITLE
				, TRG.PI_DMTN_PRPS_PAY_PLAN = SRC.PI_DMTN_PRPS_PAY_PLAN
				, TRG.PI_DMTN_PRPS_JOB_SERIES = SRC.PI_DMTN_PRPS_JOB_SERIES
				, TRG.PI_DMTN_PRPS_GRADE = SRC.PI_DMTN_PRPS_GRADE
				, TRG.PI_DMTN_PRP_STEP = SRC.PI_DMTN_PRP_STEP
				, TRG.PI_DMTN_FIN_POS_TITLE = SRC.PI_DMTN_FIN_POS_TITLE
				, TRG.PI_DMTN_FIN_PAY_PLAN = SRC.PI_DMTN_FIN_PAY_PLAN
				, TRG.PI_DMTN_FIN_JOB_SERIES = SRC.PI_DMTN_FIN_JOB_SERIES
				, TRG.PI_DMTN_FIN_GRADE = SRC.PI_DMTN_FIN_GRADE
				, TRG.PI_DMTN_FIN_STEP = SRC.PI_DMTN_FIN_STEP
				, TRG.PI_DMTN_FIN_AGCY_DECISION = SRC.PI_DMTN_FIN_AGCY_DECISION
				, TRG.PI_DMTN_FIN_DECIDING_OFC = SRC.PI_DMTN_FIN_DECIDING_OFC
				, TRG.PI_DMTN_FIN_DECISION_ISSUE_DT = SRC.PI_DMTN_FIN_DECISION_ISSUE_DT		
				, TRG.PI_DMTN_DECISION_EFF_DT = SRC.PI_DMTN_DECISION_EFF_DT	
				, TRG.PI_DMTN_APPEAL_DECISION = SRC.PI_DMTN_APPEAL_DECISION
				, TRG.PI_PIP_RSNBL_ACMDTN = SRC.PI_PIP_RSNBL_ACMDTN
				, TRG.PI_PIP_EMPL_SBMT_MEDDOC = SRC.PI_PIP_EMPL_SBMT_MEDDOC
				, TRG.PI_PIP_DOC_SBMT_FOH_RVW = SRC.PI_PIP_DOC_SBMT_FOH_RVW
				, TRG.PI_PIP_WGI_WTHLD = SRC.PI_PIP_WGI_WTHLD
				, TRG.PI_PIP_WGI_RVW_DT	= SRC.PI_PIP_WGI_RVW_DT
				, TRG.PI_PIP_MEDDOC_RVW_OUTCOME = SRC.PI_PIP_MEDDOC_RVW_OUTCOME
				, TRG.PI_PIP_START_DT = SRC.PI_PIP_START_DT	
				, TRG.PI_PIP_END_DT = SRC.PI_PIP_END_DT	
				, TRG.PI_PIP_EXT_END_DT = SRC.PI_PIP_EXT_END_DT	
				, TRG.PI_PIP_EXT_END_REASON = SRC.PI_PIP_EXT_END_REASON				 
				, TRG.PI_PIP_EXT_END_NOTIFY_DT = SRC.PI_PIP_EXT_END_NOTIFY_DT	
				, TRG.PI_PIP_EXT_DT_LIST = SRC.PI_PIP_EXT_DT_LIST	
				, TRG.PI_PIP_ACTUAL_DT = SRC.PI_PIP_ACTUAL_DT	
				, TRG.PI_PIP_END_PRIOR_TO_PLAN = SRC.PI_PIP_END_PRIOR_TO_PLAN
				, TRG.PI_PIP_END_PRIOR_TO_PLAN_RSN = SRC.PI_PIP_END_PRIOR_TO_PLAN_RSN
				, TRG.PI_PIP_SUCCESS_CMPLT = SRC.PI_PIP_SUCCESS_CMPLT
				, TRG.PI_PIP_PMAP_RTNG_SIGN_DT = SRC.PI_PIP_PMAP_RTNG_SIGN_DT	
				, TRG.PI_PIP_PMAP_RVW_SIGN_DT = SRC.PI_PIP_PMAP_RVW_SIGN_DT	
				, TRG.PI_PIP_PRPS_ACTN = SRC.PI_PIP_PRPS_ACTN	
				, TRG.PI_PIP_PRPS_ISSUE_DT = SRC.PI_PIP_PRPS_ISSUE_DT	
				, TRG.PI_PIP_ORAL_PRSNT_REQ	= SRC.PI_PIP_ORAL_PRSNT_REQ
				, TRG.PI_PIP_ORAL_PRSNT_DT = SRC.PI_PIP_ORAL_PRSNT_DT	
				, TRG.PI_PIP_WRTN_RESP_SBMT = SRC.PI_PIP_WRTN_RESP_SBMT	
				, TRG.PI_PIP_WRTN_RESP_DUE_DT = SRC.PI_PIP_WRTN_RESP_DUE_DT	
				, TRG.PI_PIP_WRTN_SBMT_DT = SRC.PI_PIP_WRTN_SBMT_DT	
				, TRG.PI_PIP_FIN_AGCY_DECISION = SRC.PI_PIP_FIN_AGCY_DECISION
				, TRG.PI_PIP_DECIDING_OFFICAL = SRC.PI_PIP_DECIDING_OFFICAL
				, TRG.PI_PIP_FIN_AGCY_DECISION_DT = SRC.PI_PIP_FIN_AGCY_DECISION_DT	
				, TRG.PI_PIP_DECISION_ISSUE_DT = SRC.PI_PIP_DECISION_ISSUE_DT	
				, TRG.PI_PIP_EFF_ACTN_DT = SRC.PI_PIP_EFF_ACTN_DT	
				, TRG.PI_PIP_EMPL_GRIEVANCE = SRC.PI_PIP_EMPL_GRIEVANCE	
				, TRG.PI_PIP_APPEAL_DECISION = SRC.PI_PIP_APPEAL_DECISION
				, TRG.PI_REASGN_NOTICE_DT = SRC.PI_REASGN_NOTICE_DT	
				, TRG.PI_REASGN_EFF_DT = SRC.PI_REASGN_EFF_DT	
				, TRG.PI_REASGN_CUR_ADMIN_CD = SRC.PI_REASGN_CUR_ADMIN_CD
				, TRG.PI_REASGN_CUR_ORG_NM = SRC.PI_REASGN_CUR_ORG_NM	
				, TRG.PI_REASGN_FIN_ADMIN_CD = SRC.PI_REASGN_FIN_ADMIN_CD
				, TRG.PI_REASGN_FIN_ORG_NM = SRC.PI_REASGN_FIN_ORG_NM	
				, TRG.PI_RMV_PRPS_ACTN_ISSUE_DT	= SRC.PI_RMV_PRPS_ACTN_ISSUE_DT
				, TRG.PI_RMV_EMPL_NOTC_LEV	= SRC.PI_RMV_EMPL_NOTC_LEV
				, TRG.PI_RMV_NOTC_LEV_START_DT = SRC.PI_RMV_NOTC_LEV_START_DT	
				, TRG.PI_RMV_NOTC_LEV_END_DT = SRC.PI_RMV_NOTC_LEV_END_DT	
				, TRG.PI_RMV_ORAL_PRSNT_REQ	= SRC.PI_RMV_ORAL_PRSNT_REQ
				, TRG.PI_RMV_ORAL_PRSNT_DT	= SRC.PI_RMV_ORAL_PRSNT_DT
				, TRG.PI_RMV_WRTN_RESP_DUE_DT	= SRC.PI_RMV_WRTN_RESP_DUE_DT
				, TRG.PI_RMV_WRTN_RESP_SBMT_DT	= SRC.PI_RMV_WRTN_RESP_SBMT_DT
				, TRG.PI_RMV_FIN_AGCY_DECISION	= SRC.PI_RMV_FIN_AGCY_DECISION
				, TRG.PI_RMV_FIN_DECIDING_OFC	= SRC.PI_RMV_FIN_DECIDING_OFC
				, TRG.PI_RMV_DECISION_ISSUE_DT	= SRC.PI_RMV_DECISION_ISSUE_DT
				, TRG.PI_RMV_EFF_DT	= SRC.PI_RMV_EFF_DT
				, TRG.PI_RMV_NUM_DAYS	= SRC.PI_RMV_NUM_DAYS
				, TRG.PI_RMV_APPEAL_DECISION = SRC.PI_RMV_APPEAL_DECISION	
				, TRG.PI_WRTN_NRTV_RVW_TYPE	= SRC.PI_WRTN_NRTV_RVW_TYPE
				, TRG.PI_WNR_SPCLST_RVW_CMPLT_DT = SRC.PI_WNR_SPCLST_RVW_CMPLT_DT	
				, TRG.PI_WNR_MGR_RVW_RTNG_DT	= SRC.PI_WNR_MGR_RVW_RTNG_DT
				, TRG.PI_WNR_CRITICAL_ELM	= SRC.PI_WNR_CRITICAL_ELM
				, TRG.PI_WNR_FIN_RATING = SRC.PI_WNR_FIN_RATING
				, TRG.PI_WNR_RVW_OFC_CONCUR_DT	= SRC.PI_WNR_RVW_OFC_CONCUR_DT
				, TRG.PI_WNR_WGI_WTHLD = SRC.PI_WNR_WGI_WTHLD
				, TRG.PI_WNR_WGI_RVW_DT	= SRC.PI_WNR_WGI_RVW_DT
            WHEN NOT MATCHED THEN INSERT
            (
                TRG.ERLR_CASE_NUMBER
				, TRG.PI_ACTION_TYPE
				, TRG.PI_NEXT_WGI_DUE_DT	
				, TRG.PI_PERF_COUNSEL_ISSUE_DT	
				, TRG.PI_CNSL_GRV_DECISION
				, TRG.PI_DMTN_PRPS_ACTN_ISSUE_DT	
				, TRG.PI_DMTN_ORAL_PRSNT_REQ
				, TRG.PI_DMTN_ORAL_PRSNT_DT	
				, TRG.PI_DMTN_WRTN_RESP_SBMT
				, TRG.PI_DMTN_WRTN_RESP_DUE_DT	
				, TRG.PI_DMTN_WRTN_RESP_SBMT_DT	
				, TRG.PI_DMTN_CUR_POS_TITLE
				, TRG.PI_DMTN_CUR_PAY_PLAN
				, TRG.PI_DMTN_CUR_JOB_SERIES
				, TRG.PI_DMTN_CUR_GRADE
				, TRG.PI_DMTN_CUR_STEP
				, TRG.PI_DMTN_PRPS_POS_TITLE
				, TRG.PI_DMTN_PRPS_PAY_PLAN
				, TRG.PI_DMTN_PRPS_JOB_SERIES
				, TRG.PI_DMTN_PRPS_GRADE
				, TRG.PI_DMTN_PRP_STEP
				, TRG.PI_DMTN_FIN_POS_TITLE
				, TRG.PI_DMTN_FIN_PAY_PLAN
				, TRG.PI_DMTN_FIN_JOB_SERIES
				, TRG.PI_DMTN_FIN_GRADE
				, TRG.PI_DMTN_FIN_STEP
				, TRG.PI_DMTN_FIN_AGCY_DECISION
				, TRG.PI_DMTN_FIN_DECIDING_OFC
				, TRG.PI_DMTN_FIN_DECISION_ISSUE_DT	
				, TRG.PI_DMTN_DECISION_EFF_DT	
				, TRG.PI_DMTN_APPEAL_DECISION
				, TRG.PI_PIP_RSNBL_ACMDTN
				, TRG.PI_PIP_EMPL_SBMT_MEDDOC
				, TRG.PI_PIP_DOC_SBMT_FOH_RVW
				, TRG.PI_PIP_WGI_WTHLD
				, TRG.PI_PIP_WGI_RVW_DT	
				, TRG.PI_PIP_MEDDOC_RVW_OUTCOME
				, TRG.PI_PIP_START_DT	
				, TRG.PI_PIP_END_DT	
				, TRG.PI_PIP_EXT_END_DT	
				, TRG.PI_PIP_EXT_END_REASON
				, TRG.PI_PIP_EXT_END_NOTIFY_DT	
				, TRG.PI_PIP_EXT_DT_LIST	
				, TRG.PI_PIP_ACTUAL_DT	
				, TRG.PI_PIP_END_PRIOR_TO_PLAN
				, TRG.PI_PIP_END_PRIOR_TO_PLAN_RSN
				, TRG.PI_PIP_SUCCESS_CMPLT
				, TRG.PI_PIP_PMAP_RTNG_SIGN_DT	
				, TRG.PI_PIP_PMAP_RVW_SIGN_DT	
				, TRG.PI_PIP_PRPS_ACTN	
				, TRG.PI_PIP_PRPS_ISSUE_DT	
				, TRG.PI_PIP_ORAL_PRSNT_REQ	
				, TRG.PI_PIP_ORAL_PRSNT_DT	
				, TRG.PI_PIP_WRTN_RESP_SBMT	
				, TRG.PI_PIP_WRTN_RESP_DUE_DT	
				, TRG.PI_PIP_WRTN_SBMT_DT	
				, TRG.PI_PIP_FIN_AGCY_DECISION
				, TRG.PI_PIP_DECIDING_OFFICAL
				, TRG.PI_PIP_FIN_AGCY_DECISION_DT	
				, TRG.PI_PIP_DECISION_ISSUE_DT	
				, TRG.PI_PIP_EFF_ACTN_DT	
				, TRG.PI_PIP_EMPL_GRIEVANCE	
				, TRG.PI_PIP_APPEAL_DECISION
				, TRG.PI_REASGN_NOTICE_DT	
				, TRG.PI_REASGN_EFF_DT	
				, TRG.PI_REASGN_CUR_ADMIN_CD
				, TRG.PI_REASGN_CUR_ORG_NM	
				, TRG.PI_REASGN_FIN_ADMIN_CD
				, TRG.PI_REASGN_FIN_ORG_NM	
				, TRG.PI_RMV_PRPS_ACTN_ISSUE_DT	
				, TRG.PI_RMV_EMPL_NOTC_LEV	
				, TRG.PI_RMV_NOTC_LEV_START_DT	
				, TRG.PI_RMV_NOTC_LEV_END_DT	
				, TRG.PI_RMV_ORAL_PRSNT_REQ	
				, TRG.PI_RMV_ORAL_PRSNT_DT	
				, TRG.PI_RMV_WRTN_RESP_DUE_DT	
				, TRG.PI_RMV_WRTN_RESP_SBMT_DT	
				, TRG.PI_RMV_FIN_AGCY_DECISION	
				, TRG.PI_RMV_FIN_DECIDING_OFC	
				, TRG.PI_RMV_DECISION_ISSUE_DT	
				, TRG.PI_RMV_EFF_DT	
				, TRG.PI_RMV_NUM_DAYS	
				, TRG.PI_RMV_APPEAL_DECISION	
				, TRG.PI_WRTN_NRTV_RVW_TYPE	
				, TRG.PI_WNR_SPCLST_RVW_CMPLT_DT	
				, TRG.PI_WNR_MGR_RVW_RTNG_DT	
				, TRG.PI_WNR_CRITICAL_ELM	
				, TRG.PI_WNR_FIN_RATING
				, TRG.PI_WNR_RVW_OFC_CONCUR_DT	
				, TRG.PI_WNR_WGI_WTHLD
				, TRG.PI_WNR_WGI_RVW_DT	               
            )
            VALUES
            (
                SRC.ERLR_CASE_NUMBER
				, SRC.PI_ACTION_TYPE
				, SRC.PI_NEXT_WGI_DUE_DT	
				, SRC.PI_PERF_COUNSEL_ISSUE_DT	
				, SRC.PI_CNSL_GRV_DECISION
				, SRC.PI_DMTN_PRPS_ACTN_ISSUE_DT	
				, SRC.PI_DMTN_ORAL_PRSNT_REQ
				, SRC.PI_DMTN_ORAL_PRSNT_DT	
				, SRC.PI_DMTN_WRTN_RESP_SBMT
				, SRC.PI_DMTN_WRTN_RESP_DUE_DT	
				, SRC.PI_DMTN_WRTN_RESP_SBMT_DT	
				, SRC.PI_DMTN_CUR_POS_TITLE
				, SRC.PI_DMTN_CUR_PAY_PLAN
				, SRC.PI_DMTN_CUR_JOB_SERIES
				, SRC.PI_DMTN_CUR_GRADE
				, SRC.PI_DMTN_CUR_STEP
				, SRC.PI_DMTN_PRPS_POS_TITLE
				, SRC.PI_DMTN_PRPS_PAY_PLAN
				, SRC.PI_DMTN_PRPS_JOB_SERIES
				, SRC.PI_DMTN_PRPS_GRADE
				, SRC.PI_DMTN_PRP_STEP
				, SRC.PI_DMTN_FIN_POS_TITLE
				, SRC.PI_DMTN_FIN_PAY_PLAN
				, SRC.PI_DMTN_FIN_JOB_SERIES
				, SRC.PI_DMTN_FIN_GRADE
				, SRC.PI_DMTN_FIN_STEP
				, SRC.PI_DMTN_FIN_AGCY_DECISION
				, SRC.PI_DMTN_FIN_DECIDING_OFC
				, SRC.PI_DMTN_FIN_DECISION_ISSUE_DT	
				, SRC.PI_DMTN_DECISION_EFF_DT	
				, SRC.PI_DMTN_APPEAL_DECISION
				, SRC.PI_PIP_RSNBL_ACMDTN
				, SRC.PI_PIP_EMPL_SBMT_MEDDOC
				, SRC.PI_PIP_DOC_SBMT_FOH_RVW
				, SRC.PI_PIP_WGI_WTHLD
				, SRC.PI_PIP_WGI_RVW_DT	
				, SRC.PI_PIP_MEDDOC_RVW_OUTCOME
				, SRC.PI_PIP_START_DT	
				, SRC.PI_PIP_END_DT	
				, SRC.PI_PIP_EXT_END_DT	
				, SRC.PI_PIP_EXT_END_REASON
				, SRC.PI_PIP_EXT_END_NOTIFY_DT	
				, SRC.PI_PIP_EXT_DT_LIST	
				, SRC.PI_PIP_ACTUAL_DT	
				, SRC.PI_PIP_END_PRIOR_TO_PLAN
				, SRC.PI_PIP_END_PRIOR_TO_PLAN_RSN
				, SRC.PI_PIP_SUCCESS_CMPLT
				, SRC.PI_PIP_PMAP_RTNG_SIGN_DT	
				, SRC.PI_PIP_PMAP_RVW_SIGN_DT	
				, SRC.PI_PIP_PRPS_ACTN	
				, SRC.PI_PIP_PRPS_ISSUE_DT	
				, SRC.PI_PIP_ORAL_PRSNT_REQ	
				, SRC.PI_PIP_ORAL_PRSNT_DT	
				, SRC.PI_PIP_WRTN_RESP_SBMT	
				, SRC.PI_PIP_WRTN_RESP_DUE_DT	
				, SRC.PI_PIP_WRTN_SBMT_DT	
				, SRC.PI_PIP_FIN_AGCY_DECISION
				, SRC.PI_PIP_DECIDING_OFFICAL
				, SRC.PI_PIP_FIN_AGCY_DECISION_DT	
				, SRC.PI_PIP_DECISION_ISSUE_DT	
				, SRC.PI_PIP_EFF_ACTN_DT	
				, SRC.PI_PIP_EMPL_GRIEVANCE	
				, SRC.PI_PIP_APPEAL_DECISION
				, SRC.PI_REASGN_NOTICE_DT	
				, SRC.PI_REASGN_EFF_DT	
				, SRC.PI_REASGN_CUR_ADMIN_CD
				, SRC.PI_REASGN_CUR_ORG_NM	
				, SRC.PI_REASGN_FIN_ADMIN_CD
				, SRC.PI_REASGN_FIN_ORG_NM	
				, SRC.PI_RMV_PRPS_ACTN_ISSUE_DT	
				, SRC.PI_RMV_EMPL_NOTC_LEV	
				, SRC.PI_RMV_NOTC_LEV_START_DT	
				, SRC.PI_RMV_NOTC_LEV_END_DT	
				, SRC.PI_RMV_ORAL_PRSNT_REQ	
				, SRC.PI_RMV_ORAL_PRSNT_DT	
				, SRC.PI_RMV_WRTN_RESP_DUE_DT	
				, SRC.PI_RMV_WRTN_RESP_SBMT_DT	
				, SRC.PI_RMV_FIN_AGCY_DECISION	
				, SRC.PI_RMV_FIN_DECIDING_OFC	
				, SRC.PI_RMV_DECISION_ISSUE_DT	
				, SRC.PI_RMV_EFF_DT	
				, SRC.PI_RMV_NUM_DAYS	
				, SRC.PI_RMV_APPEAL_DECISION	
				, SRC.PI_WRTN_NRTV_RVW_TYPE	
				, SRC.PI_WNR_SPCLST_RVW_CMPLT_DT	
				, SRC.PI_WNR_MGR_RVW_RTNG_DT	
				, SRC.PI_WNR_CRITICAL_ELM	
				, SRC.PI_WNR_FIN_RATING
				, SRC.PI_WNR_RVW_OFC_CONCUR_DT	
				, SRC.PI_WNR_WGI_WTHLD
				, SRC.PI_WNR_WGI_RVW_DT	               
            );

		END;

		--------------------------------
		-- ERLR_GRIEVANCE table
		--------------------------------
		BEGIN
            MERGE INTO  ERLR_GRIEVANCE TRG
            USING
            (
                SELECT
                    V_CASE_NUMBER AS ERLR_CASE_NUMBER
					, X.GI_TYPE
					, X.GI_NEGOTIATED_GRIEVANCE_TYPE
					, X.GI_TIMELY_FILING_2
					, X.GI_IND_MANAGER
					, TO_DATE(X.GI_FILING_DT_2,'MM/DD/YYYY HH24:MI:SS') AS GI_FILING_DT_2
					, X.GI_TIMELY_FILING
					, TO_DATE(X.GI_FILING_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_FILING_DT
					, TO_DATE(X.GI_IND_MEETING_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_MEETING_DT
					, TO_DATE(X.GI_IND_STEP_1_DECISION_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_STEP_1_DECISION_DT
					, TO_DATE(X.GI_IND_DECISION_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_DECISION_ISSUE_DT
					, X.GI_IND_STEP_1_DEADLINE
					, TO_DATE(X.GI_IND_STEP_1_EXT_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_STEP_1_EXT_DUE_DT
					, X.GI_IND_STEP_1_EXT_DUE_REASON
					, X.GI_STEP_2_REQUEST
					, TO_DATE(X.GI_IND_STEP_2_MTG_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_STEP_2_MTG_DT
					, TO_DATE(X.GI_IND_STEP_2_DECISION_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_STEP_2_DECISION_DUE_DT
					, TO_DATE(X.GI_IND_STEP_2_DCSN_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_STEP_2_DCSN_ISSUE_DT
					, X.GI_IND_STEP_2_DEADLINE
					, TO_DATE(X.GI_IND_EXT_2_EXT_DUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_EXT_2_EXT_DUE_DT
					, X.GI_IND_STEP_2_EXT_DUE_REASON
					, TO_DATE(X.GI_IND_THIRD_PARTY_APPEAL_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_IND_THIRD_PARTY_APPEAL_DT
					, X.GI_IND_THIRD_APPEAL_REQUEST
					, X.GI_UM_GRIEVABILITY
					, TO_DATE(X.GI_MEETING_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_MEETING_DT
					, X.GI_GRIEVANCE_STATUS
					, TO_DATE(X.GI_ARBITRATION_DEADLINE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_ARBITRATION_DEADLINE_DT
					, X.GI_ARBITRATION_REQUEST
					, X.GI_ADMIN_OFFCL_1
					, TO_DATE(X.GI_ADMIN_STG_1_DECISION_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_ADMIN_STG_1_DECISION_DT
					, TO_DATE(X.GI_ADMIN_STG_1_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_ADMIN_STG_1_ISSUE_DT
					, X.GI_ADMIN_STG_2_RESP
					, X.GI_ADMIN_OFFCL_2
					, TO_DATE(X.GI_ADMIN_STG_2_DECISION_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_ADMIN_STG_2_DECISION_DT
					, TO_DATE(X.GI_ADMIN_STG_2_ISSUE_DT,'MM/DD/YYYY HH24:MI:SS') AS GI_ADMIN_STG_2_ISSUE_DT
                    
                FROM TBL_FORM_DTL FD
                    , XMLTABLE('/formData/items'
						PASSING FD.FIELD_DATA
						COLUMNS
                            GI_TYPE	NVARCHAR2(200) PATH './item[id="GI_TYPE"]/value'
							, GI_NEGOTIATED_GRIEVANCE_TYPE	NVARCHAR2(200) PATH './item[id="GI_NEGOTIATED_GRIEVANCE_TYPE"]/value'
							, GI_TIMELY_FILING_2	VARCHAR2(10) PATH './item[id="GI_TIMELY_FILING_2"]/value'	
							, GI_IND_MANAGER	NVARCHAR2(10) PATH './item[id="GI_IND_MANAGER"]/value/id'
							, GI_FILING_DT_2	VARCHAR2(10) PATH './item[id="GI_FILING_DT_2"]/value'
							, GI_TIMELY_FILING	VARCHAR2(10) PATH './item[id="GI_TIMELY_FILING"]/value'
							, GI_FILING_DT	VARCHAR2(10) PATH './item[id="GI_FILING_DT"]/value'
							, GI_IND_MEETING_DT	VARCHAR2(10) PATH './item[id="GI_IND_MEETING_DT"]/value'
							, GI_IND_STEP_1_DECISION_DT	VARCHAR2(10) PATH './item[id="GI_IND_STEP_1_DECISION_DT"]/value'
							, GI_IND_DECISION_ISSUE_DT	VARCHAR2(10) PATH './item[id="GI_IND_DECISION_ISSUE_DT"]/value'
							, GI_IND_STEP_1_DEADLINE	VARCHAR2(10) PATH './item[id="GI_IND_STEP_1_DEADLINE"]/value'
							, GI_IND_STEP_1_EXT_DUE_DT	VARCHAR2(10) PATH './item[id="GI_IND_STEP_1_EXT_DUE_DT"]/value'
							, GI_IND_STEP_1_EXT_DUE_REASON	NVARCHAR2(500) PATH './item[id="GI_IND_STEP_1_EXT_DUE_REASON"]/value'
							, GI_STEP_2_REQUEST	VARCHAR2(10) PATH './item[id="GI_STEP_2_REQUEST"]/value'
							, GI_IND_STEP_2_MTG_DT	VARCHAR2(10) PATH './item[id="GI_IND_STEP_2_MTG_DT"]/value'
							, GI_IND_STEP_2_DECISION_DUE_DT	VARCHAR2(10) PATH './item[id="GI_IND_STEP_2_DECISION_DUE_DT"]/value'
							, GI_IND_STEP_2_DCSN_ISSUE_DT	VARCHAR2(10) PATH './item[id="GI_IND_STEP_2_DCSN_ISSUE_DT"]/value'
							, GI_IND_STEP_2_DEADLINE	VARCHAR2(10) PATH './item[id="GI_IND_STEP_2_DEADLINE"]/value'
							, GI_IND_EXT_2_EXT_DUE_DT	VARCHAR2(10) PATH './item[id="GI_IND_EXT_2_EXT_DUE_DT"]/value'
							, GI_IND_STEP_2_EXT_DUE_REASON	NVARCHAR2(500) PATH './item[id="GI_IND_STEP_2_EXT_DUE_REASON"]/value'
							, GI_IND_THIRD_PARTY_APPEAL_DT	VARCHAR2(10) PATH './item[id="GI_IND_THIRD_PARTY_APPEAL_DT"]/value'
							, GI_IND_THIRD_APPEAL_REQUEST	VARCHAR2(10) PATH './item[id="GI_IND_THIRD_APPEAL_REQUEST"]/value'
							, GI_UM_GRIEVABILITY	NVARCHAR2(200) PATH './item[id="GI_UM_GRIEVABILITY"]/value'
							, GI_MEETING_DT	VARCHAR2(10) PATH './item[id="GI_MEETING_DT"]/value'
							, GI_GRIEVANCE_STATUS	NVARCHAR2(200) PATH './item[id="GI_GRIEVANCE_STATUS"]/value'
							, GI_ARBITRATION_DEADLINE_DT	VARCHAR2(10) PATH './item[id="GI_ARBITRATION_DEADLINE_DT"]/value'
							, GI_ARBITRATION_REQUEST	VARCHAR2(10) PATH './item[id="GI_ARBITRATION_REQUEST"]/value'
							, GI_ADMIN_OFFCL_1	NVARCHAR2(10) PATH './item[id="GI_ADMIN_OFFCL_1"]/value/id'
							, GI_ADMIN_STG_1_DECISION_DT	VARCHAR2(10) PATH './item[id="GI_ADMIN_STG_1_DECISION_DT"]/value'
							, GI_ADMIN_STG_1_ISSUE_DT	VARCHAR2(10) PATH './item[id="GI_ADMIN_STG_1_ISSUE_DT"]/value'
							, GI_ADMIN_STG_2_RESP	VARCHAR2(10) PATH './item[id="GI_ADMIN_STG_2_RESP"]/value'
							, GI_ADMIN_OFFCL_2	NVARCHAR2(10) PATH './item[id="GI_ADMIN_OFFCL_2"]/value/id'
							, GI_ADMIN_STG_2_DECISION_DT	VARCHAR2(10) PATH './item[id="GI_ADMIN_STG_2_DECISION_DT"]/value'
							, GI_ADMIN_STG_2_ISSUE_DT	VARCHAR2(10) PATH './item[id="GI_ADMIN_STG_2_ISSUE_DT"]/value'
							
                ) X
			    WHERE FD.PROCID = I_PROCID
            )SRC ON (SRC.ERLR_CASE_NUMBER = TRG.ERLR_CASE_NUMBER)
            WHEN MATCHED THEN UPDATE SET
                TRG.GI_TYPE = SRC.GI_TYPE
				, TRG.GI_NEGOTIATED_GRIEVANCE_TYPE = SRC.GI_NEGOTIATED_GRIEVANCE_TYPE
				, TRG.GI_TIMELY_FILING_2 = SRC.GI_TIMELY_FILING_2
				, TRG.GI_IND_MANAGER = SRC.GI_IND_MANAGER
				, TRG.GI_FILING_DT_2 = SRC.GI_FILING_DT_2
				, TRG.GI_TIMELY_FILING = SRC.GI_TIMELY_FILING
				, TRG.GI_FILING_DT = SRC.GI_FILING_DT
				, TRG.GI_IND_MEETING_DT = SRC.GI_IND_MEETING_DT
				, TRG.GI_IND_STEP_1_DECISION_DT = SRC.GI_IND_STEP_1_DECISION_DT
				, TRG.GI_IND_DECISION_ISSUE_DT = SRC.GI_IND_DECISION_ISSUE_DT
				, TRG.GI_IND_STEP_1_DEADLINE = SRC.GI_IND_STEP_1_DEADLINE
				, TRG.GI_IND_STEP_1_EXT_DUE_DT = SRC.GI_IND_STEP_1_EXT_DUE_DT
				, TRG.GI_IND_STEP_1_EXT_DUE_REASON = SRC.GI_IND_STEP_1_EXT_DUE_REASON
				, TRG.GI_STEP_2_REQUEST = SRC.GI_STEP_2_REQUEST
				, TRG.GI_IND_STEP_2_MTG_DT = SRC.GI_IND_STEP_2_MTG_DT
				, TRG.GI_IND_STEP_2_DECISION_DUE_DT = SRC.GI_IND_STEP_2_DECISION_DUE_DT
				, TRG.GI_IND_STEP_2_DCSN_ISSUE_DT = SRC.GI_IND_STEP_2_DCSN_ISSUE_DT	
				, TRG.GI_IND_STEP_2_DEADLINE = SRC.GI_IND_STEP_2_DEADLINE
				, TRG.GI_IND_EXT_2_EXT_DUE_DT = SRC.GI_IND_EXT_2_EXT_DUE_DT
				, TRG.GI_IND_STEP_2_EXT_DUE_REASON = SRC.GI_IND_STEP_2_EXT_DUE_REASON
				, TRG.GI_IND_THIRD_PARTY_APPEAL_DT = SRC.GI_IND_THIRD_PARTY_APPEAL_DT
				, TRG.GI_IND_THIRD_APPEAL_REQUEST = SRC.GI_IND_THIRD_APPEAL_REQUEST
				, TRG.GI_UM_GRIEVABILITY = SRC.GI_UM_GRIEVABILITY
				, TRG.GI_MEETING_DT = SRC.GI_MEETING_DT
				, TRG.GI_GRIEVANCE_STATUS = SRC.GI_GRIEVANCE_STATUS
				, TRG.GI_ARBITRATION_DEADLINE_DT = SRC.GI_ARBITRATION_DEADLINE_DT
				, TRG.GI_ARBITRATION_REQUEST = SRC.GI_ARBITRATION_REQUEST
				, TRG.GI_ADMIN_OFFCL_1 = SRC.GI_ADMIN_OFFCL_1
				, TRG.GI_ADMIN_STG_1_DECISION_DT = SRC.GI_ADMIN_STG_1_DECISION_DT
				, TRG.GI_ADMIN_STG_1_ISSUE_DT = SRC.GI_ADMIN_STG_1_ISSUE_DT
				, TRG.GI_ADMIN_STG_2_RESP = SRC.GI_ADMIN_STG_2_RESP
				, TRG.GI_ADMIN_OFFCL_2 = SRC.GI_ADMIN_OFFCL_2
				, TRG.GI_ADMIN_STG_2_DECISION_DT = SRC.GI_ADMIN_STG_2_DECISION_DT
				, TRG.GI_ADMIN_STG_2_ISSUE_DT = SRC.GI_ADMIN_STG_2_ISSUE_DT
				
            WHEN NOT MATCHED THEN INSERT
            (
                TRG.ERLR_CASE_NUMBER
				, TRG.GI_TYPE				
				, TRG.GI_NEGOTIATED_GRIEVANCE_TYPE				
				, TRG.GI_TIMELY_FILING_2
				, TRG.GI_IND_MANAGER
				, TRG.GI_FILING_DT_2
				, TRG.GI_TIMELY_FILING
				, TRG.GI_FILING_DT
				, TRG.GI_IND_MEETING_DT
				, TRG.GI_IND_STEP_1_DECISION_DT
				, TRG.GI_IND_DECISION_ISSUE_DT
				, TRG.GI_IND_STEP_1_DEADLINE
				, TRG.GI_IND_STEP_1_EXT_DUE_DT
				, TRG.GI_IND_STEP_1_EXT_DUE_REASON
				, TRG.GI_STEP_2_REQUEST
				, TRG.GI_IND_STEP_2_MTG_DT
				, TRG.GI_IND_STEP_2_DECISION_DUE_DT
				, TRG.GI_IND_STEP_2_DCSN_ISSUE_DT	
				, TRG.GI_IND_STEP_2_DEADLINE
				, TRG.GI_IND_EXT_2_EXT_DUE_DT
				, TRG.GI_IND_STEP_2_EXT_DUE_REASON
				, TRG.GI_IND_THIRD_PARTY_APPEAL_DT
				, TRG.GI_IND_THIRD_APPEAL_REQUEST
				, TRG.GI_UM_GRIEVABILITY
				, TRG.GI_MEETING_DT
				, TRG.GI_GRIEVANCE_STATUS
				, TRG.GI_ARBITRATION_DEADLINE_DT
				, TRG.GI_ARBITRATION_REQUEST
				, TRG.GI_ADMIN_OFFCL_1
				, TRG.GI_ADMIN_STG_1_DECISION_DT
				, TRG.GI_ADMIN_STG_1_ISSUE_DT	
				, TRG.GI_ADMIN_STG_2_RESP
				, TRG.GI_ADMIN_OFFCL_2
				, TRG.GI_ADMIN_STG_2_DECISION_DT
				, TRG.GI_ADMIN_STG_2_ISSUE_DT
               
            )
            VALUES
            (
                SRC.ERLR_CASE_NUMBER
				, SRC.GI_TYPE				
				, SRC.GI_NEGOTIATED_GRIEVANCE_TYPE				
				, SRC.GI_TIMELY_FILING_2
				, SRC.GI_IND_MANAGER
				, SRC.GI_FILING_DT_2
				, SRC.GI_TIMELY_FILING
				, SRC.GI_FILING_DT
				, SRC.GI_IND_MEETING_DT
				, SRC.GI_IND_STEP_1_DECISION_DT
				, SRC.GI_IND_DECISION_ISSUE_DT
				, SRC.GI_IND_STEP_1_DEADLINE
				, SRC.GI_IND_STEP_1_EXT_DUE_DT
				, SRC.GI_IND_STEP_1_EXT_DUE_REASON
				, SRC.GI_STEP_2_REQUEST
				, SRC.GI_IND_STEP_2_MTG_DT
				, SRC.GI_IND_STEP_2_DECISION_DUE_DT
				, SRC.GI_IND_STEP_2_DCSN_ISSUE_DT	
				, SRC.GI_IND_STEP_2_DEADLINE
				, SRC.GI_IND_EXT_2_EXT_DUE_DT
				, SRC.GI_IND_STEP_2_EXT_DUE_REASON
				, SRC.GI_IND_THIRD_PARTY_APPEAL_DT
				, SRC.GI_IND_THIRD_APPEAL_REQUEST
				, SRC.GI_UM_GRIEVABILITY
				, SRC.GI_MEETING_DT
				, SRC.GI_GRIEVANCE_STATUS
				, SRC.GI_ARBITRATION_DEADLINE_DT
				, SRC.GI_ARBITRATION_REQUEST
				, SRC.GI_ADMIN_OFFCL_1
				, SRC.GI_ADMIN_STG_1_DECISION_DT
				, SRC.GI_ADMIN_STG_1_ISSUE_DT	
				, SRC.GI_ADMIN_STG_2_RESP
				, SRC.GI_ADMIN_OFFCL_2
				, SRC.GI_ADMIN_STG_2_DECISION_DT
				, SRC.GI_ADMIN_STG_2_ISSUE_DT   
				            
            );

		END;
	
	END IF;
		

    COMMIT;

EXCEPTION
	WHEN E_INVALID_PROCID THEN
		SP_ERROR_LOG();
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_UPDATE_CLSF_TABLE -------------------');
		--DBMS_OUTPUT.PUT_LINE('ERROR message = ' || 'Process ID is not valid');
	WHEN E_INVALID_JOB_REQ_ID THEN
		SP_ERROR_LOG();
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_UPDATE_CLSF_TABLE -------------------');
		--DBMS_OUTPUT.PUT_LINE('ERROR message = ' || 'Job Request ID is not valid');
	WHEN E_INVALID_STRATCON_DATA THEN
		SP_ERROR_LOG();
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_UPDATE_CLSF_TABLE -------------------');
		--DBMS_OUTPUT.PUT_LINE('ERROR message = ' || 'Invalid data');
	WHEN OTHERS THEN
		SP_ERROR_LOG();
		V_ERRCODE := SQLCODE;
		V_ERRMSG := SQLERRM;
		--DBMS_OUTPUT.PUT_LINE('ERROR occurred while executing SP_UPDATE_CLSF_TABLE -------------------');
		--DBMS_OUTPUT.PUT_LINE('Error code    = ' || V_ERRCODE);
		--DBMS_OUTPUT.PUT_LINE('Error message = ' || V_ERRMSG);
END;

/
