ALTER TABLE 
   ERLR_GEN
MODIFY 
(    
   GEN_PRIMARY_REP_AFFILIATION  NVARCHAR2(20),   
   GEN_STD_CONDUCT_TYPE	 NVARCHAR2(200),
   CC_FINAL_ACTION	NVARCHAR2(200)   
);

ALTER TABLE 
   ERLR_CNDT_ISSUE
MODIFY 
( 
   CI_ACTION_TYPE    NVARCHAR2(200),
   CI_DEMO_FINAL_AGNCY_DCSN  NVARCHAR2(200),
   CI_COUNSEL_TYPE     NVARCHAR2(200),   
   CI_RMVL_FINAL_AGNCY_DCSN	NVARCHAR2(200),
   CI_SUSPENTION_TYPE   NVARCHAR2(200),
   CI_SUSP_FINAL_AGNCY_DCSN NVARCHAR2(200),
   CI_PPLAN    NVARCHAR2(50),
   CI_SERIES    NVARCHAR2(50),
   CI_CURRENT_INFO_GRADE    NVARCHAR2(50),
   CI_CURRENT_INFO_STEP    NVARCHAR2(50),
   CI_PROPOSED_PPLAN    NVARCHAR2(50),
   CI_PROPOSED_SERIES    NVARCHAR2(50),
   CI_PROPOSED_INFO_GRADE    NVARCHAR2(50),
   CI_PROPOSED_INFO_STEP    NVARCHAR2(50),
   CI_FINAL_PPLAN    NVARCHAR2(50),
   CI_FINAL_SERIES    NVARCHAR2(50),
   CI_FINAL_INFO_GRADE    NVARCHAR2(50),
   CI_FINAL_INFO_STEP    NVARCHAR2(50)
);

COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PPLAN IS 'Current Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SERIES IS 'Current Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_CURRENT_INFO_GRADE IS 'Current Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_CURRENT_INFO_STEP IS 'Current Step';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_PPLAN IS 'Proposed Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_SERIES IS 'Proposed Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_INFO_GRADE IS 'Proposed Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_INFO_STEP IS 'Proposed Step';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_PPLAN IS 'Final Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_SERIES IS 'Final Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_INFO_GRADE IS 'Final Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_INFO_STEP IS 'Final Step';

ALTER TABLE 
   ERLR_APPEAL
MODIFY 
( 
   AP_ERLR_APPEAL_TYPE    NVARCHAR2(200)
);

ALTER TABLE 
   ERLR_PERF_ISSUE
MODIFY 
( 
    PI_PIP_EXT_END_REASON     NVARCHAR2(200),
    PI_WNR_FIN_RATING    NVARCHAR2(200),
    PI_DMTN_CUR_PAY_PLAN    NVARCHAR2(50),
    PI_DMTN_CUR_JOB_SERIES  NVARCHAR2(50),
    PI_DMTN_CUR_GRADE   NVARCHAR2(50),
    PI_DMTN_CUR_STEP    NVARCHAR2(50),
    PI_DMTN_PRPS_PAY_PLAN   NVARCHAR2(50),
    PI_DMTN_PRPS_JOB_SERIES NVARCHAR2(50),
    PI_DMTN_PRPS_GRADE  NVARCHAR2(50),
    PI_DMTN_PRP_STEP    NVARCHAR2(50),
    PI_DMTN_FIN_PAY_PLAN    NVARCHAR2(50),
    PI_DMTN_FIN_JOB_SERIES  NVARCHAR2(50),
    PI_DMTN_FIN_GRADE   NVARCHAR2(50),
    PI_DMTN_FIN_STEP    NVARCHAR2(50)
);


ALTER TABLE
    ERLR_PERF_ISSUE
DROP
(
    PI_PIP_NOT_CMPLT_RSN,
    PI_PIP_NOT_CMPLT_OTHR_RSN
);

ALTER TABLE 
   ERLR_INVESTIGATION
MODIFY 
( 
   INVESTIGATION_TYPE    NVARCHAR2(200)   
);

ALTER TABLE 
   ERLR_INFO_REQUEST
MODIFY 
( 
    IR_REQUESTER    NVARCHAR2(20),
    IR_CMS_REQUESTER_NAME   NVARCHAR2(200)
);

ALTER TABLE 
   ERLR_3RDPARTY_HEAR
MODIFY 
(
    THRD_PRTY_PROC_ORDER	NVARCHAR2(2000),
    THRD_PRTY_APPEAL_TYPE    NVARCHAR2(200)    
);

ALTER TABLE 
   ERLR_PROB_ACTION
MODIFY 
(     
   PPA_ACTION_TYPE    NVARCHAR2(200),
   PPA_PPLAN  NVARCHAR2(50),
   PPA_SERIES     NVARCHAR2(50),   
   PPA_CURRENT_INFO_GRADE	NVARCHAR2(50),
   PPA_CURRENT_INFO_STEP   NVARCHAR2(50),
   PPA_PROPOSED_PPLAN NVARCHAR2(50),
   PPA_PROPOSED_SERIES  NVARCHAR2(50),
   PPA_PROPOSED_INFO_GRADE  NVARCHAR2(50),
   PPA_PROPOSED_INFO_STEP   NVARCHAR2(50),
   PPA_FINAL_PPLAN  NVARCHAR2(50),
   PPA_FINAL_SERIES NVARCHAR2(50),
   PPA_FINAL_INFO_GRADE NVARCHAR2(50),
   PPA_FINAL_INFO_STEP  NVARCHAR2(50),
   PPA_DEMO_FINAL_AGENCY_DECISION   NVARCHAR2(200),
   PPA_TERMINATION_TYPE NVARCHAR2(200),
   PPA_TERM_AGENCY_DECISION NVARCHAR2(200)
);

ALTER TABLE 
   ERLR_GRIEVANCE
MODIFY 
( 
   GI_TYPE    NVARCHAR2(200),
   GI_NEGOTIATED_GRIEVANCE_TYPE  NVARCHAR2(200),   
   GI_IND_STEP_2_EXT_DUE_REASON   NVARCHAR2(500),
   GI_GRIEVANCE_STATUS	NVARCHAR2(200)
);

ALTER TABLE
    ERLR_GRIEVANCE
ADD
(
    GI_IND_STEP_1_DEADLINE  CHAR(1 BYTE) DEFAULT '0',
    GI_IND_STEP_1_EXT_DUE_DT	DATE,
    GI_IND_STEP_1_EXT_DUE_REASON	NVARCHAR2(500)
);

ALTER TABLE 
   ERLR_ULP
MODIFY 
( 
   ULP_DISPOSITION_TYPE    NVARCHAR2(200)   
);

ALTER TABLE 
   ERLR_LABOR_NEGO
MODIFY 
( 
   LN_NEGOTIATION_TYPE    NVARCHAR2(200),
   LN_INITIATOR NVARCHAR2(200)

);