ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD HRS_RVW_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD APPROVAL_SO_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD APPROVAL_DGHO_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD APPROVAL_TABG_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD APPROVAL_COC_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD JUSTIFICATION_CRT_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD JUSTIFICATION_LASTMOD_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE ADD JUSTIFICATION_MODIFIED_DATE_D DATE;

UPDATE HHS_CMS_HR.INCENTIVES_LE
SET HRS_RVW_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 10, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy'), null)
    ,APPROVAL_SO_RESP_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 10, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy'), null)
    ,APPROVAL_DGHO_RESP_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 10, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy'), null)
    ,APPROVAL_TABG_RESP_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 10, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy'), null)
    ,APPROVAL_COC_RESP_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 10, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy'), null)
    ,JUSTIFICATION_CRT_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 19, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy hh24:mi:ss'), null)
    ,JUSTIFICATION_MODIFIED_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 19, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy hh24:mi:ss'), null)
    ,JUSTIFICATION_LASTMOD_DATE_D = DECODE(LENGTH(HRS_RVW_DATE), 19, TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy hh24:mi:ss'), null)
;
