ALTER TABLE HHS_CMS_HR.ERLR_PROB_ACTION MODIFY PPA_PROBATION_CONDUCT NVARCHAR2(5) ;
ALTER TABLE HHS_CMS_HR.ERLR_PROB_ACTION MODIFY PPA_PROBATION_PERFORMANCE NVARCHAR2(5) ;
ALTER TABLE HHS_CMS_HR.ERLR_PROB_ACTION MODIFY PPA_RE_ASSIGNMENT_CURR_ORG NVARCHAR2(100) ;
ALTER TABLE HHS_CMS_HR.ERLR_PERF_ISSUE MODIFY PI_REASGN_CUR_ORG_NM NVARCHAR2(100);
