------------------------------------------------------
--Recreate View, ADMIN_CODES, to use the Administrative
--Code Source coming from the BIIS Interface
-------------------------------------------------------
	CREATE OR REPLACE VIEW HHS_CMS_HR.ADMIN_CODES AS 
	SELECT
		ADMIN_CODE AS AC_ADMIN_CD,
		ADMIN_CODE_DESC AS AC_ADMIN_CD_DESCR,
		SUBSTR(ADMIN_CODE, 1, LENGTH(ADMIN_CODE) -1) AS AC_PARENT_CD
	FROM HHS_HR.ADMINISTRATIVE_CODE
	WHERE OPDIV = 'CMS'
	AND ADMIN_CODE = 'F' OR ADMIN_CODE LIKE 'FC%';
	
   COMMENT ON COLUMN HHS_CMS_HR.ADMIN_CODES.AC_ADMIN_CD IS 'Unique admin code';
   COMMENT ON COLUMN HHS_CMS_HR.ADMIN_CODES.AC_ADMIN_CD_DESCR IS 'Description of admin code';
   COMMENT ON COLUMN HHS_CMS_HR.ADMIN_CODES.AC_PARENT_CD IS 'Key value of associated parent admin code';	
	

	GRANT SELECT ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_RW_ROLE;
	GRANT SELECT ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_DEV_ROLE;
	GRANT SELECT ON HHS_CMS_HR.ADMIN_CODES TO BF_DEV_ROLE;	

/*
----------------------------
--Backout Script
----------------------------


  CREATE OR REPLACE VIEW HHS_CMS_HR.ADMIN_CODES AS 
  SELECT
		ADMINISTRATIVE_CODE AS AC_ADMIN_CD
		, DESCRIPTION AS AC_ADMIN_CD_DESCR
		, SUBSTR(ADMINISTRATIVE_CODE, 1, LENGTH(ADMINISTRATIVE_CODE) -1) AS AC_PARENT_CD
	FROM HHS_CMS_HR.ADMINISTRATIVE_CODE
	WHERE ADMINISTRATIVE_CODE = 'F' OR ADMINISTRATIVE_CODE LIKE 'FC%';

   COMMENT ON COLUMN "HHS_CMS_HR"."ADMIN_CODES"."AC_ADMIN_CD" IS 'Unique admin code';
   COMMENT ON COLUMN "HHS_CMS_HR"."ADMIN_CODES"."AC_ADMIN_CD_DESCR" IS 'Description of admin code';
   COMMENT ON COLUMN "HHS_CMS_HR"."ADMIN_CODES"."AC_PARENT_CD" IS 'Key value of associated parent admin code';
 

*/