ALTER TABLE STRATCON_GEN
MODIFY (
  SG_HRL_ID NVARCHAR2(32),
  SG_HRL_TITLE NVARCHAR2(200),
  SG_HRL_ORG NVARCHAR2(200)
);

ALTER TABLE CLASSIF_STRATCON
MODIFY (
  HRL_ID NVARCHAR2(32),
  HRL_TITLE NVARCHAR2(200),
  HRL_ORG NVARCHAR2(200)
);

ALTER TABLE ELIG_QUAL
MODIFY (
  HRL_ID NVARCHAR2(32),
  HRL_TITLE NVARCHAR2(200),
  HRL_ORG NVARCHAR2(200)
);

