/*
 * Performance Tuning
 * Data Type mismatch: Currency and Date fields are all varchar2.
 * Adding new column with correct datatype, and populate the column value from the varchar2 column
 */

--1. ALTER INCENTIVES_SAM
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD INIT_SALARY_SALARY_PER_ANNUM_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD RCMD_SALARY_SALARY_PER_ANNUM_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD SELECTEE_SALARY_PER_ANNUM_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD SELECTEE_BONUS_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD SELECTEE_TOTAL_COMPENSATION_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD SUP_DOC_REQ_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD SUP_DOC_RCV_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD HRS_RVW_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD RCMD_SALARY_PER_ANNUM_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD RCMD_INC_DEC_AMOUNT_N NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD APPROVAL_SO_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD APPROVAL_DGHO_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD APPROVAL_TABG_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD APPROVAL_OHC_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD APPROVAL_COC_RESP_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD JUSTIFICATION_MODIFIED_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD JUSTIFICATION_CRT_DATE_D DATE;
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM ADD JUSTIFICATION_LASTMOD_DATE_D DATE;

--2. ALTER INCENTIVES_SAM_JUST_HISTORY
ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM_JUST_HISTORY ADD JUSTIFICATION_MODIFIED_DATE_D DATE;

--3. MIGRATE DATA TO NEW COLUMNS INCENTIVES_SAM
UPDATE INCENTIVES_SAM
SET INIT_SALARY_SALARY_PER_ANNUM_N = regexp_replace(INIT_SALARY_SALARY_PER_ANNUM, '[^0-9|.]', '')
    ,RCMD_SALARY_SALARY_PER_ANNUM_N = regexp_replace(RCMD_SALARY_SALARY_PER_ANNUM, '[^0-9|.]', '')
    ,SELECTEE_SALARY_PER_ANNUM_N = regexp_replace(SELECTEE_SALARY_PER_ANNUM, '[^0-9|.]', '')
    ,SELECTEE_BONUS_N = regexp_replace(SELECTEE_BONUS, '[^0-9|.]', '')
    ,SELECTEE_TOTAL_COMPENSATION_N = regexp_replace(SELECTEE_TOTAL_COMPENSATION, '[^0-9|.]', '')
    ,SUP_DOC_REQ_DATE_D = TO_DATE(SUP_DOC_REQ_DATE, 'mm/dd/yyyy')
    ,SUP_DOC_RCV_DATE_D = TO_DATE(SUP_DOC_RCV_DATE, 'mm/dd/yyyy')
    ,HRS_RVW_DATE_D = TO_DATE(HRS_RVW_DATE, 'mm/dd/yyyy')
    ,RCMD_SALARY_PER_ANNUM_N = regexp_replace(RCMD_SALARY_PER_ANNUM, '[^0-9|.]', '')
    ,RCMD_INC_DEC_AMOUNT_N = regexp_replace(RCMD_INC_DEC_AMOUNT, '[^0-9|.|+|-]', '')
    ,APPROVAL_SO_RESP_DATE_D = TO_DATE(APPROVAL_SO_RESP_DATE, 'mm/dd/yyyy')
    ,APPROVAL_DGHO_RESP_DATE_D = TO_DATE(APPROVAL_DGHO_RESP_DATE, 'mm/dd/yyyy')
    ,APPROVAL_TABG_RESP_DATE_D = TO_DATE(APPROVAL_TABG_RESP_DATE, 'mm/dd/yyyy')
    ,APPROVAL_OHC_RESP_DATE_D = TO_DATE(APPROVAL_OHC_RESP_DATE, 'mm/dd/yyyy')
    ,APPROVAL_COC_RESP_DATE_D = TO_DATE(APPROVAL_COC_RESP_DATE, 'mm/dd/yyyy')
    ,JUSTIFICATION_MODIFIED_DATE_D = TO_DATE(JUSTIFICATION_MODIFIED_DATE, 'mm/dd/yyyy hh24:mi:ss')
    ,JUSTIFICATION_CRT_DATE_D = TO_DATE(JUSTIFICATION_CRT_DATE, 'mm/dd/yyyy hh24:mi:ss')
    ,JUSTIFICATION_LASTMOD_DATE_D = TO_DATE(JUSTIFICATION_LASTMOD_DATE, 'mm/dd/yyyy hh24:mi:ss')
;

--4. MIGRATE DATA TO NEW COLUMNS INCENTIVES_SAM_JUST_HISTORY
UPDATE HHS_CMS_HR.INCENTIVES_SAM_JUST_HISTORY
SET JUSTIFICATION_MODIFIED_DATE_D = TO_DATE(JUSTIFICATION_MODIFIED_DATE, 'mm/dd/yyyy hh24:mi:ss')
;



