--------------------------------------------------------
--  DDL for Table SLA_HIRING_TIMELINE
--------------------------------------------------------

  CREATE TABLE "HHS_CMS_HR"."SLA_HIRING_TIMELINE" 
   (	"SLA_ID" VARCHAR2(50 BYTE) NOT NULL, 
	"PROCESS_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"ACTIVITY_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"SG_RT_ID" NUMBER(20,0) NOT NULL, 
	"TARGET_BUSINESS_DAY" NUMBER(3,0) DEFAULT 0 NOT NULL, 
	"TOTAL_CALENDAR_DAY" NUMBER(3,0) DEFAULT 0 NOT NULL, 
	"DISPLAY_ORDER" NUMBER
   );

  CREATE UNIQUE INDEX "HHS_CMS_HR"."SLA_HIRING_TIMELINE_PK" ON "HHS_CMS_HR"."SLA_HIRING_TIMELINE" ("SLA_ID");
  ALTER TABLE "HHS_CMS_HR"."SLA_HIRING_TIMELINE" ADD CONSTRAINT "SLA_HIRING_TIMELINE_PK" PRIMARY KEY ("SLA_ID");
 

set define off;
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_1',	1,18,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_2',	2,18,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_3',	3,18,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_4',	4,18,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_1',	1,18,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_2',	2,18,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_3',	3,18,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_4',	4,18,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_5',	5,18,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_1',	1,18,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_2',	2,18,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_3',	3,18,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_4',	4,18,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_5',	5,18,'Classification - Minor','Create Final Package (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_1',	1,18,'Recruitment','Draft announcement (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_2',	2,18,'Recruitment','Review Assessment/Announcement (Component)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_3',	3,18,'Recruitment','Final Edits and Post to USA jobs (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_4',	4,18,'Recruitment','Announcement Open Period (Other)',10,14);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_5',	5,18,'Recruitment','Qualification Analysis (HR)',12,16);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_6',	6,18,'Recruitment','Certificate Issue (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_7',	7,18,'Recruitment','Certificate Return (Component)',11,15);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_1',	1,18,'Offer','Send Tentative Offer (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_2',	2,18,'Offer','Receive Tentative Offer Response (Applicant)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_3',	3,18,'Offer','Complete Pre-Employment Forms & Initiate Background Investigation (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_4',	4,18,'Offer','Receive Background Investigation Clearance (Other)',10,12);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_5',	5,18,'Offer','Establish Entry on Duty Date (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_6',	6,18,'Offer','Send Official Offer (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_1',	1,76,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_2',	2,76,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_3',	3,76,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_4',	4,76,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_1',	1,76,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_2',	2,76,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_3',	3,76,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_4',	4,76,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_5',	5,76,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_1',	1,76,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_2',	2,76,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_3',	3,76,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_4',	4,76,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_5',	5,76,'Classification - Minor','Create Final Package (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_EQRA_1',	1,76,'Eligibility and Qualifications Review Activities','Staff or Spec. Staff determines eligibility and qualifications (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_EQRA_2',	2,76,'Eligibility and Qualifications Review Activities','SO Selection Determination (Component)',8,10);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_1',	1,76,'Offer','Send Tentative Offer (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_2',	2,76,'Offer','Receive Tentative Offer Response (Applicant)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_3',	3,76,'Offer','Complete Pre-Employment Forms & Initiate Background Investigation (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_4',	4,76,'Offer','Receive Background Investigation Clearance (Security)',10,12);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_5',	5,76,'Offer','Establish Entry on Duty Date (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_6',	6,76,'Offer','Send Official Offer (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_1',	1,17,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_2',	2,17,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_3',	3,17,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_4',	4,17,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_1',	1,17,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_2',	2,17,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_3',	3,17,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_4',	4,17,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_5',	5,17,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_1',	1,17,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_2',	2,17,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_3',	3,17,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_4',	4,17,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_5',	5,17,'Classification - Minor','Create Final Package (HR)',0,0);
