CREATE OR REPLACE FUNCTION HHS_CMS_HR.FN_GET_HIRINGTL_SLA_DAYS 
  (
    I_DAYSTYPE IN VARCHAR2,
    I_REQUESTTYPE IN VARCHAR2,
    I_ACTNAME IN VARCHAR2,
    I_MAJORMINOR IN VARCHAR2   
  )
RETURN NUMBER 
IS
V_DAYSTOTARGETCOMPLETION NUMBER(3);
  BEGIN
    IF I_MAJORMINOR IS NOT NULL THEN 
      IF I_DAYSTYPE = 'Calendar' THEN
           SELECT TOTAL_CALENDAR_DAY INTO V_DAYSTOTARGETCOMPLETION 
            FROM HHS_CMS_HR.SLA_HIRING_TIMELINE SLA 
            INNER JOIN HHS_CMS_HR.TBL_LOOKUP LKUP ON LKUP.TBL_ID = SLA.SG_RT_ID 
            WHERE SLA.ACTIVITY_NAME = I_ACTNAME
            AND LKUP.TBL_LABEL = I_REQUESTTYPE
            AND SLA.PROCESS_NAME like '%'||I_MAJORMINOR||'%';
      ELSE 
           SELECT TARGET_BUSINESS_DAY INTO V_DAYSTOTARGETCOMPLETION 
            FROM HHS_CMS_HR.SLA_HIRING_TIMELINE SLA 
            INNER JOIN HHS_CMS_HR.TBL_LOOKUP LKUP ON LKUP.TBL_ID = SLA.SG_RT_ID 
            WHERE SLA.ACTIVITY_NAME = I_ACTNAME            
            AND LKUP.TBL_LABEL = I_REQUESTTYPE
            AND SLA.PROCESS_NAME like '%'||I_MAJORMINOR||'%';
      END IF;
    ELSE 
      IF I_DAYSTYPE = 'Calendar' THEN
           SELECT TOTAL_CALENDAR_DAY INTO V_DAYSTOTARGETCOMPLETION 
            FROM HHS_CMS_HR.SLA_HIRING_TIMELINE SLA 
            INNER JOIN HHS_CMS_HR.TBL_LOOKUP LKUP ON LKUP.TBL_ID = SLA.SG_RT_ID 
            WHERE SLA.ACTIVITY_NAME = I_ACTNAME
            AND LKUP.TBL_LABEL = I_REQUESTTYPE;
      ELSE
           SELECT TARGET_BUSINESS_DAY INTO V_DAYSTOTARGETCOMPLETION 
            FROM HHS_CMS_HR.SLA_HIRING_TIMELINE SLA 
            INNER JOIN HHS_CMS_HR.TBL_LOOKUP LKUP ON LKUP.TBL_ID = SLA.SG_RT_ID 
            WHERE SLA.ACTIVITY_NAME = I_ACTNAME
            AND LKUP.TBL_LABEL = I_REQUESTTYPE;
      END IF;
    END IF;

    RETURN V_DAYSTOTARGETCOMPLETION;
  END;
/

GRANT EXECUTE ON HHS_CMS_HR.FN_GET_HIRINGTL_SLA_DAYS TO BIZFLOW;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_HIRINGTL_SLA_DAYS TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_HIRINGTL_SLA_DAYS TO HHS_CMS_HR_DEV_ROLE;

COMMIT;
/