SET DEFINE OFF;

CREATE OR REPLACE PROCEDURE SP_UPDATE_INCENTIVES_TABLE
(
	I_PROCID            IN      NUMBER
	, I_FIELD_DATA      IN      XMLTYPE
)
IS
	V_XMLVALUE             XMLTYPE;
	V_INCENTIVE_TYPE     NVARCHAR2(50);

BEGIN
	IF I_PROCID IS NOT NULL AND I_PROCID > 0 THEN
		V_XMLVALUE := I_FIELD_DATA.EXTRACT('/formData/items/item[id="incentiveType"]/value/text()');
		IF V_XMLVALUE IS NOT NULL THEN
			V_INCENTIVE_TYPE := V_XMLVALUE.GETSTRINGVAL();
		ELSE
			V_INCENTIVE_TYPE := NULL;
		END IF;

		SP_UPDATE_INCENTIVES_COM_TABLE(I_PROCID);

		IF 'PCA' = V_INCENTIVE_TYPE THEN
			SP_UPDATE_INCENTIVES_PCA_TABLE(I_PROCID);
		ELSIF 'PDP' = V_INCENTIVE_TYPE THEN
			SP_UPDATE_INCENTIVES_PDP_TABLE(I_PROCID);
		ELSIF 'SAM' = V_INCENTIVE_TYPE THEN
			SP_UPDATE_INCENTIVES_SAM_TABLE(I_PROCID);
		ELSIF 'LE' = V_INCENTIVE_TYPE THEN
			SP_UPDATE_INCENTIVES_LE_TABLE(I_PROCID);
		END IF;
	END IF;

	EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/