ALTER TABLE
  PD_COVERSHEET
ADD
  STD_PD_TYPE NVARCHAR2(200);
  
COMMENT ON COLUMN PD_COVERSHEET.STD_PD_TYPE 
   IS 'Type of Standard PD for the Request';

ALTER TABLE
  POSITION
ADD
  POS_STD_PD_TYPE NVARCHAR2(200);
  
COMMENT ON COLUMN POSITION.POS_STD_PD_TYPE 
   IS 'Type of Standard PD for the Request';
   
