ALTER TABLE HHS_CMS_HR.INCENTIVES_SAM
ADD (
  DISAPPROVAL_REASON VARCHAR2(100), 
	DISAPPROVAL_USER_NAME VARCHAR2(100), 
	DISAPPROVAL_USER_ID VARCHAR2(10) 
);
  
ALTER TABLE HHS_CMS_HR.INCENTIVES_LE
ADD (
  DISAPPROVAL_REASON VARCHAR2(100), 
	DISAPPROVAL_USER_NAME VARCHAR2(100), 
	DISAPPROVAL_USER_ID VARCHAR2(10) 
);
