create or replace PROCEDURE SP_UPDATE_ERLR_TABLE
(
    I_PROCID            IN      NUMBER
)
IS
    V_CASE_NUMBER               NUMBER(20);
    V_CASE_TYPE                 NUMBER;
    V_JOB_REQ_NUM               NVARCHAR2(50);
    V_CASE_CREATION_DT          DATE;    
    V_VALUE                     NVARCHAR2(4000);
    V_XMLDOC                    XMLTYPE;
    V_APPEAL_TYPE               VARCHAR2(50);
BEGIN
	IF I_PROCID IS NULL OR I_PROCID = 0 THEN
		RETURN;
	END IF;

	------------------------------------------------------
	-- Transfer XML data into operational table
	--
	-- 1. Get Case number and Job Request Number
	-- 1.1 Select it from data xml from TBL_FORM_DTL table.
	-- 1.2 If not found, select it from BIZFLOW.RLVNTDATA table.
	-- 2. If Case number /Job Request Number not found, issue error.
	-- 3. For each target table,
	-- 3.1. If record found for the CASE_NUMBER, update record.
	-- 3.2. If record not found for the CASE_NUMBER, insert record.
	------------------------------------------------------

	--------------------------------
	-- get Case number
	--------------------------------
	BEGIN
	    SELECT VALUE
	    INTO V_CASE_NUMBER
	    FROM BIZFLOW.RLVNTDATA
	    WHERE PROCID = I_PROCID AND RLVNTDATANAME = 'caseNumber';
	EXCEPTION
	    WHEN NO_DATA_FOUND THEN V_CASE_NUMBER := NULL;
	END;

	IF V_CASE_NUMBER IS NULL THEN
	    RAISE_APPLICATION_ERROR(-20902, 'SP_UPDATE_ERLR_TABLE: Case Number is invalid.  I_PROCID = '
		|| TO_CHAR(I_PROCID) || ' V_CASE_NUMBER = ' || V_CASE_NUMBER || '  V_CASE_NUMBER = ' || TO_CHAR(V_CASE_NUMBER));
	END IF;

	--------------------------------
	-- get Request number 
	--------------------------------
	BEGIN
	    SELECT VALUE
	    INTO V_JOB_REQ_NUM
	    FROM BIZFLOW.RLVNTDATA
	    WHERE PROCID = I_PROCID AND RLVNTDATANAME = 'requestNum';
	EXCEPTION
	    WHEN NO_DATA_FOUND THEN V_JOB_REQ_NUM := NULL;
	END;

	--------------------------------
	-- get Case Creation Date
	--------------------------------
	BEGIN
	    SELECT CREATIONDTIME
	      INTO V_CASE_CREATION_DT
	      FROM BIZFLOW.PROCS
	     WHERE PROCID = I_PROCID;
	EXCEPTION
	    WHEN NO_DATA_FOUND THEN V_CASE_CREATION_DT := NULL;
	END;

	SELECT FIELD_DATA
	  INTO V_XMLDOC
	  FROM TBL_FORM_DTL
	 WHERE PROCID = I_PROCID;

	--------------------------------
	-- ERLR_CASE table
	--------------------------------
	DELETE ERLR_CASE WHERE PROCID = I_PROCID;
	INSERT INTO ERLR_CASE (
		  ERLR_CASE_NUMBER
		  ,ERLR_JOB_REQ_NUMBER
		  ,PROCID 
		  ,ERLR_CASE_STATUS_ID
		  ,ERLR_CASE_CREATE_DT
		)VALUES(
		  V_CASE_NUMBER
		  ,V_JOB_REQ_NUM
		  ,I_PROCID
		  ,FN_EXTRACT_STR (V_XMLDOC, 'GEN_CASE_STATUS')
		  ,V_CASE_CREATION_DT
		);

	--------------------------------
	-- ERLR_GEN table
	--------------------------------
	DELETE ERLR_GEN WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
	DECLARE V_FINAL_ACTIONS VARCHAR2(2000);
	        V_CATEGORY_NAMES VARCHAR2(1000);
	        V_CATEGORY_IDS VARCHAR2(200);
            V_CLASS VARCHAR2(10);
            V_CASE_TYPE NUMBER;
            V_THRD_PRTY_APPEAL_TYPE VARCHAR2(100);
            V_PRIMARY_SP_ID VARCHAR2(20);
            V_SECOND_SP_ID VARCHAR2(20);
            V_PRIMARY_SP_NAME VARCHAR2(150);
            V_SECOND_SP_NAME VARCHAR2(150);
	BEGIN
		SELECT XMLQUERY('for $i in /formData/items/item[id="CC_FINAL_ACTION_SEL"]/value return concat($i/value/text(), ", ")'
		       PASSING V_XMLDOC RETURNING CONTENT).GETSTRINGVAL() INTO V_FINAL_ACTIONS FROM DUAL;
		V_FINAL_ACTIONS := SUBSTR(V_FINAL_ACTIONS, 0, LENGTH(V_FINAL_ACTIONS)-2);

		SELECT XMLQUERY('for $i in /formData/items/item[id="GEN_CASE_CATEGORY_SEL"]/value return concat($i/text/text(), ", ")'
		       PASSING V_XMLDOC RETURNING CONTENT).GETSTRINGVAL() INTO V_CATEGORY_NAMES FROM DUAL;
		V_CATEGORY_NAMES := SUBSTR(V_CATEGORY_NAMES, 0, LENGTH(V_CATEGORY_NAMES)-2);

		SELECT XMLQUERY('for $i in /formData/items/item[id="GEN_CASE_CATEGORY_SEL"]/value return concat($i/value/text(), ",")'
		       PASSING V_XMLDOC RETURNING CONTENT).GETSTRINGVAL() INTO V_CATEGORY_IDS FROM DUAL;
		V_CATEGORY_IDS := SUBSTR(V_CATEGORY_IDS, 0, LENGTH(V_CATEGORY_IDS)-1);
        
        V_CASE_TYPE := TO_NUMBER(FN_EXTRACT_STR (V_XMLDOC, 'GEN_CASE_TYPE'));
        
        IF V_CASE_TYPE IN (743, 744, 746, 750, 751, 809) THEN -- 'Conduct Issue', 'Investigation', 'Medical Documentation', 'Performance Issue', 'Probationary Period Action', 'Within Grade Increase Denial/Reconsideration'            
            V_CLASS := 'ER';
        ELSIF V_CASE_TYPE IN (748, 745, 747, 754) THEN -- 'Labor Negotiation', 'Grievance', 'Information Request', 'Unfair Labor Practice'            
            V_CLASS := 'LR';
        ELSIF V_CASE_TYPE IN (753) THEN -- 'Third Party Hearing'   
            V_THRD_PRTY_APPEAL_TYPE := FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_APPEAL_TYPE');
            IF V_THRD_PRTY_APPEAL_TYPE = 'MSPB' THEN
                V_CLASS := 'ER';
            ELSIF V_THRD_PRTY_APPEAL_TYPE IN ('Arbitration', 'FLRA', 'FSIP', 'Grievance') THEN
                V_CLASS := 'LR';
            END IF;
        END IF;
        
        V_PRIMARY_SP_ID := SUBSTR(FN_EXTRACT_STR (V_XMLDOC, 'GEN_PRIMARY_SPECIALIST'), 4, 10);
        IF V_PRIMARY_SP_ID IS NOT NULL THEN
            SELECT NAME
              INTO V_PRIMARY_SP_NAME
              FROM BIZFLOW.MEMBER
             WHERE MEMBERID = V_PRIMARY_SP_ID;
        END IF;
        
        V_SECOND_SP_ID := SUBSTR(FN_EXTRACT_STR (V_XMLDOC, 'GEN_SECONDARY_SPECIALIST'), 4, 10);
        IF V_SECOND_SP_ID IS NOT NULL THEN
            SELECT NAME
              INTO V_SECOND_SP_NAME
              FROM BIZFLOW.MEMBER
             WHERE MEMBERID = V_PRIMARY_SP_ID;
        END IF;
        
		INSERT INTO ERLR_GEN (
                PROCID,
                ERLR_CASE_NUMBER,
                GEN_PRIMARY_SPECIALIST,
                GEN_SECONDARY_SPECIALIST,
                GEN_CUSTOMER_NAME,
                GEN_CUSTOMER_PHONE,
                GEN_CUSTOMER_ADMIN_CD,
                GEN_CUSTOMER_ADMIN_CD_DESC,
                GEN_EMPLOYEE_NAME,                    
                GEN_EMPLOYEE_ID,
                GEN_EMPLOYEE_PHONE,
                GEN_EMPLOYEE_ADMIN_CD,
                GEN_EMPLOYEE_ADMIN_CD_DESC,
                GEN_CASE_DESC,
                GEN_CASE_STATUS,
                GEN_CUST_INIT_CONTACT_DT,
                GEN_PRIMARY_REP_AFFILIATION,
                GEN_CMS_PRIMARY_REP_ID,
                GEN_CMS_PRIMARY_REP_PHONE,
                GEN_NON_CMS_PRIMARY_FNAME,
                GEN_NON_CMS_PRIMARY_MNAME,
                GEN_NON_CMS_PRIMARY_LNAME,
                GEN_NON_CMS_PRIMARY_EMAIL,
                GEN_NON_CMS_PRIMARY_PHONE,
                GEN_NON_CMS_PRIMARY_ORG,
                GEN_NON_CMS_PRIMARY_ADDR,
                GEN_CASE_TYPE,
                GEN_CASE_CATEGORY,
                GEN_INVESTIGATION,
                GEN_INVESTIGATE_START_DT,
                GEN_INVESTIGATE_END_DT,
                GEN_STD_CONDUCT,
                GEN_STD_CONDUCT_TYPE,
                CC_FINAL_ACTION,
                CC_FINAL_ACTION_OTHER,
                CC_CASE_COMPLETE_DT,
                GEN_CASE_CATEGORY_NAME,
                GEN_CASE_TYPE_NAME,
                GEN_CLASS,
                GEN_PRIMARY_SPECIALIST_NAME,
                GEN_SECONDARY_SPECIALIST_NAME,
                GEN_EMPLOYEE_2ND_SUB_ORG                
		       ) VALUES (
                I_PROCID,
                V_CASE_NUMBER,
                V_PRIMARY_SP_ID,
                V_SECOND_SP_ID,
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CUSTOMER_NAME'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CUSTOMER_PHONE'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CUSTOMER_ADMIN_CD'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CUSTOMER_ADMIN_CD_DESC'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_NAME'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_ID'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_PHONE'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_ADMIN_CD'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_ADMIN_CD_DESC'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CASE_DESC'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CASE_STATUS'),
                FN_EXTRACT_DATE(V_XMLDOC, 'GEN_CUST_INIT_CONTACT_DT'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_PRIMARY_REP'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CMS_PRIMARY_REP', 'value/name'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_CMS_PRIMARY_REP_PHONE'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_FNAME'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_MNAME'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_LNAME'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_EMAIL'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_PHONE'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_ORG'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_NON_CMS_PRIMARY_ADDR'),
                V_CASE_TYPE,
                V_CATEGORY_IDS,
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_INVESTIGATION'),
                FN_EXTRACT_DATE(V_XMLDOC, 'GEN_INVESTIGATE_START_DT'),
                FN_EXTRACT_DATE(V_XMLDOC, 'GEN_INVESTIGATE_END_DT'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_STD_CONDUCT'),
                FN_EXTRACT_STR (V_XMLDOC, 'GEN_STD_CONDUCT_TYPE'),
                V_FINAL_ACTIONS,
                FN_EXTRACT_STR (V_XMLDOC, 'CC_FINAL_ACTION_OTHER'),
                FN_EXTRACT_DATE(V_XMLDOC, 'CC_CASE_COMPLETE_DT'),
                V_CATEGORY_NAMES,
                (SELECT TBL_LABEL FROM TBL_LOOKUP WHERE TBL_ID = V_CASE_TYPE),
                V_CLASS,
                V_PRIMARY_SP_NAME,
                V_SECOND_SP_NAME,
                FN_GET_2ND_SUB_ORG(FN_EXTRACT_STR (V_XMLDOC, 'GEN_EMPLOYEE_ADMIN_CD'))
		       );
        
        SELECT GEN_CASE_TYPE 
          INTO V_CASE_TYPE
          FROM ERLR_GEN
         WHERE PROCID = I_PROCID;
	END;

	--------------------------------
	-- ERLR_APPEAL table
	--------------------------------	
	DELETE ERLR_APPEAL WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    V_APPEAL_TYPE := FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_APPEAL_TYPE');
    IF V_APPEAL_TYPE IS NOT NULL AND 0<LENGTH(V_APPEAL_TYPE) THEN
        INSERT INTO ERLR_APPEAL(
            ERLR_CASE_NUMBER
            , AP_ERLR_APPEAL_TYPE
            , AP_ERLR_APPEAL_FILE_DT
            , AP_ERLR_APPEAL_TIMING
            , AP_APPEAL_HEARING_REQUESTED
            , AP_ARBITRATOR_LAST_NAME
            , AP_ARBITRATOR_FIRST_NAME
            , AP_ARBITRATOR_MIDDLE_NAME
            , AP_ARBITRATOR_EMAIL
            , AP_ARBITRATOR_PHONE_NUM
            , AP_ARBITRATOR_ORG_AFFIL
            , AP_ARBITRATOR_MAILING_ADDR
            , AP_ERLR_PREHEARING_DT
            , AP_ERLR_HEARING_DT    
            , AP_POSTHEARING_BRIEF_DUE
            , AP_FINAL_ARBITRATOR_DCSN_DT
            , AP_ERLR_EXCEPTION_FILED
            , AP_ERLR_EXCEPTION_FILE_DT
            , AP_RESPON_TO_EXCEPT_DUE
            , AP_FINAL_FLRA_DECISION_DT
            , AP_ERLR_STEP_DECISION_DT
            , AP_ERLR_ARBITRATION_INVOKED
            , AP_ARBITRATOR_LAST_NAME_3
            , AP_ARBITRATOR_FIRST_NAME_3
            , AP_ARBITRATOR_MIDDLE_NAME_3
            , AP_ARBITRATOR_EMAIL_3
            , AP_ARBITRATOR_PHONE_NUM_3
            , AP_ARBITRATOR_ORG_AFFIL_3
            , AP_ARBITRATION_MAILING_ADDR_3
            , AP_ERLR_PREHEARING_DT_2
            , AP_ERLR_HEARING_DT_2
            , AP_POSTHEARING_BRIEF_DUE_2
            , AP_FINAL_ARBITRATOR_DCSN_DT_2
            , AP_ERLR_EXCEPTION_FILED_2
            , AP_ERLR_EXCEPTION_FILE_DT_2
            , AP_RESPON_TO_EXCEPT_DUE_2
            , AP_FINAL_FLRA_DECISION_DT_2
            , AP_ARBITRATOR_LAST_NAME_2
            , AP_ARBITRATOR_FIRST_NAME_2
            , AP_ARBITRATOR_MIDDLE_NAME_2
            , AP_ARBITRATOR_EMAIL_2
            , AP_ARBITRATOR_PHONE_NUM_2
            , AP_ARBITRATOR_ORG_AFFIL_2
            , AP_ARBITRATION_MAILING_ADDR_2
            , AP_ERLR_PREHEARING_DT_SC
            , AP_ERLR_HEARING_DT_SC
            , AP_ARBITRATOR_LAST_NAME_4
            , AP_ARBITRATOR_FIRST_NAME_4
            , AP_ARBITRATOR_MIDDLE_NAME_4
            , AP_ARBITRATOR_EMAIL_4
            , AP_ARBITRATOR_PHONE_NUM_4
            , AP_ARBITRATOR_ORG_AFFIL_4
            , AP_ARBITRATOR_MAILING_ADDR_4
            , AP_DT_SETTLEMENT_DISCUSSION
            , AP_DT_PREHEARING_DISCLOSURE
            , AP_DT_AGNCY_FILE_RESPON_DUE
            , AP_ERLR_PREHEARING_DT_MSPB
            , AP_WAS_DISCOVERY_INITIATED
            , AP_ERLR_DT_DISCOVERY_DUE
            , AP_ERLR_HEARING_DT_MSPB
            , AP_PETITION_FILE_DT_MSPB
            , AP_WAS_PETITION_FILED_MSPB
            , AP_INITIAL_DECISION_DT_MSPB
            , AP_FINAL_BOARD_DCSN_DT_MSPB
            , AP_DT_SETTLEMENT_DISCUSSION_2
            , AP_DT_PREHEARING_DISCLOSURE_2
            , AP_DT_AGNCY_FILE_RESPON_DUE_2
            , AP_ERLR_PREHEARING_DT_FLRA
            , AP_ERLR_HEARING_DT_FLRA
            , AP_INITIAL_DECISION_DT_FLRA
            , AP_WAS_PETITION_FILED_FLRA
            , AP_PETITION_FILE_DT_FLRA
            , AP_FINAL_BOARD_DCSN_DT_FLRA
            )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_APPEAL_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_APPEAL_FILE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_APPEAL_TIMING')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_APPEAL_HEARING_REQUESTED')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_LAST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_FIRST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_MIDDLE_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_EMAIL')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_PHONE_NUMBER')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_ORGANIZATION_AFFILIATION')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATION_MAILING_ADDR')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PREHEARING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_HEARING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_POSTHEARING_BRIEF_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_ARBITRATOR_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_EXCEPTION_FILED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_EXCEPTION_FILE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_RESPONSE_TO_EXCEPTIONS_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_FLRA_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_STEP_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATION_INVOKED')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_LAST_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_FIRST_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_MIDDLE_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_EMAIL_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_PHONE_NUMBER_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_ORGANIZATION_AFFILIATION_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATION_MAILING_ADDR_3')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PREHEARING_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_HEARING_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_POSTHEARING_BRIEF_DUE_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_ARBITRATOR_DECISION_DT_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_EXCEPTION_FILED_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_EXCEPTION_FILE_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_RESPONSE_TO_EXCEPTIONS_DUE_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_FLRA_DECISION_DT_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_LAST_NAME_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_FIRST_NAME_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_MIDDLE_NAME_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_EMAIL_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_PHONE_NUMBER_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_ORGANIZATION_AFFILIATION_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATION_MAILING_ADDR_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PREHEARING_DT_SC')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_HEARING_DT_SC')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_LAST_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_FIRST_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_MIDDLE_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_EMAIL_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_PHONE_NUMBER_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATOR_ORGANIZATION_AFFILIATION_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_ARBITRATION_MAILING_ADDR')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_SETTLEMENT_DISCUSSION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_PREHEARING_DISCLOSURE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_AGENCY_FILE_RESPONSE_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PREHEARING_DT_MSPB')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_WAS_DISCOVERY_INITIATED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_DISCOVERY_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_HEARING_DT_MSPB')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PETITION_4REVIEW_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_WAS_PETITION_4REVIEW_MSPB')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_initial_decision_MSPB_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_DECISION_MSPB_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_SETTLEMENT_DISCUSSION_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_PREHEARING_DISCLOSURE_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DT_AGENCY_FILE_RESPONSE_DUE_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_PREHEARING_DT_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_HEARING_DT_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_DECISION_DT_FLRA')
            , FN_EXTRACT_STR (V_XMLDOC, 'AP_ERLR_WAS_DECISION_APPEALED_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_APPEAL_FILE_DT_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'AP_ERLR_FINAL_DECISION_FLRA_DT')
            );
    END IF;    

	--------------------------------
	-- ERLR_CNDT_ISSUE table
	--------------------------------
	DELETE ERLR_CNDT_ISSUE WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 743 THEN
        INSERT INTO ERLR_CNDT_ISSUE(
            ERLR_CASE_NUMBER
            , CI_ACTION_TYPE
            , CI_ADMIN_INVESTIGATORY_LEAVE
            , CI_ADMIN_NOTICE_LEAVE            
            , CI_LEAVE_START_DT
            , CI_LEAVE_END_DT
            , CI_APPROVAL_NAME
            , CI_LEAVE_START_DT_2
            , CI_LEAVE_END_DT_2
            , CI_APPROVAL_NAME_2
            , CI_PROP_ACTION_ISSUED_DT
            , CI_ORAL_PREZ_REQUESTED
            , CI_ORAL_PREZ_DT
            , CI_ORAL_RESPONSE_SUBMITTED
            , CI_RESPONSE_DUE_DT
            , CI_WRITTEN_RESPONSE_SBMT_DT
            , CI_POS_TITLE
            , CI_PPLAN
            , CI_SERIES
            , CI_CURRENT_INFO_GRADE
            , CI_CURRENT_INFO_STEP
            , CI_PROPOSED_POS_TITLE
            , CI_PROPOSED_PPLAN
            , CI_PROPOSED_SERIES
            , CI_PROPOSED_INFO_GRADE
            , CI_PROPOSED_INFO_STEP
            , CI_FINAL_POS_TITLE
            , CI_FINAL_PPLAN
            , CI_FINAL_SERIES
            , CI_FINAL_INFO_GRADE
            , CI_FINAL_INFO_STEP
            , CI_DEMO_FINAL_AGNCY_DCSN
            , CI_DECIDING_OFFCL
            , CI_DECISION_ISSUED_DT
            , CI_DEMO_FINAL_AGENCY_EFF_DT
            , CI_NUMB_DAYS
            , CI_COUNSEL_TYPE
            , CI_COUNSEL_ISSUED_DT
            , CI_SICK_LEAVE_ISSUED_DT
            , CI_RESTRICTION_ISSED_DT
            , CI_SL_REVIEWED_DT_LIST
            , CI_SL_WARNING_DISCUSS_DT_LIST
            , CI_SL_WARN_ISSUE
            , CI_NOTICE_ISSUED_DT
            , CI_EFFECTIVE_DT
            , CI_CURRENT_ADMIN_CODE
            , CI_RE_ASSIGNMENT_CURR_ORG
            , CI_FINAL_ADMIN_CODE
            , CI_RE_ASSIGNMENT_FINAL_ORG
            , CI_REMOVAL_PROP_ACTION_DT
            , CI_EMP_NOTICE_LEAVE_PLACED
            , CI_REMOVAL_NOTICE_START_DT
            , CI_REMOVAL_NOTICE_END_DT
            , CI_RMVL_ORAL_PREZ_RQSTED
            , CI_REMOVAL_ORAL_PREZ_DT
            , CI_RMVL_WRTN_RESPONSE
            , CI_WRITTEN_RESPONSE_DUE_DT
            , CI_WRITTEN_SUBMITTED_DT
            , CI_RMVL_FINAL_AGNCY_DCSN
            , CI_DECIDING_OFFCL_NAME
            , CI_RMVL_DATE_DCSN_ISSUED
            , CI_REMOVAL_EFFECTIVE_DT
            , CI_RMVL_NUMB_DAYS
            , CI_SUSPENTION_TYPE
            , CI_SUSP_PROP_ACTION_DT
            , CI_SUSP_ORAL_PREZ_REQUESTED
            , CI_SUSP_ORAL_PREZ_DT
            , CI_SUSP_WRITTEN_RESP
            , CI_SUSP_WRITTEN_RESP_DUE_DT
            , CI_SUSP_WRITTEN_RESP_DT
            , CI_SUSP_FINAL_AGNCY_DCSN
            , CI_SUSP_DECIDING_OFFCL_NAME
            , CI_SUSP_DECISION_ISSUED_DT
            , CI_SUSP_EFFECTIVE_DECISION_DT
            , CI_SUS_NUMB_DAYS
            , CI_REPRIMAND_ISSUE_DT
            , CI_EMP_APPEAL_DECISION               
            )
            VALUES
            (
            V_CASE_NUMBER
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_ACTION_TYPE')
            ,CASE WHEN FN_EXTRACT_STR (V_XMLDOC, 'CI_ADMIN_INVESTIGATORY_LEAVE') = 'true'  THEN '1' ELSE '0' END
            ,CASE WHEN FN_EXTRACT_STR (V_XMLDOC, 'CI_ADMIN_NOTICE_LEAVE') = 'true'  THEN '1' ELSE '0' END
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_LEAVE_START_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_LEAVE_END_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_APPROVAL_NAME', 'value/name')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_LEAVE_START_DT_2')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_LEAVE_END_DT_2')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_APPROVAL_NAME_2', 'value/name')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_PROP_ACTION_ISSUED_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_ORAL_PREZ_REQUESTED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_ORAL_PREZ_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_ORAL_RESPONSE_SUBMITTED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_RESPONSE_DUE_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_WRITTEN_RESPONSE_SUBMITTED_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_POS_TITLE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PPLAN')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SERIES')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_CURRENT_INFO_GRADE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_CURRENT_INFO_STEP')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PROPOSED_POS_TITLE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PROPOSED_PPLAN')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PROPOSED_SERIES')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PROPOSED_INFO_GRADE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_PROPOSED_INFO_STEP')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_POS_TITLE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_PPLAN')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_SERIES')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_INFO_GRADE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_INFO_STEP')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_DEMO_FINAL_AGENCY_DECISION')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_DECIDING_OFFCL', 'value/name')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_DECISION_ISSUED_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_DEMO_FINAL_AGENCY_EFF_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_NUMB_DAYS')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_COUNSEL_TYPE')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_COUNSEL_ISSUED_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SICK_LEAVE_ISSUED_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_RESTRICTION_ISSED_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SICK_LEAVE_REVIEWED_DT_LIST')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SL_WARNING_DISCUSSION_DT_LIST')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SL_WARN_ISSUE')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_NOTICE_ISSUED_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_EFFECTIVE_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_CURRENT_ADMIN_CODE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_RE_ASSIGNMENT_CURR_ORG')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_FINAL_ADMIN_CODE')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_RE_ASSIGNMENT_FINAL_ORG')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_PROP_ACTION_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_EMP_NOTICE_LEAVE_PLACED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_NOTICE_START_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_NOTICE_END_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_REMOVAL_ORAL_PREZ_REQUESTED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_ORAL_PREZ_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_REMOVAL_WRITTEN_RESPONSE')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_WRITTEN_RESPONSE_DUE_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_WRITTEN_SUBMITTED_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_RMVL_FINAL_AGENCY_DECISION')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_DECIDING_OFFCL_NAME', 'value/name')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_DATE_DECISION_ISSUED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REMOVAL_EFFECTIVE_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_RMVL_NUMB_DAYS')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUSPENTION_TYPE')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_PROP_ACTION_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUSP_ORAL_PREZ_REQUESTED')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_ORAL_PREZ_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUSP_WRITTEN_RESP')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_WRITTEN_RESP_DUE_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_WRITTEN_RESP_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUSP_FINAL_AGENCY_DECISION')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUSP_DECIDING_OFFCL_NAME', 'value/name')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_DECISION_ISSUED_DT')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_SUSP_EFFECTIVE_DECISION_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_SUS_NUMB_DAYS')
            ,FN_EXTRACT_DATE(V_XMLDOC, 'CI_REPRIMAND_ISSUE_DT')
            ,FN_EXTRACT_STR (V_XMLDOC, 'CI_EMP_APPEAL_DECISION')
            );
    END IF;
    
	--------------------------------
	-- ERLR_PERF_ISSUE table
	--------------------------------
	DELETE ERLR_PERF_ISSUE WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 750 THEN
        INSERT INTO ERLR_PERF_ISSUE(
            ERLR_CASE_NUMBER
            , PI_ACTION_TYPE
            , PI_NEXT_WGI_DUE_DT    
            , PI_PERF_COUNSEL_ISSUE_DT    
            , PI_CNSL_GRV_DECISION
            , PI_DMTN_PRPS_ACTN_ISSUE_DT    
            , PI_DMTN_ORAL_PRSNT_REQ
            , PI_DMTN_ORAL_PRSNT_DT    
            , PI_DMTN_WRTN_RESP_SBMT
            , PI_DMTN_WRTN_RESP_DUE_DT    
            , PI_DMTN_WRTN_RESP_SBMT_DT    
            , PI_DMTN_CUR_POS_TITLE
            , PI_DMTN_CUR_PAY_PLAN
            , PI_DMTN_CUR_JOB_SERIES
            , PI_DMTN_CUR_GRADE
            , PI_DMTN_CUR_STEP
            , PI_DMTN_PRPS_POS_TITLE
            , PI_DMTN_PRPS_PAY_PLAN
            , PI_DMTN_PRPS_JOB_SERIES
            , PI_DMTN_PRPS_GRADE
            , PI_DMTN_PRP_STEP
            , PI_DMTN_FIN_POS_TITLE
            , PI_DMTN_FIN_PAY_PLAN
            , PI_DMTN_FIN_JOB_SERIES
            , PI_DMTN_FIN_GRADE
            , PI_DMTN_FIN_STEP
            , PI_DMTN_FIN_AGCY_DECISION
            , PI_DMTN_FIN_DECIDING_OFC
            , PI_DMTN_FIN_DECISION_ISSUE_DT    
            , PI_DMTN_DECISION_EFF_DT    
            , PI_DMTN_APPEAL_DECISION
            , PI_PIP_RSNBL_ACMDTN
            , PI_PIP_EMPL_SBMT_MEDDOC
            , PI_PIP_DOC_SBMT_FOH_RVW
            , PI_PIP_WGI_WTHLD
            , PI_PIP_WGI_RVW_DT    
            , PI_PIP_MEDDOC_RVW_OUTCOME
            , PI_PIP_START_DT    
            , PI_PIP_END_DT    
            , PI_PIP_EXT_END_DT    
            , PI_PIP_EXT_END_REASON
            , PI_PIP_EXT_END_NOTIFY_DT    
            , PI_PIP_EXT_DT_LIST    
            , PI_PIP_ACTUAL_DT    
            , PI_PIP_END_PRIOR_TO_PLAN
            , PI_PIP_END_PRIOR_TO_PLAN_RSN
            , PI_PIP_SUCCESS_CMPLT
            , PI_PIP_PMAP_RTNG_SIGN_DT    
            , PI_PIP_PMAP_RVW_SIGN_DT    
            , PI_PIP_PRPS_ACTN    
            , PI_PIP_PRPS_ISSUE_DT    
            , PI_PIP_ORAL_PRSNT_REQ    
            , PI_PIP_ORAL_PRSNT_DT    
            , PI_PIP_WRTN_RESP_SBMT    
            , PI_PIP_WRTN_RESP_DUE_DT    
            , PI_PIP_WRTN_SBMT_DT    
            , PI_PIP_FIN_AGCY_DECISION
            , PI_PIP_DECIDING_OFFICAL
            , PI_PIP_FIN_AGCY_DECISION_DT    
            , PI_PIP_DECISION_ISSUE_DT    
            , PI_PIP_EFF_ACTN_DT    
            , PI_PIP_EMPL_GRIEVANCE    
            , PI_PIP_APPEAL_DECISION
            , PI_REASGN_NOTICE_DT    
            , PI_REASGN_EFF_DT    
            , PI_REASGN_CUR_ADMIN_CD
            , PI_REASGN_CUR_ORG_NM    
            , PI_REASGN_FIN_ADMIN_CD
            , PI_REASGN_FIN_ORG_NM    
            , PI_RMV_PRPS_ACTN_ISSUE_DT    
            , PI_RMV_EMPL_NOTC_LEV    
            , PI_RMV_NOTC_LEV_START_DT    
            , PI_RMV_NOTC_LEV_END_DT    
            , PI_RMV_ORAL_PRSNT_REQ    
            , PI_RMV_ORAL_PRSNT_DT    
            , PI_RMV_WRTN_RESP_DUE_DT    
            , PI_RMV_WRTN_RESP_SBMT_DT    
            , PI_RMV_FIN_AGCY_DECISION    
            , PI_RMV_FIN_DECIDING_OFC    
            , PI_RMV_DECISION_ISSUE_DT    
            , PI_RMV_EFF_DT    
            , PI_RMV_NUM_DAYS    
            , PI_RMV_APPEAL_DECISION    
            , PI_WRTN_NRTV_RVW_TYPE    
            , PI_WNR_SPCLST_RVW_CMPLT_DT    
            , PI_WNR_MGR_RVW_RTNG_DT    
            , PI_WNR_CRITICAL_ELM    
            , PI_WNR_FIN_RATING
            , PI_WNR_RVW_OFC_CONCUR_DT    
            , PI_WNR_WGI_WTHLD
            , PI_WNR_WGI_RVW_DT
            , PI_CLPD_ENTRANCE_DUTY_DT
            , PI_CLPD_NEXT_CLP_DUE_DT
            , PI_CLPD_PRE_WITHHELD
            , PI_CLPD_FIRST_WNI_DT
            , PI_CLPD_NEXT_REVIEW_DUE_DT
            , PI_CLPD_DAPI_DT
            , PI_CLPD_FIRST_WITHHELD_DT
            , PI_CLPD_PLANNED_REVIEW_DT
            , PI_CLPD_DETER_FAV
            , PI_CLPD_SECOND_WNI_DT
            , PI_CLPD_DECISION_ISSUED_DT
            , PI_CLPD_DECIDING_OFFCL
            , PI_CLPD_EMP_GRIEVANCE
            , PI_CLPD_EMP_APPEAL_DECISION            
            )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_ACTION_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_NEXT_WGI_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PERF_COUNSEL_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CNSL_GRV_DECISION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_PRPS_ACTN_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_ORAL_PRSNT_REQ')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_ORAL_PRSNT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_WRTN_RESP_SBMT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_WRTN_RESP_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_WRTN_RESP_SBMT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_CUR_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_CUR_PAY_PLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_CUR_JOB_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_CUR_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_CUR_STEP')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_PRPS_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_PRPS_PAY_PLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_PRPS_JOB_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_PRPS_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_PRP_STEP')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_PAY_PLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_JOB_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_STEP')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_AGCY_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_FIN_DECIDING_OFC_NM', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_FIN_DECISION_ISSUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_DMTN_DECISION_EFF_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_DMTN_APPEAL_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_RSNBL_ACMDTN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_EMPL_SBMT_MEDDOC')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_DOC_SBMT_FOH_RVW')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_WGI_WTHLD')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_WGI_RVW_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_MEDDOC_RVW_OUTCOME')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_START_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_END_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_EXT_END_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_EXT_END_REASON')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_EXT_END_NOTIFY_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_EXT_DT_LIST')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_ACTUAL_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_END_PRIOR_TO_PLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_END_PRIOR_TO_PLAN_RSN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_SUCCESS_CMPLT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_PMAP_RTNG_SIGN_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_PMAP_RVW_SIGN_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_PRPS_ACTN')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_PRPS_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_ORAL_PRSNT_REQ')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_ORAL_PRSNT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_WRTN_RESP_SBMT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_WRTN_RESP_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_WRTN_SBMT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_FIN_AGCY_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_DECIDING_OFFICAL_NM', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_FIN_AGCY_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_DECISION_ISSUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_PIP_EFF_ACTN_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_EMPL_GRIEVANCE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_PIP_APPEAL_DECISION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_REASGN_NOTICE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_REASGN_EFF_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_REASGN_CUR_ADMIN_CD')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_REASGN_CUR_ORG_NM')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_REASGN_FIN_ADMIN_CD')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_REASGN_FIN_ORG_NM')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_PRPS_ACTN_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_RMV_EMPL_NOTC_LEV')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_NOTC_LEV_START_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_NOTC_LEV_END_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_RMV_ORAL_PRSNT_REQ')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_ORAL_PRSNT_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_WRTN_RESP_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_WRTN_RESP_SBMT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_RMV_FIN_AGCY_DECISION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_FIN_DECIDING_OFC_NM', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_DECISION_ISSUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_RMV_EFF_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_RMV_NUM_DAYS')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_RMV_APPEAL_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_WRTN_NRTV_RVW_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_WNR_SPCLST_RVW_CMPLT_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_WNR_MGR_RVW_RTNG_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_WNR_CRITICAL_ELM')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_WNR_FIN_RATING')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_WNR_RVW_OFC_CONCUR_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_WNR_WGI_WTHLD')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_WNR_WGI_RVW_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_ENTRANCE_DUTY_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_NEXT_CLP_DUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CLPD_PRE_WITHHELD')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_FIRST_WNI_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_NEXT_REVIEW_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_DAPI_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_FIRST_WITHHELD_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_PLANNED_REVIEW_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CLPD_DETER_FAV')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_SECOND_WNI_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PI_CLPD_DECISION_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CLPD_DECIDING_OFFCL', 'value/name')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CLPD_EMP_GRIEVANCE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PI_CLPD_EMP_APPEAL_DECISION')            
            );
    END IF;
    
	--------------------------------
	-- ERLR_GRIEVANCE table
	--------------------------------
	DELETE ERLR_GRIEVANCE WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 745 THEN
        INSERT INTO ERLR_GRIEVANCE(
            ERLR_CASE_NUMBER
            , GI_TYPE                
            , GI_NEGOTIATED_GRIEVANCE_TYPE                
            , GI_TIMELY_FILING_2
            , GI_IND_MANAGER
            , GI_FILING_DT_2
            , GI_TIMELY_FILING
            , GI_FILING_DT
            , GI_IND_MEETING_DT
            , GI_IND_STEP_1_DECISION_DT
            , GI_IND_DECISION_ISSUE_DT
            , GI_IND_STEP_1_DEADLINE
            , GI_IND_STEP_1_EXT_DUE_DT
            , GI_IND_STEP_1_EXT_DUE_REASON
            , GI_STEP_2_REQUEST
            , GI_IND_STEP_2_MTG_DT
            , GI_IND_STEP_2_DECISION_DUE_DT
            , GI_IND_STEP_2_DCSN_ISSUE_DT    
            , GI_IND_STEP_2_DEADLINE
            , GI_IND_EXT_2_EXT_DUE_DT
            , GI_IND_STEP_2_EXT_DUE_REASON
            , GI_IND_THIRD_PARTY_APPEAL_DT
            , GI_IND_THIRD_APPEAL_REQUEST
            , GI_UM_GRIEVABILITY
            , GI_MEETING_DT
            , GI_GRIEVANCE_STATUS
            , GI_ARBITRATION_DEADLINE_DT
            , GI_ARBITRATION_REQUEST
            , GI_ADMIN_OFFCL_1
            , GI_ADMIN_STG_1_DECISION_DT
            , GI_ADMIN_STG_1_ISSUE_DT    
            , GI_ADMIN_STG_2_RESP
            , GI_ADMIN_OFFCL_2
            , GI_ADMIN_STG_2_DECISION_DT
            , GI_ADMIN_STG_2_ISSUE_DT
            ) VALUES (
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_TYPE')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_NEGOTIATED_GRIEVANCE_TYPE')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_TIMELY_FILING_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_MANAGER', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_FILING_DT_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_TIMELY_FILING')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_FILING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_MEETING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_STEP_1_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_DECISION_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_STEP_1_DEADLINE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_STEP_1_EXT_DUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_STEP_1_EXT_DUE_REASON')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_STEP_2_REQUEST')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_STEP_2_MTG_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_STEP_2_DECISION_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_STEP_2_DECISION_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_STEP_2_DEADLINE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_EXT_2_EXT_DUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_STEP_2_EXT_DUE_REASON')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_IND_THIRD_PARTY_APPEAL_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_IND_THIRD_APPEAL_REQUEST')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_UM_GRIEVABILITY')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_MEETING_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_GRIEVANCE_STATUS')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_ARBITRATION_DEADLINE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_ARBITRATION_REQUEST')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_ADMIN_OFFCL_1', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_ADMIN_STG_1_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_ADMIN_STG_1_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_ADMIN_STG_2_RESP')
            , FN_EXTRACT_STR (V_XMLDOC, 'GI_ADMIN_OFFCL_2', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_ADMIN_STG_2_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'GI_ADMIN_STG_2_ISSUE_DT')
            );
    END IF;
    
	--------------------------------
	-- ERLR_INVESTIGATION table
	--------------------------------
	DELETE ERLR_INVESTIGATION WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 744 THEN
        INSERT INTO ERLR_INVESTIGATION(
            ERLR_CASE_NUMBER
            , INVESTIGATION_TYPE
            , I_MISCONDUCT_FOUND 
            ) VALUES (
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'INVESTIGATION_TYPE')
            , FN_EXTRACT_STR (V_XMLDOC, 'I_MISCONDUCT_FOUND')
            );
    END IF;
    
	--------------------------------
	-- ERLR_WGI_DNL table
	--------------------------------
	DELETE ERLR_WGI_DNL WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 809 THEN
        INSERT INTO ERLR_WGI_DNL(
            ERLR_CASE_NUMBER
            , WGI_DTR_DENIAL_ISSUED_DT
            , WGI_DTR_EMP_REQ_RECON
            , WGI_DTR_RECON_REQ_DT
            , WGI_DTR_RECON_ISSUE_DT
            , WGI_DTR_DENIED
            , WGI_DTR_DENIAL_ISSUE_TO_EMP_DT
            , WGI_RVW_REDTR_NOTI_ISSUED_DT
            , WGI_REVIEW_DTR_FAVORABLE
            , WGI_REVIEW_EMP_REQ_RECON
            , WGI_REVIEW_RECON_REQ_DT
            , WGI_REVIEW_RECON_ISSUE_DT
            , WGI_REVIEW_DENIED
            , WGI_EMP_APPEAL_DECISION
            )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_DTR_DENIAL_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_DTR_EMP_REQ_RECON')
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_DTR_RECON_REQ_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_DTR_RECON_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_DTR_DENIED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_DTR_DENIAL_ISSUE_TO_EMP_DT'                            )
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_REVIEW_DTR_NOTICE_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_REVIEW_DTR_FAVORABLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_REVIEW_EMP_REQ_RECON')
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_REVIEW_RECON_REQ_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'WGI_REVIEW_RECON_ISSUE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_REVIEW_DENIED')
            , FN_EXTRACT_STR (V_XMLDOC, 'WGI_EMP_APPEAL_DECISION')
            );
    END IF;
    
	--------------------------------
	-- ERLR_MEDDOC table
	--------------------------------
	DELETE ERLR_MEDDOC WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 746 THEN
        INSERT INTO ERLR_MEDDOC(
            ERLR_CASE_NUMBER
            , MD_REQUEST_REASON
            , MD_MED_DOC_SBMT_DEADLINE_DT
            , MD_FMLA_DOC_SBMT_DT
            , MD_FMLA_BEGIN_DT
            , MD_FMLA_APROVED
            , MD_FMLA_DISAPRV_REASON
            , MD_FMLA_GRIEVANCE
            , MD_MEDEXAM_EXTENDED
            , MD_MEDEXAM_ACCEPTED
            , MD_MEDEXAM_RECEIVED_DT
            , MD_DOC_SUBMITTED
            , MD_DOC_SBMT_DT
            , MD_DOC_SBMT_FOH
            , MD_DOC_REVIEW_OUTCOME
            , MD_DOC_ADMTV_ACCEPTABLE
            , MD_DOC_ADMTV_REJECT_REASON
        )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_REQUEST_REASON')
            , FN_EXTRACT_DATE(V_XMLDOC, 'MD_MED_DOC_SBMT_DEADLINE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'MD_FMLA_DOC_SBMT_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'MD_FMLA_BEGIN_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_FMLA_APROVED')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_FMLA_DISAPRV_REASON')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_FMLA_GRIEVANCE')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_MEDEXAM_EXTENDED')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_MEDEXAM_ACCEPTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'MD_MEDEXAM_RECEIVED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_DOC_SUBMITTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'MD_DOC_SBMT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_DOC_SBMT_FOH')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_DOC_REVIEW_OUTCOME')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_DOC_ADMTV_ACCEPTABLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'MD_DOC_ADMTV_REJECT_REASON')
        );
    END IF;
    
	--------------------------------
	-- ERLR_INFO_REQUEST table
	--------------------------------
	DELETE ERLR_INFO_REQUEST WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 747 THEN
        INSERT INTO ERLR_INFO_REQUEST(
            ERLR_CASE_NUMBER
            , IR_REQUESTER    
            , IR_CMS_REQUESTER_NAME    
            , IR_CMS_REQUESTER_PHONE    
            , IR_NCMS_REQUESTER_LAST_NAME    
            , IR_NCMS_REQUESTER_FIRST_NAME
            , IR_NCMS_REQUESTER_MN    
            , IR_NON_CMS_REQUESTER_PHONE    
            , IR_NON_CMS_REQUESTER_EMAIL    
            , IR_NCMS_REQUESTER_ORG_AFFIL    
            , IR_SUBMIT_DT
            , IR_MEET_PTCLRIZED_NEED_STND
            , IR_RSNABLY_AVAIL_N_NECESSARY
            , IR_PRTCT_DISCLOSURE_BY_LAW
            , IR_MAINTAINED_BY_AGENCY
            , IR_COLLECTIVE_BARGAINING_UNIT
            , IR_APPROVE
            , IR_PROVIDE_DT
            , IR_DENIAL_NOTICE_DT_LIST
            , IR_APPEAL_DENIAL
        )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_REQUESTER')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_CMS_REQUESTER_NAME', 'value/value')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_CMS_REQUESTER_PHONE')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_LAST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_FIRST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_MIDDLE_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_PHONE')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_EMAIL')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_NON_CMS_REQUESTER_ORGANIZATION_AFFILIATION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'IR_SUBMIT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_MEET_PARTICULARIZED_NEED_STANDARD')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_REASONABLY_AVAILABLE_AND_NECESSARY')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_PROTECTED_FROM_DISCLOSURE_BY_LAW')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_MAINTAINED_BY_AGENCY')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_COLLECTIVE_BARGAINING_UNIT')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_APPROVE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'IR_PROVIDE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_PROVIDE_DT_LIST')
            , FN_EXTRACT_STR (V_XMLDOC, 'IR_APPEAL_DENIAL')
        );
    END IF;
    
	--------------------------------
	-- ERLR_3RDPARTY_HEAR table
	--------------------------------
	DELETE ERLR_3RDPARTY_HEAR WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 753 THEN
        INSERT INTO ERLR_3RDPARTY_HEAR(
              ERLR_CASE_NUMBER
            , THRD_PRTY_APPEAL_TYPE
            , THRD_PRTY_APPEAL_FILE_DT
            , THRD_PRTY_ASSISTANCE_REQ_DT
            , THRD_PRTY_HEARING_TIMING
            , THRD_PRTY_HEARING_REQUESTED
            , THRD_PRTY_STEP_DECISION_DT
            , THRD_PRTY_ARBITRATION_INVOKED
            , THRD_PRTY_ARBIT_LNM_3
            , THRD_PRTY_ARBIT_FNM_3
            , THRD_PRTY_ARBIT_MNM_3
            , THRD_PRTY_ARBIT_EMAIL_3
            , THRD_ERLR_ARBIT_PHONE_NUM_3
            , THRD_PRTY_ARBIT_ORG_AFFIL_3
            , THRD_PRTY_ARBIT_MAILING_ADDR_3
            , THRD_PRTY_PREHEARING_DT_2
            , THRD_PRTY_HEARING_DT_2
            , THRD_PRTY_POSTHEAR_BRIEF_DUE_2
            , THRD_PRTY_FNL_ARBIT_DCSN_DT_2
            , THRD_PRTY_EXCEPTION_FILED_2
            , THRD_PRTY_EXCEPTION_FILE_DT_2
            , THRD_PRTY_RSPS_TO_EXCPT_DUE_2
            , THRD_PRTY_FNL_FLRA_DCSN_DT_2
            , THRD_PRTY_ARBIT_LNM
            , THRD_PRTY_ARBIT_FNM
            , THRD_PRTY_ARBIT_MNM
            , THRD_PRTY_ARBIT_EMAIL
            , THRD_ERLR_ARBIT_PHONE_NUM
            , THRD_PRTY_ARBIT_ORG_AFFIL
            , THRD_PRTY_ARBIT_MAILING_ADDR
            , THRD_PRTY_PREHEARING_DT
            , THRD_PRTY_HEARING_DT
            , THRD_PRTY_POSTHEAR_BRIEF_DUE
            , THRD_PRTY_FNL_ARBIT_DCSN_DT
            , THRD_PRTY_EXCEPTION_FILED
            , THRD_PRTY_EXCEPTION_FILE_DT
            , THRD_PRTY_RSPS_TO_EXCPT_DUE
            , THRD_PRTY_FNL_FLRA_DCSN_DT
            , THRD_PRTY_ARBIT_LNM_4
            , THRD_PRTY_ARBIT_FNM_4
            , THRD_PRTY_ARBIT_MNM_4
            , THRD_PRTY_ARBIT_EMAIL_4
            , THRD_ERLR_ARBIT_PHONE_NUM_4
            , THRD_PRTY_ARBIT_ORG_AFFIL_4
            , THRD_PRTY_ARBIT_MAILING_ADDR_4
            , THRD_PRTY_DT_STLMNT_DSCUSN
            , THRD_PRTY_DT_PREHEAR_DSCLS
            , THRD_PRTY_DT_AGNCY_RSP_DUE
            , THRD_PRTY_PREHEARING_DT_MSPB
            , THRD_PRTY_WAS_DSCVRY_INIT
            , THRD_PRTY_DT_DISCOVERY_DUE
            , THRD_PRTY_HEARING_DT_MSPB
            , THRD_PRTY_INIT_DCSN_DT_MSPB
            , THRD_PRTY_WAS_PETI_FILED_MSPB
            , THRD_PRTY_PETITION_RV_DT
            , THRD_PRTY_FNL_BRD_DCSN_DT_MSPB
            , THRD_PRTY_DT_STLMNT_DSCUSN_2
            , THRD_PRTY_DT_PREHEAR_DSCLS_2
            , THRD_PRTY_PREHEARING_CONF
            , THRD_PRTY_HEARING_DT_FLRA
            , THRD_PRTY_DECISION_DT_FLRA
            , THRD_PRTY_TIMELY_REQ
            , THRD_PRTY_PROC_ORDER
            , THRD_PRTY_PANEL_MEMBER_LNAME
            , THRD_PRTY_PANEL_MEMBER_FNAME
            , THRD_PRTY_PANEL_MEMBER_MNAME
            , THRD_PRTY_PANEL_MEMBER_EMAIL
            , THRD_PRTY_PANEL_MEMBER_PHONE
            , THRD_PRTY_PANEL_MEMBER_ORG
            , THRD_PRTY_PANEL_MEMBER_MAILING
            , THRD_PRTY_PANEL_DESCR         
            )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_APPEAL_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_APPEAL_FILE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_ASSISTANCE_REQ_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_HEARING_TIMING')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_HEARING_REQUESTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_STEP_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_INVOKED')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_LAST_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_FIRST_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_MIDDLE_NAME_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_EMAIL_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_ERLR_ARBITRATOR_PHONE_NUMBER_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_ORGANIZATION_AFFILIATION_3')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_MAILING_ADDR_3')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_PREHEARING_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_HEARING_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_POSTHEARING_BRIEF_DUE_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_FINAL_ARBITRATOR_DECISION_DT_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_EXCEPTION_FILED_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_EXCEPTION_FILE_DT_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_RESPONSE_TO_EXCEPTIONS_DUE_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_FINAL_FLRA_DECISION_DT_2')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_LAST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_FIRST_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_MIDDLE_NAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_EMAIL')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_ERLR_ARBITRATOR_PHONE_NUMBER')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_ORGANIZATION_AFFILIATION')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_MAILING_ADDR')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_PREHEARING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_HEARING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_POSTHEARING_BRIEF_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_FINAL_ARBITRATOR_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_EXCEPTION_FILED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_EXCEPTION_FILE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_RESPONSE_TO_EXCEPTIONS_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_FINAL_FLRA_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_LAST_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_FIRST_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_MIDDLE_NAME_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATOR_EMAIL_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_ERLR_ARBITRATOR_PHONE_NUMBER_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_ORGANIZATION_AFFILIATION_4')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_ARBITRATION_MAILING_ADDR_4')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_SETTLEMENT_DISCUSSION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_PREHEARING_DISCLOSURE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_AGENCY_FILE_RESPONSE_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_PREHEARING_DT_MSPB')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_WAS_DISCOVERY_INITIATED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_DISCOVERY_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_HEARING_DT_MSPB')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_INITIAL_DECISION_DT_MSPB')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_WAS_PETITION_FILED_MSPB')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_PETITION_RV_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_FINAL_BOARD_DECISION_DT_MSPB')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_SETTLEMENT_DISCUSSION_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DT_PREHEARING_DISCLOSURE_2')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_PREHEARING_CONF')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_HEARING_DT_FLRA')
            , FN_EXTRACT_DATE(V_XMLDOC, 'THRD_PRTY_DECISION_DT_FLRA')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_TIMELY_REQ')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PROC_ORDER')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_LNAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_FNAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_MNAME')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_EMAIL')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_PHONE')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_ORG')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_MEMBER_MAILING')
            , FN_EXTRACT_STR (V_XMLDOC, 'THRD_PRTY_PANEL_DESCR')
            );
    END IF;
    
	--------------------------------
	-- ERLE_PROB_ACTION table
	--------------------------------
	DELETE ERLR_PROB_ACTION WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 751 THEN
        INSERT INTO ERLR_PROB_ACTION(
            ERLR_CASE_NUMBER
            , PPA_ACTION_TYPE
            , PPA_TERMINATION_TYPE
            , PPA_TERM_PROP_ACTION_DT
            , PPA_TERM_ORAL_PREZ_REQUESTED
            , PPA_TERM_ORAL_PREZ_DT    
            , PPA_TERM_WRITTEN_RESP
            , PPA_TERM_WRITTEN_RESP_DUE_DT    
            , PPA_TERM_WRITTEN_RESP_DT    
            , PPA_TERM_AGENCY_DECISION
            , PPA_TERM_DECIDING_OFFCL_NAME
            , PPA_TERM_DECISION_ISSUED_DT    
            , PPA_TERM_EFFECTIVE_DECISION_DT    
            , PPA_PROB_TERM_DCSN_ISSUED_DT    
            , PPA_PROBATION_CONDUCT
            , PPA_PROBATION_PERFORMANCE
            , PPA_APPEAL_GRIEVANCE_DEADLINE    
            , PPA_EMP_APPEAL_DECISION
            , PPA_PROP_ACTION_ISSUED_DT    
            , PPA_ORAL_PREZ_REQUESTED
            , PPA_ORAL_PREZ_DT    
            , PPA_ORAL_RESPONSE_SUBMITTED
            , PPA_RESPONSE_DUE_DT    
            , PPA_WRITTEN_RESPONSE_SBMT_DT    
            , PPA_POS_TITLE
            , PPA_PPLAN
            , PPA_SERIES
            , PPA_CURRENT_INFO_GRADE
            , PPA_CURRENT_INFO_STEP
            , PPA_PROPOSED_POS_TITLE
            , PPA_PROPOSED_PPLAN
            , PPA_PROPOSED_SERIES
            , PPA_PROPOSED_INFO_GRADE
            , PPA_PROPOSED_INFO_STEP
            , PPA_FINAL_POS_TITLE
            , PPA_FINAL_PPLAN
            , PPA_FINAL_SERIES
            , PPA_FINAL_INFO_GRADE
            , PPA_FINAL_INFO_STEP
            , PPA_NOTICE_ISSUED_DT    
            , PPA_DEMO_FINAL_AGENCY_DECISION
            , PPA_DECIDING_OFFCL
            , PPA_DECISION_ISSUED_DT    
            , PPA_DEMO_FINAL_AGENCY_EFF_DT    
            , PPA_NUMB_DAYS
            , PPA_EFFECTIVE_DT    
            , PPA_CURRENT_ADMIN_CODE
            , PPA_RE_ASSIGNMENT_CURR_ORG
            , PPA_FINAL_ADMIN_CODE
            , PPA_FINAL_ADMIN_CODE_FINAL_ORG
        )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_ACTION_TYPE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_TERMINATION_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_PROP_ACTION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_TERM_ORAL_PREZ_REQUESTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_ORAL_PREZ_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_TERM_WRITTEN_RESP')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_WRITTEN_RESP_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_WRITTEN_RESP_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_TERM_AGENCY_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_TERM_DECIDING_OFFCL_NAME', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_DECISION_ISSUED_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_TERM_EFFECTIVE_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_PROBATION_TERMINATION_DECISION_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROBATION_CONDUCT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROBATION_PERFORMANCE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_APPEAL_GRIEVANCE_DEADLINE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_EMP_APPEAL_DECISION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_PROP_ACTION_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_ORAL_PREZ_REQUESTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_ORAL_PREZ_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_ORAL_RESPONSE_SUBMITTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_RESPONSE_DUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_WRITTEN_RESPONSE_SUBMITTED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PPLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_CURRENT_INFO_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_CURRENT_INFO_STEP')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROPOSED_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROPOSED_PPLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROPOSED_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROPOSED_INFO_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_PROPOSED_INFO_STEP')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_POS_TITLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_PPLAN')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_SERIES')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_INFO_GRADE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_INFO_STEP')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_NOTICE_ISSUED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_DEMO_FINAL_AGENCY_DECISION')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_DECIDING_OFFCL', 'value/name')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_DECISION_ISSUED_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_DEMO_FINAL_AGENCY_EFF_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_NUMB_DAYS')
            , FN_EXTRACT_DATE(V_XMLDOC, 'PPA_EFFECTIVE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_CURRENT_ADMIN_CODE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_RE_ASSIGNMENT_CURR_ORG')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_ADMIN_CODE')
            , FN_EXTRACT_STR (V_XMLDOC, 'PPA_FINAL_ADMIN_CODE_FINAL_ORG')
        );
    END IF;
    
	--------------------------------
	-- ERLR_ULP table
	--------------------------------
	DELETE ERLR_ULP WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 754 THEN
        INSERT INTO ERLR_ULP(
            ERLR_CASE_NUMBER
            , ULP_RECEIPT_CHARGE_DT
            , ULP_CHARGE_FILED_TIMELY
            , ULP_AGENCY_RESPONSE_DT
            , ULP_FLRA_DOCUMENT_REUQESTED
            , ULP_DOC_SUBMISSION_FLRA_DT
            , ULP_DOCUMENT_DESCRIPTION
            , ULP_DISPOSITION_DT
            , ULP_DISPOSITION_TYPE
            , ULP_COMPLAINT_DT
            , ULP_AGENCY_ANSWER_DT
            , ULP_AGENCY_ANSWER_FILED_DT
            , ULP_SETTLEMENT_DISCUSSION_DT
            , ULP_PREHEARING_DISCLOSURE_DUE
            , ULP_PREHEARING_DISCLOSUE_DT
            , ULP_PREHEARING_CONFERENCE_DT
            , ULP_HEARING_DT
            , ULP_DECISION_DT
            , ULP_EXCEPTION_FILED
            , ULP_EXCEPTION_FILED_DT
        )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_RECEIPT_CHARGE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'ULP_CHARGE_FILED_TIMELY')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_AGENCY_RESPONSE_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'ULP_FLRA_DOCUMENT_REUQESTED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_DOCUMENT_SUBMISSION_FLRA_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'ULP_DOCUMENT_DESCRIPTION')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_DISPOSITION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'ULP_DISPOSITION_TYPE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_COMPLAINT_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_AGENCY_ANSWER_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_AGENCY_ANSWER_FILED_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_SETTLEMENT_DISCUSSION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_PREHEARING_DISCLOSURE_DUE')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_PREHEARING_DISCLOSUE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_PREHEARING_CONFERENCE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_HEARING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_DECISION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'ULP_EXCEPTION_FILED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'ULP_EXCEPTION_FILED_DT')
        );
    END IF;
    
	--------------------------------
	-- ERLR_LABOR_NEGO table
	--------------------------------
	DELETE ERLR_LABOR_NEGO WHERE ERLR_CASE_NUMBER = V_CASE_NUMBER;
    IF V_CASE_TYPE = 748 THEN
        INSERT INTO ERLR_LABOR_NEGO(
            ERLR_CASE_NUMBER
            , LN_NEGOTIATION_TYPE
            , LN_INITIATOR
            , LN_DEMAND2BARGAIN_DT
            , LN_BRIEFING_REQUEST
            , LN_BRIEFING_DT
            , LN_PROPOSAL_SUBMISSION_DT
            , LN_PROPOSAL_SUBMISSION
            , LN_PROPOSAL_NEGOTIABLE
            , LN_NON_NEGOTIABLE_LETTER
            , LN_FILE_ULP
            , LN_PROPOSAL_INFO_GROUND_RULES
            , LN_PRPSAL_INFO_NEG_COMMENCE_DT
            , LN_LETTER_PROVIDED
            , LN_LETTER_PROVIDED_DT
            , LN_NEGOTIABLE_PROPOSAL
            , LN_BARGAINING_BEGAN_DT
            , LN_IMPASSE_DT
            , LN_FSIP_DECISION_DT
            , LN_BARGAINING_END_DT
            , LN_AGREEMENT_DT
            , LN_SUMMARY_OF_ISSUE
            , LN_SECON_LETTER_REQUEST
            , LN_2ND_LETTER_PROVIDED
            , LN_NEGOTIABL_ISSUE_SUMMARY
            , LN_2ND_PROVIDED_DT
            , LN_MNGMNT_ARTICLE4_NTC_DT
            , LN_MNGMNT_NOTICE_RESPONSE
            , LN_MNGMNT_BRIEFING_REQUEST
            , LN_BRIEFING_REQUESTED2_DT
            , LN_MNGMNT_BARGAIN_SBMSSION_DT
            , LN_MNGMNT_PROPOSAL_SBMSSION
            )VALUES(
            V_CASE_NUMBER
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_NEGOTIATION_TYPE')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_INITIATOR')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_DEMAND2BARGAIN_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_BRIEFING_REQUEST')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_BRIEFING_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_PROPOSAL_SUBMISSION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_PROPOSAL_SUBMISSION')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_PROPOSAL_NEGOTIABLE')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_NON_NEGOTIABLE_LETTER')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_FILE_ULP')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_PROPOSAL_INFO_GROUND_RULES')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_PROPOSAL_INFO_NEG_COMMENCED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_LETTER_PROVIDED')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_LETTER_PROVIDED_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_NEGOTIABLE_PROPOSAL')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_BARGAINING_BEGAN_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_IMPASSE_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_FSIP_DECISION_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_BARGAINING_END_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_AGREEMENT_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_SUMMARY_OF_ISSUE')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_SECON_LETTER_REQUEST')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_2ND_LETTER_PROVIDED')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_NEGOTIABL_ISSUE_SUMMARY')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_2ND_PROVIDED_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_MNGMNT_ARTICLE4_NTC_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_MNGMNT_NOTICE_RESPONSE')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_MNGMNT_BRIEFING_REQUEST')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_BRIEFING_REQUESTED2_DT')
            , FN_EXTRACT_DATE(V_XMLDOC, 'LN_MNGMNT_BARGAIN_SUBMISSION_DT')
            , FN_EXTRACT_STR (V_XMLDOC, 'LN_MNGMNT_PROPOSAL_SUBMISSION')
            );
    END IF;
EXCEPTION
    WHEN OTHERS THEN
        RAISE;
END;