create or replace PROCEDURE SP_ERLR_UPDATE_FINAL_RATING(     
    I_LABEL IN VARCHAR2,
    I_UPDATED_LABEL IN VARCHAR2 DEFAULT ''
)
IS
/* THIS IS TEMPORARY PROCEDURE */

    V_DEL_LABEL VARCHAR2(100);
    V_XPATH VARCHAR2(200);
    V_XPATH_DEL VARCHAR2(200);
BEGIN
    V_XPATH := '/formData/items/item[id="PI_WNR_FIN_RATING"]/value[.="'||I_LABEL||'"]/text()';
    FOR FORM_REC IN (
        SELECT P.PROCID, P.STATE, FIELD_DATA, XMLQUERY(V_XPATH PASSING FIELD_DATA RETURNING CONTENT).getStringVal() as FINAL_RATING
        FROM TBL_FORM_DTL F JOIN BIZFLOW.PROCS P ON F.PROCID = P.PROCID WHERE FORM_TYPE = 'CMSERLR'
    ) 
    LOOP
        IF FORM_REC.FINAL_RATING IS NOT NULL THEN
            V_XPATH := '/formData/items/item[id="PI_WNR_FIN_RATING"]/value[.="'||I_LABEL||'"]/text()';
            SELECT UPDATEXML(FORM_REC.FIELD_DATA, V_XPATH, I_UPDATED_LABEL) INTO FORM_REC.FIELD_DATA FROM DUAL;
            V_XPATH := '/formData/items/item[id="PI_WNR_FIN_RATING"]//text[.="'||I_LABEL||'"]/text()';
            SELECT UPDATEXML(FORM_REC.FIELD_DATA, V_XPATH, I_UPDATED_LABEL) INTO FORM_REC.FIELD_DATA FROM DUAL;

            UPDATE TBL_FORM_DTL
               SET FIELD_DATA = FORM_REC.FIELD_DATA
             WHERE PROCID = FORM_REC.PROCID;

            SP_UPDATE_ERLR_TABLE(FORM_REC.PROCID);
        END IF;
    END LOOP;
    
    UPDATE TBL_LOOKUP
       SET TBL_NAME = I_UPDATED_LABEL,
           TBL_LABEL = I_UPDATED_LABEL
     WHERE TBL_CATEGORY = 'ERLR'
       AND TBL_LABEL = I_LABEL
       AND TBL_LTYPE='ERLRPipFinalRating';
END;