------------------------------------------------------------------
-- ALTER DDL for Panel tab
------------------------------------------------------------------
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP DROP (PANEL_MEMBER_NAME, PANEL_MEMBER_COMPONENT, PANEL_ROLE, VOTING_STATUS, PANEL_RECOMMENDED_COMPENSATION);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PANEL_CURRENT_SALARY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PANEL_PDP_AMOUNT NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PANEL_RECOMM_ANNUAL_SALARY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP ADD DATE_OF_RECOMMENDATION DATE;

------------------------------------------------------------------
-- ALTER DDL for Details tab
------------------------------------------------------------------
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXEC_RESP_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXPT_QF_Q1_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXPT_QF_Q2_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXPT_QF_Q3_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXPT_QF_Q4_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY EXPT_QF_Q5_AMT_REQUESTED NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY TOTAL_AMT_EXPT_QUALIFICATIONS NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_RECRUITMENT NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_RELOCATION NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_RETENTION NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_3R_TOTAL NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_BASE NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_LOCALITY_MARKET NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_TOTAL_ANNUAL_PAY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CURRENT_PAY_TOTAL_COMPENSATION NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_PAY_RECRUITMENT NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_PAY_RELOCATION NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_PAY_RETENTION NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_PAY_TOTAL_3R NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_GS_BASE_PAY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_MARKET_PAY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_TOTAL_ANNUAL_PAY NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY PROPOSED_TOTAL_ANNUAL_COMPENS NUMBER(20,2);
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY CLINICAL_SPECIALTY_BOARD_CERT VARCHAR2(2000); -- MULTI VALUES
ALTER TABLE HHS_CMS_HR.INCENTIVES_PDP MODIFY INCENTIVES_APPROVED_BY_TABG VARCHAR2(2000); -- MULTI VALUES


------------------------------------------------------------------
-- CREATE DDL for Panel Members
------------------------------------------------------------------
CREATE TABLE HHS_CMS_HR.INCENTIVES_PDP_PANEL 
(
    PROC_ID         NUMBER(10,0) NOT NULL, 
    SEQ_NUM         NUMBER(10,0) NOT NULL, 
    FULL_NAME       VARCHAR2(200),
    COMPONENT_NAME  VARCHAR2(200),
    EMAIL           VARCHAR2(100),
    HHSID           VARCHAR2(20),
    ADMIN_CODE      VARCHAR2(20),
    PANEL_ROLE      VARCHAR2(20),
    VOTING_STATUS   VARCHAR2(50),
    PANEL_REC_COMP  VARCHAR2(200)
);
CREATE UNIQUE INDEX HHS_CMS_HR.INCENTIVES_PDP_PANEL_PK ON HHS_CMS_HR.INCENTIVES_PDP_PANEL (PROC_ID, SEQ_NUM);
