ALTER TABLE HHS_CMS_HR.INCENTIVES_LE_JUST_HISTORY ADD JUSTIFICATION_MODIFIED_DATE_D DATE;

UPDATE HHS_CMS_HR.INCENTIVES_LE_JUST_HISTORY
SET JUSTIFICATION_MODIFIED_DATE_D 
    = DECODE(LENGTH(JUSTIFICATION_MODIFIED_DATE), 19, TO_DATE(JUSTIFICATION_MODIFIED_DATE, 'mm/dd/yyyy hh24:mi:ss'), null)
;
