create or replace PROCEDURE SP_INIT_INCENTIVES
(
    I_INCENTIVE_TYPE       IN VARCHAR2, -- SAM, LE, PCA, PDP
    I_PROCID               IN NUMBER
)
IS
    V_PARENT_PROCID        NUMBER(10);
    V_XMLDOC               XMLTYPE;
    V_CNT                  INT;
BEGIN

    BEGIN
        SELECT TO_NUMBER(VALUE)
          INTO V_PARENT_PROCID
          FROM BIZFLOW.RLVNTDATA
         WHERE PROCID = I_PROCID
           AND RLVNTDATANAME = 'parentProcId';
    EXCEPTION
    WHEN NO_DATA_FOUND THEN
        V_PARENT_PROCID := NULL;
    END;
    
    SELECT COUNT(*)
      INTO V_CNT
      FROM TBL_FORM_DTL
     WHERE PROCID = I_PROCID;
    
    IF V_PARENT_PROCID IS NOT NULL AND V_CNT = 0 THEN
        INSERT INTO TBL_FORM_DTL (PROCID, ACTSEQ, WITEMSEQ, FORM_TYPE, FIELD_DATA, CRT_DT, CRT_USR, MOD_DT, MOD_USR)
        SELECT I_PROCID, ACTSEQ, WITEMSEQ, FORM_TYPE, FIELD_DATA, CRT_DT, CRT_USR, MOD_DT, MOD_USR 
          FROM TBL_FORM_DTL
         WHERE PROCID=V_PARENT_PROCID;
    
        SELECT FIELD_DATA
          INTO V_XMLDOC
          FROM TBL_FORM_DTL
         WHERE PROCID = I_PROCID;
    
        SP_UPDATE_INCENTIVES_TABLE(I_PROCID, V_XMLDOC);
    END IF;        
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;


GRANT EXECUTE ON HHS_CMS_HR.SP_INIT_INCENTIVES TO BIZFLOW;