CREATE OR REPLACE FORCE VIEW HHS_CMS_HR.VW_INCENTIVES_PCA (
    PROC_ID
    ,PCA_TYPE
    ,CANDI_AGREE
    ,CP_NAME
    ,CP_EMAIL
    ,CP_ID
    ,OFM_NAME
    ,OFM_EMAIL
    ,OFM_ID
    ,ADMIN_APPROVAL_REQ
    ,OHC_NAME
    ,OHC_EMAIL
    ,OHC_ID
    ,OADMIN_NAME
    ,OADMIN_EMAIL
    ,OADMIN_ID
    ,WORK_SCHEDULE
    ,HOURS_PER_WEEK
    ,BD_CERT_REQ
    ,LIC_INFO
    ,LIC_STATE1_STATE
    ,LIC_STATE1_NAME
    ,LIC_STATE1_EXP_DATE --
    ,LIC_STATE2_STATE
    ,LIC_STATE2_NAME
    ,LIC_STATE2_EXP_DATE --
    ,BD_CERT_SPEC1
    ,BD_CERT_SPEC2
    ,BD_CERT_SPEC3
    ,BD_CERT_SPEC4
    ,BD_CERT_SPEC5
    ,BD_CERT_SPEC6
    ,BD_CERT_SPEC7
    ,BD_CERT_SPEC8
    ,BD_CERT_SPEC9
    ,BD_CERT_SPEC_OTHER
    ,LEN_SERVED
    ,LEN_SERVICE
    ,ALW_CATEGORY  --
    ,ALW_BD_CERT --
    ,ALW_MULTI_YEAR_AGMT --
    ,ALW_MISSION_SC --
    ,ALW_TOTAL --
    ,ALW_TOTAL_PAYABLE --
    ,DETAIL_REMARKS
    ,RVW_SO_NAME
    ,RVW_SO_ID
    ,RVW_SO_DATE --
    ,RVW_DGHO_NAME
    ,RVW_DGHO_ID
    ,RVW_DGHO_DATE --
    ,RVW_CP_NAME
    ,RVW_CP_ID
    ,RVW_CP_DATE --
    ,RVW_OFM_NAME
    ,RVW_OFM_ID
    ,RVW_OFM_DATE --
    ,RVW_TABG_NAME
    ,RVW_TABG_ID
    ,RVW_TABG_DATE --
    ,RVW_OHC_NAME
    ,RVW_OHC_ID
    ,RVW_OHC_DATE --
    ,APPROVAL_TABG_NAME
    ,APPROVAL_TABG_ID
    ,APPROVAL_TABG_DATE --
    ,APPROVAL_OADMIN_NAME
    ,APPROVAL_OADMIN_ID
    ,APPROVAL_OADMIN_DATE --
    ---- correct data type
    ,LIC_STATE1_EXP_DATE_D
    ,LIC_STATE2_EXP_DATE_D
    ,ALW_CATEGORY_N
    ,ALW_BD_CERT_N
    ,ALW_MULTI_YEAR_AGMT_N
    ,ALW_MISSION_SC_N
    ,ALW_TOTAL_N
    ,ALW_TOTAL_PAYABLE_N
    ,RVW_SO_DATE_D
    ,RVW_DGHO_DATE_D
    ,RVW_CP_DATE_D
    ,RVW_OFM_DATE_D
    ,RVW_TABG_DATE_D
    ,RVW_OHC_DATE_D
    ,APPROVAL_TABG_DATE_D
    ,APPROVAL_OADMIN_DATE_D
) AS 
SELECT 
    PROC_ID
    ,PCA_TYPE
    ,CANDI_AGREE
    ,CP_NAME
    ,CP_EMAIL
    ,CP_ID
    ,OFM_NAME
    ,OFM_EMAIL
    ,OFM_ID
    ,ADMIN_APPROVAL_REQ
    ,OHC_NAME
    ,OHC_EMAIL
    ,OHC_ID
    ,OADMIN_NAME
    ,OADMIN_EMAIL
    ,OADMIN_ID
    ,WORK_SCHEDULE
    ,HOURS_PER_WEEK
    ,BD_CERT_REQ
    ,LIC_INFO
    ,LIC_STATE1_STATE
    ,LIC_STATE1_NAME
    ,TO_CHAR(LIC_STATE1_EXP_DATE_D, 'mm/dd/yyyy') as LIC_STATE1_EXP_DATE --
    ,LIC_STATE2_STATE
    ,LIC_STATE2_NAME
    ,TO_CHAR(LIC_STATE2_EXP_DATE_D, 'mm/dd/yyyy') as LIC_STATE2_EXP_DATE --
    ,BD_CERT_SPEC1
    ,BD_CERT_SPEC2
    ,BD_CERT_SPEC3
    ,BD_CERT_SPEC4
    ,BD_CERT_SPEC5
    ,BD_CERT_SPEC6
    ,BD_CERT_SPEC7
    ,BD_CERT_SPEC8
    ,BD_CERT_SPEC9
    ,BD_CERT_SPEC_OTHER
    ,LEN_SERVED
    ,LEN_SERVICE
    ,TO_CHAR(ALW_CATEGORY_N, '$999,999,999,999,999,999.99' ) as ALW_CATEGORY  --
    ,TO_CHAR(ALW_BD_CERT_N, '$999,999,999,999,999,999.99' ) as ALW_BD_CERT --
    ,TO_CHAR(ALW_MULTI_YEAR_AGMT_N, '$999,999,999,999,999,999.99' ) as ALW_MULTI_YEAR_AGMT --
    ,TO_CHAR(ALW_MISSION_SC_N, '$999,999,999,999,999,999.99' ) as ALW_MISSION_SC --
    ,TO_CHAR(ALW_TOTAL_N, '$999,999,999,999,999,999.99' ) as ALW_TOTAL --
    ,TO_CHAR(ALW_TOTAL_PAYABLE_N, '$999,999,999,999,999,999.99' ) as ALW_TOTAL_PAYABLE --
    ,DETAIL_REMARKS
    ,RVW_SO_NAME
    ,RVW_SO_ID
    ,TO_CHAR(RVW_SO_DATE_D, 'mm/dd/yyyy') as RVW_SO_DATE --
    ,RVW_DGHO_NAME
    ,RVW_DGHO_ID
    ,TO_CHAR(RVW_DGHO_DATE_D, 'mm/dd/yyyy') as RVW_DGHO_DATE --
    ,RVW_CP_NAME
    ,RVW_CP_ID
    ,TO_CHAR(RVW_CP_DATE_D, 'mm/dd/yyyy') as RVW_CP_DATE --
    ,RVW_OFM_NAME
    ,RVW_OFM_ID
    ,TO_CHAR(RVW_OFM_DATE_D, 'mm/dd/yyyy') as RVW_OFM_DATE --
    ,RVW_TABG_NAME
    ,RVW_TABG_ID
    ,TO_CHAR(RVW_TABG_DATE_D, 'mm/dd/yyyy') as RVW_TABG_DATE --
    ,RVW_OHC_NAME
    ,RVW_OHC_ID
    ,TO_CHAR(RVW_OHC_DATE_D, 'mm/dd/yyyy') as RVW_OHC_DATE --
    ,APPROVAL_TABG_NAME
    ,APPROVAL_TABG_ID
    ,TO_CHAR(APPROVAL_TABG_DATE_D, 'mm/dd/yyyy') as APPROVAL_TABG_DATE --
    ,APPROVAL_OADMIN_NAME
    ,APPROVAL_OADMIN_ID
    ,TO_CHAR(APPROVAL_OADMIN_DATE_D, 'mm/dd/yyyy') as APPROVAL_OADMIN_DATE --
    ---- correct data type
    ,LIC_STATE1_EXP_DATE_D
    ,LIC_STATE2_EXP_DATE_D
    ,ALW_CATEGORY_N
    ,ALW_BD_CERT_N
    ,ALW_MULTI_YEAR_AGMT_N
    ,ALW_MISSION_SC_N
    ,ALW_TOTAL_N
    ,ALW_TOTAL_PAYABLE_N
    ,RVW_SO_DATE_D
    ,RVW_DGHO_DATE_D
    ,RVW_CP_DATE_D
    ,RVW_OFM_DATE_D
    ,RVW_TABG_DATE_D
    ,RVW_OHC_DATE_D
    ,APPROVAL_TABG_DATE_D
    ,APPROVAL_OADMIN_DATE_D
FROM HHS_CMS_HR.INCENTIVES_PCA;




