CREATE OR REPLACE VIEW VW_RPT_ERLR_TRENDS
AS
SELECT
      P.COMPONENT,
      G.ERLR_CASE_NUMBER CASENUMBER,
      G.GEN_EMPLOYEE_NAME EMPNAME,
      G.GEN_CUSTOMER_NAME CONTACTNAME,
      G.GEN_EMPLOYEE_2ND_SUB_ORG SECONDSUBORGDESC,
      G.GEN_EMPLOYEE_ADMIN_CD ADMINCD,
      G.GEN_CASE_TYPE CASETYPE,
      G.GEN_CASE_CATEGORY CASECATEGORY,
      CASE 
        WHEN TRIM( G.CC_FINAL_ACTION_OTHER ) IS NOT NULL THEN G.CC_FINAL_ACTION || ' - ' || G.CC_FINAL_ACTION_OTHER
        ELSE G.CC_FINAL_ACTION
      END FINAL_ACTION,
      G.GEN_CUST_INIT_CONTACT_DT INITIALCONTACTDATE,
      G.CC_CASE_COMPLETE_DT DATE_CASE_COMPLETED,
      G.GEN_CLASS AS TYPE      
  FROM (SELECT COMPONENT FROM HHS_CMS_HR.CMS_TIME_TO_HIRE_WEEKLY_PILOT GROUP BY COMPONENT) P LEFT OUTER JOIN HHS_CMS_HR.ERLR_GEN G 
       ON NVL(G.GEN_CASE_STATUS,'') <> 'Closed' AND P.COMPONENT = G.GEN_EMPLOYEE_2ND_SUB_ORG;       
       
GRANT SELECT ON HHS_CMS_HR.VW_RPT_ERLR_TRENDS TO HHS_CMS_HR_RW_ROLE;       
GRANT SELECT ON HHS_CMS_HR.VW_RPT_ERLR_TRENDS TO HHS_CMS_HR_DEV_ROLE;