
ALTER TABLE HHS_CMS_HR.INCENTIVES_COM ADD CANDI_NAME2 VARCHAR2(150);
ALTER TABLE HHS_CMS_HR.INCENTIVES_COM ADD NOT_TO_EXCEED_DT VARCHAR2(100);
/

CREATE INDEX INCENTIVES_COM_IX3 ON HHS_CMS_HR.INCENTIVES_COM (CANDI_NAME2);
/

UPDATE HHS_CMS_HR.INCENTIVES_COM
SET CANDI_NAME2 = NVL(CANDI_LAST, '') || ', ' || NVL(CANDI_FIRST, '')
;

