/*
-- CMS_40
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1810, 750, 'ERLRCasesCompletedFinalAction', 'Oral Counseling Issued', 'Oral Counseling Issued', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1811, 750, 'ERLRCasesCompletedFinalAction', 'Written Counseling Issued', 'Written Counseling Issued', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1812, 750, 'ERLRCasesCompletedFinalAction', 'Other', 'Other', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1813, 744, 'ERLRCasesCompletedFinalAction', 'Termination of Probationary Employee', 'Termination of Probationary Employee', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1814, 747, 'ERLRCasesCompletedFinalAction', 'Request Withdrawn by Union', 'Request Withdrawn by Union', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1815, 754, 'ERLRCasesCompletedFinalAction', 'Unfair Labor Practice', 'Unfair Labor Practice', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1816, 746, 'ERLRCasesCompletedFinalAction', 'Agency Offer of Medical Exam', 'Agency Offer of Medical Exam', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1817, 745, 'ERLRCasesCompletedFinalAction', 'All Relief Granted', 'All Relief Granted', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1818, 745, 'ERLRCasesCompletedFinalAction', 'Withdrawn by Management', 'Withdrawn by Management', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1819, 745, 'ERLRCasesCompletedFinalAction', 'Withdrawn by Union', 'Withdrawn by Union', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

SP_ERLR_MNG_FINAL_ACTION('DELETE', '743', 'Leave Denied');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '744', 'Leave Denied');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '746', 'Settlement Agreement');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Resolved');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '750', 'Employee Placed on PIP');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '748', 'Full Agreement Reached', 'Agreement Reached (MOA/MOU)');

-- CMS_74
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1830, 1771, 'ERLRCasesCompletedFinalAction', 'Grievance Withdrawn by Employee', 'Grievance Withdrawn by Employee', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1831, 1772, 'ERLRCasesCompletedFinalAction', 'Case Withdrawn by Employee', 'Case Withdrawn by Employee', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1832, 1772, 'ERLRCasesCompletedFinalAction', 'FLRA Case Remanded to Parties for New Hearing', 'FLRA Case Remanded to Parties for New Hearing', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1833, 1773, 'ERLRCasesCompletedFinalAction', 'Case Withdrawn by Employee', 'Case Withdrawn by Employee', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1834, 1773, 'ERLRCasesCompletedFinalAction', 'FSIP Imposed Agency Final Offer', 'FSIP Imposed Agency Final Offer', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1835, 1774, 'ERLRCasesCompletedFinalAction', 'Grievance Withdrawn by Employee', 'Grievance Withdrawn by Employee', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

update tbl_lookup set tbl_disp_order = 999 WHERE tbl_ltype='ERLRCasesCompletedFinalAction' and tbl_label = 'Other';

SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1775', 'Appeal Dismissed', 'MSPB Appeal Dismissed');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1775', 'Appeal Granted', 'MSPB Appeal Granted');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1775', 'Appeal Granted in Part, Dismissed in Part', 'MSPB Appeal Granted in Part, Dismissed in Part');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1775', 'Appeal Withdrawn', 'MSPB Appeal Withdrawn by Employee');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1772', 'Posting Ordered', 'FLRA Posting Ordered');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1773', 'FSIP Developed Decision', 'FSIP Imposed Decision');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1773', 'Union''s Last Final Offer', 'FSIP Imposed Union''s Last Final Offer');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1773', 'Med- Arb Split Decision', 'Mediation/Arbitration Split Decision');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1773', 'Med- Arb Agency Win', 'Mediation/Arbitration Agency Prevailed');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '1773', 'Med- Arb Union Win', 'Mediation/Arbitration Union Prevailed');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '750', 'WIGI Delayed', 'WGI Delayed');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '750', 'WIGI Withheld', 'WGI Withheld');
SP_ERLR_MNG_FINAL_ACTION('UPDATE', '750', 'WIGI Denied', 'WGI Denied');

--CMS_126

UPDATE TBL_LOOKUP SET TBL_ACTIVE = 0 WHERE TBL_ID IN (1840,1687,1723,1722,1720,1719,1718,1684);

SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Grievance Withdrawn by Management');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Grievance Withdrawn by Union');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Grievance Granted in Part, Denied in Part');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Grievance Granted');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Grievance Denied');
SP_ERLR_MNG_FINAL_ACTION('DELETE', '745', 'Resolved');

--CMS_100
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1836, 743, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1837, 750, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1838, 751, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

--CMS_105
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1840, 745, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1841, 746, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1843, 748, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1844, 753, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) 
VALUES (1846, 809, 'ERLRCasesCompletedFinalAction', 'Settlement Agreement', 'Settlement Agreement', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

--CMS_108
Insert into HHS_CMS_HR.TBL_LOOKUP(TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1847,1773,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));
Insert into HHS_CMS_HR.TBL_LOOKUP(TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) 
values (1848,744,'ERLRCasesCompletedFinalAction','Settlement Agreement','Settlement Agreement','1',null,'N',null,'ERLR',TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

--CMS_110
UPDATE HHS_CMS_HR.TBL_LOOKUP SET TBL_NAME = 'FLRA Ordered Union Posting', TBL_LABEL='FLRA Ordered Union Posting' WHERE TBL_ID = 1728;
UPDATE HHS_CMS_HR.TBL_LOOKUP SET TBL_ACTIVE = '0' WHERE TBL_ID = 1815;
*/

BEGIN
-- missed
    --SP_ERLR_MNG_FINAL_ACTION('UPDATE', '744', 'Termination', 'Termination of Probationary Employee');
    SP_ERLR_MNG_FINAL_ACTION('DELETE', '744', 'Termination');
    SP_ERLR_MNG_FINAL_ACTION('UPDATE', '754', 'Posting', 'FLRA Ordered Union Posting');

END;

COMMIT;