
ALTER TABLE INCENTIVES_PDP DROP COLUMN CURRENT_PAY_TIER;
ALTER TABLE INCENTIVES_PDP DROP COLUMN PROPOSED_PAY_TIER;
ALTER TABLE INCENTIVES_PDP ADD CURRENT_PAY_TIER VARCHAR2(20);
ALTER TABLE INCENTIVES_PDP ADD PROPOSED_PAY_TIER VARCHAR2(20);


