
--
-- Update Series
--

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0601 - General Medical and Healthcare Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 139;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0602 - Physician Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 140;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0610 - Nursing Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 141;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0630 - Dietetics and Nutrition Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 142;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0644 - Clinical Laboratory Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 143;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0660 - Pharmacy Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 144;

UPDATE HHS_CMS_HR.TBL_LOOKUP set TBL_LABEL = '0680 - Dentistry Series'
 WHERE TBL_LTYPE = 'OccupationalSeries'
   AND TBL_ID = 145;

--
-- Add Series
--
-- select max(TBL_ID) from HHS_CMS_HR.TBL_LOOKUP -- 1798

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1799, 0, 'OccupationalSeries', '0603', '0603 - Physician Assistant Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1800, 0, 'OccupationalSeries', '0631', '0631 - Occupational Therapy Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1801, 0, 'OccupationalSeries', '0633', '0633 - Physical Therapy Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1802, 0, 'OccupationalSeries', '0635', '0635 - Kinesiotherapy Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1803, 0, 'OccupationalSeries', '0638', '0638 - Recreation/Creative Arts Therapy Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1804, 0, 'OccupationalSeries', '0662', '0662 - Optometry Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1805, 0, 'OccupationalSeries', '0665', '0665 - Speech/Language Pathology and Audiology Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1806, 0, 'OccupationalSeries', '0668', '0668 - Podiatry Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1807, 0, 'OccupationalSeries', '0690', '0690 - Industrial Hygiene Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1808, 0, 'OccupationalSeries', '0696', '0696 - Consumer Safety Series', '1', null, 'N', null, 'CMS', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

/
