create or replace FUNCTION HHS_FN_ADD_BUSDAY 
(
  I_ACTSTART IN DATE 
, I_SLADAYS IN INT 
) 
RETURN DATE
IS
  V_DAY DATE;

  BEGIN
    SELECT CALDTIME INTO V_DAY
    
        FROM (SELECT 
                C.CALDTIME AS CALDTIME, ROW_NUMBER() OVER (ORDER BY C.CALDTIME ASC) AS SEQNUM
              FROM BIZFLOW.CAL C
                INNER JOIN BIZFLOW.CALHEAD CH
               ON CH.DAYOFWEEK = C.DAYOFWEEK
               WHERE CH.DAYTYPE <> 'H'
                AND C.CALDTIME NOT IN (SELECT CALDTIME FROM BIZFLOW.MEMBERCAL WHERE DAYTYPE = 'H' AND MEMBERID = '0000000000')
                AND CH.MEMBERID = '0000000000'
                AND C.CALDTIME > I_ACTSTART
             ) TBL_NEW
             
    WHERE SEQNUM = I_SLADAYS;
    
    IF I_ACTSTART IS NULL THEN
      RETURN I_ACTSTART;
    ELSE
      RETURN V_DAY;
    END IF;

  END;
  
GRANT EXECUTE ON BIZFLOW.HHS_FN_ADD_BUSDAY TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON BIZFLOW.HHS_FN_ADD_BUSDAY TO HHS_CMS_HR_DEV_ROLE;  