--------------------------------------------------------
--  DDL for View VW_UNIFIED_REQUESTS
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HHS_CMS_HR"."VW_UNIFIED_REQUESTS" ("REQ_ID", "REQUEST_NUMBER", "REQUEST_DATE", "REQ_CANCEL_DATE", "REQ_CANCEL_REASON", "PROC_ID", "PROC_STATE", "PROC_TYPE", "REQUEST_TYPE_ID", "REQUEST_TYPE", "ADMIN_CODE", "ADMIN_CODE_DESC", "SO_ID", "SO_NAME", "SO_TITLE", "SO_ORG", "XO_ID", "XO_NAME", "XO_TITLE", "XO_ORG", "HRL_ID", "HRL_NAME", "HRL_TITLE", "HRL_ORG", "POS_TITLE", "PAY_PLAN_ID", "PAY_PLAN_DESC", "POS_SERIES_ID", "POS_SERIES_DESC", "POS_GRADE1", "POS_GRADE2", "POS_GRADE3", "POS_GRADE4", "POS_GRADE5", "POS_DESC_NUM1", "POS_DESC_NUM2", "POS_DESC_NUM3", "POS_DESC_NUM4", "POS_DESC_NUM5", "CANDI_FIRST_NAME", "CANDI_MIDDLE_NAME", "CANDI_LAST_NAME", "LICENSE", "LICENSE_INFO", "POS_WORK_SCHED_ID", "POS_WORK_SCHED_DSCR", "POS_HOURS_PER_WEEK", "POS_NTE", "TYPE_OF_APPT", "XO_ID1", "XO_ID2", "XO_ID3", "XO_NAME1", "XO_NAME2", "XO_NAME3", "XO_TITLE1", "XO_TITLE2", "XO_TITLE3", "XO_ORG1", "XO_ORG2", "XO_ORG3") AS 
  SELECT REQ."REQ_ID",REQ."REQUEST_NUMBER",REQ."REQUEST_DATE",REQ."REQ_CANCEL_DATE",REQ."REQ_CANCEL_REASON",REQ."PROC_ID",REQ."PROC_STATE",REQ."PROC_TYPE",REQ."REQUEST_TYPE_ID",REQ."REQUEST_TYPE",REQ."ADMIN_CODE",REQ."ADMIN_CODE_DESC",REQ."SO_ID",REQ."SO_NAME",REQ."SO_TITLE",REQ."SO_ORG",REQ."XO_ID",REQ."XO_NAME",REQ."XO_TITLE",REQ."XO_ORG",REQ."HRL_ID",REQ."HRL_NAME",REQ."HRL_TITLE",REQ."HRL_ORG",REQ."POS_TITLE",REQ."PAY_PLAN_ID",REQ."PAY_PLAN_DESC",REQ."POS_SERIES_ID",REQ."POS_SERIES_DESC",REQ."POS_GRADE1",REQ."POS_GRADE2",REQ."POS_GRADE3",REQ."POS_GRADE4",REQ."POS_GRADE5",REQ."POS_DESC_NUM1",REQ."POS_DESC_NUM2",REQ."POS_DESC_NUM3",REQ."POS_DESC_NUM4",REQ."POS_DESC_NUM5",REQ."CANDI_FIRST_NAME",REQ."CANDI_MIDDLE_NAME",REQ."CANDI_LAST_NAME",REQ."LICENSE",REQ."LICENSE_INFO",REQ."POS_WORK_SCHED_ID",REQ."POS_WORK_SCHED_DSCR",REQ."POS_HOURS_PER_WEEK",REQ."POS_NTE",REQ."TYPE_OF_APPT"
    ,REGEXP_SUBSTR(XO_ID, '[^,]+', 1, 1) AS XO_ID1
    ,REGEXP_SUBSTR(XO_ID, '[^,]+', 1, 2) AS XO_ID2
    ,REGEXP_SUBSTR(XO_ID, '[^,]+', 1, 3) AS XO_ID3
    ,REGEXP_SUBSTR(XO_NAME, '[^;]+', 1, 1) AS XO_NAME1
    ,REGEXP_SUBSTR(XO_NAME, '[^;]+', 1, 2) AS XO_NAME2
    ,REGEXP_SUBSTR(XO_NAME, '[^;]+', 1, 3) AS XO_NAME3
    ,REGEXP_SUBSTR(XO_TITLE, '[^_/~]+', 1, 1) AS XO_TITLE1
    ,REGEXP_SUBSTR(XO_TITLE, '[^_/~]+', 1, 2) AS XO_TITLE2
    ,REGEXP_SUBSTR(XO_TITLE, '[^_/~]+', 1, 3) AS XO_TITLE3
    ,REGEXP_SUBSTR(XO_ORG, '[^_/~]+', 1, 1) AS XO_ORG1
    ,REGEXP_SUBSTR(XO_ORG, '[^_/~]+', 1, 2) AS XO_ORG2
    ,REGEXP_SUBSTR(XO_ORG, '[^_/~]+', 1, 3) AS XO_ORG3
  FROM (
         SELECT RR.REQ_ID, RR.REQ_JOB_REQ_NUMBER REQUEST_NUMBER, RR.REQ_JOB_REQ_CREATE_DT REQUEST_DATE
           , RR.REQ_CANCEL_DT REQ_CANCEL_DATE, RR.REQ_CANCEL_REASON, RR.PROC_ID, RR.PROC_STATE, RR.PROC_TYPE
           , VST.SG_RT_ID REQUEST_TYPE_ID, VST.SG_RT_DSCR REQUEST_TYPE
           , VST.SG_ADMIN_CD ADMIN_CODE, VST.SG_ADMIN_CD_DSCR ADMIN_CODE_DESC
           , VST.SG_SO_ID SO_ID, VST.SG_SO_NAME SO_NAME, VST.SG_SO_TITLE SO_TITLE, VST.SG_SO_ORG SO_ORG
           , VST.SG_XO_ID XO_ID, VST.SG_XO_NAME XO_NAME, VST.SG_XO_TITLE XO_TITLE, VST.SG_XO_ORG XO_ORG
           , VST.SG_HRL_ID HRL_ID, VST.SG_HL_NAME HRL_NAME, VST.SG_HRL_TITLE HRL_TITLE, VST.SG_HRL_ORG HRL_ORG
           , VST.POS_TITLE POS_TITLE, VST.POS_PAY_PLAN_ID PAY_PLAN_ID, VST.POS_PAY_PLAN_DSCR PAY_PLAN_DESC
           , VST.POS_SR_ID POS_SERIES_ID
	   ,(SELECT LU_SR.TBL_LABEL FROM TBL_LOOKUP LU_SR WHERE LU_SR.TBL_NAME = VST.POS_SERIES AND ROWNUM = 1) AS POS_SERIES_DESC
           , VST.POS_GRADE_1 POS_GRADE1, VST.POS_GRADE_2 POS_GRADE2, VST.POS_GRADE_3 POS_GRADE3, VST.POS_GRADE_4 POS_GRADE4, VST.POS_GRADE_5 POS_GRADE5
           , VST.POS_DESC_NUMBER_1 POS_DESC_NUM1, VST.POS_DESC_NUMBER_2 POS_DESC_NUM2, VST.POS_DESC_NUMBER_3 POS_DESC_NUM3, VST.POS_DESC_NUMBER_4 POS_DESC_NUM4, VST.POS_DESC_NUMBER_5 POS_DESC_NUM5
           , VST.POS_CNDT_FIRST_NM CANDI_FIRST_NAME, VST.POS_CNDT_MIDDLE_NM CANDI_MIDDLE_NAME, VST.POS_CNDT_LAST_NM CANDI_LAST_NAME
           , VST.POS_CE_LIC LICENSE, VST.POS_CE_LIC_INFO LICENSE_INFO
           , VST.POS_WORK_SCHED_ID, VST.POS_WORK_SCHED_DSCR, VST.POS_HOURS_PER_WEEK, VST.POS_NTE
           , VST.POS_AT_DSCR TYPE_OF_APPT
         FROM VW_UNIFIED_REQUESTS_RANK RR
           INNER JOIN VW_STRATCON VST ON VST.REQ_ID = RR.REQ_ID AND RR.PROC_TYPE='STRATCON' AND RR.REQ_RANK=1

         UNION ALL

         SELECT RR.REQ_ID, RR.REQ_JOB_REQ_NUMBER REQUEST_NUMBER, RR.REQ_JOB_REQ_CREATE_DT REQUEST_DATE
           , RR.REQ_CANCEL_DT REQ_CANCEL_DATE, RR.REQ_CANCEL_REASON, RR.PROC_ID, RR.PROC_STATE, RR.PROC_TYPE
           , VST.SG_RT_ID REQUEST_TYPE_ID, VST.SG_RT_DSCR REQUEST_TYPE
           , VCL.CS_ADMIN_CD ADMIN_CODE, VCL.CS_ADMIN_CD_DSCR ADMIN_CODE_DESC
           , VST.SG_SO_ID SO_ID, VST.SG_SO_NAME SO_NAME, VST.SG_SO_TITLE SO_TITLE, VST.SG_SO_ORG SO_ORG
           , VST.SG_XO_ID XO_ID, VST.SG_XO_NAME XO_NAME, VST.SG_XO_TITLE XO_TITLE, VST.SG_XO_ORG XO_ORG
           , VST.SG_HRL_ID HRL_ID, VST.SG_HL_NAME HRL_NAME, VST.SG_HRL_TITLE HRL_TITLE, VST.SG_HRL_ORG HRL_ORG
           , VCL.CS_TITLE POS_TITLE, VCL.CS_PAY_PLAN_ID PAY_PLAN_ID, VCL.CS_PAY_PLAN_DSCR PAY_PLAN_DESC
           , VCL.CS_SR_ID POS_SERIES_ID, VCL.CS_SR_DSCR POS_SERIES_DESC
           , VCL.CS_GR_ID_1 POS_GRADE1, VCL.CS_GR_ID_2 POS_GRADE2, VCL.CS_GR_ID_3 POS_GRADE3, VCL.CS_GR_ID_4 POS_GRADE4, VCL.CS_GR_ID_5 POS_GRADE5
           , VCL.CS_PD_NUMBER_JOBCD_1 POS_DESC_NUM1, VCL.CS_PD_NUMBER_JOBCD_2 POS_DESC_NUM2, VCL.CS_PD_NUMBER_JOBCD_3 POS_DESC_NUM3, VCL.CS_PD_NUMBER_JOBCD_4 POS_DESC_NUM4, VCL.CS_PD_NUMBER_JOBCD_5 POS_DESC_NUM5
           , VST.POS_CNDT_FIRST_NM CANDI_FIRST_NAME, VST.POS_CNDT_MIDDLE_NM CANDI_MIDDLE_NAME, VST.POS_CNDT_LAST_NM CANDI_LAST_NAME
           , VST.POS_CE_LIC LICENSE, VST.POS_CE_LIC_INFO LICENSE_INFO
           , VST.POS_WORK_SCHED_ID, VST.POS_WORK_SCHED_DSCR, VST.POS_HOURS_PER_WEEK, VST.POS_NTE
           , VST.POS_AT_DSCR TYPE_OF_APPT
         FROM VW_UNIFIED_REQUESTS_RANK RR
           INNER JOIN VW_CLASSIFICATION VCL ON VCL.REQ_ID = RR.REQ_ID AND RR.PROC_TYPE='CLASSIFICATION' AND RR.REQ_RANK=1
           INNER JOIN VW_STRATCON VST ON VST.REQ_JOB_REQ_NUMBER = RR.REQ_JOB_REQ_NUMBER

         UNION ALL

         SELECT RR.REQ_ID, RR.REQ_JOB_REQ_NUMBER REQUEST_NUMBER, RR.REQ_JOB_REQ_CREATE_DT REQUEST_DATE
           , RR.REQ_CANCEL_DT REQ_CANCEL_DATE, RR.REQ_CANCEL_REASON, RR.PROC_ID, RR.PROC_STATE, RR.PROC_TYPE
           , VEL.RT_ID REQUEST_TYPE_ID, VEL.RT_DSCR REQUEST_TYPE
           , VEL.ADMIN_CD ADMIN_CODE, VEL.ADMIN_CD_DSCR ADMIN_CODE_DESC
           , VEL.SO_ID SO_ID, VEL.SO_NAME SO_NAME, VEL.SO_TITLE SO_TITLE, VEL.SO_ORG SO_ORG
           , VEL.XO_ID XO_ID, VEL.XO_NAME XO_NAME, VEL.XO_TITLE XO_TITLE, VEL.XO_ORG XO_ORG
           , VEL.HRL_ID HRL_ID, VEL.HL_NAME HRL_NAME, VEL.HRL_TITLE HRL_TITLE, VEL.HRL_ORG HRL_ORG
           , VEL.POS_TITLE POS_TITLE, VEL.PAY_PLAN_ID PAY_PLAN_ID, VEL.PAY_PLAN_DSCR PAY_PLAN_DESC
           , VEL.SR_ID POS_SERIES_ID
	   , (SELECT LU_SR.TBL_LABEL FROM TBL_LOOKUP LU_SR WHERE LU_SR.TBL_ID = VEL.SERIES AND ROWNUM = 1) AS POS_SERIES_DESC
           , VEL.GRADE_1 POS_GRADE1, VEL.GRADE_2 POS_GRADE2, VEL.GRADE_3 POS_GRADE3, VEL.GRADE_4 POS_GRADE4, VEL.GRADE_5 POS_GRADE5
           , VEL.POS_DESC_NUMBER_1 POS_DESC_NUM1, VEL.POS_DESC_NUMBER_2 POS_DESC_NUM2, VEL.POS_DESC_NUMBER_3 POS_DESC_NUM3, VEL.POS_DESC_NUMBER_4 POS_DESC_NUM4, VEL.POS_DESC_NUMBER_5 POS_DESC_NUM5
           , VEL.CNDT_FIRST_NM CANDI_FIRST_NAME, VEL.CNDT_MIDDLE_NM CANDI_MIDDLE_NAME, VEL.CNDT_LAST_NM CANDI_LAST_NAME
           , VEL.CE_LIC LICENSE, VEL.CE_LIC_INFO LICENSE_INFO
           , VEL.WORK_SCHED_ID POS_WORK_SCHED_ID, VEL.WORK_SCHED_DSCR POS_WORK_SCHED_DSCR, VEL.HOURS_PER_WEEK POS_HOURS_PER_WEEK, VEL.NTE POS_NTE
           , VEL.TA_DSCR TYPE_OF_APPT
         FROM VW_UNIFIED_REQUESTS_RANK RR
           INNER JOIN VW_ELIGQUAL VEL ON VEL.REQ_ID = RR.REQ_ID AND RR.PROC_TYPE='ELIGQUAL' AND RR.REQ_RANK=1
       ) REQ;

/