/*
 * Performance Tuning
 * Change the view to pull records not from XML but custom tables
 * Adding new column with correct datatype, and populate the column value from the varchar2 column
 */

CREATE OR REPLACE FORCE VIEW HHS_CMS_HR.VW_INCENTIVES_SAM
(
    PROC_ID
    ,INIT_SALARY_GRADE
    ,INIT_SALARY_STEP
    ,INIT_SALARY_SALARY_PER_ANNUM
    ,INIT_SALARY_LOCALITY_PAY_SCALE
    ,SUPPORT_SAM
    ,RCMD_SALARY_GRADE
    ,RCMD_SALARY_STEP
    ,RCMD_SALARY_SALARY_PER_ANNUM
    ,RCMD_SALARY_LOCALITY_PAY_SCALE
    ,SELECTEE_SALARY_PER_ANNUM
    ,SELECTEE_SALARY_TYPE
    ,SELECTEE_BONUS
    ,SELECTEE_BENEFITS
    ,SELECTEE_TOTAL_COMPENSATION
    ,SUP_DOC_REQ_DATE
    ,SUP_DOC_RCV_DATE
    ,JUSTIFICATION_SUPER_QUAL_DESC
    ,JUSTIFICATION_QUAL_COMP_DESC
    ,JUSTIFICATION_PAY_EQUITY_DESC
    ,JUSTIFICATION_EXIST_PKG_DESC
    ,JUSTIFICATION_EXPLAIN_CONSID
    ,SELECT_MEET_ELIGIBILITY
    ,SELECT_MEET_CRITERIA
    ,SUPERIOR_QUAL_REASON
    ,OTHER_FACTORS
    ,SPL_AGENCY_NEED_RSN
    ,SPL_AGENCY_NEED_RSN_ESS
    ,QUAL_REAPPT
    ,OTHER_EXCEPTS
    ,BASIC_PAY_RATE_FACTOR1
    ,BASIC_PAY_RATE_FACTOR2
    ,BASIC_PAY_RATE_FACTOR3
    ,BASIC_PAY_RATE_FACTOR4
    ,BASIC_PAY_RATE_FACTOR5
    ,BASIC_PAY_RATE_FACTOR6
    ,BASIC_PAY_RATE_FACTOR7
    ,BASIC_PAY_RATE_FACTOR8
    ,BASIC_PAY_RATE_FACTOR9
    ,BASIC_PAY_RATE_FACTOR10
    ,OTHER_RLVNT_FACTOR
    ,OTHER_REQ_JUST_APVD
    ,OTHER_REQ_SUFF_INFO_PRVD
    ,OTHER_REQ_INCEN_REQD
    ,OTHER_REQ_DOC_PRVD
    ,HRS_RVW_CERT
    ,HRS_NOT_SPT_RSN
    ,RVW_HRS
    ,HRS_RVW_DATE
    ,RCMD_GRADE
    ,RCMD_STEP
    ,RCMD_SALARY_PER_ANNUM
    ,RCMD_LOCALITY_PAY_SCALE
    ,RCMD_INC_DEC_AMOUNT
    ,RCMD_PERC_DIFF
    ,OHC_APPRO_REQ
    ,RCMD_APPRO_OHC_NAME
    ,RCMD_APPRO_OHC_EMAIL
    ,RCMD_APPRO_OHC_ID
    ,RVW_REMARKS
    ,APPROVAL_SO_VALUE
    ,APPROVAL_SO
    ,APPROVAL_SO_RESP_DATE 
    ,APPROVAL_DGHO_VALUE
    ,APPROVAL_DGHO
    ,APPROVAL_DGHO_RESP_DATE 
    ,APPROVAL_TABG_VALUE
    ,APPROVAL_TABG
    ,APPROVAL_TABG_RESP_DATE 
    ,APPROVAL_OHC_VALUE
    ,APPROVAL_OHC
    ,APPROVAL_OHC_RESP_DATE 
    ,APPROVER_NOTES
    ,COC_NAME
    ,COC_EMAIL
    ,COC_ID
    ,COC_TITLE
    ,APPROVAL_COC_VALUE
    ,APPROVAL_COC_ACTING
    ,APPROVAL_COC
    ,APPROVAL_COC_RESP_DATE 
    ,APPROVAL_SO_ACTING
    ,APPROVAL_DGHO_ACTING
    ,APPROVAL_TABG_ACTING
    ,APPROVAL_OHC_ACTING
    ,JUSTIFICATION_MOD_REASON
    ,JUSTIFICATION_MOD_SUMMARY
    ,JUSTIFICATION_MODIFIER_NAME
    ,JUSTIFICATION_MODIFIER_ID
    ,JUSTIFICATION_MODIFIED_DATE
    ,JUSTIFICATION_VER
    ,JUSTIFICATION_CRT_NAME
    ,JUSTIFICATION_CRT_ID
    ,JUSTIFICATION_CRT_DATE 
    ,JUSTIFICATION_LASTMOD_NAME
    ,JUSTIFICATION_LASTMOD_ID
    ,JUSTIFICATION_LASTMOD_DATE
    ,INIT_SALARY_SALARY_PER_ANNUM_N
    ,RCMD_SALARY_SALARY_PER_ANNUM_N
    ,SELECTEE_SALARY_PER_ANNUM_N
    ,SELECTEE_BONUS_N
    ,SELECTEE_TOTAL_COMPENSATION_N
    ,SUP_DOC_REQ_DATE_D
    ,SUP_DOC_RCV_DATE_D
    ,HRS_RVW_DATE_D
    ,RCMD_SALARY_PER_ANNUM_N
    ,RCMD_INC_DEC_AMOUNT_N
    ,APPROVAL_SO_RESP_DATE_D
    ,APPROVAL_DGHO_RESP_DATE_D
    ,APPROVAL_TABG_RESP_DATE_D
    ,APPROVAL_OHC_RESP_DATE_D
    ,APPROVAL_COC_RESP_DATE_D
    ,JUSTIFICATION_MODIFIED_DATE_D
    ,JUSTIFICATION_CRT_DATE_D
    ,JUSTIFICATION_LASTMOD_DATE_D
)
AS
--------------------------------------------------------------------------------------------------------------------------------
SELECT 
    PROC_ID
    ,INIT_SALARY_GRADE
    ,INIT_SALARY_STEP
    ,TO_CHAR(INIT_SALARY_SALARY_PER_ANNUM_N, '$999,999,999,999,999,999.99' ) as INIT_SALARY_SALARY_PER_ANNUM 
    ,INIT_SALARY_LOCALITY_PAY_SCALE
    ,SUPPORT_SAM
    ,RCMD_SALARY_GRADE
    ,RCMD_SALARY_STEP
    ,TO_CHAR(RCMD_SALARY_SALARY_PER_ANNUM_N, '$999,999,999,999,999,999.99' ) as RCMD_SALARY_SALARY_PER_ANNUM
    ,RCMD_SALARY_LOCALITY_PAY_SCALE
    ,TO_CHAR(SELECTEE_SALARY_PER_ANNUM_N, '$999,999,999,999,999,999.99' ) as SELECTEE_SALARY_PER_ANNUM
    ,SELECTEE_SALARY_TYPE
    ,TO_CHAR(SELECTEE_BONUS_N, '$999,999,999,999,999,999.99' ) as SELECTEE_BONUS
    ,SELECTEE_BENEFITS
    ,TO_CHAR(SELECTEE_TOTAL_COMPENSATION_N, '$999,999,999,999,999,999.99' ) as SELECTEE_TOTAL_COMPENSATION
    ,TO_CHAR(SUP_DOC_REQ_DATE_D, 'mm/dd/yyyy') as SUP_DOC_REQ_DATE
    ,TO_CHAR(SUP_DOC_RCV_DATE_D, 'mm/dd/yyyy') as SUP_DOC_RCV_DATE
    ,JUSTIFICATION_SUPER_QUAL_DESC
    ,JUSTIFICATION_QUAL_COMP_DESC
    ,JUSTIFICATION_PAY_EQUITY_DESC
    ,JUSTIFICATION_EXIST_PKG_DESC
    ,JUSTIFICATION_EXPLAIN_CONSID
    ,SELECT_MEET_ELIGIBILITY
    ,SELECT_MEET_CRITERIA
    ,SUPERIOR_QUAL_REASON
    ,OTHER_FACTORS
    ,SPL_AGENCY_NEED_RSN
    ,SPL_AGENCY_NEED_RSN_ESS
    ,QUAL_REAPPT
    ,OTHER_EXCEPTS
    ,BASIC_PAY_RATE_FACTOR1
    ,BASIC_PAY_RATE_FACTOR2
    ,BASIC_PAY_RATE_FACTOR3
    ,BASIC_PAY_RATE_FACTOR4
    ,BASIC_PAY_RATE_FACTOR5
    ,BASIC_PAY_RATE_FACTOR6
    ,BASIC_PAY_RATE_FACTOR7
    ,BASIC_PAY_RATE_FACTOR8
    ,BASIC_PAY_RATE_FACTOR9
    ,BASIC_PAY_RATE_FACTOR10
    ,OTHER_RLVNT_FACTOR
    ,OTHER_REQ_JUST_APVD
    ,OTHER_REQ_SUFF_INFO_PRVD
    ,OTHER_REQ_INCEN_REQD
    ,OTHER_REQ_DOC_PRVD
    ,HRS_RVW_CERT
    ,HRS_NOT_SPT_RSN
    ,RVW_HRS
    ,TO_CHAR(HRS_RVW_DATE_D, 'mm/dd/yyyy') as HRS_RVW_DATE
    ,RCMD_GRADE
    ,RCMD_STEP
    ,DECODE(RCMD_SALARY_PER_ANNUM_N, 0, '0.00', TO_CHAR(RCMD_SALARY_PER_ANNUM_N, 's999,999,999,999,999,999.99')) as RCMD_SALARY_PER_ANNUM
    ,RCMD_LOCALITY_PAY_SCALE
    ,DECODE(RCMD_INC_DEC_AMOUNT_N, 0, '0.00', TO_CHAR(RCMD_INC_DEC_AMOUNT_N, 's999,999,999,999,999,999.99')) as RCMD_INC_DEC_AMOUNT 
    ,RCMD_PERC_DIFF
    ,OHC_APPRO_REQ
    ,RCMD_APPRO_OHC_NAME
    ,RCMD_APPRO_OHC_EMAIL
    ,RCMD_APPRO_OHC_ID
    ,RVW_REMARKS
    ,APPROVAL_SO_VALUE
    ,APPROVAL_SO
    ,TO_CHAR(APPROVAL_SO_RESP_DATE_D, 'mm/dd/yyyy') as APPROVAL_SO_RESP_DATE
    ,APPROVAL_DGHO_VALUE
    ,APPROVAL_DGHO
    ,TO_CHAR(APPROVAL_DGHO_RESP_DATE_D, 'mm/dd/yyyy') as APPROVAL_DGHO_RESP_DATE
    ,APPROVAL_TABG_VALUE
    ,APPROVAL_TABG
    ,TO_CHAR(APPROVAL_TABG_RESP_DATE_D, 'mm/dd/yyyy') as APPROVAL_TABG_RESP_DATE
    ,APPROVAL_OHC_VALUE
    ,APPROVAL_OHC
    ,TO_CHAR(APPROVAL_OHC_RESP_DATE_D, 'mm/dd/yyyy') as APPROVAL_OHC_RESP_DATE
    ,APPROVER_NOTES
    ,COC_NAME
    ,COC_EMAIL
    ,COC_ID
    ,COC_TITLE
    ,APPROVAL_COC_VALUE
    ,APPROVAL_COC_ACTING
    ,APPROVAL_COC
    ,TO_CHAR(APPROVAL_COC_RESP_DATE_D, 'mm/dd/yyyy') as APPROVAL_COC_RESP_DATE
    ,APPROVAL_SO_ACTING
    ,APPROVAL_DGHO_ACTING
    ,APPROVAL_TABG_ACTING
    ,APPROVAL_OHC_ACTING
    ,JUSTIFICATION_MOD_REASON
    ,JUSTIFICATION_MOD_SUMMARY
    ,JUSTIFICATION_MODIFIER_NAME
    ,JUSTIFICATION_MODIFIER_ID
    ,TO_CHAR(JUSTIFICATION_MODIFIED_DATE_D, 'mm/dd/yyyy hh24:mi:ss') as JUSTIFICATION_MODIFIED_DATE
    ,JUSTIFICATION_VER
    ,JUSTIFICATION_CRT_NAME
    ,JUSTIFICATION_CRT_ID
    ,TO_CHAR(JUSTIFICATION_CRT_DATE_D, 'mm/dd/yyyy hh24:mi:ss') as JUSTIFICATION_CRT_DATE
    ,JUSTIFICATION_LASTMOD_NAME
    ,JUSTIFICATION_LASTMOD_ID
    ,TO_CHAR(JUSTIFICATION_LASTMOD_DATE_D, 'mm/dd/yyyy hh24:mi:ss') as JUSTIFICATION_LASTMOD_DATE
    ,INIT_SALARY_SALARY_PER_ANNUM_N
    ,RCMD_SALARY_SALARY_PER_ANNUM_N
    ,SELECTEE_SALARY_PER_ANNUM_N
    ,SELECTEE_BONUS_N
    ,SELECTEE_TOTAL_COMPENSATION_N
    ,SUP_DOC_REQ_DATE_D 
    ,SUP_DOC_RCV_DATE_D
    ,HRS_RVW_DATE_D
    ,RCMD_SALARY_PER_ANNUM_N
    ,RCMD_INC_DEC_AMOUNT_N
    ,APPROVAL_SO_RESP_DATE_D
    ,APPROVAL_DGHO_RESP_DATE_D
    ,APPROVAL_TABG_RESP_DATE_D
    ,APPROVAL_OHC_RESP_DATE_D
    ,APPROVAL_COC_RESP_DATE_D
    ,JUSTIFICATION_MODIFIED_DATE_D
    ,JUSTIFICATION_CRT_DATE_D
    ,JUSTIFICATION_LASTMOD_DATE_D
FROM HHS_CMS_HR.INCENTIVES_SAM
;

