create or replace FUNCTION HHS_FN_GET_ACCCALDAYSDIFF(
	I_PROCID               IN      INT
	, I_ACTNAME            IN      VARCHAR2
)
RETURN INT
IS
	V_EVENT CHAR(1);
	V_EXECDTIME DATE;
	V_END DATE;
	V_FOUND_COMPLETED_DATE CHAR(1);
	V_DAYDIFF INT;
	V_DAYDIFF_TOTAL INT;

	CURSOR CUR_AUDITINFO IS
		SELECT EVENT, EXECDTIME
		FROM AUDITINFO
		WHERE OBJNAME = I_ACTNAME
			AND EVENT IN ('R', 'C')
			AND OBJTYPE = 'A'
			AND PROCID = I_PROCID
		ORDER BY EXECSEQ DESC;
BEGIN
	V_FOUND_COMPLETED_DATE := 'N';
	V_DAYDIFF := 0;
	V_DAYDIFF_TOTAL := 0;

	OPEN CUR_AUDITINFO;

	LOOP
		FETCH CUR_AUDITINFO INTO V_EVENT, V_EXECDTIME;
		EXIT WHEN CUR_AUDITINFO%NOTFOUND;

		IF (V_EVENT = 'R' AND V_FOUND_COMPLETED_DATE = 'Y') THEN
			SELECT ( V_END - V_EXECDTIME ) INTO V_DAYDIFF FROM dual;
			V_DAYDIFF_TOTAL := V_DAYDIFF_TOTAL + V_DAYDIFF;
			V_FOUND_COMPLETED_DATE := 'N';
		ELSIF (V_EVENT = 'C') THEN
			V_FOUND_COMPLETED_DATE := 'Y';
			V_END := V_EXECDTIME;
		END IF;

	END LOOP;

	CLOSE CUR_AUDITINFO;
	RETURN V_DAYDIFF_TOTAL;
END;