create or replace PROCEDURE SP_UPDATE_PV_ERLR
  (
      I_PROCID         IN      NUMBER
    , I_FIELD_DATA     IN      XMLTYPE
  )
IS
  V_REQUEST_NUMBER       VARCHAR2(20);
  ERLR_GEN_REC           ERLR_GEN%ROWTYPE;
BEGIN
    SELECT *
      INTO ERLR_GEN_REC
      FROM ERLR_GEN
    WHERE PROCID = I_PROCID;

    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_CASE_CATEGORY_NAME
     WHERE RLVNTDATANAME = 'caseCategory'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_CASE_STATUS
     WHERE RLVNTDATANAME = 'caseStatus'
       AND PROCID = I_PROCID;
    
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_CASE_TYPE_NAME
     WHERE RLVNTDATANAME = 'caseType'
       AND PROCID = I_PROCID;
  
    IF ERLR_GEN_REC.GEN_CASE_TYPE_NAME IS NOT NULL THEN
      --- set requestNum ------
      SELECT VALUE INTO V_REQUEST_NUMBER 
        FROM BIZFLOW.RLVNTDATA 
       WHERE RLVNTDATANAME = 'requestNum' 
         AND PROCID = I_PROCID;
      IF V_REQUEST_NUMBER IS NULL THEN
          GET_REQUEST_NUM (V_REQUEST_NUMBER);
          UPDATE BIZFLOW.RLVNTDATA 
             SET VALUE = V_REQUEST_NUMBER
           WHERE RLVNTDATANAME = 'requestNum' 
             AND PROCID = I_PROCID;
      END IF;        
    END IF;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_CUSTOMER_NAME
     WHERE RLVNTDATANAME = 'contactName'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_EMPLOYEE_NAME
     WHERE RLVNTDATANAME = 'employeeName'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = TO_CHAR(SYS_EXTRACT_UTC(CAST(ERLR_GEN_REC.GEN_CUST_INIT_CONTACT_DT AS TIMESTAMP)), 'YYYY/MM/DD HH24:MI:SS')
     WHERE RLVNTDATANAME = 'initialContactDate'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA
       SET VALUE = TO_CHAR((sys_extract_utc(systimestamp)), 'YYYY/MM/DD HH24:MI:SS')
     WHERE RLVNTDATANAME = 'lastModifiedDate'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_EMPLOYEE_NAME
     WHERE RLVNTDATANAME = 'employeeName'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = ERLR_GEN_REC.GEN_EMPLOYEE_ADMIN_CD
     WHERE RLVNTDATANAME = 'organization'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = CASE WHEN ERLR_GEN_REC.GEN_PRIMARY_SPECIALIST IS NOT NULL THEN '[U]'||ERLR_GEN_REC.GEN_PRIMARY_SPECIALIST ELSE NULL END
     WHERE RLVNTDATANAME = 'primaryDWCSpecialist'
       AND PROCID = I_PROCID;
  
    UPDATE BIZFLOW.RLVNTDATA 
       SET VALUE = CASE WHEN ERLR_GEN_REC.GEN_SECONDARY_SPECIALIST IS NOT NULL THEN '[U]'||ERLR_GEN_REC.GEN_SECONDARY_SPECIALIST ELSE NULL END
     WHERE RLVNTDATANAME = 'secondaryDWCSpecialist'
       AND PROCID = I_PROCID;
     
    IF I_FIELD_DATA IS NOT NULL THEN
      SP_UPDATE_PV_BY_XPATH(I_PROCID, I_FIELD_DATA, 'reassign',               '/formData/items/item[id=''reassign'']/value/text()');      
      SP_UPDATE_PV_BY_XPATH(I_PROCID, I_FIELD_DATA, 'requestStatusDate',      '/formData/items/item[id=''REQ_STATUS_DT'']/value/text()');
    END IF;
END;