--------------------------------------------------------
--  DDL for Table SLA_HIRING_TIMELINE
--------------------------------------------------------

  CREATE TABLE "HHS_CMS_HR"."SLA_HIRING_TIMELINE" 
   (	"SLA_ID" VARCHAR2(50 BYTE) NOT NULL, 
	"PROCESS_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"ACTIVITY_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"SG_RT_ID" NUMBER(20,0) NOT NULL, 
	"TARGET_BUSINESS_DAY" NUMBER(3,0) DEFAULT 0 NOT NULL, 
	"TOTAL_CALENDAR_DAY" NUMBER(3,0) DEFAULT 0 NOT NULL, 
	"DISPLAY_ORDER" NUMBER
   );

  CREATE UNIQUE INDEX "HHS_CMS_HR"."SLA_HIRING_TIMELINE_PK" ON "HHS_CMS_HR"."SLA_HIRING_TIMELINE" ("SLA_ID");
  ALTER TABLE "HHS_CMS_HR"."SLA_HIRING_TIMELINE" ADD CONSTRAINT "SLA_HIRING_TIMELINE_PK" PRIMARY KEY ("SLA_ID");
 

set define off;
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_1',	101,18,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_2',	102,18,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_3',	103,18,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_SC_4',	104,18,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_1',	121,18,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_2',	122,18,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_3',	123,18,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_4',	124,18,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMA_5',	125,18,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_1',	141,18,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_2',	142,18,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_3',	143,18,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_4',	144,18,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_CMI_5',	145,18,'Classification - Minor','Create Final Package (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_1',	161,18,'Recruitment','Draft announcement (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_2',	162,18,'Recruitment','Review Assessment/Announcement (Component)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_3',	163,18,'Recruitment','Final Edits and Post to USA jobs (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_4',	164,18,'Recruitment','Announcement Open Period (Other)',10,14);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_5',	165,18,'Recruitment','Qualification Analysis (HR)',12,16);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_6',	166,18,'Recruitment','Certificate Issue (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_R_7',	167,18,'Recruitment','Certificate Return (Component)',11,15);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_1',	181,18,'Offer','Send Tentative Offer (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_2',	182,18,'Offer','Receive Tentative Offer Response (Applicant)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_3',	183,18,'Offer','Complete Pre-Employment Forms & Initiate Background Investigation (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_4',	184,18,'Offer','Receive Background Investigation Clearance (Other)',10,12);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_5',	185,18,'Offer','Establish Entry on Duty Date (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('R_O_6',	186,18,'Offer','Send Official Offer (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_1',	201,76,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_2',	202,76,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_3',	203,76,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_SC_4',	204,76,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_1',	221,76,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_2',	222,76,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_3',	223,76,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_4',	224,76,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMA_5',	225,76,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_1',	241,76,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_2',	242,76,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_3',	243,76,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_4',	244,76,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_CMI_5',	245,76,'Classification - Minor','Create Final Package (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_EQRA_1',	261,76,'Eligibility and Qualifications Review Activities','Staff or Spec. Staff determines eligibility and qualifications (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_EQRA_2',	262,76,'Eligibility and Qualifications Review Activities','SO Selection Determination (Component)',8,10);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_1',	281,76,'Offer','Send Tentative Offer (HR)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_2',	282,76,'Offer','Receive Tentative Offer Response (Applicant)',2,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_3',	283,76,'Offer','Complete Pre-Employment Forms & Initiate Background Investigation (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_4',	284,76,'Offer','Receive Background Investigation Clearance (Security)',10,12);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_5',	285,76,'Offer','Establish Entry on Duty Date (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('A_O_6',	286,76,'Offer','Send Official Offer (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_1',	301,17,'Strategic Consultation','Create/Review/Modify Request (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_2',	302,17,'Strategic Consultation','Hold Strategic Consultation Meeting (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_3',	303,17,'Strategic Consultation','Acknowledge Strategic Consultation Meeting (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_SC_4',	304,17,'Strategic Consultation','Approve Strategic Consultation Meeting (HR)',2,3);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_1',	321,17,'Classification - Major','Complete PD Coversheet & Classification Analysis (HR)',4,5);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_2',	322,17,'Classification - Major','Confirm Analysis (Component)',1,2);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_3',	323,17,'Classification - Major','BUS Code Review (HR)',0,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_4',	324,17,'Classification - Major','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMA_5',	325,17,'Classification - Major','Create Final Package (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_1',	341,17,'Classification - Minor','Complete PD Coversheet & Classification Analysis (HR)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_2',	342,17,'Classification - Minor','Confirm Analysis (Component)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_3',	343,17,'Classification - Minor','BUS Code Review (HR)',0,0);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_4',	344,17,'Classification - Minor','Approve Coversheet (Component)',1,1);
INSERT INTO SLA_HIRING_TIMELINE (SLA_ID,DISPLAY_ORDER,SG_RT_ID,PROCESS_NAME,ACTIVITY_NAME,TARGET_BUSINESS_DAY,TOTAL_CALENDAR_DAY) VALUES ('C_CMI_5',	345,17,'Classification - Minor','Create Final Package (HR)',0,0);
