SET DEFINE OFF;

 CREATE OR REPLACE PROCEDURE SP_UPDATE_INCENTIVES_COM_TABLE
(
	I_PROCID            IN      NUMBER
)
IS
BEGIN
	IF I_PROCID IS NOT NULL AND I_PROCID > 0 THEN
		DELETE INCENTIVES_COM WHERE PROC_ID = I_PROCID;
		INSERT INTO INCENTIVES_COM (PROC_ID, INCEN_TYPE, REQ_NUM, REQ_TYPE, ADMIN_CODE, ORG_NAME
			, CANDI_NAME, CANDI_FIRST, CANDI_MIDDLE, CANDI_LAST
			, SO_NAME, SO_EMAIL, SO_ID, SO_TITLE
			, XO1_NAME, XO1_EMAIL, XO1_ID, XO2_NAME, XO2_EMAIL, XO2_ID, XO3_NAME, XO3_EMAIL, XO3_ID
			, HRL1_NAME, HRL1_EMAIL, HRL1_ID, HRL2_NAME, HRL2_EMAIL, HRL2_ID, HRL3_NAME, HRL3_EMAIL, HRL3_ID
			, HRS1_NAME, HRS1_EMAIL, HRS1_ID, HRS2_NAME, HRS2_EMAIL, HRS2_ID
			, DGHO_NAME, DGHO_EMAIL, DGHO_ID
			, TABG_NAME, TABG_EMAIL, TABG_ID, POS_TITLE
			, PAY_PLAN, SERIES, GRADE, POS_DESC_NUM, TYPE_OF_APPT, DS_STATE, DS_CITY, CANCEL_RESAON, CANCEL_USER_NAME, CANCEL_USER_ID)
			SELECT PROC_ID, INCEN_TYPE, REQ_NUM, REQ_TYPE, ADMIN_CODE, ORG_NAME
			, CANDI_NAME, CANDI_FIRST, CANDI_MIDDLE, CANDI_LAST
			, SO_NAME, SO_EMAIL, SO_ID, SO_TITLE
			, XO1_NAME, XO1_EMAIL, XO1_ID, XO2_NAME, XO2_EMAIL, XO2_ID, XO3_NAME, XO3_EMAIL, XO3_ID
			, HRL1_NAME, HRL1_EMAIL, HRL1_ID, HRL2_NAME, HRL2_EMAIL, HRL2_ID, HRL3_NAME, HRL3_EMAIL, HRL3_ID
			, HRS1_NAME, HRS1_EMAIL, HRS1_ID, HRS2_NAME, HRS2_EMAIL, HRS2_ID
			, DGHO_NAME, DGHO_EMAIL, DGHO_ID
			, TABG_NAME, TABG_EMAIL, TABG_ID, POS_TITLE
			, PAY_PLAN, SERIES, GRADE, POS_DESC_NUM, TYPE_OF_APPT, DS_STATE, DS_CITY, CANCEL_RESAON, CANCEL_USER_NAME, CANCEL_USER_ID
			FROM VW_INCENTIVES_COM WHERE PROC_ID = I_PROCID;
	END IF;

	EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;
/
