create or replace FUNCTION HHS_FN_ADD_BUSDAY 
(
  I_ACTSTART IN DATE 
, I_SLADAYS IN INT 
) 
RETURN DATE
IS
  V_DAY DATE;

BEGIN
    IF I_ACTSTART IS NOT NULL AND I_SLADAYS > 0 THEN
        SELECT CALDTIME 
          INTO V_DAY
          FROM (SELECT 
                    C.CALDTIME AS CALDTIME, ROW_NUMBER() OVER (ORDER BY C.CALDTIME ASC) AS SEQNUM
                  FROM BIZFLOW.CAL C
                    INNER JOIN BIZFLOW.CALHEAD CH
                   ON CH.DAYOFWEEK = C.DAYOFWEEK
                   WHERE CH.DAYTYPE <> 'H'
                    AND C.CALDTIME NOT IN (SELECT CALDTIME FROM BIZFLOW.MEMBERCAL WHERE DAYTYPE = 'H' AND MEMBERID = '0000000000')
                    AND CH.MEMBERID = '0000000000'
                    AND C.CALDTIME BETWEEN I_ACTSTART AND I_ACTSTART+((30+I_SLADAYS)*2)
                 ) TBL_NEW
        WHERE SEQNUM = I_SLADAYS;
        
        RETURN V_DAY;
    ELSE
        RETURN I_ACTSTART;
    END IF;

END;