-- Set active 'Career Ladder Promotion Denial' and 'Administrative Leave' action
UPDATE HHS_CMS_HR.TBL_LOOKUP 
   SET TBL_ACTIVE = '1'
 WHERE TBL_ID IN (1794, 1796);

DELETE HHS_CMS_HR.TBL_LOOKUP WHERE TBL_ID = 746;
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT) VALUES (746, 0, 'ERLRInitialResponseCaseType', 'Medical Documentation/Exam', 'Medical Documentation/Exam', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

UPDATE BIZFLOW.RLVNTDATA
   SET VALUE = 'Medical Documentation/Exam'
 WHERE RLVNTDATANAME = 'caseType'
   AND VALUE = 'Medical Documentation';

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1797, 0, 'ERLRMeddocRejectReason', 'Documentation insufficient', 'Documentation insufficient', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;

INSERT INTO TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (1798, 0, 'ERLRMeddocRejectReason', 'Documentation not applicable', 'Documentation not applicable', '1', null, 'N', null, 'ERLR', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'))
;
