package com.bizflow.drools.document.rules;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map
import java.util.Iterator
import java.util.Arrays

import com.bizflow.ps.drools.document.model.WorkflowDocument;
import com.bizflow.ps.drools.document.model.WorkflowRuleSearch;
import com.bizflow.ps.drools.document.model.WorkflowField;

dialect "mvel"

function void addDocument(ArrayList bizflowDocument, String documentName, boolean required) {
    boolean exist = false;
    int len = bizflowDocument.size();
    for (int i=0; i < len; i++) {
        WorkflowDocument doc = (WorkflowDocument) bizflowDocument.get(i);
        if(documentName.equalsIgnoreCase(doc.getName())) {
            exist = true;
            break;
        }
    }

    if(!exist) {
        bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, required));
    }
}

function void addDocumentOther(ArrayList bizflowDocument, String documentName, boolean required) {
    boolean isRequiredDocument = required;
    int len = bizflowDocument.size();
    for (int i=0; i < len; i++) {
        WorkflowDocument doc = (WorkflowDocument) bizflowDocument.get(i);
        if("Other".equalsIgnoreCase(doc.getName())) {
            isRequiredDocument = false;
            break;
        }
    }
	bizflowDocument.add(new WorkflowDocument(1, bizflowDocument.size() + 1, documentName, "DocumentType", "Other", 0, bizflowDocument.size()+1, isRequiredDocument));
}

function void addDocumentEx(ArrayList bizflowDocument, String documentName, String actName, String[] actNames, boolean required) {
    boolean isRequiredDocument = false;
    for (String act: actNames) {
        if (act.equals(actName)) {
            isRequiredDocument = required;
            break;
        }
    }
    bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, isRequiredDocument));
}

rule "Incentives / PCA Required Documents / New / Recruitment"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "pcaType", fieldValue == "New" ) from $fields
         $field4: WorkflowField ( fieldId == "requestType", fieldValue == "Recruitment" ) from $fields
         $field5: WorkflowField ( fieldId == "candiAgreeRenewal", fieldValue != "No" ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments, "Vacancy Announcement", true);
end

rule "Incentives / PCA Required Documents / New"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "pcaType", fieldValue == "New" ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments, "Request to fill", ($actName == "Start New"));
end

rule "Incentives / PCA Required Documents / Declination of Renewal"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "pcaType", fieldValue == "Renewal" ) from $fields
         $field5: WorkflowField ( fieldId == "candiAgreeRenewal", fieldValue == "No" ) from $fields
         $field6: WorkflowField ( fieldId == "doesHaveOther", fieldValue == false ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocumentOther($workflowDocuments, "Employee's Declination of Renewal", true);
end

rule "Incentives / PCA Required Documents / RequireBoardCert"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "requireBoardCert", fieldValue == "Yes" ) from $fields
         $field4: WorkflowField ( fieldId == "candiAgreeRenewal", fieldValue != "No" ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments, "Board Certification", true);
end


rule "Incentives / PCA Required Documents "
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "candiAgreeRenewal", fieldValue != "No" ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments,"Final Position Description Package", true);
        addDocument($workflowDocuments,"Resume/Curriculum Vitae", true);
        addDocument($workflowDocuments,"Justification Narrative", true);
        addDocument($workflowDocuments,"Medical License", true);
end

rule "Incentives / SAM Required Documents / Resume"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "SAM" ) from $fields
         $field3: WorkflowField ( fieldId == "doesHaveResume", fieldValue == false ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments,"Resume/Curriculum Vitae", true);
end

rule "Incentives / SAM Required Documents / Package"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "SAM" ) from $fields
         $field3: WorkflowField ( fieldId == "doesHavePackage", fieldValue == false ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments,"Final Position Description Package", true);
end

rule "Incentives / SAM Required Documents "
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "RequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "SAM" ) from $fields

        $workflowDocuments : ArrayList()

    then
        addDocument($workflowDocuments,"Resume/Curriculum Vitae", false);
        addDocument($workflowDocuments,"Competing Job Offer", false);
        addDocument($workflowDocuments,"Pay Stub", false);
        addDocument($workflowDocuments,"Additional Compensation", false);
        addDocument($workflowDocuments,"Vacancy Announcement", false);
        addDocument($workflowDocuments,"Final Position Description Package", false);
end

//------------------------------
// DEFAULT DOCUMENT
//------------------------------
rule "Incentives / Default"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                        )
        $workflowDocuments : ArrayList()
    then
        addDocument($workflowDocuments, "Other", false);
end