package com.bizflow.drools.document.rules;

import java.util.ArrayList;
import java.util.List;
import java.util.HashMap;
import java.util.Map
import java.util.Iterator
import java.util.Arrays

import com.bizflow.ps.drools.document.model.WorkflowDocument;
import com.bizflow.ps.drools.document.model.WorkflowRuleSearch;
import com.bizflow.ps.drools.document.model.WorkflowField;

dialect "mvel"

function void addDocument(ArrayList bizflowDocument, String documentName, boolean required) {
    boolean exist = false;
    int len = bizflowDocument.size();
    for (int i=0; i < len; i++) {
        WorkflowDocument doc = (WorkflowDocument) bizflowDocument.get(i);
        if(documentName.equalsIgnoreCase(doc.getName())) {
            exist = true;
            break;
        }
    }

    if(!exist) {
        bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, required));
    }
}

function void addDocumentEx(ArrayList bizflowDocument, String documentName, String actName, String[] actNames, boolean required) {
    boolean isRequiredDocument = false;
    for (String act: actNames) {
        if (act.equals(actName)) {
            isRequiredDocument = required;
            break;
        }
    }
    bizflowDocument.add(new WorkflowDocument(bizflowDocument.size() + 1, documentName, bizflowDocument.size()+1, isRequiredDocument));
}

rule "Incentives / PCA Required Documents / New / Recruitment"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "PCARequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field3: WorkflowField ( fieldId == "requestType", fieldValue == "Recruitment" ) from $fields
         $field4: WorkflowField ( fieldId == "pcaType", fieldValue == "New" ) from $fields

        $workflowDocuments : ArrayList()

    then
        System.out.println("INCENTIVES-DOCUMENT-RULE: PCA Required Documents  / New / Recruitment >> " + $docSearch);
        addDocument($workflowDocuments, "Vacancy Announcement", true);
end

rule "Incentives / PCA Required Documents / RequireBoardCert"
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "PCARequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields
         $field4: WorkflowField ( fieldId == "requireBoardCert", fieldValue == "Yes" ) from $fields

        $workflowDocuments : ArrayList()

    then
        System.out.println("INCENTIVES-DOCUMENT-RULE: PCA Required Documents  / RequireBoardCert >> " + $docSearch);
        addDocument($workflowDocuments, "Board Certification", true);
end


rule "Incentives / PCA Required Documents "
    when
        $docSearch: WorkflowRuleSearch (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                            )
         $field1: WorkflowField ( fieldId == "rule", fieldValue == "PCARequiredDocuments" ) from $fields
         $field2: WorkflowField ( fieldId == "incentiveType", fieldValue == "PCA" ) from $fields

        $workflowDocuments : ArrayList()

    then
        System.out.println("INCENTIVES-DOCUMENT-RULE: PCA Required Documents >> " + $docSearch);
        addDocument($workflowDocuments, "Board Certification", false);
        addDocument($workflowDocuments, "Candidate Declination", false);
        addDocument($workflowDocuments, "Final Position Description Package", false);
        addDocument($workflowDocuments, "Justification Narrative", true);
        addDocument($workflowDocuments, "Medical License", true);
        addDocument($workflowDocuments, "PD Coversheet/OF-8", true);
        addDocument($workflowDocuments, "Position Description", true);
        addDocument($workflowDocuments, "Request to Fill", false);
        addDocument($workflowDocuments, "Resume/Curriculum Vitae", true);
        addDocument($workflowDocuments, "Service Agreement", false);
        addDocument($workflowDocuments, "Supporting Documents", false);
        addDocument($workflowDocuments, "Vacancy Announcement", false);
end

//------------------------------
// DEFAULT DOCUMENT
//------------------------------
rule "Incentives / Default"
    when
        $docSearch  :   WorkflowRuleSearch
                        (
                            $procName: procName
                            , $actName: actName
                            , $fields : fields
                        )
        $workflowDocuments : ArrayList()
    then
        System.out.println("INCENTIVES-DOCUMENT-RULE: Default >> " + $docSearch);
        addDocument($workflowDocuments, "Other", false);
end