--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_RW_ROLE;
--GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_DEV_ROLE;
--------------------------
-- ADMIN_CODES is turned into a view to ADMINISTRATIVE_CODE table (EHRP integration table)
--------------------------
GRANT SELECT ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ADMIN_CODES TO HHS_CMS_HR_DEV_ROLE;

GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.APPROVALS TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.APPROVALS TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.AREAS_OF_CONS TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.AREAS_OF_CONS TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.CLASSIF_STRATCON TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.CLASSIF_STRATCON TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.CLASSIFICATION TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.CLASSIFICATION TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.ELIG_QUAL TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.ELIG_QUAL TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.FLSA TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.FLSA TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.GRADE_DETAIL TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.GRADE_DETAIL TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.JOB_ANALYSIS TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.JOB_ANALYSIS TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.LOCATION TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.LOCATION TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.PD_COVERSHEET TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.PD_COVERSHEET TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.POSITION TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.POSITION TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.RECRUIT_INCENTIVES TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.RECRUIT_INCENTIVES TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.REQUEST TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.REQUEST TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.REQUEST_CONTROL TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.REQUEST_CONTROL TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.SME_INFO TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.SME_INFO TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.STRATCON_GEN TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.STRATCON_GEN TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.STRATCON_SCHED_HIST TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.STRATCON_SCHED_HIST TO HHS_CMS_HR_DEV_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.TARGET_RECRUIT TO HHS_CMS_HR_RW_ROLE;
GRANT DELETE, INSERT, SELECT, UPDATE ON HHS_CMS_HR.TARGET_RECRUIT TO HHS_CMS_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CMS_HR.GET_REQUEST_NUM TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.GET_REQUEST_NUM TO HHS_CMS_HR_DEV_ROLE;

-- INCENTIVES
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_COM TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_PCA TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_LE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM_JUST_HISTORY TO HHS_CMS_HR_RW_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_COM TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_PCA TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_LE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM_JUST_HISTORY TO HHS_CMS_HR_DEV_ROLE;

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_COM TO BIZFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_PCA TO BIZFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM TO BIZFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_LE TO BIZFLOW;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.INCENTIVES_SAM_JUST_HISTORY TO BIZFLOW;

