--------------------------------------------------------
--  File created - Thursday-March-09-2017
--------------------------------------------------------
--DROP TABLE ADMIN_CODES;
DROP TABLE APPROVALS;
DROP TABLE AREAS_OF_CONS;
DROP TABLE CLASSIFICATION;
DROP TABLE CLASSIF_STRATCON;
DROP TABLE ELIG_QUAL;
DROP TABLE FLSA;
DROP TABLE GRADE_DETAIL;
DROP TABLE JOB_ANALYSIS;
DROP TABLE LOCATION;
DROP TABLE PD_COVERSHEET;
DROP TABLE POSITION;
DROP TABLE RECRUIT_INCENTIVES;
DROP TABLE REQUEST;
DROP TABLE REQUEST_CONTROL;
DROP TABLE SME_INFO;
DROP TABLE STRATCON_GEN;
DROP TABLE STRATCON_SCHED_HIST;
DROP TABLE TARGET_RECRUIT;

--DROP SEQUENCE ADMIN_CODES_SEQ;
DROP SEQUENCE ELIG_QUAL_SEQ;
DROP SEQUENCE LOC_SEQ;
DROP SEQUENCE PD_COVERSHEET_SEQ;
DROP SEQUENCE REQUEST_SEQ;
DROP SEQUENCE STRATCON_SCHED_HIST_SEQ;









--------------------------------------------------------
--  DDL for Table ADMIN_CODES
--------------------------------------------------------
-- NOTE: ADMIN_CODES table is turned into view to
--       HHS EHRP integration table ADMINISTRATIVE_CODE table
--       which is maintained by HHS DBA team.
----------------
--
--CREATE TABLE ADMIN_CODES
--(
--	AC_ID NUMBER(*,0)
--	, AC_ADMIN_CD NVARCHAR2(8)
--	, AC_ADMIN_CD_DESCR NVARCHAR2(100)
--	, AC_ADMIN_CD_EFF_DT DATE
--	, AC_ADMIN_CD_EXP_DT DATE
--	, AC_PARENT_CD NVARCHAR2(8)
--)
--;
--
--COMMENT ON COLUMN ADMIN_CODES.AC_ID IS 'Primary key';
--COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD IS 'Unique admin code';
--COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD_DESCR IS 'Description of admin code';
--COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD_EFF_DT IS 'Date admin code goes into effect';
--COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD_EXP_DT IS 'Date the admin code expires';
--COMMENT ON COLUMN ADMIN_CODES.AC_PARENT_CD IS 'Key value of associated parent admin code';




--------------------------------------------------------
--  DDL for Table APPROVALS
--------------------------------------------------------
CREATE TABLE APPROVALS
(
	SCA_REQ_ID NUMBER(20,0)
	, SCA_SO_SIG NVARCHAR2(100)
	, SCA_SO_SIG_DT DATE
	, SCA_CLASS_SPEC_SIG NVARCHAR2(100)
	, SCA_CLASS_SPEC_SIG_DT DATE
	, SCA_STAFF_SIG NVARCHAR2(100)
	, SCA_STAFF_SIG_DT DATE
)
;

COMMENT ON COLUMN APPROVALS.SCA_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN APPROVALS.SCA_SO_SIG IS 'Selecting Official signature';
COMMENT ON COLUMN APPROVALS.SCA_SO_SIG_DT IS 'Selecting Official Signature Date';
COMMENT ON COLUMN APPROVALS.SCA_CLASS_SPEC_SIG IS 'Classification Specialist signature';
COMMENT ON COLUMN APPROVALS.SCA_CLASS_SPEC_SIG_DT IS 'Classification Specialist signature date';
COMMENT ON COLUMN APPROVALS.SCA_STAFF_SIG IS 'Staff signature';
COMMENT ON COLUMN APPROVALS.SCA_STAFF_SIG_DT IS 'Staff signature date';


--------------------------------------------------------
--  DDL for Table AREAS_OF_CONS
--------------------------------------------------------
CREATE TABLE AREAS_OF_CONS
(
	AOC_REQ_ID NUMBER(20,0)
	, AOC_30PCT_DISABLED_VETS CHAR(1 BYTE) DEFAULT '0'
	, AOC_EXPERT_CONS CHAR(1 BYTE) DEFAULT '0'
	, AOC_IPA CHAR(1 BYTE) DEFAULT '0'
	, AOC_OPER_WARFIGHTER CHAR(1 BYTE) DEFAULT '0'
	, AOC_DISABILITIES CHAR(1 BYTE) DEFAULT '0'
	, AOC_STUDENT_VOL CHAR(1 BYTE) DEFAULT '0'
	, AOC_VETS_RECRUIT_APPT CHAR(1 BYTE) DEFAULT '0'
	, AOC_VOC_REHAB_EMPL CHAR(1 BYTE) DEFAULT '0'
	, AOC_WORKFORCE_RECRUIT CHAR(1 BYTE) DEFAULT '0'
	, AOC_NON_COMP_APPL NVARCHAR2(140)
	, AOC_MIL_SPOUSES CHAR(1 BYTE) DEFAULT '0'
	, AOC_DIRECT_HIRE CHAR(1 BYTE) DEFAULT '0'
	, AOC_RE_EMPLOYMENT CHAR(1 BYTE) DEFAULT '0'
	, AOC_PATHWAYS CHAR(1 BYTE) DEFAULT '0'
	, AOC_PEACE_CORPS_VOL CHAR(1 BYTE) DEFAULT '0'
	, AOC_REINSTATEMENT CHAR(1 BYTE) DEFAULT '0'
	, AOC_SHARED_CERT CHAR(1 BYTE) DEFAULT '0'
	, AOC_DELEGATE_EXAM CHAR(1 BYTE) DEFAULT '0'
	, AOC_DH_US_CITIZENS CHAR(1 BYTE) DEFAULT '0'
	, AOC_MP_GOV_WIDE CHAR(1 BYTE) DEFAULT '0'
	, AOC_MP_HHS_ONLY CHAR(1 BYTE) DEFAULT '0'
	, AOC_MP_CMS_ONLY CHAR(1 BYTE) DEFAULT '0'
	, AOC_MP_COMP_CONS_ONLY CHAR(1 BYTE) DEFAULT '0'
	, AOC_MP_I_CTAP_VEGA CHAR(1 BYTE) DEFAULT '0'
	, AOC_NON_BARGAIN_DOC_RATIONALE NVARCHAR2(500)
)
;

COMMENT ON COLUMN AREAS_OF_CONS.AOC_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_30PCT_DISABLED_VETS IS 'Disabled vet? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_EXPERT_CONS IS 'Expert cons? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_IPA IS 'IPA? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_OPER_WARFIGHTER IS 'Oper warfighter?  1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_DISABILITIES IS 'Disabilities?  1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_STUDENT_VOL IS 'Student vol  1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_VETS_RECRUIT_APPT IS 'Vets recruit appt? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_VOC_REHAB_EMPL IS 'Voc rehab empl? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_WORKFORCE_RECRUIT IS 'Workforce recruit? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_NON_COMP_APPL IS 'Non comp appl';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MIL_SPOUSES IS 'Military spouses?  1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_DIRECT_HIRE IS 'Direct hire? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_RE_EMPLOYMENT IS 'Re-employment? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_PATHWAYS IS 'Pathways? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_PEACE_CORPS_VOL IS 'Peace corps voluntee? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_REINSTATEMENT IS 'Reinstatement? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_SHARED_CERT IS 'Shared cert? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_DELEGATE_EXAM IS 'Delegate exam? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_DH_US_CITIZENS IS 'DH us citizens? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MP_GOV_WIDE IS 'MP gov wide? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MP_HHS_ONLY IS 'MP hhs only? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MP_CMS_ONLY IS 'MP cms only? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MP_COMP_CONS_ONLY IS 'MP comp cons only? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_MP_I_CTAP_VEGA IS 'MP i ctap vega? 1=true, 0=false';
COMMENT ON COLUMN AREAS_OF_CONS.AOC_NON_BARGAIN_DOC_RATIONALE IS 'Non-bargain doc rationale';


--------------------------------------------------------
--  DDL for Table CLASSIFICATION
--------------------------------------------------------
CREATE TABLE CLASSIFICATION
(
	CLS_ID NUMBER(20,0)
	, CLS_COMP_DOCS_RECVD_DT DATE
	, CLS_BUS_REQ_DT DATE
	, CLS_BUS_RECVD_DT DATE
	, CLS_FINAL_PD_PKG_SENT_DT DATE
	, CLS_PD_PKG_UPLOAD_DT DATE
	, CLS_CANCELLED_YN RAW(1)
	, CLS_CANCEL_DT DATE
	, CLS_CANCEL_REASON NVARCHAR2(75)
	, CLS_ONLY_CANCEL_NOTIFY NVARCHAR2(200)
	, CLS_RECRUIT_CANCEL_NOTIFY NVARCHAR2(200)
	, CLS_NOTIFY_SENT_DT DATE
	, CLS_REQ_STATUS NVARCHAR2(100)
)
;



--------------------------------------------------------
--  DDL for Table CLASSIF_STRATCON
--------------------------------------------------------
CREATE TABLE CLASSIF_STRATCON
(
	CS_REQ_ID NUMBER(20,0)
	, CS_TITLE NVARCHAR2(140)
	, CS_PAY_PLAN_ID NUMBER(20,0)
	, CS_SR_ID NUMBER(20,0)
	--, CS_PERFORMANCE_LEVEL NUMBER(9,0)
	, CS_PERFORMANCE_LEVEL NVARCHAR2(2)
	, CS_SUPERVISORY NUMBER(20,0)
	, CS_AC_ID NUMBER(20,0)
	, CS_ADMIN_CD NVARCHAR2(8)
	, CS_FIN_STMT_REQ_ID NUMBER(20,0)
	, CS_SEC_ID NUMBER(20,0)
	, CS_PD_NUMBER_JOBCD_1 NVARCHAR2(10)
	, CS_CLASSIFICATION_DT_1 DATE
	--, CS_GR_ID_1 NUMBER(2,0)
	, CS_GR_ID_1 NVARCHAR2(2)
	, CS_FLSA_DETERM_ID_1 NUMBER(20,0)
	, CS_PD_NUMBER_JOBCD_2 NVARCHAR2(10)
	, CS_CLASSIFICATION_DT_2 DATE
	--, CS_GR_ID_2 NUMBER(2,0)
	, CS_GR_ID_2 NVARCHAR2(2)
	, CS_FLSA_DETERM_ID_2 NUMBER(20,0)
	, CS_PD_NUMBER_JOBCD_3 NVARCHAR2(10)
	, CS_CLASSIFICATION_DT_3 DATE
	--, CS_GR_ID_3 NUMBER(2,0)
	, CS_GR_ID_3 NVARCHAR2(2)
	, CS_FLSA_DETERM_ID_3 NUMBER(20,0)
	, CS_PD_NUMBER_JOBCD_4 NVARCHAR2(10)
	, CS_CLASSIFICATION_DT_4 DATE
	--, CS_GR_ID_4 NUMBER(2,0)
	, CS_GR_ID_4 NVARCHAR2(2)
	, CS_FLSA_DETERM_ID_4 NUMBER(20,0)
	, CS_PD_NUMBER_JOBCD_5 NVARCHAR2(10)
	, CS_CLASSIFICATION_DT_5 DATE
	--, CS_GR_ID_5 NUMBER(2,0)
	, CS_GR_ID_5 NVARCHAR2(2)
	, CS_FLSA_DETERM_ID_5 NUMBER(20,0)
)
;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_TITLE IS 'Position title';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PAY_PLAN_ID IS 'Pay Plan for Lookup table, LTYPE=PayPlan';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_SR_ID IS 'Occupational Series for Lookup table, LTYPE=OccupationalSeries';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PERFORMANCE_LEVEL IS 'ID for Lookup table, Performance Level  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_SUPERVISORY IS 'Supervisory ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_AC_ID IS 'ID for ADMIN_CODES table';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_ADMIN_CD IS 'Admin Code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FIN_STMT_REQ_ID IS 'Financial statement required ID for Lookup table, LTYPE=FinancialStatementRequired';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_SEC_ID IS 'Security code - also Position Sensitivity code for Lookup table, LTYPE=PositionSensitivity';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PD_NUMBER_JOBCD_1 IS 'Position description number or job code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_CLASSIFICATION_DT_1 IS 'Classification date';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_1 IS 'ID for Lookup table, Grade  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FLSA_DETERM_ID_1 IS 'FLSA final determination ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PD_NUMBER_JOBCD_2 IS 'Position description number or job code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_CLASSIFICATION_DT_2 IS 'Classification date 2';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_2 IS 'ID for Lookup table, Grade  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FLSA_DETERM_ID_2 IS 'FLSA final determination ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PD_NUMBER_JOBCD_3 IS 'Position description number or job code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_CLASSIFICATION_DT_3 IS 'Classification date 3';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_3 IS 'ID for Lookup table, Grade  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FLSA_DETERM_ID_3 IS 'FLSA final determination ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PD_NUMBER_JOBCD_4 IS 'Position description number or job code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_CLASSIFICATION_DT_4 IS 'Classification date 4';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_4 IS 'ID for Lookup table, Grade  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FLSA_DETERM_ID_4 IS 'FLSA final determination ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_PD_NUMBER_JOBCD_5 IS 'Position description number or job code';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_CLASSIFICATION_DT_5 IS 'Classification date 5';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_5 IS 'ID for Lookup table, Grade  LTYPE';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_FLSA_DETERM_ID_5 IS 'FLSA final determination ID';


--------------------------------------------------------
--  DDL for Table ELIG_QUAL
--------------------------------------------------------
CREATE TABLE ELIG_QUAL
(
	ELIGQUAL_ID             NUMBER(20,0),
	ADMIN_CD                NVARCHAR2(8),
	RT_ID                   NUMBER(20,0),
	AT_ID                   NUMBER(20,0),
	VT_ID                   NUMBER(20,0),
	SAT_ID                  NUMBER(20,0),
	CT_ID                   NUMBER(20,0),
	SO_ID                   NVARCHAR2(10),
	SO_TITLE                NVARCHAR2(50),
	SO_ORG                  NVARCHAR2(50),
	XO_ID                   NVARCHAR2(10),
	XO_TITLE                NVARCHAR2(50),
	XO_ORG                  NVARCHAR2(50),
	HRL_ID                  NVARCHAR2(10),
	HRL_TITLE               NVARCHAR2(100),
	HRL_ORG                 NVARCHAR2(100),
	SS_ID                   NVARCHAR2(10),
	CS_ID                   NVARCHAR2(10),
	SO_AGREE                CHAR(1 BYTE) DEFAULT '0',
	OTHER_CERT              NVARCHAR2(200),
	POS_ID                  NUMBER(20,0),     -- TODO: remove?
	CNDT_LAST_NM            NVARCHAR2(50),
	CNDT_FIRST_NM           NVARCHAR2(50),
	CNDT_MIDDLE_NM          NVARCHAR2(50),
	BGT_APR_OFM             CHAR(1 BYTE),
	SPNSR_ORG_NM            NVARCHAR2(140),
	SPNSR_ORG_FUND_PC       NUMBER(3, 0),
	JOB_REQ_NUMBER          NVARCHAR2(16),         -- TODO: remove?
	JOB_REQ_CREATE_DT       DATE,                       -- TODO: remove?
	POS_TITLE               NVARCHAR2(140),
	PAY_PLAN_ID             NUMBER(20,0),
	SERIES                  NUMBER(20,0),
	POS_DESC_NUMBER_1       NVARCHAR2(20),
	CLASSIFICATION_DT_1     DATE,
	GRADE_1                 NVARCHAR2(2),
	POS_DESC_NUMBER_2       NVARCHAR2(20),
	CLASSIFICATION_DT_2     DATE,
	GRADE_2                 NVARCHAR2(2),
	POS_DESC_NUMBER_3       NVARCHAR2(20),
	CLASSIFICATION_DT_3     DATE,
	GRADE_3                 NVARCHAR2(2),
	POS_DESC_NUMBER_4       NVARCHAR2(20),
	CLASSIFICATION_DT_4     DATE,
	GRADE_4                 NVARCHAR2(2),
	POS_DESC_NUMBER_5       NVARCHAR2(20),
	CLASSIFICATION_DT_5     DATE,
	GRADE_5                 NVARCHAR2(2),
	MED_OFFICERS_ID         NUMBER(20, 0),
	PERFORMANCE_LEVEL       NVARCHAR2(2),
	SUPERVISORY             NUMBER(20, 0),
	SKILL                   NVARCHAR2(200),
	GRADES_ADVERTISED       NVARCHAR2(100),
	LOCATION                NVARCHAR2(200),
	VACANCIES               NUMBER(9, 0),
	REPORT_SUPERVISOR       NVARCHAR2(10),
	CAN                     NVARCHAR2(8),
	VICE                    CHAR(1 BYTE) DEFAULT '0',
	VICE_NAME               NVARCHAR2(50),
	DAYS_ADVERTISED         NVARCHAR2(50),
	TA_ID                   NUMBER(20, 0),
	NTE                     NVARCHAR2(140),
	WORK_SCHED_ID           NUMBER(20, 0),
	HOURS_PER_WEEK          NVARCHAR2(50),
	DUAL_EMPLMT             NVARCHAR2(10),
	SEC_ID                  NUMBER(20, 0),
	CE_FINANCIAL_DISC       CHAR(1 BYTE) DEFAULT '0',
	CE_FINANCIAL_TYPE_ID    NUMBER(20, 0),
	CE_PE_PHYSICAL          CHAR(1 BYTE) DEFAULT '0',
	CE_DRUG_TEST            CHAR(1 BYTE) DEFAULT '0',
	CE_IMMUN                CHAR(1 BYTE) DEFAULT '0',
	CE_TRAVEL               CHAR(1 BYTE) DEFAULT '0',
	CE_TRAVEL_PER           NVARCHAR2(3),
	CE_LIC                  CHAR(1 BYTE) DEFAULT '0',
	CE_LIC_INFO             NVARCHAR2(140),
	REMARKS                 NVARCHAR2(500),
	PROC_REQ_TYPE           NUMBER(20, 0),
	RECRUIT_OFFICE_ID       NUMBER(20, 0),
	REQ_ID                  NUMBER(20, 0),
	REQ_CREATE_NOTIFY_DT    DATE,
	ASSOC_DESCR_NUMBERS     NVARCHAR2(100),
	PROMOTE_POTENTIAL       NUMBER(2, 0),
	VICE_EMPL_ID            NVARCHAR2(25),
	SR_ID                   NUMBER(20,0),
	GR_ID                   NUMBER(20,0),
	PROCID                  NUMBER(20,0),
	STATUS_ID               NUMBER(20,0),
	SC_REQUESTED            CHAR(1 BYTE) DEFAULT '0',
	SG_ID                   NUMBER(20,0),
	PD_ID                   NUMBER(20,0),
	GA_1                    CHAR(1 BYTE) DEFAULT '0',
	GA_2                    CHAR(1 BYTE) DEFAULT '0',
	GA_3                    CHAR(1 BYTE) DEFAULT '0',
	GA_4                    CHAR(1 BYTE) DEFAULT '0',
	GA_5                    CHAR(1 BYTE) DEFAULT '0',
	GA_6                    CHAR(1 BYTE) DEFAULT '0',
	GA_7                    CHAR(1 BYTE) DEFAULT '0',
	GA_8                    CHAR(1 BYTE) DEFAULT '0',
	GA_9                    CHAR(1 BYTE) DEFAULT '0',
	GA_10                   CHAR(1 BYTE) DEFAULT '0',
	GA_11                   CHAR(1 BYTE) DEFAULT '0',
	GA_12                   CHAR(1 BYTE) DEFAULT '0',
	GA_13                   CHAR(1 BYTE) DEFAULT '0',
	GA_14                   CHAR(1 BYTE) DEFAULT '0',
	GA_15                   CHAR(1 BYTE) DEFAULT '0',
	CNDT_ELIGIBLE           NVARCHAR2(10),
	INELIG_REASON           NUMBER(20,0),
	CNDT_QUALIFIED          NVARCHAR2(10),
	DISQUAL_REASON          NUMBER(20,0),
	SEL_DETERM              NUMBER(20,0),
	DCO_CERT                NVARCHAR2(10),
	DCO_NAME                NVARCHAR2(100),
	DCO_SIG                 NVARCHAR2(100),
	DCO_SIG_DT              DATE
);

COMMENT ON COLUMN ELIG_QUAL.ELIGQUAL_ID IS 'The unique ID on ELIG_QUAL';
COMMENT ON COLUMN ELIG_QUAL.ADMIN_CD IS 'Admin code';
COMMENT ON COLUMN ELIG_QUAL.RT_ID IS 'Request Type ID';
COMMENT ON COLUMN ELIG_QUAL.AT_ID IS 'Appointment Type ID';
COMMENT ON COLUMN ELIG_QUAL.VT_ID IS 'Volunteer Type ID';
COMMENT ON COLUMN ELIG_QUAL.SAT_ID IS 'Schedule A Type ID';
COMMENT ON COLUMN ELIG_QUAL.CT_ID IS 'ID to Lookup table ClassificationType';
COMMENT ON COLUMN ELIG_QUAL.SO_ID IS 'Selecting Officer ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.SO_TITLE IS 'Selecting Officer Title';
COMMENT ON COLUMN ELIG_QUAL.SO_ORG IS 'Selecting Officer''s organization';
COMMENT ON COLUMN ELIG_QUAL.XO_ID IS 'Executive Office ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.XO_TITLE IS 'Executive Officer''s title';
COMMENT ON COLUMN ELIG_QUAL.XO_ORG IS 'Executive Officer''s organization';
COMMENT ON COLUMN ELIG_QUAL.POS_ID IS 'Position ID';
COMMENT ON COLUMN ELIG_QUAL.HRL_ID IS 'HR Liaison ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.HRL_TITLE IS 'HR Liaison title';
COMMENT ON COLUMN ELIG_QUAL.HRL_ORG IS 'HR Liaison organization';
COMMENT ON COLUMN ELIG_QUAL.SS_ID IS 'Staffing Specialist ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.CS_ID IS 'Classification Specialist foriegn ID to BizFlow member table';
COMMENT ON COLUMN ELIG_QUAL.SO_AGREE IS 'Checkbox for Selecting official concurrence 1=yes, 0=no';
COMMENT ON COLUMN ELIG_QUAL.OTHER_CERT IS 'Other certification';
COMMENT ON COLUMN ELIG_QUAL.CNDT_LAST_NM IS 'Candidate/Selectee Last Name';
COMMENT ON COLUMN ELIG_QUAL.CNDT_FIRST_NM IS 'Candidate/Selectee First Name';
COMMENT ON COLUMN ELIG_QUAL.CNDT_MIDDLE_NM IS 'Candidate/Selectee Middle Name';
COMMENT ON COLUMN ELIG_QUAL.BGT_APR_OFM IS 'Budget Approved by OFM?';
COMMENT ON COLUMN ELIG_QUAL.SPNSR_ORG_NM IS 'Name of Sponsoring Organization';
COMMENT ON COLUMN ELIG_QUAL.SPNSR_ORG_FUND_PC IS 'Sponsoring Organization Funding Percentage';
COMMENT ON COLUMN ELIG_QUAL.JOB_REQ_NUMBER IS 'Generated from current date + sequence number: yyyy-mm-ddnnnn';
COMMENT ON COLUMN ELIG_QUAL.JOB_REQ_CREATE_DT IS 'Date requested was made';
COMMENT ON COLUMN ELIG_QUAL.POS_TITLE IS 'Position title';
COMMENT ON COLUMN ELIG_QUAL.PAY_PLAN_ID IS 'Pay Plan ID from the Lookup table';
COMMENT ON COLUMN ELIG_QUAL.SERIES IS 'Organizational Series - 2 characters';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_1 IS 'PD Number 1';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_1 IS 'Classification date 1';
COMMENT ON COLUMN ELIG_QUAL.GRADE_1 IS 'Grade #1';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_2 IS 'PD Number 2';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_2 IS 'Classification date 2';
COMMENT ON COLUMN ELIG_QUAL.GRADE_2 IS 'Grade #2';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_3 IS 'PD Number 3';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_3 IS 'Classification date 3';
COMMENT ON COLUMN ELIG_QUAL.GRADE_3 IS 'Grade #3';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_4 IS 'PD Number 4';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_4 IS 'Classification date 4';
COMMENT ON COLUMN ELIG_QUAL.GRADE_4 IS 'Grade #4';
COMMENT ON COLUMN ELIG_QUAL.POS_DESC_NUMBER_5 IS 'PD Number 5';
COMMENT ON COLUMN ELIG_QUAL.CLASSIFICATION_DT_5 IS 'Classification date 5';
COMMENT ON COLUMN ELIG_QUAL.GRADE_5 IS 'Grade #5';
COMMENT ON COLUMN ELIG_QUAL.MED_OFFICERS_ID IS 'Medical Officers';
COMMENT ON COLUMN ELIG_QUAL.PERFORMANCE_LEVEL IS 'Full Performance Level';
COMMENT ON COLUMN ELIG_QUAL.SUPERVISORY IS 'Supervisory';
COMMENT ON COLUMN ELIG_QUAL.SKILL IS 'Primary skill';
COMMENT ON COLUMN ELIG_QUAL.GRADES_ADVERTISED IS 'List of grades advertised';
COMMENT ON COLUMN ELIG_QUAL.LOCATION IS 'Location';
COMMENT ON COLUMN ELIG_QUAL.VACANCIES IS 'Number of vacancies';
COMMENT ON COLUMN ELIG_QUAL.REPORT_SUPERVISOR IS 'Member ID of Report Supervisor';
COMMENT ON COLUMN ELIG_QUAL.CAN IS 'Common Accounting Number(CAN)';
COMMENT ON COLUMN ELIG_QUAL.VICE IS 'Replacing a position? 1=tru 0=false';
COMMENT ON COLUMN ELIG_QUAL.VICE_NAME IS 'Name of position being replaced';
COMMENT ON COLUMN ELIG_QUAL.DAYS_ADVERTISED IS 'Number of days position should be advertised';
COMMENT ON COLUMN ELIG_QUAL.TA_ID IS 'Type of Appointment';
COMMENT ON COLUMN ELIG_QUAL.NTE IS 'Not To Exceed - temporary employment duration';
COMMENT ON COLUMN ELIG_QUAL.WORK_SCHED_ID IS 'Work schedule ID';
COMMENT ON COLUMN ELIG_QUAL.HOURS_PER_WEEK IS 'Hours per week';
COMMENT ON COLUMN ELIG_QUAL.DUAL_EMPLMT IS 'Dual Employment';
COMMENT ON COLUMN ELIG_QUAL.SEC_ID IS 'Security code - also Position Sensitivity code LTYPE=PositionSensitivity';
COMMENT ON COLUMN ELIG_QUAL.CE_FINANCIAL_DISC IS 'Financial dsclosure or Financial statement required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_FINANCIAL_TYPE_ID IS 'Financial type ID';
COMMENT ON COLUMN ELIG_QUAL.CE_PE_PHYSICAL IS 'Pre-employment physical required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_DRUG_TEST IS 'Drug test required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_IMMUN IS 'Immunization?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_TRAVEL IS 'Travel required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_TRAVEL_PER IS 'Percentage travel required: 0-100';
COMMENT ON COLUMN ELIG_QUAL.CE_LIC IS 'License required?; 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CE_LIC_INFO IS 'License information';
COMMENT ON COLUMN ELIG_QUAL.REMARKS IS 'Remarks related to the position';
COMMENT ON COLUMN ELIG_QUAL.PROC_REQ_TYPE IS 'Process request type';
COMMENT ON COLUMN ELIG_QUAL.RECRUIT_OFFICE_ID IS 'Recruiting Office ID';
COMMENT ON COLUMN ELIG_QUAL.REQ_ID IS 'Request ID';
COMMENT ON COLUMN ELIG_QUAL.REQ_CREATE_NOTIFY_DT IS 'Date of request notification';
COMMENT ON COLUMN ELIG_QUAL.ASSOC_DESCR_NUMBERS IS 'List of additional PD numbers associated with this position';
COMMENT ON COLUMN ELIG_QUAL.PROMOTE_POTENTIAL IS 'Level of promotion';
COMMENT ON COLUMN ELIG_QUAL.VICE_EMPL_ID IS 'Vice employee ID';
COMMENT ON COLUMN ELIG_QUAL.SR_ID IS 'Lookup ID for Organizational Series';
COMMENT ON COLUMN ELIG_QUAL.GR_ID IS 'Lookup value for grade';
COMMENT ON COLUMN ELIG_QUAL.PROCID IS 'Process ID. Foreign key to BIZFLOW.PROCS table';
COMMENT ON COLUMN ELIG_QUAL.STATUS_ID IS 'Status of the request for all stages';
COMMENT ON COLUMN ELIG_QUAL.SC_REQUESTED IS '';
COMMENT ON COLUMN ELIG_QUAL.SG_ID IS 'ID from the STRATCON_GEN table';
COMMENT ON COLUMN ELIG_QUAL.PD_ID IS 'ID from the PD Coversheet table';
COMMENT ON COLUMN ELIG_QUAL.GA_1 IS 'Grade 1 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_2 IS 'Grade 2 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_3 IS 'Grade 3 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_4 IS 'Grade 4 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_5 IS 'Grade 5 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_6 IS 'Grade 6 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_7 IS 'Grade 7 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_8 IS 'Grade 8 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_9 IS 'Grade 9 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_10 IS 'Grade 10 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_11 IS 'Grade 11 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_12 IS 'Grade 12 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_13 IS 'Grade 13 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_14 IS 'Grade 14 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.GA_15 IS 'Grade 15 advertised? 1=true 0=false';
COMMENT ON COLUMN ELIG_QUAL.CNDT_ELIGIBLE IS 'Candidate/selectee eligible? Yes/No';
COMMENT ON COLUMN ELIG_QUAL.INELIG_REASON IS 'Reason for Ineligibility';
COMMENT ON COLUMN ELIG_QUAL.CNDT_QUALIFIED IS 'Candidate/selectee qualified? Yes/No';
COMMENT ON COLUMN ELIG_QUAL.DISQUAL_REASON IS 'Reason for Disqualification';
COMMENT ON COLUMN ELIG_QUAL.SEL_DETERM IS 'Selection Determination: Selected? 1=true, 0=false';
COMMENT ON COLUMN ELIG_QUAL.DCO_CERT IS 'DCO approved? Yes/No';
COMMENT ON COLUMN ELIG_QUAL.DCO_NAME IS 'DCO name';
COMMENT ON COLUMN ELIG_QUAL.DCO_SIG IS 'DCO signature';
COMMENT ON COLUMN ELIG_QUAL.DCO_SIG_DT IS 'DCO signature date';


--------------------------------------------------------
--  DDL for Table FLSA
--------------------------------------------------------
CREATE TABLE FLSA
(
	FLSA_PD_ID NUMBER(20,0)
	, FLSA_EX_EXEC CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_ADMIN CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_PROF_LEARNED CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_PROF_CREATIVE CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_PROF_COMPUTER CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_LAW_ENFORC CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_FOREIGN CHAR(1 BYTE) DEFAULT '0'
	, FLSA_EX_REMARKS NVARCHAR2(140)
	, FLSA_NONEX_SALARY CHAR(1 BYTE) DEFAULT '0'
	, FLSA_NONEX_EQUIP_OPER CHAR(1 BYTE) DEFAULT '0'
	, FLSA_NONEX_TECHN CHAR(1 BYTE) DEFAULT '0'
	, FLSA_NONEX_FED_WAGE_SYS CHAR(1 BYTE) DEFAULT '0'
	, FLSA_NONEX_REMARKS NVARCHAR2(140)
	, FLSA_HR_SPECIALIST_NAME NVARCHAR2(50)
	, FLSA_APPROVAL_DT DATE
)
;

COMMENT ON COLUMN FLSA.FLSA_PD_ID IS 'Primary key as well as foreign key to PD_COVERSHEET table';
COMMENT ON COLUMN FLSA.FLSA_EX_EXEC IS 'Primary duty of the position is management or supervision; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_ADMIN IS 'Primary duty is performance of office or non-manual work directly related to the management or general business functions; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_PROF_LEARNED IS 'occupations that have a recognized professional status; entrance into these professions requires a prolonged course of specialized intellectual instruction; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_PROF_CREATIVE IS 'Exemption depends upon the extent of invention, imagination, originality or talent of the employee; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_PROF_COMPUTER IS 'Salary based exemption applies to any computer professional compensated on an hourly bases at a rate of  given basic pay per hour and above; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_LAW_ENFORC IS 'Special exemption/exclusion applies to all law enforcement agents receiving availability pay; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_FOREIGN IS 'Exempt area means any foreign country, or any territory under the jurisdiction of the United States other than listed exceptions; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_EX_REMARKS IS 'Exempt Remarks';
COMMENT ON COLUMN FLSA.FLSA_NONEX_SALARY IS 'Checked if annual salary under given amount; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_NONEX_EQUIP_OPER IS 'Position is non-supervisory and engaged in equipment operation, or is a protective or clerical occupation; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_NONEX_TECHN IS 'Position involves technician work properly classified at the GS-09 level or below; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_NONEX_FED_WAGE_SYS IS 'Position is nonsupervisory in the Federal Wage System or other comparable wage system; 1=true 0=false';
COMMENT ON COLUMN FLSA.FLSA_NONEX_REMARKS IS 'Non-Exempt Remarks';
COMMENT ON COLUMN FLSA.FLSA_HR_SPECIALIST_NAME IS 'HR Specialist name';
COMMENT ON COLUMN FLSA.FLSA_APPROVAL_DT IS 'Approval date';


--------------------------------------------------------
--  DDL for Table GRADE_DETAIL
--------------------------------------------------------
CREATE TABLE GRADE_DETAIL
(
	GD_ID NUMBER(*,0)
	, GD_PAYPLAN_CD NVARCHAR2(2)
	, GD_GRADE NUMBER(1,0)
	, GD_MIN NUMBER(2,0)
	, GD_MAX NUMBER(2,0)
	, GD_RESTRICT NUMBER(2,0)
	, GD_FPL NUMBER(1,0)
)
;

COMMENT ON COLUMN GRADE_DETAIL.GD_ID IS 'Primary key';
COMMENT ON COLUMN GRADE_DETAIL.GD_PAYPLAN_CD IS 'Pay plan';
COMMENT ON COLUMN GRADE_DETAIL.GD_GRADE IS 'Grade';
COMMENT ON COLUMN GRADE_DETAIL.GD_MIN IS 'Minimum grade';
COMMENT ON COLUMN GRADE_DETAIL.GD_MAX IS 'Maximum grade';
COMMENT ON COLUMN GRADE_DETAIL.GD_RESTRICT IS 'Restriction';
COMMENT ON COLUMN GRADE_DETAIL.GD_FPL IS 'Full Performance Level';


--------------------------------------------------------
--  DDL for Table JOB_ANALYSIS
--------------------------------------------------------
CREATE TABLE JOB_ANALYSIS
(
	JA_REQ_ID NUMBER(20,0)
	, JA_REVIEWED_PD CHAR(1 BYTE) DEFAULT '0'
	, JA_MAJ_COMP CHAR(1 BYTE) DEFAULT '0'
	, JA_TASK_ITEMS CHAR(1 BYTE) DEFAULT '0'
	, JA_SEL_FACTOR_REQ CHAR(1 BYTE) DEFAULT '0'
	, JA_SEL_FACTOR_JUST NVARCHAR2(100)
	, JA_QUAL_RANK_REQ CHAR(1 BYTE) DEFAULT '0'
	, JA_QUAL_RANK_JUST NVARCHAR2(100)
	, JA_RESPONSES_REQ CHAR(1 BYTE) DEFAULT '0'
	, JA_TYPE_YES_NO CHAR(1 BYTE) DEFAULT '0'
	, JA_TYPE_REQ_DEFAULT CHAR(1 BYTE) DEFAULT '0'
	, JA_TYPE_KNOWL_SCALE CHAR(1 BYTE) DEFAULT '0'
)
;

COMMENT ON COLUMN JOB_ANALYSIS.JA_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN JOB_ANALYSIS.JA_REVIEWED_PD IS 'PD reviewed? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_MAJ_COMP IS 'Major Comp? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_TASK_ITEMS IS 'Task items? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_SEL_FACTOR_REQ IS 'Selection factor req? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_SEL_FACTOR_JUST IS 'Selection factor justification';
COMMENT ON COLUMN JOB_ANALYSIS.JA_QUAL_RANK_REQ IS 'Qualification rank req? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_QUAL_RANK_JUST IS 'Qualification rank justification';
COMMENT ON COLUMN JOB_ANALYSIS.JA_RESPONSES_REQ IS 'Responses req? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_TYPE_YES_NO IS 'Multiple types of assessment question responses requested?1=yes, 0=no';
COMMENT ON COLUMN JOB_ANALYSIS.JA_TYPE_REQ_DEFAULT IS 'Type request default? 1=true 0=false';
COMMENT ON COLUMN JOB_ANALYSIS.JA_TYPE_KNOWL_SCALE IS 'Type knowledge scale? 1=true 0=false';


-------------------------------------------------------
--  DDL for Table LOCATION
--------------------------------------------------------
CREATE TABLE LOCATION
(
	LOC_ID NUMBER(20,0)
	, LOC_GEO_CODE NVARCHAR2(12)
	, LOC_EFF_STATUS CHAR(1 BYTE) DEFAULT '0'
	, LOC_EFF_DT DATE
	, LOC_COUNTRY NVARCHAR2(30)
	, LOC_STATE NVARCHAR2(2)
	, LOC_CITY NVARCHAR2(50)
)
;

COMMENT ON COLUMN LOCATION.LOC_ID IS 'Primary key';
COMMENT ON COLUMN LOCATION.LOC_GEO_CODE IS 'Unique GEO code for this location';
COMMENT ON COLUMN LOCATION.LOC_EFF_STATUS IS 'Is code in effect? 1=true, 0=false';
COMMENT ON COLUMN LOCATION.LOC_EFF_DT IS 'Date the code becomes effective';
COMMENT ON COLUMN LOCATION.LOC_COUNTRY IS 'Country name';
COMMENT ON COLUMN LOCATION.LOC_STATE IS 'State 2 character abbreviation';
COMMENT ON COLUMN LOCATION.LOC_CITY IS 'City name';


--------------------------------------------------------
--  DDL for Table PD_COVERSHEET
--------------------------------------------------------
CREATE TABLE PD_COVERSHEET
(
	PD_ID                   NUMBER(20,0)
	, PD_REQ_ID             NUMBER(20,0)
	, PD_PROCID             NUMBER(20,0)
	, PD_ORG_POS_TITLE      NVARCHAR2(140)
	, PD_NUMBER_JOBCD       NVARCHAR2(10)
	, PD_EMPLOYING_OFFICE   NUMBER(20,0)
	, PD_SUBJECT_IA         CHAR(1 BYTE) DEFAULT '0'
	, PD_ORGANIZATION       NVARCHAR2(10)
	, PD_SUB_ORG_1          NVARCHAR2(10)
	, PD_SUB_ORG_2          NVARCHAR2(10)
	, PD_SUB_ORG_3          NVARCHAR2(10)
	, PD_SUB_ORG_4          NVARCHAR2(10)
	, PD_SUB_ORG_5          NVARCHAR2(10)
	, PD_SCOPE              NVARCHAR2(10)
	, PD_PCA                CHAR(1 BYTE) DEFAULT '0'
	, PD_PDP                CHAR(1 BYTE) DEFAULT '0'
	, PD_FTT                CHAR(1 BYTE) DEFAULT '0'
	, PD_OUTSTATION         CHAR(1 BYTE) DEFAULT '0'
	, PD_INCUMBENCY         CHAR(1 BYTE) DEFAULT '0'
	, PD_POSITION_IS        NUMBER(20,0)
	, PD_CLS_STANDARDS      NVARCHAR2(100)
	, PD_ACQ_CODE           NUMBER(20,0)
	, PD_CYB_SEC_CD         NUMBER(20,0)
	, PD_COMPET_LVL_CD      NVARCHAR2(140)
	, PD_BUS_CD             NUMBER(20,0)
	, BYPASS_DWC_FL         NVARCHAR2(10)
	, PD_SUPV_CERT          CHAR(1 BYTE) DEFAULT '0'
	, PD_SUPV_NAME          NVARCHAR2(100)
	, PD_SUPV_TITLE         NVARCHAR2(140)
	, PD_SUPV_SIG           NVARCHAR2(10)
	, PD_SUPV_SIG_DT        DATE
	, PD_CLS_SPEC_CERT      CHAR(1 BYTE) DEFAULT '0'
	, PD_CLS_SPEC_NAME      NVARCHAR2(100)
	, PD_CLS_SPEC_TITLE     NVARCHAR2(140)
	, PD_CLS_SPEC_SIG       NVARCHAR2(10)
	, PD_CLS_SPEC_DT        DATE
	, PD_REMARKS            NVARCHAR2(500)
)
;

COMMENT ON COLUMN PD_COVERSHEET.PD_ID IS 'Primary key';
COMMENT ON COLUMN PD_COVERSHEET.PD_REQ_ID IS 'Foreign key to REQUEST table';
COMMENT ON COLUMN PD_COVERSHEET.PD_PROCID IS 'Process ID.  Foreign key to BIZFLOW.PROCS table';
COMMENT ON COLUMN PD_COVERSHEET.PD_ORG_POS_TITLE IS 'Entered if not the same as position title ';
COMMENT ON COLUMN PD_COVERSHEET.PD_NUMBER_JOBCD IS 'This field is called PD Number or Job Code';
COMMENT ON COLUMN PD_COVERSHEET.PD_EMPLOYING_OFFICE IS 'Value stored on Lookup table under LTYPE EmployingOffice';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUBJECT_IA IS 'Subject to Identical Additional? 1=true 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_ORGANIZATION IS 'ID to Admin_Codes table for HHS';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUB_ORG_1 IS 'ID to value on Admin Code table';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUB_ORG_2 IS 'ID to value on Admin Code table';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUB_ORG_3 IS 'ID to value on Admin Code table';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUB_ORG_4 IS 'ID to value on Admin Code table';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUB_ORG_5 IS 'ID to value on Admin Code table';
COMMENT ON COLUMN PD_COVERSHEET.PD_SCOPE IS 'Component-wide? Yes or No';
COMMENT ON COLUMN PD_COVERSHEET.PD_PCA IS 'Physicians Comparability Allowance option? 1=true, 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_PDP IS 'Physician and Dentist Pay option? 1=true, 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_FTT IS 'Full-Time Telework? 1=true, 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_OUTSTATION IS 'Position is in remote location? 1=true, 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_INCUMBENCY IS 'Incumbency only? 1=true, 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_POSITION_IS IS 'Has values on Lookup table';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_STANDARDS IS 'Standards used';
COMMENT ON COLUMN PD_COVERSHEET.PD_ACQ_CODE IS 'Has values on TBL_LOOKUP table';
COMMENT ON COLUMN PD_COVERSHEET.PD_CYB_SEC_CD IS 'Cyber Security - has values on Lookup table';
COMMENT ON COLUMN PD_COVERSHEET.PD_COMPET_LVL_CD IS 'Competetive level';
COMMENT ON COLUMN PD_COVERSHEET.PD_BUS_CD IS 'BUS Code Value on Lookup table';
COMMENT ON COLUMN PD_COVERSHEET.BYPASS_DWC_FL IS 'Bypass DWC flag. Yes, No';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUPV_CERT IS 'Checkbox 1=checked 0=unchecked to certify concurance from the Selecting Officer';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUPV_NAME IS 'Supervisor name';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUPV_TITLE IS 'Supervisor title';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUPV_SIG IS 'Supervisor signature (member ID)';
COMMENT ON COLUMN PD_COVERSHEET.PD_SUPV_SIG_DT IS 'Generated when Selecting Officer clicks on the SUPV CERT checkbox';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_SPEC_CERT IS 'Specialist certification? 1=true 0=false';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_SPEC_NAME IS 'Classification Specialist name';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_SPEC_TITLE IS 'Classification Specialist title';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_SPEC_SIG IS 'Classification Specialist signature (member ID)';
COMMENT ON COLUMN PD_COVERSHEET.PD_CLS_SPEC_DT IS 'Classification Specialist signature date';
COMMENT ON COLUMN PD_COVERSHEET.PD_REMARKS IS 'Remarks';


--------------------------------------------------------
--  DDL for Table POSITION
--------------------------------------------------------
CREATE TABLE POSITION
(
	POS_REQ_ID NUMBER(20,0) NOT NULL
	, POS_REQ_CREATE_NOTIFY_DT DATE
	, POS_CNDT_LAST_NM NVARCHAR2(50)
	, POS_CNDT_FIRST_NM NVARCHAR2(50)
	, POS_CNDT_MIDDLE_NM NVARCHAR2(50)
	, POS_BGT_APR_OFM CHAR(1)
	, POS_SPNSR_ORG_NM NVARCHAR2(140)
	, POS_SPNSR_ORG_FUND_PC NUMBER(3,0)
	, POS_TITLE NVARCHAR2(140)
	, POS_PAY_PLAN_ID NUMBER(20,0)
	, POS_SERIES NVARCHAR2(140)    -- TODO: numeric?
	, POS_DESC_NUMBER_1 NVARCHAR2(20)
	, POS_CLASSIFICATION_DT_1 DATE
	--, POS_GRADE_1 NUMBER(2,0)
	, POS_GRADE_1 NVARCHAR2(2)
	, POS_DESC_NUMBER_2 NVARCHAR2(20)
	, POS_CLASSIFICATION_DT_2 DATE
	--, POS_GRADE_2 NUMBER(2,0)
	, POS_GRADE_2 NVARCHAR2(2)
	, POS_DESC_NUMBER_3 NVARCHAR2(20)
	, POS_CLASSIFICATION_DT_3 DATE
	--, POS_GRADE_3 NUMBER(2,0)
	, POS_GRADE_3 NVARCHAR2(2)
	, POS_DESC_NUMBER_4 NVARCHAR2(20)
	, POS_CLASSIFICATION_DT_4 DATE
	--, POS_GRADE_4 NUMBER(2,0)
	, POS_GRADE_4 NVARCHAR2(2)
	, POS_DESC_NUMBER_5 NVARCHAR2(20)
	, POS_CLASSIFICATION_DT_5 DATE
	--, POS_GRADE_5 NUMBER(2,0)
	, POS_GRADE_5 NVARCHAR2(2)
	, POS_MED_OFFICERS_ID NUMBER(20,0)
	--, POS_PERFORMANCE_LEVEL NVARCHAR2(50)
	, POS_PERFORMANCE_LEVEL NVARCHAR2(2)
	, POS_SUPERVISORY NVARCHAR2(50)
	, POS_SKILL NVARCHAR2(200)
	, POS_GRADES_ADVERTISED NVARCHAR2(100)
	, POS_LOCATION NVARCHAR2(200)
	, POS_VACANCIES NUMBER(9,0)
	, POS_REPORT_SUPERVISOR NVARCHAR2(10)
	, POS_PROMOTE_POTENTIAL NUMBER(2,0)
	, POS_CAN NVARCHAR2(8)
	, POS_VICE CHAR(1 BYTE) DEFAULT '0'
	, POS_VICE_NAME NVARCHAR2(50)
	, POS_DAYS_ADVERTISED NVARCHAR2(50)
	, POS_AT_ID NUMBER(20,0)
	, POS_NTE NVARCHAR2(140)
	, POS_WORK_SCHED_ID NUMBER(20,0)
	, POS_HOURS_PER_WEEK NVARCHAR2(50)
	, POS_DUAL_EMPLMT NVARCHAR2(10)
	, POS_SEC_ID NUMBER(20,0)
	, POS_CE_FINANCIAL_DISC CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_FINANCIAL_TYPE_ID NUMBER(20,0)
	, POS_CE_PE_PHYSICAL CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_DRUG_TEST CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_IMMUN CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_TRAVEL CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_TRAVEL_PER NVARCHAR2(3)
	, POS_CE_LIC CHAR(1 BYTE) DEFAULT '0'
	, POS_CE_LIC_INFO NVARCHAR2(140)
	, POS_REMARKS NVARCHAR2(500)
	, POS_PROC_REQ_TYPE NUMBER(20,0)
	, POS_RECRUIT_OFFICE_ID NUMBER(20,0)
	, POS_SO_ID NUMBER(9,0)
	, POS_ASSOC_DESCR_NUMBERS NVARCHAR2(100)
	, POS_VICE_EMPL_ID NVARCHAR2(25)
	, POS_SR_ID NUMBER(20,0)
	, POS_GR_ID NUMBER(20,0)
	, POS_AC_ID NUMBER(20,0)
	, POS_GA_1 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_2 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_3 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_4 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_5 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_6 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_7 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_8 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_9 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_10 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_11 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_12 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_13 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_14 CHAR(1 BYTE) DEFAULT '0'
	, POS_GA_15 CHAR(1 BYTE) DEFAULT '0'
)
;

COMMENT ON COLUMN POSITION.POS_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN POSITION.POS_REQ_CREATE_NOTIFY_DT IS 'Date of request notification';
COMMENT ON COLUMN POSITION.POS_CNDT_LAST_NM IS 'Candidate/Selectee Last Name';
COMMENT ON COLUMN POSITION.POS_CNDT_FIRST_NM IS 'Candidate/Selectee First Name';
COMMENT ON COLUMN POSITION.POS_CNDT_MIDDLE_NM IS 'Candidate/Selectee Middle Name';
COMMENT ON COLUMN POSITION.POS_BGT_APR_OFM IS 'Budget Approved by OFM?';
COMMENT ON COLUMN POSITION.POS_SPNSR_ORG_NM IS 'Name of Sponsoring Organization';
COMMENT ON COLUMN POSITION.POS_SPNSR_ORG_FUND_PC IS 'Sponsoring Organization Funding Percentage';
COMMENT ON COLUMN POSITION.POS_TITLE IS 'Position title';
COMMENT ON COLUMN POSITION.POS_PAY_PLAN_ID IS 'Pay Plan ID from the Lookup table';
COMMENT ON COLUMN POSITION.POS_SERIES IS 'Organizational Series - 2 characters';
COMMENT ON COLUMN POSITION.POS_DESC_NUMBER_1 IS 'PD Number 1';
COMMENT ON COLUMN POSITION.POS_CLASSIFICATION_DT_1 IS 'Classification date 1';
COMMENT ON COLUMN POSITION.POS_GRADE_1 IS 'Grade #1';
COMMENT ON COLUMN POSITION.POS_DESC_NUMBER_2 IS 'PD Number 2';
COMMENT ON COLUMN POSITION.POS_CLASSIFICATION_DT_2 IS 'Classification date 2';
COMMENT ON COLUMN POSITION.POS_GRADE_2 IS 'Grade #2';
COMMENT ON COLUMN POSITION.POS_DESC_NUMBER_3 IS 'PD Number 3';
COMMENT ON COLUMN POSITION.POS_CLASSIFICATION_DT_3 IS 'Classification date 3';
COMMENT ON COLUMN POSITION.POS_GRADE_3 IS 'Grade #3';
COMMENT ON COLUMN POSITION.POS_DESC_NUMBER_4 IS 'PD Number 4';
COMMENT ON COLUMN POSITION.POS_CLASSIFICATION_DT_4 IS 'Classification date 4';
COMMENT ON COLUMN POSITION.POS_GRADE_4 IS 'Grade #4';
COMMENT ON COLUMN POSITION.POS_DESC_NUMBER_5 IS 'PD Number 5';
COMMENT ON COLUMN POSITION.POS_CLASSIFICATION_DT_5 IS 'Classification date 5';
COMMENT ON COLUMN POSITION.POS_GRADE_5 IS 'Grade #5';
COMMENT ON COLUMN POSITION.POS_MED_OFFICERS_ID IS 'Medical Officers';
COMMENT ON COLUMN POSITION.POS_PERFORMANCE_LEVEL IS 'Full Performance Level';
COMMENT ON COLUMN POSITION.POS_SUPERVISORY IS 'Supervisory';
COMMENT ON COLUMN POSITION.POS_SKILL IS 'Primary skill';
COMMENT ON COLUMN POSITION.POS_GRADES_ADVERTISED IS 'List of grades advertised';
COMMENT ON COLUMN POSITION.POS_LOCATION IS 'Location';
COMMENT ON COLUMN POSITION.POS_VACANCIES IS 'Number of vacancies';
COMMENT ON COLUMN POSITION.POS_REPORT_SUPERVISOR IS 'Member ID of Report Supervisor';
COMMENT ON COLUMN POSITION.POS_PROMOTE_POTENTIAL IS 'Level of promotion';
COMMENT ON COLUMN POSITION.POS_CAN IS 'Common Accounting Number(CAN)';
COMMENT ON COLUMN POSITION.POS_VICE IS 'Replacing a position? 1=tru 0=false';
COMMENT ON COLUMN POSITION.POS_VICE_NAME IS 'Name of position being replaced';
COMMENT ON COLUMN POSITION.POS_DAYS_ADVERTISED IS 'Number of days position should be advertised';
COMMENT ON COLUMN POSITION.POS_AT_ID IS 'Lookup ID for the Admin Type';
COMMENT ON COLUMN POSITION.POS_NTE IS 'Not To Exceed - temporary employment duration';
COMMENT ON COLUMN POSITION.POS_WORK_SCHED_ID IS 'Work schedule ID';
COMMENT ON COLUMN POSITION.POS_HOURS_PER_WEEK IS 'Hours per week';
COMMENT ON COLUMN POSITION.POS_DUAL_EMPLMT IS 'Dual Employment';
COMMENT ON COLUMN POSITION.POS_SEC_ID IS 'Security code - also Position Sensitivity code LTYPE=PositionSensitivity';
COMMENT ON COLUMN POSITION.POS_CE_FINANCIAL_DISC IS 'Financial dsclosure or Financial statement required?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_FINANCIAL_TYPE_ID IS 'Financial type ID';
COMMENT ON COLUMN POSITION.POS_CE_PE_PHYSICAL IS 'Pre-employment physical required?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_DRUG_TEST IS 'Drug test required?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_IMMUN IS 'Immunization?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_TRAVEL IS 'Travel required?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_TRAVEL_PER IS 'Percentage travel required: 0-100';
COMMENT ON COLUMN POSITION.POS_CE_LIC IS 'License required?; 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_CE_LIC_INFO IS 'License information';
COMMENT ON COLUMN POSITION.POS_REMARKS IS 'Remarks related to the position';
COMMENT ON COLUMN POSITION.POS_PROC_REQ_TYPE IS 'Process request type';
COMMENT ON COLUMN POSITION.POS_RECRUIT_OFFICE_ID IS 'Recruiting Office ID';
COMMENT ON COLUMN POSITION.POS_SO_ID IS 'Selecting Officer ID ';
COMMENT ON COLUMN POSITION.POS_ASSOC_DESCR_NUMBERS IS 'List of additional PD numbers associated with this position';
COMMENT ON COLUMN POSITION.POS_VICE_EMPL_ID IS 'Vice employee ID';
COMMENT ON COLUMN POSITION.POS_SR_ID IS 'Lookup ID for Organizational Series';
COMMENT ON COLUMN POSITION.POS_GR_ID IS 'Lookup value for grade';
COMMENT ON COLUMN POSITION.POS_AC_ID IS 'ID from the Admin Code table';
COMMENT ON COLUMN POSITION.POS_GA_1 IS 'Grade 1 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_2 IS 'Grade 2 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_3 IS 'Grade 3 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_4 IS 'Grade 4 advertised?1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_5 IS 'Grade 5 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_6 IS 'Grade 6 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_7 IS 'Grade 7 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_8 IS 'Grade 8 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_9 IS 'Grade 9 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_10 IS 'Grade 10 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_11 IS 'Grade 11 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_12 IS 'Grade 12 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_13 IS 'Grade 13 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_14 IS 'Grade 14 advertised? 1=true 0=false';
COMMENT ON COLUMN POSITION.POS_GA_15 IS 'Grade 15 advertised? 1=true 0=false';


--------------------------------------------------------
--  DDL for Table RECRUIT_INCENTIVES
--------------------------------------------------------
CREATE TABLE RECRUIT_INCENTIVES
(
	RI_REQ_ID NUMBER(20,0)
	, RI_OA_APRV_ITEM NVARCHAR2(20)
	, RI_MOVING_EXP_AUTH CHAR(1 BYTE) DEFAULT '0'
)
;

COMMENT ON COLUMN RECRUIT_INCENTIVES.RI_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN RECRUIT_INCENTIVES.RI_OA_APRV_ITEM IS 'Office of Administrator approved item';
COMMENT ON COLUMN RECRUIT_INCENTIVES.RI_MOVING_EXP_AUTH IS 'Moving expense authorized? 1=true 0=false';


--------------------------------------------------------
--  DDL for Table REQUEST
--------------------------------------------------------
CREATE TABLE REQUEST
(
	REQ_ID NUMBER(20,0)
	, REQ_JOB_REQ_NUMBER NVARCHAR2(16)
	, REQ_JOB_REQ_CREATE_DT DATE
	, REQ_STATUS_ID NUMBER(20,0)
	, REQ_CANCEL_DT DATE
	, REQ_CANCEL_REASON NVARCHAR2(140)
)
;

COMMENT ON COLUMN REQUEST.REQ_ID IS 'Primary key';
COMMENT ON COLUMN REQUEST.REQ_JOB_REQ_NUMBER IS 'Generated from current date + sequence number: yyyy-mm-ddnnnn ';
COMMENT ON COLUMN REQUEST.REQ_JOB_REQ_CREATE_DT IS 'Date requested was made';
COMMENT ON COLUMN REQUEST.REQ_STATUS_ID IS 'Status of the request for all stages';
COMMENT ON COLUMN REQUEST.REQ_CANCEL_DT IS 'Date the request was cancelled';
COMMENT ON COLUMN REQUEST.REQ_CANCEL_REASON IS 'Reason the request was cancelled';


-------------------------------------------------------
--  DDL for Table REQUEST_CONTROL
--------------------------------------------------------
CREATE TABLE REQUEST_CONTROL
(
	RC_DATE DATE
	, RC_SEQ NUMBER(4,0) DEFAULT 0001
	, RC_REQUEST_NUM VARCHAR2(13 BYTE)
)
;


--------------------------------------------------------
--  DDL for Table SME_INFO
--------------------------------------------------------
CREATE TABLE SME_INFO
(
	SME_REQ_ID NUMBER(20,0)
	, SME_FOR_JOB_ANALYSIS CHAR(1 BYTE) DEFAULT '0'
	, SME_NAME_JA NVARCHAR2(100)
	, SME_EMAIL_JA NVARCHAR2(100)
	, SME_FOR_QUALIFICATION CHAR(1 BYTE) DEFAULT '0'
	, SME_NAME_QUAL_1 NVARCHAR2(100)
	, SME_EMAIL_QUAL_1 NVARCHAR2(100)
	, SME_NAME_QUAL_2 NVARCHAR2(100)
	, SME_EMAIL_QUAL_2 NVARCHAR2(100)
)
;

COMMENT ON COLUMN SME_INFO.SME_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN SME_INFO.SME_FOR_JOB_ANALYSIS IS 'SME used for job analysis? 1=true 0=false';
COMMENT ON COLUMN SME_INFO.SME_NAME_JA IS 'Name of job analysis';
COMMENT ON COLUMN SME_INFO.SME_EMAIL_JA IS 'Email contact for job analysis';
COMMENT ON COLUMN SME_INFO.SME_FOR_QUALIFICATION IS 'SME used for qualification? 1=true 0=false';
COMMENT ON COLUMN SME_INFO.SME_NAME_QUAL_1 IS 'First name for qualification';
COMMENT ON COLUMN SME_INFO.SME_EMAIL_QUAL_1 IS 'First email for qualification';
COMMENT ON COLUMN SME_INFO.SME_NAME_QUAL_2 IS 'Second name for qualification';
COMMENT ON COLUMN SME_INFO.SME_EMAIL_QUAL_2 IS 'Second email contact for qualification';


--------------------------------------------------------
--  DDL for Table STRATCON_GEN
--------------------------------------------------------
CREATE TABLE STRATCON_GEN
(
	SG_REQ_ID NUMBER(20,0)
	, SG_PROCID NUMBER(20,0)
	, SG_AC_ID NUMBER(20,0)
	, SG_ADMIN_CD NVARCHAR2(8)
	, SG_RT_ID NUMBER(20,0)
	, SG_CT_ID NUMBER(20,0)
	, SG_AT_ID NUMBER(20,0)
	, SG_VT_ID NUMBER(20,0)
	, SG_SAT_ID NUMBER(20,0)
	, SG_SO_ID NVARCHAR2(10)
	, SG_SO_TITLE NVARCHAR2(50)
	, SG_SO_ORG NVARCHAR2(50)
	, SG_XO_ID NVARCHAR2(10)
	, SG_XO_TITLE NVARCHAR2(50)
	, SG_XO_ORG NVARCHAR2(50)
	, SG_HRL_ID NVARCHAR2(10)
	, SG_HRL_TITLE NVARCHAR2(100)
	, SG_HRL_ORG NVARCHAR2(100)
	, SG_SS_ID NVARCHAR2(10)
	, SG_CS_ID NVARCHAR2(10)
	, SG_SO_AGREE CHAR(1 BYTE) DEFAULT '0'
	, SG_ACCESS_CERT NVARCHAR2(200)
	, SG_OTHER_CERT NVARCHAR2(200)
)
;

COMMENT ON COLUMN STRATCON_GEN.SG_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN STRATCON_GEN.SG_PROCID IS 'Process ID.  Foreign key to BIZFLOW.PROCS table';
COMMENT ON COLUMN STRATCON_GEN.SG_AC_ID IS 'ID for Admin Code table';
COMMENT ON COLUMN STRATCON_GEN.SG_ADMIN_CD IS 'Admin Code';
COMMENT ON COLUMN STRATCON_GEN.SG_RT_ID IS 'ID to RECRUIT_TARGET table';
COMMENT ON COLUMN STRATCON_GEN.SG_CT_ID IS 'ID to Lookup table ClassificationType';
COMMENT ON COLUMN STRATCON_GEN.SG_AT_ID IS 'Appointment Type ID';
COMMENT ON COLUMN STRATCON_GEN.SG_VT_ID IS 'Volunteer Type ID';
COMMENT ON COLUMN STRATCON_GEN.SG_SAT_ID IS 'Schedule A Type ID';
COMMENT ON COLUMN STRATCON_GEN.SG_SO_ID IS 'Selecting Officer ID to BizFlow member table';
COMMENT ON COLUMN STRATCON_GEN.SG_SO_TITLE IS 'Selecting Officer Title';
COMMENT ON COLUMN STRATCON_GEN.SG_SO_ORG IS 'Selecting Officer''s organization';
COMMENT ON COLUMN STRATCON_GEN.SG_XO_ID IS 'Executive Office ID to BizFlow member table';
COMMENT ON COLUMN STRATCON_GEN.SG_XO_TITLE IS 'Executive Officer''s title';
COMMENT ON COLUMN STRATCON_GEN.SG_XO_ORG IS 'Executive Officer''s organization';
COMMENT ON COLUMN STRATCON_GEN.SG_HRL_ID IS 'HR Liaison ID to BizFlow member table';
COMMENT ON COLUMN STRATCON_GEN.SG_HRL_TITLE IS 'HR Liaison title';
COMMENT ON COLUMN STRATCON_GEN.SG_HRL_ORG IS 'HR Liaison organization';
COMMENT ON COLUMN STRATCON_GEN.SG_SS_ID IS 'Staffing Specialist ID to BizFlow member table';
COMMENT ON COLUMN STRATCON_GEN.SG_CS_ID IS 'Classification Specialist foriegn ID to BizFlow member table';
COMMENT ON COLUMN STRATCON_GEN.SG_SO_AGREE IS 'Checkbox for Selecting official concurrence 1=yes, 0=no';
COMMENT ON COLUMN STRATCON_GEN.SG_ACCESS_CERT IS 'Comment supporting certificate';
COMMENT ON COLUMN STRATCON_GEN.SG_OTHER_CERT IS 'Other certification';


--------------------------------------------------------
--  DDL for Table STRATCON_SCHED_HIST
--------------------------------------------------------
CREATE TABLE STRATCON_SCHED_HIST
(
	SSH_ID NUMBER(20,0)
	, SSH_REQ_ID NUMBER(20,0)
	, SSH_IS_RESCHEDULED CHAR(1 BYTE) DEFAULT '0'
	, SSH_MEETING_SCHED_DT DATE
	, SSH_RESCHED_FROM_DT DATE
	, SSH_RESCHED_REASON_ID NUMBER(20,0)
	, SSH_RESCHED_REASON_TEXT NVARCHAR2(140)
	, SSH_RESCHED_COMMENTS NVARCHAR2(140)
	, SSH_RESCHED_BY_ID NVARCHAR2(50)
	, SSH_RESCHED_BY_NAME NVARCHAR2(100)
	, SSH_RESCHED_ON DATE
)
;

COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_ID IS 'Primary key M:1 REQUEST record';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_REQ_ID IS 'Foreign key to REQUEST table';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_IS_RESCHEDULED IS 'Is the meeting rescheduled? 1=tru 0=false';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_MEETING_SCHED_DT IS 'Date the next meeting is scheduled for';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_FROM_DT IS 'Original date to be rescheduled';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_REASON_ID IS 'Reason ID select from TBL_LOOKUP, LTYPE=StratConMeetingRescheduleReason';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_REASON_TEXT IS 'Text for reason rescheduling';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_COMMENTS IS 'Additional comments for rescheduling';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_BY_ID IS 'ID of person rescheduling meeting';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_BY_NAME IS 'Name of person rescheduling meeting';
COMMENT ON COLUMN STRATCON_SCHED_HIST.SSH_RESCHED_ON IS 'Date on which the rescheduling transaction took place';


--------------------------------------------------------
--  DDL for Table TARGET_RECRUIT
--------------------------------------------------------
CREATE TABLE TARGET_RECRUIT
(
	TR_REQ_ID NUMBER(20,0)
	, TR_PAID_AD CHAR(1 BYTE) DEFAULT '0'
	, TR_PAID_AD_SPEC NVARCHAR2(1000)
	, TR_PAID_AD_SPEC_OTHR NVARCHAR2(500)
	, TR_SCHL_PSTG CHAR(1 BYTE) DEFAULT '0'
	, TR_SCHL_PSTG_SPEC NVARCHAR2(1000)
	, TR_SCHL_PSTG_SPEC_OTHR NVARCHAR2(500)
	, TR_SOCIAL_MEDIA CHAR(1 BYTE) DEFAULT '0'
	, TR_SOCIAL_MEDIA_SPEC NVARCHAR2(1000)
	, TR_SOCIAL_MEDIA_SPEC_OTHR NVARCHAR2(500)
	, TR_OTHER CHAR(1 BYTE) DEFAULT '0'
	, TR_OTHER_SPEC NVARCHAR2(500)
)
;

COMMENT ON COLUMN TARGET_RECRUIT.TR_REQ_ID IS 'Primary key as well as foreign key to REQUEST table';
COMMENT ON COLUMN TARGET_RECRUIT.TR_PAID_AD IS 'Paid advertising? 1=true 0=false';
COMMENT ON COLUMN TARGET_RECRUIT.TR_PAID_AD_SPEC IS 'Specify paid advertising';
COMMENT ON COLUMN TARGET_RECRUIT.TR_PAID_AD_SPEC_OTHR IS 'Specify other paid advertising';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SCHL_PSTG IS 'School posting used? 1=true 0=false';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SCHL_PSTG_SPEC IS 'Specify school posting';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SCHL_PSTG_SPEC_OTHR IS 'Specify other school posting';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SOCIAL_MEDIA IS 'Social media used? 1=true 0=false';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SOCIAL_MEDIA_SPEC IS 'Specify social media source';
COMMENT ON COLUMN TARGET_RECRUIT.TR_SOCIAL_MEDIA_SPEC_OTHR IS 'Specify other social media source';
COMMENT ON COLUMN TARGET_RECRUIT.TR_OTHER IS 'Other recruitment method used? 1=true 0=false';
COMMENT ON COLUMN TARGET_RECRUIT.TR_OTHER_SPEC IS 'Specify other recruitment source';


Commit;






--------------------------------------------
-- Clear constraints for recreation
--------------------------------------------
/*

BEGIN
	FOR R IN (
		SELECT TABLE_NAME, CONSTRAINT_NAME
		FROM USER_CONSTRAINTS
		WHERE 1=1
			AND OWNER = 'HHS_CMS_HR'
			AND TABLE_NAME IN ('ADMIN_CODES','APPROVALS','AREAS_OF_CONS'
				,'CLASSIFICATION','CLASSIF_STRATCON','FLSA','GRADE_DETAIL','JOB_ANALYSIS'
				,'LOCATION','PD_COVERSHEET','POSITION','RECRUIT_INCENTIVES','REQUEST'
				,'REQUEST_CONTROL','SME_INFO','STRATCON_GEN','STRATCON_SCHED_HIST','TARGET_RECRUIT')
		ORDER BY TABLE_NAME, CONSTRAINT_NAME
	)
	LOOP
		--DBMS_OUTPUT.PUT_LINE('R.TABLE_NAME = ' || R.TABLE_NAME || '     R.CONSTRAINT_NAME = ' || R.CONSTRAINT_NAME);
		EXECUTE IMMEDIATE 'ALTER TABLE '||R.TABLE_NAME  ||' DROP CONSTRAINT '||R.CONSTRAINT_NAME;
	END LOOP;
END;

*/



--------------------------------------------------------
--  Constraints for Table ADMIN_CODES
--------------------------------------------------------

--ALTER TABLE ADMIN_CODES ADD CONSTRAINT ADMIN_CODES_PK PRIMARY KEY (AC_ID);


--------------------------------------------------------
--  Constraints for Table APPROVALS
--------------------------------------------------------

ALTER TABLE APPROVALS ADD CONSTRAINT APPROVALS_PK PRIMARY KEY (SCA_REQ_ID);


--------------------------------------------------------
--  Constraints for Table AREAS_OF_CONS
--------------------------------------------------------

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_PK PRIMARY KEY (AOC_REQ_ID);

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK1  CHECK ( AOC_30PCT_DISABLED_VETS IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK2  CHECK ( AOC_EXPERT_CONS         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK3  CHECK ( AOC_IPA                 IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK4  CHECK ( AOC_OPER_WARFIGHTER     IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK5  CHECK ( AOC_DISABILITIES        IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK6  CHECK ( AOC_STUDENT_VOL         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK7  CHECK ( AOC_VETS_RECRUIT_APPT   IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK8  CHECK ( AOC_VOC_REHAB_EMPL      IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK9  CHECK ( AOC_WORKFORCE_RECRUIT   IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK10 CHECK ( AOC_MIL_SPOUSES         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK11 CHECK ( AOC_DIRECT_HIRE         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK12 CHECK ( AOC_RE_EMPLOYMENT       IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK13 CHECK ( AOC_PATHWAYS            IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK14 CHECK ( AOC_PEACE_CORPS_VOL     IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK15 CHECK ( AOC_REINSTATEMENT       IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK16 CHECK ( AOC_SHARED_CERT         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK17 CHECK ( AOC_DELEGATE_EXAM       IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK18 CHECK ( AOC_DH_US_CITIZENS      IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK19 CHECK ( AOC_MP_GOV_WIDE         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK20 CHECK ( AOC_MP_HHS_ONLY         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK21 CHECK ( AOC_MP_CMS_ONLY         IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK22 CHECK ( AOC_MP_COMP_CONS_ONLY   IN ('0', '1')) ENABLE;

ALTER TABLE AREAS_OF_CONS ADD CONSTRAINT AREAS_OF_CONS_CK23 CHECK ( AOC_MP_I_CTAP_VEGA      IN ('0', '1')) ENABLE;

--------------------------------------------------------
--  Constraints for Table CLASSIF_STRATCON
--------------------------------------------------------
ALTER TABLE CLASSIF_STRATCON ADD CONSTRAINT CLASSIF_STRATCON_PK PRIMARY KEY (CS_REQ_ID);


--------------------------------------------------------
--  Constraints for Table CLASSIFICATION
--------------------------------------------------------
ALTER TABLE CLASSIFICATION ADD CONSTRAINT CLASSIFICATION_PK PRIMARY KEY (CLS_ID);


--------------------------------------------------------
--  DDL for Index ELIG_QUAL_PK
--------------------------------------------------------
CREATE UNIQUE INDEX ELIG_QUAL_PK ON ELIG_QUAL (ELIGQUAL_ID);

--------------------------------------------------------
--  Constraints for Table ELIG_QUAL
--------------------------------------------------------
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_PK PRIMARY KEY (ELIGQUAL_ID);
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK1   CHECK ( SO_AGREE          IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK2   CHECK ( VICE              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK3   CHECK ( CE_FINANCIAL_DISC IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK4   CHECK ( CE_PE_PHYSICAL    IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK5   CHECK ( CE_DRUG_TEST      IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK6   CHECK ( CE_IMMUN          IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK7   CHECK ( CE_TRAVEL         IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK8   CHECK ( CE_LIC            IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK9   CHECK ( GA_1              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK10  CHECK ( GA_2              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK11  CHECK ( GA_3              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK12  CHECK ( GA_4              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK13  CHECK ( GA_5              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK14  CHECK ( GA_6              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK15  CHECK ( GA_7              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK16  CHECK ( GA_8              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK17  CHECK ( GA_9              IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK18  CHECK ( GA_10             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK19  CHECK ( GA_11             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK20  CHECK ( GA_12             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK21  CHECK ( GA_13             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK22  CHECK ( GA_14             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK23  CHECK ( GA_15             IN('0', '1')) ENABLE;
ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK24  CHECK ( SC_REQUESTED      IN('0', '1')) ENABLE;
--ALTER TABLE ELIG_QUAL ADD CONSTRAINT ELIG_QUAL_CK27  CHECK ( DCO_CERT          IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table FLSA
--------------------------------------------------------
ALTER TABLE FLSA ADD CONSTRAINT FLSA_PK PRIMARY KEY (FLSA_PD_ID);

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK1  CHECK ( FLSA_EX_EXEC            IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK2  CHECK ( FLSA_EX_ADMIN           IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK3  CHECK ( FLSA_EX_PROF_LEARNED    IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK4  CHECK ( FLSA_EX_PROF_CREATIVE   IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK5  CHECK ( FLSA_EX_PROF_COMPUTER   IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK6  CHECK ( FLSA_EX_LAW_ENFORC      IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK7  CHECK ( FLSA_EX_FOREIGN         IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK8  CHECK ( FLSA_NONEX_SALARY       IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK9  CHECK ( FLSA_NONEX_EQUIP_OPER   IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK10 CHECK ( FLSA_NONEX_TECHN        IN('0', '1')) ENABLE;

ALTER TABLE FLSA ADD CONSTRAINT FLSA_CK11 CHECK ( FLSA_NONEX_FED_WAGE_SYS IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table GRADE_DETAIL
--------------------------------------------------------
ALTER TABLE GRADE_DETAIL ADD CONSTRAINT GRADE_DETAIL_PK PRIMARY KEY (GD_ID);

ALTER TABLE GRADE_DETAIL ADD CONSTRAINT GD_FPL_CONST CHECK (GD_FPL IN (0, 1));
ALTER TABLE GRADE_DETAIL ADD CONSTRAINT GD_GRADE_CONST CHECK (GD_GRADE IN (0, 1));

--------------------------------------------------------
--  Constraints for Table JOB_ANALYSIS
--------------------------------------------------------
ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_PK PRIMARY KEY (JA_REQ_ID);

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK1 CHECK ( JA_REVIEWED_PD      IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK2 CHECK ( JA_MAJ_COMP         IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK3 CHECK ( JA_TASK_ITEMS       IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK4 CHECK ( JA_SEL_FACTOR_REQ   IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK5 CHECK ( JA_QUAL_RANK_REQ    IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK6 CHECK ( JA_RESPONSES_REQ    IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK7 CHECK ( JA_TYPE_YES_NO      IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK8 CHECK ( JA_TYPE_REQ_DEFAULT IN('0', '1')) ENABLE;

ALTER TABLE JOB_ANALYSIS ADD CONSTRAINT JOB_ANALYSIS_CK9 CHECK ( JA_TYPE_KNOWL_SCALE IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table LOCATION
--------------------------------------------------------
ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_PK PRIMARY KEY (LOC_ID);

ALTER TABLE LOCATION ADD CONSTRAINT LOCATION_CK1 CHECK ( LOC_EFF_STATUS IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table PD_COVERSHEET
--------------------------------------------------------
ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_PK PRIMARY KEY (PD_ID);

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK1 CHECK ( PD_SUBJECT_IA    IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK2 CHECK ( PD_PCA           IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK3 CHECK ( PD_PDP           IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK4 CHECK ( PD_FTT           IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK5 CHECK ( PD_OUTSTATION    IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK6 CHECK ( PD_INCUMBENCY    IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK7 CHECK ( PD_SUPV_CERT     IN ('0', '1')) ENABLE;

ALTER TABLE PD_COVERSHEET ADD CONSTRAINT PD_COVERSHEET_CK8 CHECK ( PD_CLS_SPEC_CERT IN ('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table POSITION
--------------------------------------------------------
ALTER TABLE POSITION ADD CONSTRAINT POSITION_PK PRIMARY KEY (POS_REQ_ID);

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK1  CHECK ( POS_VICE              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK2  CHECK ( POS_CE_FINANCIAL_DISC IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK3  CHECK ( POS_CE_PE_PHYSICAL    IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK4  CHECK ( POS_CE_DRUG_TEST      IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK5  CHECK ( POS_CE_IMMUN          IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK6  CHECK ( POS_CE_TRAVEL         IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK7  CHECK ( POS_CE_LIC            IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK8  CHECK ( POS_GA_1              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK9  CHECK ( POS_GA_2              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK10 CHECK ( POS_GA_3              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK11 CHECK ( POS_GA_4              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK12 CHECK ( POS_GA_5              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK13 CHECK ( POS_GA_6              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK14 CHECK ( POS_GA_7              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK15 CHECK ( POS_GA_8              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK16 CHECK ( POS_GA_9              IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK17 CHECK ( POS_GA_10             IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK18 CHECK ( POS_GA_11             IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK19 CHECK ( POS_GA_12             IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK20 CHECK ( POS_GA_13             IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK21 CHECK ( POS_GA_14             IN('0', '1')) ENABLE;

ALTER TABLE POSITION ADD CONSTRAINT POSITION_CK22 CHECK ( POS_GA_15             IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table RECRUIT_INCENTIVES
--------------------------------------------------------
ALTER TABLE RECRUIT_INCENTIVES ADD CONSTRAINT RECRUIT_INCENTIVES_PK PRIMARY KEY (RI_REQ_ID);

ALTER TABLE RECRUIT_INCENTIVES ADD CONSTRAINT RECRUIT_INCENTIVES_CK1 CHECK ( RI_MOVING_EXP_AUTH IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table REQUEST
--------------------------------------------------------
ALTER TABLE REQUEST ADD CONSTRAINT REQUEST_PK PRIMARY KEY (REQ_ID);

--------------------------------------------------------
--  Constraints for Table SME_INFO
--------------------------------------------------------
ALTER TABLE SME_INFO ADD CONSTRAINT SME_INFO_PK PRIMARY KEY (SME_REQ_ID);

ALTER TABLE SME_INFO ADD CONSTRAINT SME_INFO_CK1 CHECK ( SME_FOR_JOB_ANALYSIS IN('0', '1')) ENABLE;

ALTER TABLE SME_INFO ADD CONSTRAINT SME_INFO_CK2 CHECK ( SME_FOR_QUALIFICATION IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table STRATCON_GEN
--------------------------------------------------------
ALTER TABLE STRATCON_GEN ADD CONSTRAINT STRATCON_GEN_PK PRIMARY KEY (SG_REQ_ID);

ALTER TABLE STRATCON_GEN ADD CONSTRAINT STRATCON_GEN_CK1 CHECK ( SG_SO_AGREE IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table STRATCON_SCHED_HIST
--------------------------------------------------------
ALTER TABLE STRATCON_SCHED_HIST ADD CONSTRAINT STRATCON_SCHED_HIST_PK PRIMARY KEY (SSH_ID);

ALTER TABLE STRATCON_SCHED_HIST MODIFY (SSH_REQ_ID NOT NULL);

ALTER TABLE STRATCON_SCHED_HIST ADD CONSTRAINT STRATCON_SCHED_HIST_CK1 CHECK ( SSH_IS_RESCHEDULED IN('0', '1')) ENABLE;


--------------------------------------------------------
--  Constraints for Table TARGET_RECRUIT
--------------------------------------------------------

ALTER TABLE TARGET_RECRUIT ADD CONSTRAINT TARGET_RECRUIT_PK PRIMARY KEY (TR_REQ_ID);

ALTER TABLE TARGET_RECRUIT ADD CONSTRAINT TARGET_RECRUIT_CK1 CHECK ( TR_PAID_AD      IN('0', '1')) ENABLE;

ALTER TABLE TARGET_RECRUIT ADD CONSTRAINT TARGET_RECRUIT_CK2 CHECK ( TR_SCHL_PSTG    IN('0', '1')) ENABLE;

ALTER TABLE TARGET_RECRUIT ADD CONSTRAINT TARGET_RECRUIT_CK3 CHECK ( TR_SOCIAL_MEDIA IN('0', '1')) ENABLE;

ALTER TABLE TARGET_RECRUIT ADD CONSTRAINT TARGET_RECRUIT_CK4 CHECK ( TR_OTHER        IN('0', '1')) ENABLE;





--------------------------------------------------------
--  DDL for Sequence ADMIN_CODES_SEQ
--------------------------------------------------------
--
--CREATE SEQUENCE ADMIN_CODES_SEQ
--	INCREMENT BY 1
--	START WITH 1
--	NOMAXVALUE
--	NOCACHE
--	NOCYCLE ;
--/


--------------------------------------------------------
--  DDL for Sequence ELIG_QUAL_SEQ
--------------------------------------------------------
CREATE SEQUENCE ELIG_QUAL_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;

/

--------------------------------------------------------
--  DDL for Sequence LOC_SEQ
--------------------------------------------------------

CREATE SEQUENCE LOC_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCACHE
	NOCYCLE;
/


--------------------------------------------------------
--  DDL for Sequence PD_COVERSHEET_SEQ
--------------------------------------------------------

CREATE SEQUENCE PD_COVERSHEET_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/


--------------------------------------------------------
--  DDL for Sequence REQUEST_SEQ
--------------------------------------------------------

CREATE SEQUENCE REQUEST_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/


--------------------------------------------------------
--  DDL for Sequence STRATCON_SCHED_HIST_SEQ
--------------------------------------------------------

CREATE SEQUENCE STRATCON_SCHED_HIST_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/



--------------------------------------------------------
--  DDL for Trigger ADMIN_CODES_TRG
--------------------------------------------------------
--
--CREATE OR REPLACE TRIGGER ADMIN_CODES_TRG
--BEFORE INSERT ON ADMIN_CODES
--FOR EACH ROW
--BEGIN
--	IF INSERTING AND :NEW.AC_ID IS NULL THEN
--		SELECT ADMIN_CODES_SEQ.NEXTVAL INTO :NEW.AC_ID FROM DUAL;
--	END IF;
--END;
--
--/


--------------------------------------------------------
--  DDL for Trigger ELIG_QUAL_BIR
--------------------------------------------------------
CREATE OR REPLACE TRIGGER ELIG_QUAL_BIR
BEFORE INSERT ON ELIG_QUAL
FOR EACH ROW
BEGIN
	SELECT ELIG_QUAL_SEQ.NEXTVAL
	INTO :NEW.ELIGQUAL_ID
	FROM DUAL;
END;

/

--------------------------------------------------------
--  DDL for Trigger LOC_TRG
--------------------------------------------------------

CREATE OR REPLACE TRIGGER LOC_TRG
BEFORE INSERT ON LOCATION
FOR EACH ROW
BEGIN
	IF INSERTING AND :NEW.LOC_ID IS NULL THEN
		SELECT LOC_SEQ.NEXTVAL INTO :NEW.LOC_ID FROM DUAL;
	END IF;
END;

/


--------------------------------------------------------
--  DDL for Trigger PD_COVERSHEET_BIR
--------------------------------------------------------

CREATE OR REPLACE TRIGGER PD_COVERSHEET_BIR
BEFORE INSERT ON PD_COVERSHEET
FOR EACH ROW
BEGIN
	SELECT PD_COVERSHEET_SEQ.NEXTVAL
	INTO :NEW.PD_ID
	FROM DUAL;
END;

/


--------------------------------------------------------
--  DDL for Trigger REQUEST_BIR
--------------------------------------------------------

CREATE OR REPLACE TRIGGER REQUEST_BIR
BEFORE INSERT ON REQUEST
FOR EACH ROW
BEGIN
	SELECT REQUEST_SEQ.NEXTVAL
	INTO :NEW.REQ_ID
	FROM DUAL
	;
END
;

/


--------------------------------------------------------
--  DDL for Trigger STRATCON_SCHED_HIST_BIR
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER STRATCON_SCHED_HIST_BIR
BEFORE INSERT ON STRATCON_SCHED_HIST
FOR EACH ROW
BEGIN
	SELECT STRATCON_SCHED_HIST_SEQ.NEXTVAL
	INTO :NEW.SSH_ID
	FROM DUAL
	;
END
;

/
