--------------------------------------------------------
--  File created - Thursday-March-09-2017
--------------------------------------------------------
REM INSERTING into GRADE_DETAIL
SET DEFINE OFF;
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (1,'GP',1,1,15,13,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (2,'GR',1,1,15,13,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (3,'GS',1,1,15,13,1);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (4,'ES',1,1,6,7,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (5,'WG',1,1,10,11,1);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (6,'AD',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (7,'ED',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (8,'EE',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (9,'EF',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (10,'EG',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (11,'EX',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (12,'SL',0,0,0,0,0);
Insert into GRADE_DETAIL (GD_ID,GD_PAYPLAN_CD,GD_GRADE,GD_MIN,GD_MAX,GD_RESTRICT,GD_FPL) values (13,'ZZ',0,0,0,0,0);
