/**
 * Script to regrant select permissions to BIZFLOW and HHS_CMS_HR database roles.
 * Last Updated by Taeho Lee on Feb 25, 2019
 * Usage: run this query whenever there are any changes made in HHS_HR database.
 **/

SET SERVEROUTPUT ON;

DECLARE 

BEGIN

    DBMS_OUTPUT.PUT_LINE('-- ReGranting begins');

    DBMS_OUTPUT.PUT_LINE('-- Tables');
	FOR ATAB IN (SELECT TABLE_NAME FROM ALL_TABLES WHERE OWNER = 'HHS_HR' AND TABLE_NAME NOT LIKE '%_IHS_%' ORDER BY TABLE_NAME ) LOOP
        DBMS_OUTPUT.PUT_LINE('GRANT SELECT ON HHS_HR.'||ATAB.TABLE_NAME||' TO BIZFLOW  WITH GRANT OPTION;');
		EXECUTE IMMEDIATE 'GRANT SELECT ON HHS_HR.'||ATAB.TABLE_NAME||' TO BIZFLOW WITH GRANT OPTION';
        DBMS_OUTPUT.PUT_LINE('GRANT SELECT ON HHS_HR.'||ATAB.TABLE_NAME||' TO HHS_CMS_HR WITH GRANT OPTION;');
		EXECUTE IMMEDIATE 'GRANT SELECT ON HHS_HR.'||ATAB.TABLE_NAME||' TO HHS_CMS_HR WITH GRANT OPTION';        
	END LOOP;
    DBMS_OUTPUT.PUT_LINE('-- ReGranting ends');

END;
/
