create or replace PROCEDURE SP_ERLR_DELETE_RELATED_CASE
(
    I_CASE_NUMBER IN NUMBER,
    I_RELATED_CASE_NUMBER IN NUMBER
)
IS
BEGIN
    -- DELETE ONLY MANUALLY ENTERED CASE
    DELETE ERLR_RELATED_CASE
     WHERE CASE_NUMBER = I_CASE_NUMBER
       AND RELATED_CASE_NUMBER = I_RELATED_CASE_NUMBER
       AND M_DT IS NOT NULL; 
    
EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;