
-- Selection Determination
INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (701, 0, 'SelectionDetermination', 'Selected', 'Selected', '1', NULL, 'N', NULL, NULL, TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_DISP_ORDER, TBL_MANDATORY, TBL_REGION, TBL_CATEGORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (702, 0, 'SelectionDetermination', 'Not Selected', 'Not Selected', '1', NULL, 'N', NULL, NULL, TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));



INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (703, 0, 'MandatoryDocument', 'Eligibility', 'Eligibility', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (704, 703, 'MDClassificationType', 'Create New Position Description', 'Create New Position Description', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (705, 703, 'MDClassificationType', 'Conduct 5-year Recertification', 'Conduct 5-year Recertification', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (706, 703, 'MDClassificationType', 'Update Coversheet', 'Update Coversheet', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (707, 703, 'MDClassificationType', 'Audit Position', 'Audit Position', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (708, 703, 'MDClassificationType', 'Update Major Duties', 'Update Major Duties', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (709, 703, 'MDClassificationType', 'Reorganization for Existing Position', 'Reorganization for Existing Position', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (710, 703, 'MDClassificationType', 'Reorganization for New Position', 'Reorganization for New Position', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (711, 703, 'MDClassificationType', 'Review Existing Position Description', 'Review Existing Position Description', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (712, 704, 'MDDocumentType', 'Organization Chart', 'Organization Chart', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (713, 705, 'MDDocumentType', 'Organization Chart', 'Organization Chart', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (714, 708, 'MDDocumentType', 'Organization Chart', 'Organization Chart', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (715, 710, 'MDDocumentType', 'Organization Chart', 'Organization Chart', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));




INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (716, 0, 'IneligibilityReason', 'NOT_US_CITIZEN', 'The candidate is not a US Citizen and therefore ineligible for consideration under this hiring authority.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (717, 0, 'IneligibilityReason', 'NOT_MEET_REQUIREMENT', 'The candidate does not meet eligibility requirements for this hiring authority.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (718, 0, 'IneligibilityReason', 'SA_NO_SCHEDULE_A_DOC', 'Did not provide proper Schedule A documentation demonstrating Schedule A eligibility.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (719, 0, 'IneligibilityReason', 'VS_NO_CURRENT_ENRL', 'The candidate''s transcript(s) does not show current enrollment in order to be considered under the student volunteer program.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (720, 0, 'IneligibilityReason', 'VS_LOW_GPA', 'The candidate''s transcripts does not show a current GPA of 2.0 or higher in order to be considered under the student volunteer program.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));



INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (721, 0, 'DisqualificationReason', 'NOT_SPECIAL_EXPR', 'The candidate does not meet the specialized experience required for this position.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (722, 0, 'DisqualificationReason', 'NOT_SPECIAL_EXPR_LENGTH', 'The candidate does not possess the length of specialized experience required for this position.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (723, 0, 'DisqualificationReason', 'NOT_GENERAL_EXPR', 'The candidate does not meet the general experience required for this position.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (724, 0, 'DisqualificationReason', 'NOT_EDUCATION_REQ', 'The candidate does not meet the education requirement(s) for this position.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (725, 0, 'DisqualificationReason', 'NOT_MET_SKILL', 'The candidate''s application does not demonstrate having met the typing skills requirement of this position.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));

INSERT INTO HHS_CMS_HR.TBL_LOOKUP (TBL_ID, TBL_PARENT_ID, TBL_LTYPE, TBL_NAME, TBL_LABEL, TBL_ACTIVE, TBL_MANDATORY, TBL_EFFECTIVE_DT, TBL_EXPIRATION_DT)
VALUES (726, 0, 'DisqualificationReason', 'NOT_QUAL_RESUME', 'Unable to determine candidate qualifications based on the resume provided.', '1', 'N', TO_DATE('2017-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'), TO_DATE('2050-01-01 00:00:00', 'YYYY-MM-DD HH24:MI:SS'));


-- remove incorrect special character

UPDATE TBL_LOOKUP SET TBL_LABEL = 'U.S. OPM Flysheet for Comp Science, GS-1550; TS-83; 01/88' WHERE TBL_ID = 568;

UPDATE TBL_LOOKUP SET TBL_LABEL = 'U.S. OPM Flysheet for Mgmt and Prog Analy, GS-0343; TS-98; 08/90' WHERE TBL_ID = 573;

UPDATE TBL_LOOKUP SET TBL_NAME = 'FlysheetForMiscAdminandProg', TBL_LABEL = 'U.S. OPM Flysheet for Misc Admin and Prog, GS-0301; TS-34; 01/79' WHERE TBL_ID = 574;

UPDATE TBL_LOOKUP SET TBL_LABEL = 'U.S. OPM JFS for Prof and Admin Work in Acct and Budget Group, GS-0500; 12/00' WHERE TBL_ID = 601;

UPDATE TBL_LOOKUP SET TBL_LABEL = 'U.S. OPM PCS for Secretary, GS-0318; TS-64; 06/82' WHERE TBL_ID = 628;

UPDATE TBL_LOOKUP SET TBL_LABEL = 'U.S. OPM Research Grade Eval Guide; 09/06' WHERE TBL_ID = 632;


COMMIT;
