--------------------------------------------------------
--  DDL for VW_ERLR_3RDPARTY_HEAR
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_3RDPARTY_HEAR
AS
SELECT
    TPH.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , THRD_PRTY_APPEAL_TYPE
	, THRD_PRTY_APPEAL_FILE_DT
	, THRD_PRTY_ASSISTANCE_REQ_DT
	, CASE WHEN THRD_PRTY_HEARING_TIMING = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_HEARING_TIMING
	, CASE WHEN THRD_PRTY_HEARING_REQUESTED = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_HEARING_REQUESTED
	, THRD_PRTY_STEP_DECISION_DT
	, CASE WHEN THRD_PRTY_ARBITRATION_INVOKED = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_ARBITRATION_INVOKED
	, THRD_PRTY_ARBIT_LNM_3
	, THRD_PRTY_ARBIT_FNM_3
	, THRD_PRTY_ARBIT_MNM_3
	, THRD_PRTY_ARBIT_EMAIL_3
	, THRD_ERLR_ARBIT_PHONE_NUM_3
	, THRD_PRTY_ARBIT_ORG_AFFIL_3
	, THRD_PRTY_ARBIT_MAILING_ADDR_3
	, THRD_PRTY_PREHEARING_DT_2
	, THRD_PRTY_HEARING_DT_2
	, THRD_PRTY_POSTHEAR_BRIEF_DUE_2
	, THRD_PRTY_FNL_ARBIT_DCSN_DT_2
	, CASE WHEN THRD_PRTY_EXCEPTION_FILED_2 = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_EXCEPTION_FILED_2
	, THRD_PRTY_EXCEPTION_FILE_DT_2
	, THRD_PRTY_RSPS_TO_EXCPT_DUE_2
	, THRD_PRTY_FNL_FLRA_DCSN_DT_2
	, THRD_PRTY_ARBIT_LNM
	, THRD_PRTY_ARBIT_FNM
	, THRD_PRTY_ARBIT_MNM
	, THRD_PRTY_ARBIT_EMAIL
	, THRD_ERLR_ARBIT_PHONE_NUM
	, THRD_PRTY_ARBIT_ORG_AFFIL
	, THRD_PRTY_ARBIT_MAILING_ADDR
	, THRD_PRTY_PREHEARING_DT
	, THRD_PRTY_HEARING_DT
	, THRD_PRTY_POSTHEAR_BRIEF_DUE
	, THRD_PRTY_FNL_ARBIT_DCSN_DT
	, CASE WHEN THRD_PRTY_EXCEPTION_FILED = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_EXCEPTION_FILED
	, THRD_PRTY_EXCEPTION_FILE_DT
	, THRD_PRTY_RSPS_TO_EXCPT_DUE
	, THRD_PRTY_FNL_FLRA_DCSN_DT
	, THRD_PRTY_ARBIT_LNM_4
	, THRD_PRTY_ARBIT_FNM_4
	, THRD_PRTY_ARBIT_MNM_4
	, THRD_PRTY_ARBIT_EMAIL_4
	, THRD_ERLR_ARBIT_PHONE_NUM_4
	, THRD_PRTY_ARBIT_ORG_AFFIL_4
	, THRD_PRTY_ARBIT_MAILING_ADDR_4
	, THRD_PRTY_DT_STLMNT_DSCUSN
	, THRD_PRTY_DT_PREHEAR_DSCLS
	, THRD_PRTY_DT_AGNCY_RSP_DUE
	, THRD_PRTY_PREHEARING_DT_MSPB
	, CASE WHEN THRD_PRTY_WAS_DSCVRY_INIT = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_WAS_DSCVRY_INIT
	, THRD_PRTY_DT_DISCOVERY_DUE
	, THRD_PRTY_HEARING_DT_MSPB
	, THRD_PRTY_INIT_DCSN_DT_MSPB
	, CASE WHEN THRD_PRTY_WAS_PETI_FILED_MSPB = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_WAS_PETI_FILED_MSPB
	, THRD_PRTY_PETITION_RV_DT
	, THRD_PRTY_FNL_BRD_DCSN_DT_MSPB
	, THRD_PRTY_DT_STLMNT_DSCUSN_2
	, THRD_PRTY_DT_PREHEAR_DSCLS_2
	, THRD_PRTY_PREHEARING_CONF
	, THRD_PRTY_HEARING_DT_FLRA
	, THRD_PRTY_DECISION_DT_FLRA
	, CASE WHEN THRD_PRTY_TIMELY_REQ = '1'  THEN 'Yes' ELSE 'No' END AS THRD_PRTY_TIMELY_REQ
    , THRD_PRTY_PROC_ORDER
	, THRD_PRTY_PANEL_MEMBER_LNAME
	, THRD_PRTY_PANEL_MEMBER_FNAME
	, THRD_PRTY_PANEL_MEMBER_MNAME
	, THRD_PRTY_PANEL_MEMBER_EMAIL
	, THRD_PRTY_PANEL_MEMBER_PHONE
	, THRD_PRTY_PANEL_MEMBER_ORG
	, THRD_PRTY_PANEL_MEMBER_MAILING
	, THRD_PRTY_PANEL_DESCR
FROM
	ERLR_3RDPARTY_HEAR TPH
    LEFT OUTER JOIN ERLR_CASE EC ON TPH.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/