SET DEFINE OFF ;




ALTER TABLE PD_COVERSHEET ADD BYPASS_DWC_FL NVARCHAR2(10) ;

COMMENT ON COLUMN PD_COVERSHEET.BYPASS_DWC_FL IS 'Bypass DWC flag. Yes, No';

COMMENT ON COLUMN PD_COVERSHEET.PD_BUS_CD IS 'BUS Code Value on Lookup table';






