SET DEFINE OFF ;




ALTER TABLE PD_COVERSHEET ADD BYPASS_DWC_FL NVARCHAR2(10) ;

COMMENT ON COLUMN PD_COVERSHEET.BYPASS_DWC_FL IS 'Bypass DWC flag. Yes, No';
COMMENT ON COLUMN PD_COVERSHEET.PD_BUS_CD IS 'BUS Code Value on Lookup table';

COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD IS 'Unique admin code';
COMMENT ON COLUMN ADMIN_CODES.AC_ADMIN_CD_DESCR IS 'Description of admin code';
COMMENT ON COLUMN ADMIN_CODES.AC_PARENT_CD IS 'Key value of associated parent admin code';







