create or replace FUNCTION FN_GET_TIMEZONE_OFFSET(
    I_TIMEZONE  IN VARCHAR2 DEFAULT 'America/New_York'
)
RETURN FLOAT
IS
   V_TZ_OFFSET     VARCHAR2(10); 
BEGIN   
    V_TZ_OFFSET := TZ_OFFSET(I_TIMEZONE);
    RETURN SIGN(TO_NUMBER(SUBSTR(V_TZ_OFFSET, 1, 3))) * (TO_NUMBER(SUBSTR(V_TZ_OFFSET, 2, 2)) + TO_NUMBER(SUBSTR(V_TZ_OFFSET, 5, 2)) / 60);
EXCEPTION WHEN OTHERS THEN
    RETURN 0;
END;
/
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_TIMEZONE_OFFSET TO BIZFLOW;
/

create or replace FUNCTION FN_CONVERT_UTC_TO_LOCAL(
    I_DATE      IN  DATE,
    I_TIMEZONE  IN  VARCHAR2 DEFAULT 'America/New_York'
)
RETURN DATE
IS  
    V_DT            DATE;
    V_TZ_OFFSET     FLOAT(4);
BEGIN
    IF I_DATE IS NULL THEN
        RETURN NULL;
    END IF;

    V_TZ_OFFSET := FN_GET_TIMEZONE_OFFSET(I_TIMEZONE);
    RETURN I_DATE + V_TZ_OFFSET/24;

EXCEPTION WHEN OTHERS THEN
    RETURN NULL;
END;
/
GRANT EXECUTE ON HHS_CMS_HR.FN_CONVERT_UTC_TO_LOCAL TO BIZFLOW;
/

