--------------------------------------------------------
--  DDL for VW_ERLR_LABOR_NEGO
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_LABOR_NEGO
AS
SELECT
    LN.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , LN_NEGOTIATION_TYPE	
    , LN_INITIATOR
	, LN_DEMAND2BARGAIN_DT
	, CASE WHEN LN_BRIEFING_REQUEST = '1'  THEN 'Yes' ELSE 'No' END AS LN_BRIEFING_REQUEST
	, LN_PROPOSAL_SUBMISSION_DT
	, CASE WHEN LN_PROPOSAL_SUBMISSION = '1'  THEN 'Yes' ELSE 'No' END AS LN_PROPOSAL_SUBMISSION
	, CASE WHEN LN_UNION_PROPOSAL_NEGOTIABLE = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_PROPOSAL_NEGOTIABLE
	, CASE WHEN LN_UNION_NON_NEGOTIABLE_LETTER = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_NON_NEGOTIABLE_LETTER
	, CASE WHEN LN_UNION_FILE_ULP = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_FILE_ULP
	, CASE WHEN LN_PROPOSAL_INFO_GROUND_RULES = '1'  THEN 'Yes' ELSE 'No' END AS LN_PROPOSAL_INFO_GROUND_RULES
	, LN_PRPSAL_INFO_NEG_COMMENCE_DT
	, CASE WHEN LN_UNION_LETTER_PROVIDED = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_LETTER_PROVIDED
	, LN_LETTER_PROVIDED_DT
	, CASE WHEN LN_UNION_NEGOTIABLE_PROPOSAL = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_NEGOTIABLE_PROPOSAL
	, LN_UNION_BARGAINING_BEGAN_DT
	, LN_UNION_IMPASSE_DT
	, LN_UNION_FSIP_DECISION_DT
	, LN_UNION_BARGAINING_END_DT
	, LN_AGREEMENT_DT
	, LN_UNION_SUMMARY_OF_ISSUE
	, CASE WHEN LN_UNION_SECON_LETTER_REQUEST = '1'  THEN 'Yes' ELSE 'No' END AS LN_UNION_SECON_LETTER_REQUEST
	, CASE WHEN LN_2ND_LETTER_PROVIDED = '1'  THEN 'Yes' ELSE 'No' END AS LN_2ND_LETTER_PROVIDED
	, LN_UNION_NEGO_ISSUE_SUMMARY
	, LN_MNGMNT_ARTICLE4_NTC_DT
	, CASE WHEN LN_MNGMNT_NOTICE_RESPONSE = '1'  THEN 'Yes' ELSE 'No' END AS LN_MNGMNT_NOTICE_RESPONSE
	, CASE WHEN LN_MNGMNT_BRIEFING_REQUEST = '1'  THEN 'Yes' ELSE 'No' END AS LN_MNGMNT_BRIEFING_REQUEST
	, LN_MNGMNT_BARGAIN_SBMSSION_DT
	, CASE WHEN LN_MNGMNT_PROPOSAL_SBMSSION = '1'  THEN 'Yes' ELSE 'No' END AS LN_MNGMNT_PROPOSAL_SBMSSION

FROM
	ERLR_LABOR_NEGO LN
    LEFT OUTER JOIN ERLR_CASE EC ON LN.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/
