CREATE TABLE INCENTIVES_LE_CRED
(
	PROC_ID				NUMBER(10) NOT NULL,
	SEQ_NUM				NUMBER(10) NOT NULL,
	START_DATE			VARCHAR2(10),
	END_DATE			VARCHAR2(10),
	WORK_SCHEDULE		VARCHAR2(15),
	POS_TITLE			VARCHAR2(140),
	CALCULATED_YEARS	NUMBER(10) DEFAULT 0 NULL,
	CALCULATED_MONTHS	NUMBER(10) DEFAULT 0 NULL,
	CREDITABLE_YEARS	NUMBER(10) DEFAULT 0 NULL,
	CREDITABLE_MONTHS	NUMBER(10) DEFAULT 0 NULL
);

CREATE UNIQUE INDEX INCENTIVES_LE_CRED_UK1 ON INCENTIVES_LE_CRED (PROC_ID, SEQ_NUM);
/
