CREATE TABLE INCENTIVES_LE_CNFS
(
	PROC_ID			NUMBER(10) NOT NULL,
	SEQ_NUM			NUMBER(10) NOT NULL,
	START_DATE		VARCHAR2(10),
	END_DATE		VARCHAR2(10),
	WORK_SCHEDULE	VARCHAR2(15),
	POS_TITLE		VARCHAR2(140),
	YEARS			NUMBER(10),
	MONTHS			NUMBER(10)
);

CREATE UNIQUE INDEX INCENTIVES_LE_CNFS_UK1 ON INCENTIVES_LE_CNFS (PROC_ID, SEQ_NUM);
/
