ALTER TABLE  "HHS_CMS_HR"."ERLR_GEN" ADD GEN_EMPLOYEE_ID VARCHAR2(64);

UPDATE HHS_CMS_HR.ERLR_GEN
   SET GEN_EMPLOYEE_ID
     = (SELECT 
        XMLQUERY('/formData/items/item[id="GEN_EMPLOYEE_ID"]/value/text()' PASSING FIELD_DATA RETURNING CONTENT).GETSTRINGVAL()
        FROM HHS_CMS_HR.TBL_FORM_DTL F JOIN HHS_CMS_HR.ERLR_CASE C ON F.PROCID = C.PROCID 
	WHERE C.ERLR_CASE_NUMBER = ERLR_GEN.ERLR_CASE_NUMBER);

COMMIT;

