SET DEFINE OFF;

--------------------------------------------------------
--  DDL for altering the tables INCENTIVES_COM
--------------------------------------------------------
ALTER TABLE INCENTIVES_COM ADD (
	SS_NAME        VARCHAR2(100),
	SS_EMAIL       VARCHAR2(100),
	SS_ID          VARCHAR2(10),
	VACANCY_NUMBER	 NUMBER(10)

);
/

CREATE TABLE INCENTIVES_PDP
(
	PROC_ID              NUMBER(10),
	PDP_TYPE             VARCHAR2(18),
	PDP_TYPE_OTHER	VARCHAR2(150),
	EXISTINGREQUEST	CHAR(1),
	-- Position
	WORK_SCHEDULE        VARCHAR2(15),
	HOURS_PER_WEEK       VARCHAR2(5),
	BD_CERT_REQ          VARCHAR2(5),
	LIC_INFO             VARCHAR2(140),
	MARKET_PAY_RATE VARCHAR2(9), 
	CURRENT_FED_EMPLOYEE  CHAR(1), 
	LEVEL_RESPONSIBILITY VARCHAR2(50),
	EXEC_RESP_AMT_REQUESTED NUMBER(10), 
	EXEC_RESP_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	EXPT_QF_Q1_AMT_REQUESTED NUMBER(10), 
	EXPT_QF_Q1_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	EXPT_QF_Q2_AMT_REQUESTED NUMBER(10), 
	EXPT_QF_Q2_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	EXPT_QF_Q3_AMT_REQUESTED NUMBER(10), 
	EXPT_QF_Q3_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	EXPT_QF_Q4_AMT_REQUESTED NUMBER(10), 
	EXPT_QF_Q4_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	EXPT_QF_Q5_AMT_REQUESTED NUMBER(10), 
	EXPT_QF_Q5_JUSTIF_DETERMIN_AMT VARCHAR2(1000), 
	TOTAL_AMT_EXPT_QUALIFICATIONS NUMBER(10),
	CURRENT_PAY_GRADE NUMBER(2), 
	CURRENT_PAY_STEP NUMBER(2), 
	CURRENT_PAY_POSITION_TITLE VARCHAR2(70), 
	CURRENT_PAY_TABLE NUMBER(2), 
	CURRENT_PAY_TIER NUMBER(2), 
	CLINICAL_SPECIALTY_BOARD_CERT VARCHAR2(200),
	OTHER_SPECIALTY VARCHAR2(140),
	CURRENT_PAY_RECRUITMENT NUMBER(10), 
	CURRENT_PAY_RELOCATION NUMBER(10), 
	CURRENT_PAY_RETENTION NUMBER(10), 
	CURRENT_PAY_3R_TOTAL NUMBER(10), 
	CURRENT_PAY_BASE NUMBER(10), 
	CURRENT_PAY_LOCALITY_MARKET NUMBER(10), 
	CURRENT_PAY_TOTAL_ANNUAL_PAY NUMBER(10), 
	CURRENT_PAY_TOTAL_COMPENSATION NUMBER(10), 
	CURRENT_PAY_NOTES VARCHAR2(500), 
	PROPOSED_PAY_STEP NUMBER(2), 
	PROPOSED_PAY_TABLE NUMBER(2), 
	PROPOSED_PAY_TIER NUMBER(2), 
	PROPOSED_PAY_RECRUITMENT NUMBER(10), 
	PROPOSED_PAY_RELOCATION NUMBER(10), 
	PROPOSED_PAY_RETENTION NUMBER(10), 
	PROPOSED_PAY_TOTAL_3R NUMBER(10), 
	PROPOSED_GS_BASE_PAY NUMBER(10), 
	PROPOSED_MARKET_PAY NUMBER(10), 
	PROPOSED_TOTAL_ANNUAL_PAY NUMBER(10), 
	PROPOSED_TOTAL_ANNUAL_COMPENS NUMBER(10), 
	INCENTIVES_APPROVED_BY_TABG VARCHAR2(3), 
	PROPOSED_PAY_NOTES VARCHAR2(500), 
	DATE_OF_MEETING DATE, 
	PANEL_MEMBER_NAME VARCHAR2(100), 
	PANEL_MEMBER_COMPONENT VARCHAR2(50), 
	PANEL_ROLE VARCHAR2(9), 
	VOTING_STATUS VARCHAR2(16), 
	PANEL_RECOMMENDED_COMPENSATION NUMBER(10), 
	QUORUM_REACHED CHAR(1),
	PANEL_CURRENT_SALARY NUMBER(10), 
	PANEL_PDP_AMOUNT NUMBER(10), 
	PANEL_RECOMM_ANNUAL_SALARY NUMBER(10), 
	SELECTING_OFFICIAL_REVIEWER VARCHAR2(100), 
	SELECTING_OFFICIAL_REVIEW_DT DATE, 
	TABG_DIVISION_DIR_REVIEW_DT DATE, 
	CMS_CHIEF_PHYSICIAN_REVIEW_DT DATE, 
	OFM_REVIEW_DATE DATE, 
	TABG_REVIEW_DATE DATE, 
	OHC_REVIEW_DATE DATE, 
	ADMINISTRATOR_APPROVAL_DATE DATE
);

CREATE UNIQUE INDEX INCENTIVES_PDP_UK1 ON INCENTIVES_PDP (PROC_ID);

/