ALTER TABLE  "HHS_CMS_HR"."ERLR_GEN" ADD GEN_EMPLOYEE_ID VARCHAR2(64);


CREATE TABLE "HHS_CMS_HR"."ERLR_RELATED_CASE" 
   (	
	"CASEID" NUMBER(10,0) NOT NULL, 
	"RELATED_CASEID" NUMBER(10,0) NULL,
	"PROCID" NUMBER(10),
	"TRIGGER_F" CHAR(1) DEFAULT 'F' NOT NULL,
	"HHSID" VARCHAR2(64 BYTE),  
	"CASE_TYPE_ID" NUMBER(10,0), 
	"CASE_TYPE_NAME" VARCHAR2(100 BYTE), 
	"EMP_FIRST_NAME" VARCHAR2(100 BYTE), 
	"EMP_LAST_NAME" VARCHAR2(100 BYTE), 
	"M_DT" DATE, 
	"M_MEMBER_ID" VARCHAR2(10 BYTE), 
	"M_MEMBER_NAME" NVARCHAR2(100)
   );
   

CREATE INDEX "HHS_CMS_HR"."ERLR_RELATED_CASE_PK" 
    ON "HHS_CMS_HR"."ERLR_RELATED_CASE" 
    (
     "CASEID", "RELATED_CASEID"
    );


-- MIGRATION
-- not triggered cases
INSERT INTO ERLR_RELATED_CASE (CASEID, RELATED_CASEID, TRIGGER_F, HHSID, CASE_TYPE_ID, CASE_TYPE_NAME, EMP_FIRST_NAME, EMP_LAST_NAME, M_DT, M_MEMBER_ID, M_MEMBER_NAME) 
SELECT CASEID, NULL, 'F', HHSID, CASE_TYPE_ID, CASE_TYPE_NAME, EMP_FIRST_NAME, EMP_LAST_NAME, M_DT, M_MEMBER_ID, M_MEMBER_NAME
FROM ERLR_EMPLOYEE_CASE
WHERE FROM_CASEID IS NULL;


-- triggered cases
INSERT INTO ERLR_RELATED_CASE (CASEID, RELATED_CASEID, PROCID, TRIGGER_F) 
select b.caseid, a.erlr_case_number, b.procid, 'T'
from erlr_case a, (   
SELECT procid, max(casenumber) as caseid, max(fromprocid) as fromprocid
FROM(
SELECT R.procid, r.rlvntdataname, r.value 
  FROM BIZFLOW.PROCS P JOIN BIZFLOW.RLVNTDATA R ON P.PROCID = R.PROCID 
 WHERE P.NAME = 'ER/LR Case Initiation'
   and rlvntdataname in ('caseNumber', 'fromProcID')
   and value is not null
) T
PIVOT (
    MAX(VALUE) FOR RLVNTDATANAME IN ('caseNumber' casenumber, 'fromProcID' fromprocid)
)
where fromprocid is not null
group by procid 
) b
where a.procid = b.fromprocid;


UPDATE ERLR_RELATED_CASE
   SET (HHSID, CASE_TYPE_ID, CASE_TYPE_NAME, EMP_FIRST_NAME, EMP_LAST_NAME ) = (
SELECT F.HHSID, CASE_TYPE_ID, CASE_TYPE_NAME, E.FIRST_NAME, E.LAST_NAME
FROM (
SELECT PROCID,
XMLQUERY('/formData/items/item[id="GEN_EMPLOYEE_ID"]/value/text()' PASSING FIELD_DATA RETURNING CONTENT).GETSTRINGVAL() AS HHSID,
XMLQUERY('/formData/items/item[id="GEN_CASE_TYPE"]/value/text()' PASSING FIELD_DATA RETURNING CONTENT).GETSTRINGVAL() AS CASE_TYPE_ID,
XMLQUERY('/formData/items/item[id="GEN_CASE_TYPE"]/text/text()' PASSING FIELD_DATA RETURNING CONTENT).GETSTRINGVAL() AS CASE_TYPE_NAME 
  FROM TBL_FORM_DTL) F LEFT JOIN HHS_HR.EMPLOYEE_LOOKUP E ON F.HHSID = E.HHSID
 WHERE F.PROCID = ERLR_RELATED_CASE.PROCID )
 WHERE ERLR_RELATED_CASE.TRIGGER_F = 'T';

COMMIT;



DROP TABLE "HHS_CMS_HR"."ERLR_EMPLOYEE_CASE";
