create or replace PROCEDURE SP_CLOSE_ERLR
(
	I_PROCID               IN  NUMBER
)
IS
    V_CNT                   INT;
    V_CASE_NUMBER           NUMBER(10);    
BEGIN
    SELECT COUNT(1) INTO V_CNT
      FROM TBL_FORM_DTL
     WHERE PROCID = I_PROCID;

    IF V_CNT = 1 THEN        
        SELECT TO_NUMBER(VALUE)
	  INTO V_CASE_NUMBER
	  FROM BIZFLOW.RLVNTDATA
         WHERE RLVNTDATANAME = 'caseNumber' 
           AND PROCID = I_PROCID;
	
	DELETE ERLR_RELATED_CASE
	 WHERE CASE_NUMBER = V_CASE_NUMBER;

	DELETE ERLR_EMPLOYEE_CASE
	 WHERE CASE_NUMBER = V_CASE_NUMBER;
    END IF;

EXCEPTION
	WHEN OTHERS THEN
		SP_ERROR_LOG();
END;