-- Update Closed Cases
UPDATE HHS_CMS_HR.TBL_FORM_DTL
   SET FIELD_DATA = UPDATEXML(FIELD_DATA,'/formData/items/item[id="GEN_CASE_STATUS"]/value/text()', 'Closed')
 WHERE FORM_TYPE = 'CMSERLR'
   AND PROCID IN (SELECT PROCID FROM BIZFLOW.RLVNTDATA WHERE RLVNTDATANAME ='caseStatus' AND VALUE = 'closeNow');
   
UPDATE BIZFLOW.RLVNTDATA
   SET VALUE = 'Closed'
 WHERE RLVNTDATANAME ='caseStatus'
   AND VALUE = 'closeNow';

UPDATE HHS_CMS_HR.ERLR_GEN
   SET GEN_CASE_STATUS = 'Closed'
 WHERE GEN_CASE_STATUS = 'closeNow';

UPDATE HHS_CMS_HR.ERLR_CASE
   SET ERLR_CASE_STATUS_ID = 'Closed'
 WHERE ERLR_CASE_STATUS_ID = 'closeNow';
 
-- Update Completed Cases
UPDATE ERLR_GEN
   SET PROCID = (SELECT PROCID FROM ERLR_CASE WHERE ERLR_GEN.ERLR_CASE_NUMBER = ERLR_CASE.ERLR_CASE_NUMBER);

UPDATE HHS_CMS_HR.TBL_FORM_DTL
   SET FIELD_DATA = UPDATEXML(FIELD_DATA,'/formData/items/item[id="GEN_CASE_STATUS"]/value/text()', 'Completed')
 WHERE FORM_TYPE = 'CMSERLR'
   AND PROCID IN (SELECT C.PROCID FROM ERLR_CASE C JOIN BIZFLOW.PROCS P ON C.PROCID = P.PROCID
                   WHERE P.STATE = 'C'
                     AND (C.ERLR_CASE_STATUS_ID IS NULL OR C.ERLR_CASE_STATUS_ID <> 'Closed'));

UPDATE BIZFLOW.RLVNTDATA
   SET VALUE = 'Completed'
 WHERE RLVNTDATANAME ='caseStatus'
   AND PROCID IN (SELECT C.PROCID FROM ERLR_CASE C JOIN BIZFLOW.PROCS P ON C.PROCID = P.PROCID
                   WHERE P.STATE = 'C'
                     AND (C.ERLR_CASE_STATUS_ID IS NULL OR C.ERLR_CASE_STATUS_ID <> 'Closed'));

UPDATE HHS_CMS_HR.ERLR_GEN
   SET GEN_CASE_STATUS = 'Completed'
 WHERE PROCID IN (SELECT C.PROCID FROM ERLR_CASE C JOIN BIZFLOW.PROCS P ON C.PROCID = P.PROCID
                   WHERE P.STATE = 'C'
                     AND (C.ERLR_CASE_STATUS_ID IS NULL OR C.ERLR_CASE_STATUS_ID <> 'Closed'));

UPDATE HHS_CMS_HR.ERLR_CASE
   SET ERLR_CASE_STATUS_ID = 'Completed'
 WHERE PROCID IN (SELECT C.PROCID FROM ERLR_CASE C JOIN BIZFLOW.PROCS P ON C.PROCID = P.PROCID
                   WHERE P.STATE = 'C'
                     AND (C.ERLR_CASE_STATUS_ID IS NULL OR C.ERLR_CASE_STATUS_ID <> 'Closed'));

COMMIT;
