--------------------------------------------------------
--  DDL for Table ERLR_CASE
--------------------------------------------------------
CREATE TABLE ERLR_CASE
(
	ERLR_CASE_NUMBER NUMBER(20,0)
	, ERLR_JOB_REQ_NUMBER NVARCHAR2(16)
	, PROCID NUMBER(20,0)
	, ERLR_CASE_STATUS_ID NUMBER(20,0)
	, ERLR_CASE_CREATE_DT DATE	
)
;

COMMENT ON COLUMN ERLR_CASE.ERLR_CASE_NUMBER IS 'Case number - Primary Key';
COMMENT ON COLUMN ERLR_CASE.ERLR_JOB_REQ_NUMBER IS 'NEIL request number for the case - current date + sequence number: yyyymmdd-nnnn';
COMMENT ON COLUMN ERLR_CASE.PROCID IS 'Process ID. Foreign key to BIZFLOW.PROCS table';
COMMENT ON COLUMN ERLR_CASE.ERLR_CASE_STATUS_ID IS 'Case status lookup ID';
COMMENT ON COLUMN ERLR_CASE.ERLR_CASE_CREATE_DT IS 'Case creation date';

--------------------------------------------------------
--  DDL for Table ERLR_GEN
--------------------------------------------------------
CREATE TABLE ERLR_GEN
(
	ERLR_CASE_NUMBER NUMBER(20,0)
	, GEN_PRIMARY_SPECIALIST	NVARCHAR2(10)
	, GEN_SECONDARY_SPECIALIST	NVARCHAR2(10)
	, GEN_CUSTOMER_NAME 	NVARCHAR2(150)
	, GEN_CUSTOMER_PHONE	NVARCHAR2(50)
	, GEN_CUSTOMER_ADMIN_CD	NVARCHAR2(8)
	, GEN_CUSTOMER_ADMIN_CD_DESC	NVARCHAR2(50)
	, GEN_EMPLOYEE_NAME	NVARCHAR2(150)
	, GEN_EMPLOYEE_PHONE	NVARCHAR2(50)
	, GEN_EMPLOYEE_ADMIN_CD	NVARCHAR2(8)
	, GEN_EMPLOYEE_ADMIN_CD_DESC	NVARCHAR2(50)
	, GEN_CASE_DESC	NVARCHAR2(500)
	, GEN_CASE_STATUS	 NUMBER(20,0)
	, GEN_CUST_INIT_CONTACT_DT	DATE
	, GEN_PRIMARY_REP_AFFILIATION	 NVARCHAR2(20)
	, GEN_CMS_PRIMARY_REP_ID NVARCHAR2(10)
	, GEN_CMS_PRIMARY_REP_PHONE	NVARCHAR2(50)
	, GEN_NON_CMS_PRIMARY_FNAME	NVARCHAR2(50)
	, GEN_NON_CMS_PRIMARY_MNAME	NVARCHAR2(50)
	, GEN_NON_CMS_PRIMARY_LNAME	NVARCHAR2(50)
	, GEN_NON_CMS_PRIMARY_EMAIL	NVARCHAR2(100)
	, GEN_NON_CMS_PRIMARY_PHONE	NVARCHAR2(50)
	, GEN_NON_CMS_PRIMARY_ORG	NVARCHAR2(100)
	, GEN_NON_CMS_PRIMARY_ADDR	NVARCHAR2(250)
	, GEN_CASE_TYPE	 NUMBER(20,0)
	, GEN_CASE_CATEGORY	NVARCHAR2(200)
	--, GEN_INVESTIGATION	CHAR(1 BYTE) DEFAULT '0'
	, GEN_INVESTIGATION NVARCHAR2(3)
	, GEN_INVESTIGATE_START_DT	DATE
	, GEN_INVESTIGATE_END_DT	DATE
	--, GEN_STD_CONDUCT	CHAR(1 BYTE) DEFAULT '0'
	, GEN_STD_CONDUCT NVARCHAR2(3)
	, GEN_STD_CONDUCT_TYPE	 NVARCHAR2(200)
	, CC_FINAL_ACTION	NVARCHAR2(200)
	, CC_CASE_COMPLETE_DT	DATE

	-- Added
    , GEN_CUSTOMER_EMAIL  NVARCHAR2(100)
    , GEN_EMPLOYEE_EMAIL  NVARCHAR2(100)
      PRICID  NUMBER(20,0)	
)
;

COMMENT ON COLUMN ERLR_GEN.ERLR_CASE_NUMBER IS 'Case number - Primary Key';
COMMENT ON COLUMN ERLR_GEN.GEN_PRIMARY_SPECIALIST IS 'Primary Specialist. BizFlow.Member Table MEMBERID';
COMMENT ON COLUMN ERLR_GEN.GEN_SECONDARY_SPECIALIST IS 'Secondary Specialist. BizFlow.Member Table MEMBERID';
COMMENT ON COLUMN ERLR_GEN.GEN_CUSTOMER_NAME IS 'Customer Contact Name';
COMMENT ON COLUMN ERLR_GEN.GEN_CUSTOMER_PHONE IS 'Customer Phone Number';
COMMENT ON COLUMN ERLR_GEN.GEN_CUSTOMER_ADMIN_CD IS 'Customer Admin Code';
COMMENT ON COLUMN ERLR_GEN.GEN_CUSTOMER_ADMIN_CD_DESC IS 'Customer Organization';
COMMENT ON COLUMN ERLR_GEN.GEN_EMPLOYEE_NAME IS 'Employee Name';
COMMENT ON COLUMN ERLR_GEN.GEN_EMPLOYEE_PHONE IS 'Employee Phone Number';
COMMENT ON COLUMN ERLR_GEN.GEN_EMPLOYEE_ADMIN_CD IS 'Employee Admin Code';
COMMENT ON COLUMN ERLR_GEN.GEN_EMPLOYEE_ADMIN_CD_DESC IS 'Employee Organization';
COMMENT ON COLUMN ERLR_GEN.GEN_CASE_DESC IS 'Case description';
COMMENT ON COLUMN ERLR_GEN.GEN_CASE_STATUS IS 'Case description';
COMMENT ON COLUMN ERLR_GEN.GEN_CUST_INIT_CONTACT_DT IS 'Customer initial contact date';
COMMENT ON COLUMN ERLR_GEN.GEN_PRIMARY_REP_AFFILIATION IS 'Primary representative Affilication';
COMMENT ON COLUMN ERLR_GEN.GEN_CMS_PRIMARY_REP_ID IS 'CMS Primary representative BizFlow member ID';
COMMENT ON COLUMN ERLR_GEN.GEN_CMS_PRIMARY_REP_PHONE IS 'Primary representative phone number';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_FNAME IS 'Non-CMS primary representative first name';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_MNAME IS 'Non-CMS primary representative middle name';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_LNAME IS 'Non-CMS primary representative last name';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_EMAIL IS 'Non-CMS primary representative email';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_PHONE IS 'Non-CMS primary representative phone number';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_ORG IS 'Primary representative organization affilication';
COMMENT ON COLUMN ERLR_GEN.GEN_NON_CMS_PRIMARY_ADDR IS 'Primary representative mailing address';
COMMENT ON COLUMN ERLR_GEN.GEN_CASE_TYPE IS 'Case type';
COMMENT ON COLUMN ERLR_GEN.GEN_CASE_CATEGORY IS 'Case category';
COMMENT ON COLUMN ERLR_GEN.GEN_INVESTIGATION IS 'Whether investigation conducted or not';
COMMENT ON COLUMN ERLR_GEN.GEN_INVESTIGATE_START_DT IS 'Investigation Start Date';
COMMENT ON COLUMN ERLR_GEN.GEN_INVESTIGATE_END_DT IS 'Investigation End Date';
COMMENT ON COLUMN ERLR_GEN.GEN_STD_CONDUCT IS 'Whether the case involves a standards of conduct or not';
COMMENT ON COLUMN ERLR_GEN.GEN_STD_CONDUCT_TYPE IS 'Standards of conduct type';
COMMENT ON COLUMN ERLR_GEN.CC_FINAL_ACTION IS 'Final action when case completed';
COMMENT ON COLUMN ERLR_GEN.CC_CASE_COMPLETE_DT IS 'Case completion date';

--------------------------------------------------------
--  DDL for Table ERLR_CNDT_ISSUE
--------------------------------------------------------
CREATE TABLE ERLR_CNDT_ISSUE
(
	ERLR_CASE_NUMBER NUMBER(20,0)
	, CI_ACTION_TYPE	NVARCHAR2(200)
	-- , CI_ADMIN_INVESTIGATORY_LEAVE	CHAR(1 BYTE) DEFAULT '0'
	, CI_ADMIN_INVESTIGATORY_LEAVE NVARCHAR2(3)
	--, CI_ADMIN_NOTICE_LEAVE	CHAR(1 BYTE) DEFAULT '0'
	, CI_ADMIN_NOTICE_LEAVE NVARCHAR2(3)
	, CI_LEAVE_START_DT	DATE
	, CI_LEAVE_END_DT	DATE
	, CI_APPROVAL_NAME	NVARCHAR2(10)
	, CI_LEAVE_START_DT_2	DATE
	, CI_LEAVE_END_DT_2	DATE
	, CI_APPROVAL_NAME_2	NVARCHAR2(10)
	, CI_PROP_ACTION_ISSUED_DT	DATE
	--, CI_ORAL_PREZ_REQUESTED	CHAR(1 BYTE) DEFAULT '0'
	, CI_ORAL_PREZ_REQUESTED NVARCHAR2(3)
	, CI_ORAL_PREZ_DT	DATE
	--, CI_ORAL_RESPONSE_SUBMITTED	CHAR(1 BYTE) DEFAULT '0'
	, CI_ORAL_RESPONSE_SUBMITTED NVARCHAR2(3)
	, CI_RESPONSE_DUE_DT	DATE
	, CI_WRITTEN_RESPONSE_SBMT_DT	DATE
	, CI_POS_TITLE	NVARCHAR2(50)
	, CI_PPLAN	NVARCHAR2(50)
	, CI_SERIES	NVARCHAR2(50)
	, CI_CURRENT_INFO_GRADE	NVARCHAR2(50)
	, CI_CURRENT_INFO_STEP	NVARCHAR2(50)
	, CI_PROPOSED_POS_TITLE	NVARCHAR2(50)
	, CI_PROPOSED_PPLAN	NVARCHAR2(50)
	, CI_PROPOSED_SERIES	NVARCHAR2(50)
	, CI_PROPOSED_INFO_GRADE	NVARCHAR2(50)
	, CI_PROPOSED_INFO_STEP	NVARCHAR2(50)
	, CI_FINAL_POS_TITLE	NVARCHAR2(50)
	, CI_FINAL_PPLAN	NVARCHAR2(50)
	, CI_FINAL_SERIES	NVARCHAR2(50)
	, CI_FINAL_INFO_GRADE	NVARCHAR2(50)
	, CI_FINAL_INFO_STEP	NVARCHAR2(50)
	, CI_DEMO_FINAL_AGNCY_DCSN	NVARCHAR2(200)
	, CI_DECIDING_OFFCL	NVARCHAR2(10)
	, CI_DECISION_ISSUED_DT	DATE
	, CI_DEMO_FINAL_AGENCY_EFF_DT	DATE
	, CI_NUMB_DAYS	NUMBER(20,0)
	, CI_COUNSEL_TYPE	NVARCHAR2(200)
	, CI_COUNSEL_ISSUED_DT	DATE
	, CI_SICK_LEAVE_ISSUED_DT	DATE
	, CI_RESTRICTION_ISSED_DT	DATE
	, CI_SL_REVIEWED_DT_LIST	VARCHAR2(4000)
	, CI_SL_WARNING_DISCUSS_DT_LIST	VARCHAR2(4000)	
	, CI_SL_WARN_ISSUE	DATE
	, CI_NOTICE_ISSUED_DT	DATE
	, CI_EFFECTIVE_DT	DATE
	, CI_CURRENT_ADMIN_CODE	NVARCHAR2(8)
	, CI_RE_ASSIGNMENT_CURR_ORG	NVARCHAR2(50)
	, CI_FINAL_ADMIN_CODE	NVARCHAR2(8)
	, CI_RE_ASSIGNMENT_FINAL_ORG	NVARCHAR2(50)
	, CI_REMOVAL_PROP_ACTION_DT	DATE
	-- , CI_EMP_NOTICE_LEAVE_PLACED	CHAR(1 BYTE) DEFAULT '0'
	, CI_EMP_NOTICE_LEAVE_PLACED NVARCHAR2(3)
	, CI_REMOVAL_NOTICE_START_DT	DATE
	, CI_REMOVAL_NOTICE_END_DT	DATE
	-- , CI_RMVL_ORAL_PREZ_RQSTED	CHAR(1 BYTE) DEFAULT '0'
	, CI_RMVL_ORAL_PREZ_RQSTED NVARCHAR2(3)
	, CI_REMOVAL_ORAL_PREZ_DT	DATE
	-- , CI_RMVL_WRTN_RESPONSE	CHAR(1 BYTE) DEFAULT '0'
	, CI_RMVL_WRTN_RESPONSE NVARCHAR2(3)
	, CI_WRITTEN_RESPONSE_DUE_DT	DATE
	, CI_WRITTEN_SUBMITTED_DT	DATE
	, CI_RMVL_FINAL_AGNCY_DCSN	NVARCHAR2(200)
	, CI_DECIDING_OFFCL_NAME	NVARCHAR2(10)	
	, CI_RMVL_DATE_DCSN_ISSUED	DATE
	, CI_REMOVAL_EFFECTIVE_DT	DATE
	, CI_RMVL_NUMB_DAYS	NUMBER(20,0)
	, CI_SUSPENTION_TYPE	NUMBER(20,0)
	, CI_SUSP_PROP_ACTION_DT	DATE
	-- , CI_SUSP_ORAL_PREZ_REQUESTED	CHAR(1 BYTE) DEFAULT '0'
	, CI_SUSP_ORAL_PREZ_REQUESTED NVARCHAR2(3)
	, CI_SUSP_ORAL_PREZ_DT	DATE
	-- , CI_SUSP_WRITTEN_RESP	CHAR(1 BYTE) DEFAULT '0'
	, CI_SUSP_WRITTEN_RESP NVARCHAR2(3)
	, CI_SUSP_WRITTEN_RESP_DUE_DT	DATE
	, CI_SUSP_WRITTEN_RESP_DT	DATE
	, CI_SUSP_FINAL_AGNCY_DCSN	NVARCHAR2(200)
	, CI_SUSP_DECIDING_OFFCL_NAME	NVARCHAR2(10)
	, CI_SUSP_DECISION_ISSUED_DT	DATE
	, CI_SUSP_EFFECTIVE_DECISION_DT	DATE
	, CI_SUS_NUMB_DAYS	NUMBER(20,0)
	, CI_REPRIMAND_ISSUE_DT	DATE
	-- , CI_EMP_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, CI_EMP_APPEAL_DECISION NVARCHAR2(3)
)
;

COMMENT ON COLUMN ERLR_CNDT_ISSUE.ERLR_CASE_NUMBER IS 'Case Number - Primary Key';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ACTION_TYPE IS 'Lookup ID for Action Type';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ADMIN_INVESTIGATORY_LEAVE IS 'Whether it is about Investigatory Leave or not. 1=true, 0=false';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ADMIN_NOTICE_LEAVE IS 'Whether it is about Notice Leave or not. 1=true, 0=false';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_LEAVE_START_DT IS 'Leave Start Date for admin leave investigatory';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_LEAVE_END_DT IS 'Leave End Date for admin leave investigatory';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_APPROVAL_NAME IS 'Approving Official bizFlow Member ID for admin leave investigatory';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_LEAVE_START_DT_2 IS 'Leave Start Date for admin leave notice';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_LEAVE_END_DT_2 IS 'Leave End Date for admin leave notice';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_APPROVAL_NAME_2 IS 'Approving Official BizFlow Member ID for admin leave notice';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROP_ACTION_ISSUED_DT IS 'Date Proposed Action Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ORAL_PREZ_REQUESTED IS 'Oral Presentation Requested?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ORAL_PREZ_DT IS 'Date of Oral Presentation';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_ORAL_RESPONSE_SUBMITTED IS 'Written Response Submitted?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RESPONSE_DUE_DT IS 'Date Written Response Due';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_WRITTEN_RESPONSE_SBMT_DT IS 'Date Written Response Submitted';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_POS_TITLE IS 'Current Position Title';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PPLAN IS 'Lookup ID for Current Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SERIES IS 'Lookup ID for Current Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_CURRENT_INFO_GRADE IS 'Lookup ID for Current Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_CURRENT_INFO_STEP IS 'Lookup ID for Current Step';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_POS_TITLE IS 'Proposed Position Title';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_PPLAN IS 'Lookup ID for Proposed Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_SERIES IS 'Lookup ID for Proposed Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_INFO_GRADE IS 'Lookup ID for Proposed Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_PROPOSED_INFO_STEP IS 'Lookup ID for Proposed Step';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_POS_TITLE IS 'Final Position Title';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_PPLAN IS 'Lookup ID for Final Pay Plan';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_SERIES IS 'Lookup ID for Final Job Series';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_INFO_GRADE IS 'Lookup ID for Final Grade';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_INFO_STEP IS 'Lookup ID for Final Step';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_DEMO_FINAL_AGNCY_DCSN IS 'Lookup ID for Final Agency Decision';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_DECIDING_OFFCL IS 'Deciding Official BiaFlow member ID';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_DECISION_ISSUED_DT IS 'Date Decision Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_DEMO_FINAL_AGENCY_EFF_DT IS 'Effective Date of Action';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_NUMB_DAYS IS 'Number of Days';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_COUNSEL_TYPE IS 'Lookup ID for Counseling Type';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_COUNSEL_ISSUED_DT IS 'Date Counseling Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SICK_LEAVE_ISSUED_DT IS 'Date Leave Warning Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RESTRICTION_ISSED_DT IS 'Date Restriction Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SL_REVIEWED_DT_LIST IS 'Previous Date Extended history';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SL_WARNING_DISCUSS_DT_LIST IS 'Previous Date Manager Discussed Leave with Employee history';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SL_WARN_ISSUE IS 'Date Leave Warning Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_NOTICE_ISSUED_DT IS 'Date Notice Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_EFFECTIVE_DT IS 'Effective Date of Reassignment';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_CURRENT_ADMIN_CODE IS 'Current Administrative Code';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RE_ASSIGNMENT_CURR_ORG IS 'Current Organization Name';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_FINAL_ADMIN_CODE IS 'Final Administrative Code';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RE_ASSIGNMENT_FINAL_ORG IS 'Final Organization Name';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REMOVAL_PROP_ACTION_DT IS 'Date Proposed Action Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_EMP_NOTICE_LEAVE_PLACED IS 'Was Employee Placed on Notice Leave?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REMOVAL_NOTICE_START_DT IS 'Notice Leave Start Date';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REMOVAL_NOTICE_END_DT IS 'Notice Leave End Date';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RMVL_ORAL_PREZ_RQSTED IS 'Oral Presentation Requested?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REMOVAL_ORAL_PREZ_DT IS 'Date of Oral Presention';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RMVL_WRTN_RESPONSE IS 'Written Response Submitted?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_WRITTEN_RESPONSE_DUE_DT IS 'Date Written Response Due';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_WRITTEN_SUBMITTED_DT IS 'Date Written Response Submitted';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RMVL_FINAL_AGNCY_DCSN IS 'Final Agency Decision';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_DECIDING_OFFCL_NAME IS 'Deciding Official BizFlow Member ID';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RMVL_DATE_DCSN_ISSUED IS 'Date Decision Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REMOVAL_EFFECTIVE_DT IS 'Effective Date of Action';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_RMVL_NUMB_DAYS IS 'Number of Days';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSPENTION_TYPE IS 'Suspension Type';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_PROP_ACTION_DT IS 'Date Proposed Action Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_ORAL_PREZ_REQUESTED IS 'Oral Presentation Requested?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_ORAL_PREZ_DT IS 'Date of Oral Presentation';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_WRITTEN_RESP IS 'Written Response Submitted?';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_WRITTEN_RESP_DUE_DT IS 'Date Written Response Due';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_WRITTEN_RESP_DT IS 'Date Written Respnse Submitted';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_FINAL_AGNCY_DCSN IS 'Final agency Decision';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_DECIDING_OFFCL_NAME IS 'Deciding Official BizFlow Member ID';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_DECISION_ISSUED_DT IS 'Date Decision Issued to Employee';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUSP_EFFECTIVE_DECISION_DT IS 'Effective Date of Action';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_SUS_NUMB_DAYS IS 'Number of Days';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_REPRIMAND_ISSUE_DT IS 'Date Reprimand Issued';
COMMENT ON COLUMN ERLR_CNDT_ISSUE.CI_EMP_APPEAL_DECISION IS 'Did Employee Appeal Decision?';

--------------------------------------------------------
--  DDL for Table ERLR_APPEAL
--------------------------------------------------------
CREATE TABLE ERLR_APPEAL
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, AP_ERLR_APPEAL_TYPE	NVARCHAR2(200)
	, AP_ERLR_APPEAL_FILE_DT	DATE
	--, AP_ERLR_APPEAL_TIMING	CHAR(1 BYTE) DEFAULT '0'
	, AP_ERLR_APPEAL_TIMING NVARCHAR2(3)
	-- , AP_APPEAL_HEARING_REQUESTED	CHAR(1 BYTE) DEFAULT '0'
	, AP_APPEAL_HEARING_REQUESTED NVARCHAR2(3)
	, AP_ARBITRATOR_LAST_NAME	NVARCHAR2(50)
	, AP_ARBITRATOR_FIRST_NAME	NVARCHAR2(50)
	, AP_ARBITRATOR_MIDDLE_NAME	NVARCHAR2(50)
	, AP_ARBITRATOR_EMAIL	NVARCHAR2(100)
	, AP_ARBITRATOR_PHONE_NUM	NVARCHAR2(50)
	, AP_ARBITRATOR_ORG_AFFIL	NVARCHAR2(50)
	, AP_ARBITRATOR_MAILING_ADDR	NVARCHAR2(250)
	, AP_ERLR_PREHEARING_DT	DATE
	, AP_ERLR_HEARING_DT	DATE	
	, AP_POSTHEARING_BRIEF_DUE	DATE
	, AP_FINAL_ARBITRATOR_DCSN_DT	DATE
	-- , AP_ERLR_EXCEPTION_FILED	CHAR(1 BYTE) DEFAULT '0'
	, AP_ERLR_EXCEPTION_FILED NVARCHAR2(3)
	, AP_ERLR_EXCEPTION_FILE_DT	DATE
	, AP_RESPON_TO_EXCEPT_DUE	DATE
	, AP_FINAL_FLRA_DECISION_DT	DATE
	, AP_ERLR_STEP_DECISION_DT	DATE
	-- , AP_ERLR_ARBITRATION_INVOKED	CHAR(1 BYTE) DEFAULT '0'
	, AP_ERLR_ARBITRATION_INVOKED NVARCHAR2(3)
	, AP_ARBITRATOR_LAST_NAME_3	NVARCHAR2(50)
	, AP_ARBITRATOR_FIRST_NAME_3	NVARCHAR2(50)
	, AP_ARBITRATOR_MIDDLE_NAME_3	NVARCHAR2(50)
	, AP_ARBITRATOR_EMAIL_3	NVARCHAR2(100)
	, AP_ARBITRATOR_PHONE_NUM_3	NVARCHAR2(50)
	, AP_ARBITRATOR_ORG_AFFIL_3	NVARCHAR2(100)
	, AP_ARBITRATION_MAILING_ADDR_3	NVARCHAR2(250)
	, AP_ERLR_PREHEARING_DT_2	DATE
	, AP_ERLR_HEARING_DT_2	DATE
	, AP_POSTHEARING_BRIEF_DUE_2	DATE
	, AP_FINAL_ARBITRATOR_DCSN_DT_2	DATE
	-- , AP_ERLR_EXCEPTION_FILED_2	CHAR(1 BYTE) DEFAULT '0'
	, AP_ERLR_EXCEPTION_FILED_2 NVARCHAR2(3)
	, AP_ERLR_EXCEPTION_FILE_DT_2	DATE
	, AP_RESPON_TO_EXCEPT_DUE_2	DATE
	, AP_FINAL_FLRA_DECISION_DT_2	DATE
	, AP_ARBITRATOR_LAST_NAME_2	NVARCHAR2(50)
	, AP_ARBITRATOR_FIRST_NAME_2	NVARCHAR2(50)
	, AP_ARBITRATOR_MIDDLE_NAME_2	NVARCHAR2(50)
	, AP_ARBITRATOR_EMAIL_2	NVARCHAR2(100)
	, AP_ARBITRATOR_PHONE_NUM_2	NVARCHAR2(50)
	, AP_ARBITRATOR_ORG_AFFIL_2	NVARCHAR2(100)
	, AP_ARBITRATION_MAILING_ADDR_2	NVARCHAR2(250)
	, AP_ERLR_PREHEARING_DT_SC	DATE
	, AP_ERLR_HEARING_DT_SC	DATE
	, AP_ARBITRATOR_LAST_NAME_4	NVARCHAR2(50)
	, AP_ARBITRATOR_FIRST_NAME_4	NVARCHAR2(50)
	, AP_ARBITRATOR_MIDDLE_NAME_4	NVARCHAR2(50)
	, AP_ARBITRATOR_EMAIL_4	NVARCHAR2(100)
	, AP_ARBITRATOR_PHONE_NUM_4	NVARCHAR2(50)
	, AP_ARBITRATOR_ORG_AFFIL_4	NVARCHAR2(100)
	, AP_ARBITRATOR_MAILING_ADDR_4	NVARCHAR2(250)
	, AP_DT_SETTLEMENT_DISCUSSION	DATE
	, AP_DT_PREHEARING_DISCLOSURE	DATE
    , AP_DT_AGNCY_FILE_RESPON_DUE   DATE
    , AP_ERLR_PREHEARING_DT_MSPB    DATE
	-- , AP_WAS_DISCOVERY_INITIATED	CHAR(1 BYTE) DEFAULT '0'
	, AP_WAS_DISCOVERY_INITIATED NVARCHAR2(3)
	, AP_ERLR_DT_DISCOVERY_DUE	DATE
	, AP_ERLR_HEARING_DT_MSPB	DATE
	, AP_PETITION_FILE_DT_MSPB	DATE
	-- , AP_WAS_PETITION_FILED_MSPB	CHAR(1 BYTE) DEFAULT '0'
	, AP_WAS_PETITION_FILED_MSPB NVARCHAR2(3)
	, AP_INITIAL_DECISION_DT_MSPB	DATE
	, AP_FINAL_BOARD_DCSN_DT_MSPB	DATE
	, AP_DT_SETTLEMENT_DISCUSSION_2	DATE
	, AP_DT_PREHEARING_DISCLOSURE_2	DATE
	, AP_DT_AGNCY_FILE_RESPON_DUE_2	DATE
	, AP_ERLR_PREHEARING_DT_FLRA	DATE
	, AP_ERLR_HEARING_DT_FLRA	DATE
	, AP_INITIAL_DECISION_DT_FLRA	DATE
	-- , AP_WAS_PETITION_FILED_FLRA	CHAR(1 BYTE) DEFAULT '0'
	, AP_WAS_PETITION_FILED_FLRA NVARCHAR2(3)
	, AP_PETITION_FILE_DT_FLRA	DATE
	, AP_FINAL_BOARD_DCSN_DT_FLRA	DATE
)
;

--------------------------------------------------------
--  DDL for Table ERLR_WGI_DNL
--------------------------------------------------------
CREATE TABLE ERLR_WGI_DNL
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, WGI_DTR_DENIAL_ISSUED_DT	DATE
	-- , WGI_DTR_EMP_REQ_RECON	CHAR(1 BYTE) DEFAULT '0'
	, WGI_DTR_EMP_REQ_RECON NVARCHAR2(3)
	, WGI_DTR_RECON_REQ_DT	DATE
	, WGI_DTR_RECON_ISSUE_DT	DATE
	-- , WGI_DTR_DENIED	CHAR(1 BYTE) DEFAULT '0'
	, WGI_DTR_DENIED NVARCHAR2(3)
	, WGI_DTR_DENIAL_ISSUE_TO_EMP_DT	DATE
	, WGI_RVW_REDTR_NOTI_ISSUED_DT	DATE
	-- , WGI_REVIEW_DTR_FAVORABLE	CHAR(1 BYTE) DEFAULT '0'
	, WGI_REVIEW_DTR_FAVORABLE NVARCHAR2(3)
	-- , WGI_REVIEW_EMP_REQ_RECON	CHAR(1 BYTE) DEFAULT '0'
	, WGI_REVIEW_EMP_REQ_RECON NVARCHAR2(3)
	, WGI_REVIEW_RECON_REQ_DT	DATE
	, WGI_REVIEW_RECON_ISSUE_DT	DATE
	-- , WGI_REVIEW_DENIED	CHAR(1 BYTE) DEFAULT '0'
	, WGI_REVIEW_DENIED NVARCHAR2(3)
	-- , WGI_EMP_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, WGI_EMP_APPEAL_DECISION NVARCHAR2(3)
)
;

COMMENT ON COLUMN ERLR_WGI_DNL.ERLR_CASE_NUMBER IS 'Case Number - Primary Key';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_DENIAL_ISSUED_DT IS 'Date WGI Denial Issued';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_EMP_REQ_RECON IS 'Did Employee Request Reconsideration?';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_RECON_REQ_DT IS 'Date Reconsideration Requested';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_RECON_ISSUE_DT IS 'Date Reconsideration Decision Issued';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_DENIED IS 'Was WGI Denied?';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_DTR_DENIAL_ISSUE_TO_EMP_DT IS 'Date Denial Issued to Employee';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_RVW_REDTR_NOTI_ISSUED_DT IS 'Date Redetermination Notice Issued';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_REVIEW_DTR_FAVORABLE IS 'Was Determination Favorable?';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_REVIEW_EMP_REQ_RECON IS 'Did Employee Request Reconsideration?';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_REVIEW_RECON_REQ_DT IS 'Date Reconsideration Requested';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_REVIEW_RECON_ISSUE_DT IS 'Date Reconsideration Decision Issued';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_REVIEW_DENIED IS 'Was WGI Denied?';
COMMENT ON COLUMN ERLR_WGI_DNL.WGI_EMP_APPEAL_DECISION IS 'Did Employee Appeal the Decision?';

--------------------------------------------------------
--  DDL for Table ERLR_MEDDOC
--------------------------------------------------------
CREATE TABLE ERLR_MEDDOC
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, MD_REQUEST_REASON	NUMBER(20,0)
	, MD_MED_DOC_SBMT_DEADLINE_DT	DATE
	, MD_FMLA_DOC_SBMT_DT	DATE
	, MD_FMLA_BEGIN_DT	DATE
	-- , MD_FMLA_APROVED	CHAR(1 BYTE) DEFAULT '0'
	, MD_FMLA_APROVED NVARCHAR2(3)
	, MD_FMLA_DISAPRV_REASON	NUMBER(20,0)
	-- , MD_FMLA_GRIEVANCE	CHAR(1 BYTE) DEFAULT '0'
	, MD_FMLA_GRIEVANCE NVARCHAR2(3)
	-- , MD_MEDEXAM_EXTENDED	CHAR(1 BYTE) DEFAULT '0'
	, MD_MEDEXAM_EXTENDED NVARCHAR2(3)
	-- , MD_MEDEXAM_ACCEPTED	CHAR(1 BYTE) DEFAULT '0'
	, MD_MEDEXAM_ACCEPTED NVARCHAR2(3)
	, MD_MEDEXAM_RECEIVED_DT	DATE
	-- , MD_DOC_SUBMITTED	CHAR(1 BYTE) DEFAULT '0'
	, MD_DOC_SUBMITTED NVARCHAR2(3)
	, MD_DOC_SBMT_DT	DATE
	-- , MD_DOC_SBMT_FOH	CHAR(1 BYTE) DEFAULT '0'
	, MD_DOC_SBMT_FOH NVARCHAR2(3)
	, MD_DOC_REVIEW_OUTCOME	NVARCHAR2(140)
	-- , MD_DOC_ADMTV_ACCEPTABLE	CHAR(1 BYTE) DEFAULT '0'
	, MD_DOC_ADMTV_ACCEPTABLE NVARCHAR2(3)
	, MD_DOC_ADMTV_REJECT_REASON	NUMBER(20,0)
)
;

COMMENT ON COLUMN ERLR_MEDDOC.ERLR_CASE_NUMBER IS 'Case Number - Primary Key';
COMMENT ON COLUMN ERLR_MEDDOC.MD_REQUEST_REASON IS 'Reason for Request';
COMMENT ON COLUMN ERLR_MEDDOC.MD_MED_DOC_SBMT_DEADLINE_DT IS 'Medical Documentation Submission Deadline';
COMMENT ON COLUMN ERLR_MEDDOC.MD_FMLA_DOC_SBMT_DT IS 'Date Documentation Submitted';
COMMENT ON COLUMN ERLR_MEDDOC.MD_FMLA_BEGIN_DT IS 'Date FMLA Began';
COMMENT ON COLUMN ERLR_MEDDOC.MD_FMLA_APROVED IS 'Was FMLA Approved?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_FMLA_DISAPRV_REASON IS 'Disapproval Reason';
COMMENT ON COLUMN ERLR_MEDDOC.MD_FMLA_GRIEVANCE IS 'Did Employee File a Grievance?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_MEDEXAM_EXTENDED IS 'Was an Offer of a Medical Exam Extended?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_MEDEXAM_ACCEPTED IS 'Was Offer Accepted?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_MEDEXAM_RECEIVED_DT IS 'Date Received from CMS Healthcare Provider';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_SUBMITTED IS 'Was Documentation Submitted?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_SBMT_DT IS 'Date Documentation Submitted';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_SBMT_FOH IS 'Was Documentation Submitted for FOH Review?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_REVIEW_OUTCOME IS 'Outcome of Documentation Review';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_ADMTV_ACCEPTABLE IS 'Was Documentation Administratively Acceptable?';
COMMENT ON COLUMN ERLR_MEDDOC.MD_DOC_ADMTV_REJECT_REASON IS 'Documentation Reject Reason';


--------------------------------------------------------
--  DDL for Table ERLR_PERF_ISSUE
--------------------------------------------------------
CREATE TABLE ERLR_PERF_ISSUE
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, PI_ACTION_TYPE	NUMBER(20,0)
	, PI_NEXT_WGI_DUE_DT	DATE
	, PI_PERF_COUNSEL_ISSUE_DT	DATE
	-- , PI_CNSL_GRV_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, PI_CNSL_GRV_DECISION NVARCHAR2(3)
	, PI_DMTN_PRPS_ACTN_ISSUE_DT	DATE
	-- , PI_DMTN_ORAL_PRSNT_REQ	CHAR(1 BYTE) DEFAULT '0'
	, PI_DMTN_ORAL_PRSNT_REQ NVARCHAR2(3)
	, PI_DMTN_ORAL_PRSNT_DT	DATE
	-- , PI_DMTN_WRTN_RESP_SBMT	CHAR(1 BYTE) DEFAULT '0'
	, PI_DMTN_WRTN_RESP_SBMT NVARCHAR2(3)
	, PI_DMTN_WRTN_RESP_DUE_DT	DATE
	, PI_DMTN_WRTN_RESP_SBMT_DT	DATE
	, PI_DMTN_CUR_POS_TITLE	NVARCHAR2(50)
	, PI_DMTN_CUR_PAY_PLAN	NVARCHAR2(50)
	, PI_DMTN_CUR_JOB_SERIES	NVARCHAR2(50)
	, PI_DMTN_CUR_GRADE	NVARCHAR2(50)
	, PI_DMTN_CUR_STEP	NVARCHAR2(50)
	, PI_DMTN_PRPS_POS_TITLE	NVARCHAR2(50)
	, PI_DMTN_PRPS_PAY_PLAN	NVARCHAR2(50)
	, PI_DMTN_PRPS_JOB_SERIES	NVARCHAR2(50)
	, PI_DMTN_PRPS_GRADE	NVARCHAR2(50)
	, PI_DMTN_PRP_STEP	NVARCHAR2(50)
	, PI_DMTN_FIN_POS_TITLE	NVARCHAR2(50)
	, PI_DMTN_FIN_PAY_PLAN	NVARCHAR2(50)
	, PI_DMTN_FIN_JOB_SERIES	NVARCHAR2(50)
	, PI_DMTN_FIN_GRADE	NVARCHAR2(50)
	, PI_DMTN_FIN_STEP	NVARCHAR2(50)
	, PI_DMTN_FIN_AGCY_DECISION	NUMBER(20,0)
	, PI_DMTN_FIN_DECIDING_OFC NVARCHAR2(10)
	, PI_DMTN_FIN_DECISION_ISSUE_DT	DATE
	, PI_DMTN_DECISION_EFF_DT	DATE
	-- , PI_DMTN_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, PI_DMTN_APPEAL_DECISION NVARCHAR2(3)
	-- , PI_PIP_RSNBL_ACMDTN	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_RSNBL_ACMDTN NVARCHAR2(3)
	-- , PI_PIP_EMPL_SBMT_MEDDOC	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_EMPL_SBMT_MEDDOC NVARCHAR2(3)
	-- , PI_PIP_DOC_SBMT_FOH_RVW	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_DOC_SBMT_FOH_RVW NVARCHAR2(3)
	-- , PI_PIP_WGI_WTHLD	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_WGI_WTHLD NVARCHAR2(3)
	, PI_PIP_WGI_RVW_DT	DATE
	, PI_PIP_MEDDOC_RVW_OUTCOME	NVARCHAR2(140)
	, PI_PIP_START_DT	DATE
	, PI_PIP_END_DT	DATE
	, PI_PIP_EXT_END_DT	DATE
	, PI_PIP_EXT_END_REASON	NVARCHAR2(200)
	, PI_PIP_EXT_END_NOTIFY_DT	DATE
	, PI_PIP_EXT_DT_LIST	VARCHAR2(4000)
	, PI_PIP_ACTUAL_DT	DATE
	-- , PI_PIP_END_PRIOR_TO_PLAN	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_END_PRIOR_TO_PLAN NVARCHAR2(3)
	, PI_PIP_END_PRIOR_TO_PLAN_RSN	NUMBER(20,0)
	-- , PI_PIP_SUCCESS_CMPLT	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_SUCCESS_CMPLT NVARCHAR2(3)
	--, PI_PIP_NOT_CMPLT_RSN	NVARCHAR2(200)
	--, PI_PIP_NOT_CMPLT_OTHR_RSN	NVARCHAR2(100)
	, PI_PIP_PMAP_RTNG_SIGN_DT	DATE
	, PI_PIP_PMAP_RVW_SIGN_DT	DATE
	, PI_PIP_PRPS_ACTN	NUMBER(20,0)
	, PI_PIP_PRPS_ISSUE_DT	DATE
	-- , PI_PIP_ORAL_PRSNT_REQ	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_ORAL_PRSNT_REQ NVARCHAR2(3)
	, PI_PIP_ORAL_PRSNT_DT	DATE
	-- , PI_PIP_WRTN_RESP_SBMT	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_WRTN_RESP_SBMT NVARCHAR2(3)
	, PI_PIP_WRTN_RESP_DUE_DT	DATE
	, PI_PIP_WRTN_SBMT_DT	DATE
	, PI_PIP_FIN_AGCY_DECISION	NUMBER(20,0)
	, PI_PIP_DECIDING_OFFICAL	NVARCHAR2(10)
	, PI_PIP_FIN_AGCY_DECISION_DT	DATE
	, PI_PIP_DECISION_ISSUE_DT	DATE
	, PI_PIP_EFF_ACTN_DT	DATE
	-- , PI_PIP_EMPL_GRIEVANCE	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_EMPL_GRIEVANCE NVARCHAR2(3)
	-- , PI_PIP_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, PI_PIP_APPEAL_DECISION NVARCHAR2(3)
	, PI_REASGN_NOTICE_DT	DATE
	, PI_REASGN_EFF_DT	DATE
	, PI_REASGN_CUR_ADMIN_CD	NVARCHAR2(8)
	, PI_REASGN_CUR_ORG_NM	NVARCHAR2(50)
	, PI_REASGN_FIN_ADMIN_CD	NVARCHAR2(8)
	, PI_REASGN_FIN_ORG_NM	NVARCHAR2(50)
	, PI_RMV_PRPS_ACTN_ISSUE_DT	DATE
	-- , PI_RMV_EMPL_NOTC_LEV	CHAR(1 BYTE) DEFAULT '0'
	, PI_RMV_EMPL_NOTC_LEV NVARCHAR2(3)
	, PI_RMV_NOTC_LEV_START_DT	DATE
	, PI_RMV_NOTC_LEV_END_DT	DATE
	-- , PI_RMV_ORAL_PRSNT_REQ	CHAR(1 BYTE) DEFAULT '0'
	, PI_RMV_ORAL_PRSNT_REQ NVARCHAR2(3)
	, PI_RMV_ORAL_PRSNT_DT	DATE
	, PI_RMV_WRTN_RESP_DUE_DT	DATE
	, PI_RMV_WRTN_RESP_SBMT_DT	DATE
	, PI_RMV_FIN_AGCY_DECISION	NUMBER(20,0)
	, PI_RMV_FIN_DECIDING_OFC	NVARCHAR2(10)
	, PI_RMV_DECISION_ISSUE_DT	DATE
	, PI_RMV_EFF_DT	DATE
	, PI_RMV_NUM_DAYS	NUMBER(20,0)
	-- , PI_RMV_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, PI_RMV_APPEAL_DECISION NVARCHAR2(3)
	, PI_WRTN_NRTV_RVW_TYPE	NUMBER(20,0)
	, PI_WNR_SPCLST_RVW_CMPLT_DT	DATE
	, PI_WNR_MGR_RVW_RTNG_DT	DATE
	, PI_WNR_CRITICAL_ELM	NVARCHAR2(250)
	, PI_WNR_FIN_RATING	NVARCHAR2(200)
	, PI_WNR_RVW_OFC_CONCUR_DT	DATE
	-- , PI_WNR_WGI_WTHLD	CHAR(1 BYTE) DEFAULT '0'
	, PI_WNR_WGI_WTHLD NVARCHAR2(3)
	, PI_WNR_WGI_RVW_DT	DATE
)
;

--------------------------------------------------------
--  DDL for Table ERLR_INVESTIGATION
--------------------------------------------------------
CREATE TABLE ERLR_INVESTIGATION
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, INVESTIGATION_TYPE	NVARCHAR2(200)
	-- , I_MISCONDUCT_FOUND	CHAR(1 BYTE) DEFAULT '0'
	, I_MISCONDUCT_FOUND NVARCHAR2(3)
)
;

COMMENT ON COLUMN ERLR_INVESTIGATION.ERLR_CASE_NUMBER IS 'Case Number - Primary Key';
COMMENT ON COLUMN ERLR_INVESTIGATION.INVESTIGATION_TYPE IS 'Lookup ID for Type of Investigation';
COMMENT ON COLUMN ERLR_INVESTIGATION.I_MISCONDUCT_FOUND IS 'Was Misconduct Found?';
--------------------------------------------------------
--  DDL for Table ERLR_INFO_REQUEST
--------------------------------------------------------
CREATE TABLE ERLR_INFO_REQUEST
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, IR_REQUESTER	NVARCHAR2(20)
	, IR_CMS_REQUESTER_NAME	NVARCHAR2(10)
	, IR_CMS_REQUESTER_PHONE	NVARCHAR2(50)
	, IR_NCMS_REQUESTER_LAST_NAME	NVARCHAR2(50)
	, IR_NCMS_REQUESTER_FIRST_NAME	NVARCHAR2(50)
	, IR_NON_CMS_REQUESTER_PHONE	NVARCHAR2(50)
	, IR_NON_CMS_REQUESTER_EMAIL	NVARCHAR2(100)
	, IR_NCMS_REQUESTER_ORG_AFFIL	NVARCHAR2(50)
	, IR_SUBMIT_DT	DATE
	, IR_MEET_PTCLRIZED_NEED_STND NVARCHAR2(3)
	, IR_RSNABLY_AVAIL_N_NECESSARY NVARCHAR2(3)
	, IR_PRTCT_DISCLOSURE_BY_LAW NVARCHAR2(3)
	, IR_MAINTAINED_BY_AGENCY NVARCHAR2(3)
	, IR_COLLECTIVE_BARGAINING_UNIT NVARCHAR2(3)
	, IR_APPROVE	CHAR(1 BYTE) DEFAULT '0'
	, IR_DENIAL_NOTICE_DT_LIST	VARCHAR2(4000)
	, IR_APPEAL_DENIAL NVARCHAR2(3)
  	, IR_NCMS_REQUESTER_MN  NVARCHAR2(50)
  	, IR_PROVIDE_DT DATE	
)
;

--------------------------------------------------------
--  DDL for Table ERLR_3RDPARTY_HEAR
--------------------------------------------------------
CREATE TABLE ERLR_3RDPARTY_HEAR
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, THRD_PRTY_APPEAL_TYPE	NVARCHAR2(200)
	, THRD_PRTY_APPEAL_FILE_DT	DATE
	, THRD_PRTY_ASSISTANCE_REQ_DT	DATE
	, THRD_PRTY_HEARING_TIMING	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_HEARING_REQUESTED	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_STEP_DECISION_DT	DATE
	, THRD_PRTY_ARBITRATION_INVOKED	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_ARBIT_LNM_3	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_FNM_3	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_MNM_3	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_EMAIL_3	NVARCHAR2(100)
	, THRD_ERLR_ARBIT_PHONE_NUM_3	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_ORG_AFFIL_3	NVARCHAR2(100)
	, THRD_PRTY_ARBIT_MAILING_ADDR_3	NVARCHAR2(250)
	, THRD_PRTY_PREHEARING_DT_2	DATE
	, THRD_PRTY_HEARING_DT_2	DATE
	, THRD_PRTY_POSTHEAR_BRIEF_DUE_2	DATE
	, THRD_PRTY_FNL_ARBIT_DCSN_DT_2	DATE
	, THRD_PRTY_EXCEPTION_FILED_2	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_EXCEPTION_FILE_DT_2	DATE
	, THRD_PRTY_RSPS_TO_EXCPT_DUE_2	DATE
	, THRD_PRTY_FNL_FLRA_DCSN_DT_2	DATE
	, THRD_PRTY_ARBIT_LNM	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_FNM	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_MNM	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_EMAIL	NVARCHAR2(100)
	, THRD_ERLR_ARBIT_PHONE_NUM	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_ORG_AFFIL	NVARCHAR2(100)
	, THRD_PRTY_ARBIT_MAILING_ADDR	NVARCHAR2(250)
	, THRD_PRTY_PREHEARING_DT	DATE
	, THRD_PRTY_HEARING_DT	DATE
	, THRD_PRTY_POSTHEAR_BRIEF_DUE	DATE
	, THRD_PRTY_FNL_ARBIT_DCSN_DT	DATE
	, THRD_PRTY_EXCEPTION_FILED	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_EXCEPTION_FILE_DT	DATE
	, THRD_PRTY_RSPS_TO_EXCPT_DUE	DATE
	, THRD_PRTY_FNL_FLRA_DCSN_DT	DATE
	, THRD_PRTY_ARBIT_LNM_4	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_FNM_4	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_MNM_4	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_EMAIL_4	NVARCHAR2(100)
	, THRD_ERLR_ARBIT_PHONE_NUM_4	NVARCHAR2(50)
	, THRD_PRTY_ARBIT_ORG_AFFIL_4	NVARCHAR2(100)
	, THRD_PRTY_ARBIT_MAILING_ADDR_4	NVARCHAR2(250)
	, THRD_PRTY_DT_STLMNT_DSCUSN	DATE
	, THRD_PRTY_DT_PREHEAR_DSCLS	DATE
	, THRD_PRTY_DT_AGNCY_RSP_DUE	DATE
	, THRD_PRTY_PREHEARING_DT_MSPB	DATE
	, THRD_PRTY_WAS_DSCVRY_INIT	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_DT_DISCOVERY_DUE	DATE
	, THRD_PRTY_HEARING_DT_MSPB	DATE
	, THRD_PRTY_INIT_DCSN_DT_MSPB	DATE
	, THRD_PRTY_WAS_PETI_FILED_MSPB	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_PETITION_RV_DT	DATE
	, THRD_PRTY_FNL_BRD_DCSN_DT_MSPB	DATE
	, THRD_PRTY_DT_STLMNT_DSCUSN_2	DATE
	, THRD_PRTY_DT_PREHEAR_DSCLS_2	DATE
	, THRD_PRTY_PREHEARING_CONF	DATE
	, THRD_PRTY_HEARING_DT_FLRA	DATE
	, THRD_PRTY_DECISION_DT_FLRA	DATE
	, THRD_PRTY_TIMELY_REQ	CHAR(1 BYTE) DEFAULT '0'
	, THRD_PRTY_PROC_ORDER	NVARCHAR2(2000)
	, THRD_PRTY_PANEL_MEMBER_LNAME	NVARCHAR2(50)
	, THRD_PRTY_PANEL_MEMBER_FNAME	NVARCHAR2(50)
	, THRD_PRTY_PANEL_MEMBER_MNAME	NVARCHAR2(50)
	, THRD_PRTY_PANEL_MEMBER_EMAIL	NVARCHAR2(100)
	, THRD_PRTY_PANEL_MEMBER_PHONE	NVARCHAR2(50)
	, THRD_PRTY_PANEL_MEMBER_ORG	NVARCHAR2(100)
	, THRD_PRTY_PANEL_MEMBER_MAILING	NVARCHAR2(250)
	, THRD_PRTY_PANEL_DESCR	NVARCHAR2(500)

)
;

--------------------------------------------------------
--  DDL for Table ERLE_PROB_ACTION
--------------------------------------------------------
CREATE TABLE ERLR_PROB_ACTION
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, PPA_ACTION_TYPE	NVARCHAR2(200)
	, PPA_TERMINATION_TYPE	NVARCHAR2(200)
	, PPA_TERM_PROP_ACTION_DT	DATE
	--, PPA_TERM_ORAL_PREZ_REQUESTED	CHAR(1 BYTE) DEFAULT '0'	
	, PPA_TERM_ORAL_PREZ_REQUESTED NVARCHAR2(3)	
	, PPA_TERM_ORAL_PREZ_DT	DATE
	--, PPA_TERM_WRITTEN_RESP	CHAR(1 BYTE) DEFAULT '0'
	, PPA_TERM_WRITTEN_RESP	NVARCHAR2(3)
	, PPA_TERM_WRITTEN_RESP_DUE_DT	DATE
	, PPA_TERM_WRITTEN_RESP_DT	DATE
	, PPA_TERM_AGENCY_DECISION	NVARCHAR2(200)
	, PPA_TERM_DECIDING_OFFCL_NAME	NVARCHAR2(10)
	, PPA_TERM_DECISION_ISSUED_DT	DATE
	, PPA_TERM_EFFECTIVE_DECISION_DT	DATE
	, PPA_PROB_TERM_DCSN_ISSUED_DT	DATE
	--, PPA_PROBATION_CONDUCT	CHAR(1 BYTE) DEFAULT '0'	
	, PPA_PROBATION_CONDUCT	NVARCHAR2(3)
	--, PPA_PROBATION_PERFORMANCE	CHAR(1 BYTE) DEFAULT '0'
	, PPA_PROBATION_PERFORMANCE NVARCHAR2(3)
	, PPA_APPEAL_GRIEVANCE_DEADLINE	DATE
	--, PPA_EMP_APPEAL_DECISION	CHAR(1 BYTE) DEFAULT '0'
	, PPA_EMP_APPEAL_DECISION	NVARCHAR2(3)
	, PPA_PROP_ACTION_ISSUED_DT	DATE
	--, PPA_ORAL_PREZ_REQUESTED	CHAR(1 BYTE) DEFAULT '0'
	, PPA_ORAL_PREZ_REQUESTED NVARCHAR2(3)
	, PPA_ORAL_PREZ_DT	DATE
	--, PPA_ORAL_RESPONSE_SUBMITTED	CHAR(1 BYTE) DEFAULT '0'
	, PPA_ORAL_RESPONSE_SUBMITTED NVARCHAR2(3)
	, PPA_RESPONSE_DUE_DT	DATE
	, PPA_WRITTEN_RESPONSE_SBMT_DT	DATE
	, PPA_POS_TITLE	NVARCHAR2(50)
	, PPA_PPLAN	NVARCHAR2(50)
	, PPA_SERIES	NVARCHAR2(50)
	, PPA_CURRENT_INFO_GRADE	NVARCHAR2(50)
	, PPA_CURRENT_INFO_STEP	NVARCHAR2(50)
	, PPA_PROPOSED_POS_TITLE	NVARCHAR2(50)
	, PPA_PROPOSED_PPLAN	NVARCHAR2(50)
	, PPA_PROPOSED_SERIES	NVARCHAR2(50)
	, PPA_PROPOSED_INFO_GRADE	NVARCHAR2(50)
	, PPA_PROPOSED_INFO_STEP	NVARCHAR2(50)
	, PPA_FINAL_POS_TITLE	NVARCHAR2(50)
	, PPA_FINAL_PPLAN	NVARCHAR2(50)
	, PPA_FINAL_SERIES	NVARCHAR2(50)
	, PPA_FINAL_INFO_GRADE	NVARCHAR2(50)
	, PPA_FINAL_INFO_STEP	NVARCHAR2(50)
	, PPA_NOTICE_ISSUED_DT	DATE
	, PPA_DEMO_FINAL_AGENCY_DECISION	NVARCHAR2(200)
	, PPA_DECIDING_OFFCL	NVARCHAR2(10)
	, PPA_DECISION_ISSUED_DT	DATE
	, PPA_DEMO_FINAL_AGENCY_EFF_DT	DATE
	, PPA_NUMB_DAYS	NUMBER(20,0)
	, PPA_EFFECTIVE_DT	DATE
	, PPA_CURRENT_ADMIN_CODE	NVARCHAR2(8)
	, PPA_RE_ASSIGNMENT_CURR_ORG	NVARCHAR2(50)
	, PPA_FINAL_ADMIN_CODE	NVARCHAR2(8)
	, PPA_FINAL_ADMIN_CODE_FINAL_ORG	NVARCHAR2(50)
)
;

--------------------------------------------------------
--  DDL for Table ERLR_GRIEVANCE
--------------------------------------------------------
CREATE TABLE ERLR_GRIEVANCE
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, GI_TYPE	NVARCHAR2(200)
	, GI_NEGOTIATED_GRIEVANCE_TYPE	NVARCHAR2(200)
	--, GI_TIMELY_FILING_2	CHAR(1 BYTE) DEFAULT '0'	
	, GI_TIMELY_FILING_2 NVARCHAR2(3)
	, GI_IND_MANAGER	NVARCHAR2(10)
	, GI_FILING_DT_2	DATE
	, GI_TIMELY_FILING	CHAR(1 BYTE) DEFAULT '0'
	, GI_FILING_DT	DATE
	, GI_IND_MEETING_DT	DATE
	, GI_IND_STEP_1_DECISION_DT	DATE
	, GI_IND_DECISION_ISSUE_DT	DATE
	--, GI_IND_STEP_1_DEADLINE	CHAR(1 BYTE) DEFAULT '0'
	, GI_IND_STEP_1_DEADLINE NVARCHAR2(3)
	, GI_IND_STEP_1_EXT_DUE_DT	DATE
	, GI_IND_STEP_1_EXT_DUE_REASON	NVARCHAR2(500)
	--, GI_STEP_2_REQUEST	CHAR(1 BYTE) DEFAULT '0'
	, GI_STEP_2_REQUEST NVARCHAR2(3)
	, GI_IND_STEP_2_MTG_DT	DATE
	, GI_IND_STEP_2_DECISION_DUE_DT	DATE
	, GI_IND_STEP_2_DCSN_ISSUE_DT	DATE
	--, GI_IND_STEP_2_DEADLINE	CHAR(1 BYTE) DEFAULT '0'
	, GI_IND_STEP_2_DEADLINE NVARCHAR2(3)
	, GI_IND_EXT_2_EXT_DUE_DT	DATE
	, GI_IND_STEP_2_EXT_DUE_REASON	NVARCHAR2(500)
	, GI_IND_THIRD_PARTY_APPEAL_DT	DATE
	--, GI_IND_THIRD_APPEAL_REQUEST	CHAR(1 BYTE) DEFAULT '0'
	, GI_IND_THIRD_APPEAL_REQUEST NVARCHAR2(3)
	, GI_UM_GRIEVABILITY	NVARCHAR2(200)
	, GI_MEETING_DT	DATE
	, GI_GRIEVANCE_STATUS	NVARCHAR2(200)
	, GI_ARBITRATION_DEADLINE_DT	DATE
	--, GI_ARBITRATION_REQUEST	CHAR(1 BYTE) DEFAULT '0'
	, GI_ARBITRATION_REQUEST NVARCHAR2(3)
	, GI_ADMIN_OFFCL_1	NVARCHAR2(10)
	, GI_ADMIN_STG_1_DECISION_DT	DATE
	, GI_ADMIN_STG_1_ISSUE_DT	DATE
	--, GI_ADMIN_STG_2_RESP	CHAR(1 BYTE) DEFAULT '0'
	, GI_ADMIN_STG_2_RESP NVARCHAR2(3)
	, GI_ADMIN_OFFCL_2	NVARCHAR2(10)
	, GI_ADMIN_STG_2_DECISION_DT	DATE
	, GI_ADMIN_STG_2_ISSUE_DT	DATE
)
;

--------------------------------------------------------
--  DDL for Table ERLR_ULP
--------------------------------------------------------
CREATE TABLE ERLR_ULP
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, ULP_RECEIPT_CHARGE_DT	DATE
	--, ULP_CHARGE_FILED_TIMELY	CHAR(1 BYTE) DEFAULT '0'
	, ULP_CHARGE_FILED_TIMELY NVARCHAR2(3)
	, ULP_AGENCY_RESPONSE_DT	DATE
	--, ULP_FLRA_DOCUMENT_REUQESTED	CHAR(1 BYTE) DEFAULT '0'
	, ULP_FLRA_DOCUMENT_REUQESTED NVARCHAR2(3)
	, ULP_DOC_SUBMISSION_FLRA_DT	DATE
	, ULP_DOCUMENT_DESCRIPTION	NVARCHAR2(140)
	, ULP_DISPOSITION_DT	DATE
	, ULP_DISPOSITION_TYPE	NVARCHAR2(200)
	, ULP_COMPLAINT_DT	DATE
	, ULP_AGENCY_ANSWER_DT	DATE
	, ULP_AGENCY_ANSWER_FILED_DT	DATE
	, ULP_SETTLEMENT_DISCUSSION_DT	DATE
	, ULP_PREHEARING_DISCLOSURE_DUE	DATE
	, ULP_PREHEARING_DISCLOSUE_DT	DATE
	, ULP_PREHEARING_CONFERENCE_DT	DATE
	, ULP_HEARING_DT	DATE
	, ULP_DECISION_DT	DATE
	--, ULP_EXCEPTION_FILED	CHAR(1 BYTE) DEFAULT '0'
	, ULP_EXCEPTION_FILED NVARCHAR2(3)
	, ULP_EXCEPTION_FILED_DT	DATE
)
;


--------------------------------------------------------
--  DDL for Table ERLR_LABOR_NEGO
--------------------------------------------------------
CREATE TABLE ERLR_LABOR_NEGO
(	
	ERLR_CASE_NUMBER	NUMBER(20,0)
	, LN_NEGOTIATION_TYPE	NVARCHAR2(200)
	, LN_INITIATOR	NVARCHAR2(200)
	, LN_DEMAND2BARGAIN_DT	DATE
	, LN_BRIEFING_REQUEST NVARCHAR2(3)
	, LN_PROPOSAL_SUBMISSION_DT	DATE
	, LN_PROPOSAL_SUBMISSION NVARCHAR2(3)
	, LN_PROPOSAL_NEGOTIABLE NVARCHAR2(3)
	, LN_NON_NEGOTIABLE_LETTER NVARCHAR2(3)
	, LN_FILE_ULP	NVARCHAR2(3)
	, LN_PROPOSAL_INFO_GROUND_RULES NVARCHAR2(3)
	, LN_PRPSAL_INFO_NEG_COMMENCE_DT	DATE
	, LN_LETTER_PROVIDED NVARCHAR2(3)
	, LN_LETTER_PROVIDED_DT	DATE
	, LN_NEGOTIABLE_PROPOSAL NVARCHAR2(3)
	, LN_BARGAINING_BEGAN_DT	DATE
	, LN_IMPASSE_DT	DATE
	, LN_FSIP_DECISION_DT	DATE
	, LN_BARGAINING_END_DT	DATE
	, LN_AGREEMENT_DT	DATE
	, LN_SUMMARY_OF_ISSUE	NVARCHAR2(500)
	, LN_SECON_LETTER_REQUEST	NVARCHAR2(3)
	, LN_2ND_LETTER_PROVIDED NVARCHAR2(3)
	, LN_NEGOTIABL_ISSUE_SUMMARY	NVARCHAR2(500)
	, LN_MNGMNT_ARTICLE4_NTC_DT	DATE
	, LN_MNGMNT_NOTICE_RESPONSE	NVARCHAR2(3)
	, LN_MNGMNT_BRIEFING_REQUEST NVARCHAR2(3)
	, LN_MNGMNT_BARGAIN_SBMSSION_DT	DATE
	, LN_MNGMNT_PROPOSAL_SBMSSION NVARCHAR2(3),
  	, LN_BRIEFING_DT  DATE
  	, LN_2ND_PROVIDED_DT  DATE
  	, LN_BRIEFING_REQUESTED2_DT DATE
)	
;

CREATE UNIQUE INDEX ERLR_CASE_UK1 ON ERLR_CASE (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_GEN_UK1 ON ERLR_GEN (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_CNDT_ISSUE_UK1 ON ERLR_CNDT_ISSUE (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_APPEAL_UK1 ON ERLR_APPEAL (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_WGI_DNL_UK1 ON ERLR_WGI_DNL (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_MEDDOC_UK1 ON ERLR_MEDDOC (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_PERF_ISSUE_UK1 ON ERLR_PERF_ISSUE (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_INVESTIGATION_UK1 ON ERLR_INVESTIGATION (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_INFO_REQUEST_UK1 ON ERLR_INFO_REQUEST (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_3RDPARTY_HEAR_UK1 ON ERLR_3RDPARTY_HEAR (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_PROB_ACTION_UK1 ON ERLR_PROB_ACTION (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_GRIEVANCE_UK1 ON ERLR_GRIEVANCE (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_ULP_UK1 ON ERLR_ULP (ERLR_CASE_NUMBER);
CREATE UNIQUE INDEX ERLR_LABOR_NEGO_UK1 ON ERLR_LABOR_NEGO (ERLR_CASE_NUMBER);

--------------------------------------------------------
--  DDL for Table ERLR_CASE_TRIGGER
--------------------------------------------------------

CREATE TABLE ERLR_CASE_TRIGGER 
("SEQ" NUMBER NOT NULL , 
"FROM_PROCID" NUMBER(10) NOT NULL , 
"FIELD_DATA" XMLTYPE, 
"CRT_DT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
"STATUS" VARCHAR2(10 BYTE), 
"TO_PROCID" NUMBER(10),
"CASE_NUMBER" NUMBER(10) NOT NULL
);

ALTER TABLE ERLR_CASE_TRIGGER ADD CONSTRAINT ERLR_CASE_TRIGGER_PK PRIMARY KEY (SEQ);

COMMENT ON COLUMN "ERLR_CASE_TRIGGER"."STATUS" IS 'NULL, WAIT, DONE';

CREATE INDEX "ERLR_CASE_TRIGGER_1" ON "ERLR_CASE_TRIGGER" ("FROM_PROCID");
/

CREATE SEQUENCE ERLR_CASE_TRIGGER_SEQ
	INCREMENT BY 1
	START WITH 1
	NOMAXVALUE
	NOCYCLE
	NOCACHE;
/




