
--------------------------------------------------------
--  DDL for VW_ERLR_MEDDOC
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_MEDDOC
AS
SELECT
    M.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = M.MD_REQUEST_REASON AND ROWNUM = 1) AS MD_REQUEST_REASON
	, MD_MED_DOC_SBMT_DEADLINE_DT
	, MD_FMLA_DOC_SBMT_DT
	, MD_FMLA_BEGIN_DT
	, MD_FMLA_APROVED
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = M.MD_FMLA_DISAPRV_REASON AND ROWNUM = 1) AS MD_FMLA_DISAPRV_REASON
	, MD_FMLA_GRIEVANCE
	, MD_MEDEXAM_EXTENDED
	, MD_MEDEXAM_ACCEPTED
	, MD_MEDEXAM_RECEIVED_DT
	, MD_DOC_SUBMITTED
	, MD_DOC_SBMT_DT
	, MD_DOC_SBMT_FOH
	, MD_DOC_REVIEW_OUTCOME
	, MD_DOC_ADMTV_ACCEPTABLE
	, (SELECT L.TBL_LABEL FROM TBL_LOOKUP L WHERE L.TBL_ID = M.MD_DOC_ADMTV_REJECT_REASON AND ROWNUM = 1) AS MD_DOC_ADMTV_REJECT_REASON

FROM
	ERLR_MEDDOC M
    LEFT OUTER JOIN ERLR_CASE EC ON M.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/