--------------------------------------------------------
--  DDL for VW_ERLR_INFO_REQUEST
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_INFO_REQUEST
AS
SELECT
    IR.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , IR_REQUESTER
	, IR_CMS_REQUESTER_NAME
	, IR_CMS_REQUESTER_PHONE
	, IR_NCMS_REQUESTER_LAST_NAME
	, IR_NCMS_REQUESTER_FIRST_NAME
	, IR_NON_CMS_REQUESTER_PHONE
	, IR_NON_CMS_REQUESTER_EMAIL
	, IR_NCMS_REQUESTER_ORG_AFFIL
	, IR_SUBMIT_DT
	, IR_MEET_PTCLRIZED_NEED_STND
	, IR_RSNABLY_AVAIL_N_NECESSARY
	, IR_PRTCT_DISCLOSURE_BY_LAW
	, IR_MAINTAINED_BY_AGENCY
	, IR_COLLECTIVE_BARGAINING_UNIT
	, IR_APPROVE
	, IR_APPEAL_DENIAL

FROM
	ERLR_INFO_REQUEST IR
    LEFT OUTER JOIN ERLR_CASE EC ON IR.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/