--------------------------------------------------------
--  DDL for VW_ERLR_INVESTIGATION
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_INVESTIGATION
AS
SELECT
    I.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , INVESTIGATION_TYPE
	, I_MISCONDUCT_FOUND
FROM
	ERLR_INVESTIGATION I
    LEFT OUTER JOIN ERLR_CASE EC ON I.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/
