
--------------------------------------------------------
--  DDL for VW_ERLR_WGI_DNL
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_WGI_DNL
AS
SELECT
    WD.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , WGI_DTR_DENIAL_ISSUED_DT
	, WGI_DTR_EMP_REQ_RECON
	, WGI_DTR_RECON_REQ_DT
	, WGI_DTR_RECON_ISSUE_DT
	, WGI_DTR_DENIED
	, WGI_DTR_DENIAL_ISSUE_TO_EMP_DT
	, WGI_RVW_REDTR_NOTI_ISSUED_DT
	, WGI_REVIEW_DTR_FAVORABLE
	, WGI_REVIEW_EMP_REQ_RECON
	, WGI_REVIEW_RECON_REQ_DT
	, WGI_REVIEW_RECON_ISSUE_DT
	, WGI_REVIEW_DENIED
	, WGI_EMP_APPEAL_DECISION    
FROM
	ERLR_WGI_DNL WD
    LEFT OUTER JOIN ERLR_CASE EC ON WD.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

GRANT SELECT ON HHS_CMS_HR.VW_ERLR_WGI_DNL TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_WGI_DNL TO HHS_CMS_HR_DEV_ROLE;
/
