CREATE OR REPLACE VIEW VW_ERLR_GRIEVANCE
AS
SELECT
    G.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , GI_TYPE
	, GI_NEGOTIATED_GRIEVANCE_TYPE
    , CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN GI_FILING_DT_2 ELSE GI_FILING_DT END AS GI_GRIEVANCE_FILED_DT
    , CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN GI_TIMELY_FILING_2 ELSE GI_TIMELY_FILING END AS GI_TIMELY_FILING
	, GI_IND_MANAGER
	, GI_IND_MEETING_DT
    , CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN GI_IND_DECISION_ISSUE_DT WHEN GI_TYPE = 'Administrative' THEN GI_ADMIN_STG_1_DECISION_DT ELSE null END AS GI_STEP_STAGE_1_DT
    , CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN GI_IND_STEP_2_DCSN_ISSUE_DT WHEN GI_TYPE = 'Administrative' THEN GI_ADMIN_STG_2_ISSUE_DT ELSE null END AS GI_STEP_STAGE_2_DT
	, GI_IND_STEP_1_DECISION_DT
    , GI_IND_STEP_1_DEADLINE
    , GI_IND_STEP_1_EXT_DUE_DT
    , GI_IND_STEP_1_EXT_DUE_REASON	
	, GI_STEP_2_REQUEST
	, GI_IND_STEP_2_MTG_DT
	, GI_IND_STEP_2_DECISION_DUE_DT	
	, GI_IND_STEP_2_DEADLINE
	, GI_IND_EXT_2_EXT_DUE_DT
	, GI_IND_STEP_2_EXT_DUE_REASON	
    , CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN G.GI_IND_THIRD_APPEAL_REQUEST 
    WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Union' THEN G.GI_ARBITRATION_REQUEST 
    WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Management' THEN G.GI_ARBITRATION_REQUEST 	
    ELSE null END AS GI_ARBITRATION_REQUEST
	, CASE WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Individual' THEN G.GI_IND_THIRD_PARTY_APPEAL_DT 
    WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Union' THEN G.GI_ARBITRATION_DEADLINE_DT 
    WHEN GI_TYPE = 'Negotiated' and GI_NEGOTIATED_GRIEVANCE_TYPE = 'Management' THEN G.GI_ARBITRATION_DEADLINE_DT 	
    ELSE null END AS GI_ARBITRATION_DEADLINE_DT	
    , GI_UM_GRIEVABILITY
	, GI_MEETING_DT
	, GI_GRIEVANCE_STATUS
	, GI_ADMIN_OFFCL_1	
	, GI_ADMIN_STG_1_ISSUE_DT
	, GI_ADMIN_STG_2_RESP
	, GI_ADMIN_OFFCL_2
	, GI_ADMIN_STG_2_DECISION_DT	
FROM
	ERLR_GRIEVANCE G
    LEFT OUTER JOIN ERLR_CASE EC ON G.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;

GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_DEV_ROLE;
