--------------------------------------------------------
--  DDL for VW_ERLR_GRIEVANCE
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_GRIEVANCE
AS
SELECT
    G.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , GI_TYPE
	, GI_NEGOTIATED_GRIEVANCE_TYPE
	, GI_TIMELY_FILING_2
	, GI_IND_MANAGER
	, GI_FILING_DT_2
	, GI_TIMELY_FILING
	, GI_FILING_DT
	, GI_IND_MEETING_DT
	, GI_IND_STEP_1_DECISION_DT
    , GI_IND_STEP_1_DEADLINE
    , GI_IND_STEP_1_EXT_DUE_DT
    , GI_IND_STEP_1_EXT_DUE_REASON
	, GI_IND_DECISION_ISSUE_DT
	, GI_STEP_2_REQUEST
	, GI_IND_STEP_2_MTG_DT
	, GI_IND_STEP_2_DECISION_DUE_DT
	, GI_IND_STEP_2_DCSN_ISSUE_DT
	, GI_IND_STEP_2_DEADLINE
	, GI_IND_EXT_2_EXT_DUE_DT
	, GI_IND_STEP_2_EXT_DUE_REASON
	, GI_IND_THIRD_PARTY_APPEAL_DT
	, GI_IND_THIRD_APPEAL_REQUEST	
    , GI_UM_GRIEVABILITY
	, GI_MEETING_DT
	, GI_GRIEVANCE_STATUS
	, GI_ARBITRATION_DEADLINE_DT
	, GI_ARBITRATION_REQUEST
	, GI_ADMIN_OFFCL_1
	, GI_ADMIN_STG_1_DECISION_DT
	, GI_ADMIN_STG_1_ISSUE_DT
	, GI_ADMIN_STG_2_RESP
	, GI_ADMIN_OFFCL_2
	, GI_ADMIN_STG_2_DECISION_DT
	, GI_ADMIN_STG_2_ISSUE_DT
FROM
	ERLR_GRIEVANCE G
    LEFT OUTER JOIN ERLR_CASE EC ON G.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/

GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_DEV_ROLE;
