-- CMS_01_BF_ACT.sql
GRANT SELECT ON BIZFLOW.ACT TO HHS_CMS_HR;


-- CMS_01_BF_UpdateProcFolder.sql
UPDATE PROCS SET ARCHIVEFLDRID = (SELECT FLDRID FROM FLDRLIST WHERE FLDRPATH = '/Process Archives/CMS'), INSTFLDRID = (SELECT FLDRID FROM FLDRLIST WHERE FLDRPATH = '/Process Instances/CMS') 
WHERE ARCHIVEFLDRID = (SELECT FLDRID FROM FLDRLIST WHERE FLDRPATH = '/Process Archives') 
AND NAME IN ('Strategic Consultation', 'Classification', 'Eligibility and Qualifications Review');

COMMIT;
