CREATE OR REPLACE VIEW VW_STRATCON
AS
SELECT
	R.REQ_ID
	, R.REQ_JOB_REQ_NUMBER
	, R.REQ_JOB_REQ_CREATE_DT
	, R.REQ_STATUS_ID
	, R.REQ_CANCEL_DT
	, R.REQ_CANCEL_REASON

	, SG.SG_PROCID
	, SG.SG_AC_ID
	--, LU_AC.AC_ADMIN_CD AS SG_AC_CD
	--, LU_AC.AC_ADMIN_CD_DESCR AS SG_AC_DSCR
	, SG.SG_ADMIN_CD AS SG_ADMIN_CD
	--, LU_AC.AC_ADMIN_CD_DESCR AS SG_ADMIN_CD_DSCR
	--, LU_SO_1.AC_ADMIN_CD AS SUB_ORG_1_CD
	--, LU_SO_1.AC_ADMIN_CD_DESCR AS SUB_ORG_1_DSCR
	--, LU_SO_2.AC_ADMIN_CD AS SUB_ORG_2_CD
	--, LU_SO_2.AC_ADMIN_CD_DESCR AS SUB_ORG_2_DSCR
	--, LU_SO_3.AC_ADMIN_CD AS SUB_ORG_3_CD
	--, LU_SO_3.AC_ADMIN_CD_DESCR AS SUB_ORG_3_DSCR
	--, LU_SO_4.AC_ADMIN_CD AS SUB_ORG_4_CD
	--, LU_SO_4.AC_ADMIN_CD_DESCR AS SUB_ORG_4_DSCR
	--, LU_SO_5.AC_ADMIN_CD AS SUB_ORG_5_CD
	--, LU_SO_5.AC_ADMIN_CD_DESCR AS SUB_ORG_5_DSCR
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = SG.SG_ADMIN_CD AND ROWNUM = 1) AS SG_ADMIN_CD_DSCR
	, FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 1) AS SUB_ORG_1_CD
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 1) AND ROWNUM = 1) AS SUB_ORG_1_DSCR
	, FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 2) AS SUB_ORG_2_CD
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 2) AND ROWNUM = 1) AS SUB_ORG_2_DSCR
	, FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 3) AS SUB_ORG_3_CD
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 3) AND ROWNUM = 1) AS SUB_ORG_3_DSCR
	, FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 4) AS SUB_ORG_4_CD
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 4) AND ROWNUM = 1) AS SUB_ORG_4_DSCR
	, FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 5) AS SUB_ORG_5_CD
	, (SELECT AC.AC_ADMIN_CD_DESCR FROM ADMIN_CODES AC WHERE AC.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 5) AND ROWNUM = 1) AS SUB_ORG_5_DSCR
	, SG.SG_RT_ID
	--, LU_RT.TBL_LABEL AS SG_RT_DSCR
	, (SELECT LU_RT.TBL_LABEL FROM TBL_LOOKUP LU_RT WHERE LU_RT.TBL_ID = SG.SG_RT_ID AND ROWNUM = 1) AS SG_RT_DSCR
	, SG.SG_CT_ID
	--, LU_CT.TBL_LABEL AS SG_CT_DSCR
	, (SELECT LU_CT.TBL_LABEL FROM TBL_LOOKUP LU_CT WHERE LU_CT.TBL_ID = SG.SG_CT_ID AND ROWNUM = 1) AS SG_CT_DSCR
	, SG.SG_AT_ID
	--, LU_AT.TBL_LABEL AS SG_AT_DSCR
	, (SELECT LU_AT.TBL_LABEL FROM TBL_LOOKUP LU_AT WHERE LU_AT.TBL_ID = SG.SG_AT_ID AND ROWNUM = 1) AS SG_AT_DSCR
	, SG.SG_VT_ID
	--, LU_VT.TBL_LABEL AS SG_VT_DSCR
	, (SELECT LU_VT.TBL_LABEL FROM TBL_LOOKUP LU_VT WHERE LU_VT.TBL_ID = SG.SG_VT_ID AND ROWNUM = 1) AS SG_VT_DSCR
	, SG.SG_SAT_ID
	--, LU_SAT.TBL_LABEL AS SG_SAT_DSCR
	, (SELECT LU_SAT.TBL_LABEL FROM TBL_LOOKUP LU_SAT WHERE LU_SAT.TBL_ID = SG.SG_SAT_ID AND ROWNUM = 1) AS SG_SAT_DSCR
	, SG.SG_SO_ID
	--, LU_MEMSO.NAME AS SG_SO_NAME
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = SG.SG_SO_ID AND ROWNUM = 1)  AS SG_SO_NAME
	, SG.SG_SO_TITLE
	, SG.SG_SO_ORG
	, SG.SG_XO_ID
	--, LU_MEMXO.NAME AS SG_XO_NAME
	, FN_GET_NAMES(SG.SG_XO_ID)  AS SG_XO_NAME
	, SG.SG_XO_TITLE
	, SG.SG_XO_ORG
	, SG.SG_HRL_ID
	--, LU_MEMHL.NAME AS SG_HL_NAME
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = SG.SG_HRL_ID AND ROWNUM = 1)  AS SG_HL_NAME
	, SG.SG_HRL_TITLE
	, SG.SG_HRL_ORG
	, SG.SG_SS_ID
	--, LU_MEMSS.NAME AS SG_SS_NAME
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = SG.SG_SS_ID AND ROWNUM = 1)  AS SG_SS_NAME
	, SG.SG_CS_ID
	--, LU_MEMCS.NAME AS SG_CS_NAME
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = SG.SG_CS_ID AND ROWNUM = 1)  AS SG_CS_NAME
	, CASE WHEN SG.SG_SO_AGREE = '1' THEN 'Yes' ELSE 'No' END AS SG_SO_AGREE
	, SG.SG_OTHER_CERT
	, FN_GET_MEMBER_DSCR(SG.SG_OTHER_CERT) AS SG_OTHER_CERT_DSCR

	, POS.POS_CNDT_LAST_NM
	, POS.POS_CNDT_FIRST_NM
	, POS.POS_CNDT_MIDDLE_NM
	, CASE WHEN POS.POS_BGT_APR_OFM = '1' THEN 'Yes' WHEN POS.POS_BGT_APR_OFM = '0' THEN 'No' ELSE 'N/A' END AS POS_BGT_APR_OFM
	, POS.POS_SPNSR_ORG_NM
	, POS.POS_SPNSR_ORG_FUND_PC
	, POS.POS_TITLE
	, POS.POS_PAY_PLAN_ID
	--, LU_PYPL.TBL_NAME AS POS_PAY_PLAN_DSCR
	, (SELECT LU_PYPL.TBL_NAME FROM TBL_LOOKUP LU_PYPL WHERE LU_PYPL.TBL_ID = POS.POS_PAY_PLAN_ID AND ROWNUM = 1) AS POS_PAY_PLAN_DSCR
	, POS.POS_SERIES
	, POS.POS_DESC_NUMBER_1
	, POS.POS_CLASSIFICATION_DT_1
	, POS.POS_GRADE_1
	, POS.POS_DESC_NUMBER_2
	, POS.POS_CLASSIFICATION_DT_2
	, POS.POS_GRADE_2
	, POS.POS_DESC_NUMBER_3
	, POS.POS_CLASSIFICATION_DT_3
	, POS.POS_GRADE_3
	, POS.POS_DESC_NUMBER_4
	, POS.POS_CLASSIFICATION_DT_4
	, POS.POS_GRADE_4
	, POS.POS_DESC_NUMBER_5
	, POS.POS_CLASSIFICATION_DT_5
	, POS.POS_GRADE_5
	, POS.POS_MED_OFFICERS_ID
	--, LU_MO.TBL_LABEL AS POS_MED_OFFICERS_DSCR
	, (SELECT LU_MO.TBL_LABEL FROM TBL_LOOKUP LU_MO WHERE LU_MO.TBL_ID = POS.POS_MED_OFFICERS_ID AND ROWNUM = 1) AS POS_MED_OFFICERS_DSCR
	, POS.POS_PERFORMANCE_LEVEL
	, POS.POS_SUPERVISORY
	--, LU_SUP.TBL_LABEL AS POS_SUPERVISORY_DSCR
	, (SELECT LU_SUP.TBL_LABEL FROM TBL_LOOKUP LU_SUP WHERE LU_SUP.TBL_ID = TO_NUMBER(POS.POS_SUPERVISORY) AND ROWNUM = 1) AS POS_SUPERVISORY_DSCR
	, POS.POS_SKILL
	, POS.POS_LOCATION
	--, LU_LOC.LOC_CITY || ', ' || LU_LOC.LOC_STATE AS POS_LOCATION_DSCR
	, FN_GET_LOCATION_DSCR(POS.POS_LOCATION) AS POS_LOCATION_DSCR
	, POS.POS_VACANCIES
	, POS.POS_REPORT_SUPERVISOR
	--, LU_MEMRS.NAME AS POS_REPORT_SUPERVISOR_NAME
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = POS.POS_REPORT_SUPERVISOR AND ROWNUM = 1)  AS POS_REPORT_SUPERVISOR_NAME
	, POS.POS_CAN
	, CASE WHEN POS.POS_VICE = '1' THEN 'Yes' ELSE 'No' END AS POS_VICE
	, POS.POS_VICE_NAME
	, POS.POS_DAYS_ADVERTISED
	, POS.POS_AT_ID
	--, LU_ADT.TBL_LABEL AS POS_AT_DSCR
	, (SELECT LU_ADT.TBL_LABEL FROM TBL_LOOKUP LU_ADT WHERE LU_ADT.TBL_ID = POS.POS_AT_ID AND ROWNUM = 1) AS POS_AT_DSCR
	, POS.POS_NTE
	, POS.POS_WORK_SCHED_ID
	--, LU_WSCHD.TBL_LABEL AS POS_WORK_SCHED_DSCR
	, (SELECT LU_WSCHD.TBL_LABEL FROM TBL_LOOKUP LU_WSCHD WHERE LU_WSCHD.TBL_ID = POS.POS_WORK_SCHED_ID AND ROWNUM = 1) AS POS_WORK_SCHED_DSCR
	, POS.POS_HOURS_PER_WEEK
	, CASE WHEN POS.POS_DUAL_EMPLMT = '1' THEN 'Yes' WHEN POS.POS_DUAL_EMPLMT = '0' THEN 'No' ELSE NULL END AS POS_DUAL_EMPLMT
	, POS.POS_SEC_ID
	--, LU_SEC.TBL_LABEL AS POS_SEC_DSCR
	, (SELECT LU_SEC.TBL_LABEL FROM TBL_LOOKUP LU_SEC WHERE LU_SEC.TBL_ID = POS.POS_SEC_ID AND ROWNUM = 1) AS POS_SEC_DSCR
	, CASE WHEN POS.POS_CE_FINANCIAL_DISC = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_FINANCIAL_DISC
	, POS.POS_CE_FINANCIAL_TYPE_ID
	--, LU_FNTP.TBL_LABEL AS POS_CE_FINANCIAL_TYPE_DSCR
	, (SELECT LU_FNTP.TBL_LABEL FROM TBL_LOOKUP LU_FNTP WHERE LU_FNTP.TBL_ID = POS.POS_CE_FINANCIAL_TYPE_ID AND ROWNUM = 1) AS POS_CE_FINANCIAL_TYPE_DSCR
	, CASE WHEN POS.POS_CE_PE_PHYSICAL = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_PE_PHYSICAL
	, CASE WHEN POS.POS_CE_DRUG_TEST = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_DRUG_TEST
	, CASE WHEN POS.POS_CE_IMMUN = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_IMMUN
	, CASE WHEN POS.POS_CE_TRAVEL = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_TRAVEL
	, POS.POS_CE_TRAVEL_PER
	, CASE WHEN POS.POS_CE_LIC = '1' THEN 'Yes' ELSE 'No' END AS POS_CE_LIC
	, POS.POS_CE_LIC_INFO
	, POS.POS_REMARKS
	, POS.POS_PROC_REQ_TYPE
	, POS.POS_RECRUIT_OFFICE_ID
	--, POS.POS_REQ_CREATE_NOTIFY_DT
	, POS.POS_SO_ID
	, POS.POS_ASSOC_DESCR_NUMBERS
	, POS.POS_PROMOTE_POTENTIAL
	, POS.POS_VICE_EMPL_ID
	, POS.POS_SR_ID
	, POS.POS_GR_ID
	, POS.POS_AC_ID
	, CASE WHEN POS.POS_GA_1  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_1
	, CASE WHEN POS.POS_GA_2  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_2
	, CASE WHEN POS.POS_GA_3  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_3
	, CASE WHEN POS.POS_GA_4  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_4
	, CASE WHEN POS.POS_GA_5  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_5
	, CASE WHEN POS.POS_GA_6  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_6
	, CASE WHEN POS.POS_GA_7  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_7
	, CASE WHEN POS.POS_GA_8  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_8
	, CASE WHEN POS.POS_GA_9  = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_9
	, CASE WHEN POS.POS_GA_10 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_10
	, CASE WHEN POS.POS_GA_11 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_11
	, CASE WHEN POS.POS_GA_12 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_12
	, CASE WHEN POS.POS_GA_13 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_13
	, CASE WHEN POS.POS_GA_14 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_14
	, CASE WHEN POS.POS_GA_15 = '1' THEN 'Yes' ELSE 'No' END AS POS_GA_15

	, FN_GET_GRADE_ADVRT(POS.POS_GA_1, POS.POS_GA_2, POS.POS_GA_3, POS.POS_GA_4, POS.POS_GA_5
		 , POS.POS_GA_6, POS.POS_GA_7, POS.POS_GA_8, POS.POS_GA_9, POS.POS_GA_10
		 , POS.POS_GA_11, POS.POS_GA_12, POS.POS_GA_13, POS.POS_GA_14, POS.POS_GA_15)
	AS POS_GA

	, CASE WHEN AOC.AOC_30PCT_DISABLED_VETS = '1' THEN 'Yes' ELSE 'No' END AS AOC_30PCT_DISABLED_VETS
	, CASE WHEN AOC.AOC_EXPERT_CONS = '1'         THEN 'Yes' ELSE 'No' END AS AOC_EXPERT_CONS
	, CASE WHEN AOC.AOC_IPA = '1'                 THEN 'Yes' ELSE 'No' END AS AOC_IPA
	, CASE WHEN AOC.AOC_OPER_WARFIGHTER = '1'     THEN 'Yes' ELSE 'No' END AS AOC_OPER_WARFIGHTER
	, CASE WHEN AOC.AOC_DISABILITIES = '1'        THEN 'Yes' ELSE 'No' END AS AOC_DISABILITIES
	, CASE WHEN AOC.AOC_STUDENT_VOL = '1'         THEN 'Yes' ELSE 'No' END AS AOC_STUDENT_VOL
	, CASE WHEN AOC.AOC_VETS_RECRUIT_APPT = '1'   THEN 'Yes' ELSE 'No' END AS AOC_VETS_RECRUIT_APPT
	, CASE WHEN AOC.AOC_VOC_REHAB_EMPL = '1'      THEN 'Yes' ELSE 'No' END AS AOC_VOC_REHAB_EMPL
	, CASE WHEN AOC.AOC_WORKFORCE_RECRUIT = '1'   THEN 'Yes' ELSE 'No' END AS AOC_WORKFORCE_RECRUIT
	, AOC.AOC_NON_COMP_APPL
	, CASE WHEN AOC.AOC_MIL_SPOUSES = '1'         THEN 'Yes' ELSE 'No' END AS AOC_MIL_SPOUSES
	, CASE WHEN AOC.AOC_DIRECT_HIRE = '1'         THEN 'Yes' ELSE 'No' END AS AOC_DIRECT_HIRE
	, CASE WHEN AOC.AOC_RE_EMPLOYMENT = '1'       THEN 'Yes' ELSE 'No' END AS AOC_RE_EMPLOYMENT
	, CASE WHEN AOC.AOC_PATHWAYS = '1'            THEN 'Yes' ELSE 'No' END AS AOC_PATHWAYS
	, CASE WHEN AOC.AOC_PEACE_CORPS_VOL = '1'     THEN 'Yes' ELSE 'No' END AS AOC_PEACE_CORPS_VOL
	, CASE WHEN AOC.AOC_REINSTATEMENT = '1'       THEN 'Yes' ELSE 'No' END AS AOC_REINSTATEMENT
	, CASE WHEN AOC.AOC_SHARED_CERT = '1'         THEN 'Yes' ELSE 'No' END AS AOC_SHARED_CERT
	, CASE WHEN AOC.AOC_DELEGATE_EXAM = '1'       THEN 'Yes' ELSE 'No' END AS AOC_DELEGATE_EXAM
	, CASE WHEN AOC.AOC_DH_US_CITIZENS = '1'      THEN 'Yes' ELSE 'No' END AS AOC_DH_US_CITIZENS
	, CASE WHEN AOC.AOC_MP_GOV_WIDE = '1'         THEN 'Yes' ELSE 'No' END AS AOC_MP_GOV_WIDE
	, CASE WHEN AOC.AOC_MP_HHS_ONLY = '1'         THEN 'Yes' ELSE 'No' END AS AOC_MP_HHS_ONLY
	, CASE WHEN AOC.AOC_MP_CMS_ONLY = '1'         THEN 'Yes' ELSE 'No' END AS AOC_MP_CMS_ONLY
	, CASE WHEN AOC.AOC_MP_COMP_CONS_ONLY = '1'   THEN 'Yes' ELSE 'No' END AS AOC_MP_COMP_CONS_ONLY
	, CASE WHEN AOC.AOC_MP_I_CTAP_VEGA = '1'      THEN 'Yes' ELSE 'No' END AS AOC_MP_I_CTAP_VEGA
	, AOC.AOC_NON_BARGAIN_DOC_RATIONALE

	, FN_GET_ANNOUNCE_NOT_REQ(AOC.AOC_30PCT_DISABLED_VETS
		, AOC.AOC_EXPERT_CONS
		, AOC.AOC_IPA
		, AOC.AOC_OPER_WARFIGHTER
		, AOC.AOC_DISABILITIES
		, AOC.AOC_STUDENT_VOL
		, AOC.AOC_VETS_RECRUIT_APPT
		, AOC.AOC_VOC_REHAB_EMPL
		, AOC.AOC_WORKFORCE_RECRUIT)
	AS AOC_ANNOUNCE_NOT_REQ
	, FN_GET_ANNOUNCE_REQ(AOC.AOC_MIL_SPOUSES
		, AOC.AOC_DIRECT_HIRE
		, AOC.AOC_RE_EMPLOYMENT
		, AOC.AOC_PATHWAYS
		, AOC.AOC_PEACE_CORPS_VOL
		, AOC.AOC_REINSTATEMENT
		, AOC.AOC_SHARED_CERT)
	AS AOC_ANNOUNCE_REQ
	, FN_GET_ANNOUNCE_TYPE(AOC.AOC_DELEGATE_EXAM
		, AOC.AOC_DH_US_CITIZENS
		, AOC.AOC_MP_GOV_WIDE
		, AOC.AOC_MP_HHS_ONLY
		, AOC.AOC_MP_CMS_ONLY
		, AOC.AOC_MP_COMP_CONS_ONLY
		, AOC.AOC_MP_I_CTAP_VEGA)
	AS AOC_ANNOUNCE_TYPE

	, CASE WHEN SME.SME_FOR_JOB_ANALYSIS = '1'  THEN 'Yes' ELSE 'No' END AS SME_FOR_JOB_ANALYSIS
	, SME.SME_NAME_JA
	, SME.SME_EMAIL_JA
	, CASE WHEN SME.SME_FOR_QUALIFICATION = '1' THEN 'Yes' ELSE 'No' END AS SME_FOR_QUALIFICATION
	, SME.SME_NAME_QUAL_1
	, SME.SME_EMAIL_QUAL_1
	, SME.SME_NAME_QUAL_2
	, SME.SME_EMAIL_QUAL_2

	, CASE WHEN JA.JA_SEL_FACTOR_REQ = '1'   THEN 'Yes' ELSE 'No' END AS JA_SEL_FACTOR_REQ
	, JA.JA_SEL_FACTOR_JUST
	, CASE WHEN JA.JA_QUAL_RANK_REQ = '1'    THEN 'Yes' ELSE 'No' END AS JA_QUAL_RANK_REQ
	, JA.JA_QUAL_RANK_JUST
	, CASE WHEN JA.JA_RESPONSES_REQ = '1'    THEN 'Yes' ELSE 'No' END AS JA_RESPONSES_REQ
	, CASE WHEN JA.JA_TYPE_YES_NO = '1'      THEN 'Yes' ELSE 'No' END AS JA_TYPE_YES_NO
	, CASE WHEN JA.JA_TYPE_REQ_DEFAULT = '1' THEN 'Yes' ELSE 'No' END AS JA_TYPE_REQ_DEFAULT
	, CASE WHEN JA.JA_TYPE_KNOWL_SCALE = '1' THEN 'Yes' ELSE 'No' END AS JA_TYPE_KNOWL_SCALE

	, FN_GET_ASSESS_TYPE(JA.JA_TYPE_YES_NO
		, JA.JA_TYPE_REQ_DEFAULT
		, JA.JA_TYPE_KNOWL_SCALE)
	AS JA_ASSESS_TYPE

	, RI.RI_OA_APRV_ITEM
	, CASE
		WHEN RI.RI_OA_APRV_ITEM = 'C' THEN 'Recruitment'
		WHEN RI.RI_OA_APRV_ITEM = 'L' THEN 'Relocation'
		ELSE 'N/A'
	END AS RI_OA_APRV_ITEM_DSCR
	, CASE WHEN RI.RI_MOVING_EXP_AUTH = '1' THEN 'Yes' ELSE 'No' END AS RI_MOVING_EXP_AUTH

	, CASE WHEN TR.TR_PAID_AD = '1' THEN 'Yes' ELSE 'No' END AS TR_PAID_AD
	, TR.TR_PAID_AD_SPEC
	, FN_GET_LOOKUP_DSCR(TR.TR_PAID_AD_SPEC) AS TR_PAID_AD_SPEC_DSCR
	, TR.TR_PAID_AD_SPEC_OTHR
	, CASE WHEN TR.TR_SCHL_PSTG = '1' THEN 'Yes' ELSE 'No' END AS TR_SCHL_PSTG
	, TR.TR_SCHL_PSTG_SPEC
	, FN_GET_LOOKUP_DSCR(TR.TR_SCHL_PSTG_SPEC) AS TR_SCHL_PSTG_SPEC_DSCR
	, TR.TR_SCHL_PSTG_SPEC_OTHR
	, CASE WHEN TR.TR_SOCIAL_MEDIA = '1' THEN 'Yes' ELSE 'No' END AS TR_SOCIAL_MEDIA
	, TR.TR_SOCIAL_MEDIA_SPEC
	, FN_GET_LOOKUP_DSCR(TR.TR_SOCIAL_MEDIA_SPEC) AS TR_SOCIAL_MEDIA_SPEC_DSCR
	, TR.TR_SOCIAL_MEDIA_SPEC_OTHR
	, CASE WHEN TR.TR_OTHER = '1' THEN 'Yes' ELSE 'No' END AS TR_OTHER
	, TR.TR_OTHER_SPEC

	, SCA.SCA_SO_SIG
	, SCA.SCA_SO_SIG_DT
	, SCA.SCA_CLASS_SPEC_SIG
	, SCA.SCA_CLASS_SPEC_SIG_DT
	, SCA.SCA_STAFF_SIG
	, SCA.SCA_STAFF_SIG_DT

FROM
	REQUEST R
	LEFT OUTER JOIN STRATCON_GEN SG ON SG.SG_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN POSITION POS ON POS.POS_REQ_ID = R.REQ_ID
	--LEFT OUTER JOIN STRATCON_SCHED_HIST SSH ON SSH.SSH_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN AREAS_OF_CONS AOC ON AOC.AOC_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN SME_INFO SME ON SME.SME_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN JOB_ANALYSIS JA ON JA.JA_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN RECRUIT_INCENTIVES RI ON RI.RI_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN TARGET_RECRUIT TR ON TR.TR_REQ_ID = R.REQ_ID
	LEFT OUTER JOIN APPROVALS SCA ON SCA.SCA_REQ_ID = R.REQ_ID

	--LEFT OUTER JOIN ADMIN_CODES LU_AC ON LU_AC.AC_ID = SG.SG_AC_ID
	--LEFT OUTER JOIN ADMIN_CODES LU_AC ON LU_AC.AC_ADMIN_CD = SG.SG_ADMIN_CD
	--LEFT OUTER JOIN ADMIN_CODES LU_SO_1 ON LU_SO_1.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 1)
	--LEFT OUTER JOIN ADMIN_CODES LU_SO_2 ON LU_SO_2.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 2)
	--LEFT OUTER JOIN ADMIN_CODES LU_SO_3 ON LU_SO_3.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 3)
	--LEFT OUTER JOIN ADMIN_CODES LU_SO_4 ON LU_SO_4.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 4)
	--LEFT OUTER JOIN ADMIN_CODES LU_SO_5 ON LU_SO_5.AC_ADMIN_CD = FN_GET_SUBORG_CD(SG.SG_ADMIN_CD, 5)
    
	--LEFT OUTER JOIN TBL_LOOKUP LU_RT ON LU_RT.TBL_ID = SG.SG_RT_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_CT ON LU_CT.TBL_ID = SG.SG_CT_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_AT ON LU_AT.TBL_ID = SG.SG_AT_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_VT ON LU_VT.TBL_ID = SG.SG_VT_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_SAT ON LU_SAT.TBL_ID = SG.SG_SAT_ID
    
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMSO ON LU_MEMSO.MEMBERID = SG.SG_SO_ID
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMXO ON LU_MEMXO.MEMBERID = SG.SG_XO_ID
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMHL ON LU_MEMHL.MEMBERID = SG.SG_HRL_ID
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMSS ON LU_MEMSS.MEMBERID = SG.SG_SS_ID
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMCS ON LU_MEMCS.MEMBERID = SG.SG_CS_ID

	--LEFT OUTER JOIN TBL_LOOKUP LU_PYPL ON LU_PYPL.TBL_ID = POS.POS_PAY_PLAN_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_MO ON LU_MO.TBL_ID = POS.POS_MED_OFFICERS_ID
--TODO: Remove TO_NUMBER call once the data type of POS_SUPERVISORY is fixed to NUMBER(20)
	--LEFT OUTER JOIN TBL_LOOKUP LU_SUP ON LU_SUP.TBL_ID = TO_NUMBER(POS.POS_SUPERVISORY)
	--LEFT OUTER JOIN LOCATION LU_LOC ON LU_LOC.LOC_ID = POS.POS_LOCATION
	--LEFT OUTER JOIN BIZFLOW.MEMBER LU_MEMRS ON LU_MEMRS.MEMBERID = POS.POS_REPORT_SUPERVISOR
	--LEFT OUTER JOIN TBL_LOOKUP LU_ADT ON LU_ADT.TBL_ID = POS.POS_AT_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_WSCHD ON LU_WSCHD.TBL_ID = POS.POS_WORK_SCHED_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_SEC ON LU_SEC.TBL_ID = POS.POS_SEC_ID
	--LEFT OUTER JOIN TBL_LOOKUP LU_FNTP ON LU_FNTP.TBL_ID = POS.POS_CE_FINANCIAL_TYPE_ID
;
