
REM INSERTING into HHS_CMS_HR.TBL_LOOKUP
SET DEFINE OFF;

--Conduct,investigation issue case type final actions.
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (905,0,'ERLRCasesCompletedFinalAction','No Misconduct Found','No Misconduct Found','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (906,0,'ERLRCasesCompletedFinalAction','Coaching','Coaching','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (907,0,'ERLRCasesCompletedFinalAction','Demotion','Demotion','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (908,0,'ERLRCasesCompletedFinalAction','Leave Denied','Leave Denied','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (909,0,'ERLRCasesCompletedFinalAction','Oral Counseling','Oral Counseling','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (910,0,'ERLRCasesCompletedFinalAction',' Written Counseling',' Written Counseling','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (911,0,'ERLRCasesCompletedFinalAction','Removal','Removal','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (912,0,'ERLRCasesCompletedFinalAction','Reprimand','Reprimand','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (913,0,'ERLRCasesCompletedFinalAction','Short-Term Suspension','Short-Term Suspension','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (914,0,'ERLRCasesCompletedFinalAction','Long-Term Suspension','Long-Term Suspension','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (915,0,'ERLRCasesCompletedFinalAction','Termination','Termination','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (916,0,'ERLRCasesCompletedFinalAction','No Action Taken','No Action Taken','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));


--Performance Issue case type final actions
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (917,0,'ERLRCasesCompletedPerformanceFinalAction','Career Ladder Promotion Denied','Career Ladder Promotion Denied','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (918,0,'ERLRCasesCompletedPerformanceFinalAction','Career Ladder Promotion Granted','Career Ladder Promotion Granted','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (919,0,'ERLRCasesCompletedPerformanceFinalAction','Career Ladder Promotion Withheld','Career Ladder Promotion Withheld','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (920,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Placed on PIP','Employee Placed on PIP','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (921,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Successfully Completed PIP','Employee Successfully Completed PIP','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (922,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Failed PIP: Removal','Employee Failed PIP: Removal','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (923,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Failed PIP: Demotion','Employee Failed PIP: Demotion','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (924,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Failed PIP: Reassignment','Employee Failed PIP: Reassignment','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (925,0,'ERLRCasesCompletedPerformanceFinalAction','Employee Reassigned to Stand-Alone Position','Employee Reassigned to Stand-Alone Position','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (926,0,'ERLRCasesCompletedPerformanceFinalAction','EOY Written Narrative Reviewed','EOY Written Narrative Reviewed','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (927,0,'ERLRCasesCompletedPerformanceFinalAction','Midyear Written Narrative Reviewed ','Midyear Written Narrative Reviewed ','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (928,0,'ERLRCasesCompletedPerformanceFinalAction','WIGI Delayed','WIGI Delayed','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (929,0,'ERLRCasesCompletedPerformanceFinalAction','WIGI Withheld','WIGI Withheld','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Insert into HHS_CMS_HR.TBL_LOOKUP (TBL_ID,TBL_PARENT_ID,TBL_LTYPE,TBL_NAME,TBL_LABEL,TBL_ACTIVE,TBL_DISP_ORDER,TBL_MANDATORY,TBL_REGION,TBL_CATEGORY,TBL_EFFECTIVE_DT,TBL_EXPIRATION_DT) values (930,0,'ERLRCasesCompletedPerformanceFinalAction','WIGI Denied','WIGI Denied','1',null,'N',null,null,to_date('01-JAN-17','DD-MON-RR'),to_date('01-JAN-50','DD-MON-RR'));
Commit;
--When cast type is
