
SET DEFINE OFF;


DROP INDEX TBL_FORM_DTL_NK1
;

-- inspect duplicate records
WITH D AS (
	SELECT PROCID, COUNT(PROCID) CNT
	FROM TBL_FORM_DTL
	GROUP BY PROCID
) 
SELECT ID, PROCID
FROM TBL_FORM_DTL 
WHERE PROCID IN (SELECT PROCID FROM D WHERE D.CNT > 1)
ORDER BY PROCID, ID
;

-- delete duplicate records
DELETE TBL_FORM_DTL 
WHERE ID IN (
	SELECT MIN(ID) AS ID FROM TBL_FORM_DTL
	WHERE PROCID IN (
		SELECT D.PROCID 
		FROM (
			SELECT PROCID, COUNT(PROCID) CNT
			FROM TBL_FORM_DTL
			GROUP BY PROCID
		) D
		WHERE D.CNT > 1
	)
	GROUP BY PROCID
	--ORDER BY ID
)
;

CREATE UNIQUE INDEX TBL_FORM_DTL_UK1 ON TBL_FORM_DTL (PROCID)
;
