
GRANT SELECT, UPDATE ON HHS_CMS_HR.UG_MAPPING TO BIZFLOW;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_NAME TO BIZFLOW;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_KEY TO BIZFLOW;

-- privilege for HHS_CMS_HR_RW_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.UG_MAPPING TO HHS_CMS_HR_RW_ROLE;

GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_NAME TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_KEY TO HHS_CMS_HR_RW_ROLE;

-- privilege for HHS_CMS_HR_DEV_ROLE;
GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.UG_MAPPING TO HHS_CMS_HR_DEV_ROLE;

GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_NAME TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_USER_GROUP_KEY TO HHS_CMS_HR_DEV_ROLE;

