SET DEFINE OFF ;



ALTER TABLE CLASSIF_STRATCON ADD (
	SO_ID NVARCHAR2(10)
	, SO_TITLE NVARCHAR2(50)
	, SO_ORG NVARCHAR2(50)
	, XO_ID NVARCHAR2(10)
	, XO_TITLE NVARCHAR2(50)
	, XO_ORG NVARCHAR2(50)
	, HRL_ID NVARCHAR2(10)
	, HRL_TITLE NVARCHAR2(50)
	, HRL_ORG NVARCHAR2(50)
	, SS_ID NVARCHAR2(10)
	, CS_ID NVARCHAR2(10)
);

COMMENT ON COLUMN CLASSIF_STRATCON.SO_ID IS 'Selecting Official ID';
COMMENT ON COLUMN CLASSIF_STRATCON.SO_TITLE IS 'Selecting Official Title';
COMMENT ON COLUMN CLASSIF_STRATCON.SO_ORG IS 'Selecting Official Organization';
COMMENT ON COLUMN CLASSIF_STRATCON.XO_ID IS 'Executive Officer ID';
COMMENT ON COLUMN CLASSIF_STRATCON.XO_TITLE IS 'Executive Officer Title';
COMMENT ON COLUMN CLASSIF_STRATCON.XO_ORG IS 'Executive Officer Organization';
COMMENT ON COLUMN CLASSIF_STRATCON.HRL_ID IS 'HR Liaison ID';
COMMENT ON COLUMN CLASSIF_STRATCON.HRL_TITLE IS 'HR Liaison Title';
COMMENT ON COLUMN CLASSIF_STRATCON.HRL_ORG IS 'HR Liaison Organization';
COMMENT ON COLUMN CLASSIF_STRATCON.SS_ID IS 'HR Staffing Specialist ID';
COMMENT ON COLUMN CLASSIF_STRATCON.CS_ID IS 'HR Classification Specialist ID';

/