---------------------------------------------
-- POSITION table - data type change for POS_GRADE_1 through 5, POS_PERFORMANCE_LEVEL
---------------------------------------------

ALTER TABLE POSITION ADD POS_GRADE_1_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_GRADE_1_TEMP = TO_CHAR(POS_GRADE_1);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_GRADE_1;

ALTER TABLE POSITION RENAME COLUMN POS_GRADE_1_TEMP TO POS_GRADE_1;

COMMENT ON COLUMN POSITION.POS_GRADE_1 IS 'Grade #1';




ALTER TABLE POSITION ADD POS_GRADE_2_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_GRADE_2_TEMP = TO_CHAR(POS_GRADE_2);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_GRADE_2;

ALTER TABLE POSITION RENAME COLUMN POS_GRADE_2_TEMP TO POS_GRADE_2;

COMMENT ON COLUMN POSITION.POS_GRADE_2 IS 'Grade #2';




ALTER TABLE POSITION ADD POS_GRADE_3_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_GRADE_3_TEMP = TO_CHAR(POS_GRADE_3);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_GRADE_3;

ALTER TABLE POSITION RENAME COLUMN POS_GRADE_3_TEMP TO POS_GRADE_3;

COMMENT ON COLUMN POSITION.POS_GRADE_3 IS 'Grade #3';





ALTER TABLE POSITION ADD POS_GRADE_4_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_GRADE_4_TEMP = TO_CHAR(POS_GRADE_4);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_GRADE_4;

ALTER TABLE POSITION RENAME COLUMN POS_GRADE_4_TEMP TO POS_GRADE_4;

COMMENT ON COLUMN POSITION.POS_GRADE_4 IS 'Grade #4';




ALTER TABLE POSITION ADD POS_GRADE_5_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_GRADE_5_TEMP = TO_CHAR(POS_GRADE_5);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_GRADE_5;

ALTER TABLE POSITION RENAME COLUMN POS_GRADE_5_TEMP TO POS_GRADE_5;

COMMENT ON COLUMN POSITION.POS_GRADE_5 IS 'Grade #5';




ALTER TABLE POSITION ADD POS_PERFORMANCE_LEVEL_TEMP NVARCHAR2(2);

UPDATE POSITION SET POS_PERFORMANCE_LEVEL_TEMP = TO_CHAR(POS_PERFORMANCE_LEVEL);
COMMIT;

ALTER TABLE POSITION DROP COLUMN POS_PERFORMANCE_LEVEL;

ALTER TABLE POSITION RENAME COLUMN POS_PERFORMANCE_LEVEL_TEMP TO POS_PERFORMANCE_LEVEL;

COMMENT ON COLUMN POSITION.POS_PERFORMANCE_LEVEL IS 'Full Performance Level';




---------------------------------------------
-- CLASSIF_STRATCON table - data type change for CS_GR_ID_1 through 5, CS_PERFORMANCE_LEVEL
---------------------------------------------

ALTER TABLE CLASSIF_STRATCON ADD CS_GR_ID_1_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_GR_ID_1_TEMP = TO_CHAR(CS_GR_ID_1);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_GR_ID_1;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_GR_ID_1_TEMP TO CS_GR_ID_1;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_1 IS 'Grade #1';




ALTER TABLE CLASSIF_STRATCON ADD CS_GR_ID_2_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_GR_ID_2_TEMP = TO_CHAR(CS_GR_ID_2);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_GR_ID_2;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_GR_ID_2_TEMP TO CS_GR_ID_2;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_2 IS 'Grade #2';




ALTER TABLE CLASSIF_STRATCON ADD CS_GR_ID_3_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_GR_ID_3_TEMP = TO_CHAR(CS_GR_ID_3);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_GR_ID_3;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_GR_ID_3_TEMP TO CS_GR_ID_3;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_3 IS 'Grade #3';




ALTER TABLE CLASSIF_STRATCON ADD CS_GR_ID_4_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_GR_ID_4_TEMP = TO_CHAR(CS_GR_ID_4);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_GR_ID_4;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_GR_ID_4_TEMP TO CS_GR_ID_4;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_4 IS 'Grade #4';




ALTER TABLE CLASSIF_STRATCON ADD CS_GR_ID_5_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_GR_ID_5_TEMP = TO_CHAR(CS_GR_ID_5);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_GR_ID_5;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_GR_ID_5_TEMP TO CS_GR_ID_5;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_GR_ID_5 IS 'Grade #5';




ALTER TABLE CLASSIF_STRATCON ADD CS_PERFORMANCE_LEVEL_TEMP NVARCHAR2(2);

UPDATE CLASSIF_STRATCON SET CS_PERFORMANCE_LEVEL_TEMP = TO_CHAR(CS_PERFORMANCE_LEVEL);
COMMIT;

ALTER TABLE CLASSIF_STRATCON DROP COLUMN CS_PERFORMANCE_LEVEL;

ALTER TABLE CLASSIF_STRATCON RENAME COLUMN CS_PERFORMANCE_LEVEL_TEMP TO CS_PERFORMANCE_LEVEL;

COMMENT ON COLUMN CLASSIF_STRATCON.CS_PERFORMANCE_LEVEL IS 'Full Performance Level';





---------------------------------------
-- report table data conversion
---------------------------------------

UPDATE POSITION SET POS_GRADE_1 = (CASE WHEN LENGTH(POS_GRADE_1) = 1 THEN '0' || POS_GRADE_1 ELSE POS_GRADE_1 END);
UPDATE POSITION SET POS_GRADE_2 = (CASE WHEN LENGTH(POS_GRADE_2) = 1 THEN '0' || POS_GRADE_2 ELSE POS_GRADE_2 END);
UPDATE POSITION SET POS_GRADE_3 = (CASE WHEN LENGTH(POS_GRADE_3) = 1 THEN '0' || POS_GRADE_3 ELSE POS_GRADE_3 END);
UPDATE POSITION SET POS_GRADE_4 = (CASE WHEN LENGTH(POS_GRADE_4) = 1 THEN '0' || POS_GRADE_4 ELSE POS_GRADE_4 END);
UPDATE POSITION SET POS_GRADE_5 = (CASE WHEN LENGTH(POS_GRADE_5) = 1 THEN '0' || POS_GRADE_5 ELSE POS_GRADE_5 END);
UPDATE POSITION SET POS_PERFORMANCE_LEVEL = (CASE WHEN LENGTH(POS_PERFORMANCE_LEVEL) = 1 THEN '0' || POS_PERFORMANCE_LEVEL ELSE POS_PERFORMANCE_LEVEL END);
COMMIT;

UPDATE CLASSIF_STRATCON SET CS_GR_ID_1 = (CASE WHEN LENGTH(CS_GR_ID_1) = 1 THEN '0' || CS_GR_ID_1 ELSE CS_GR_ID_1 END);
UPDATE CLASSIF_STRATCON SET CS_GR_ID_2 = (CASE WHEN LENGTH(CS_GR_ID_2) = 1 THEN '0' || CS_GR_ID_2 ELSE CS_GR_ID_2 END);
UPDATE CLASSIF_STRATCON SET CS_GR_ID_3 = (CASE WHEN LENGTH(CS_GR_ID_3) = 1 THEN '0' || CS_GR_ID_3 ELSE CS_GR_ID_3 END);
UPDATE CLASSIF_STRATCON SET CS_GR_ID_4 = (CASE WHEN LENGTH(CS_GR_ID_4) = 1 THEN '0' || CS_GR_ID_4 ELSE CS_GR_ID_4 END);
UPDATE CLASSIF_STRATCON SET CS_GR_ID_5 = (CASE WHEN LENGTH(CS_GR_ID_5) = 1 THEN '0' || CS_GR_ID_5 ELSE CS_GR_ID_5 END);
UPDATE CLASSIF_STRATCON SET CS_PERFORMANCE_LEVEL = (CASE WHEN LENGTH(CS_PERFORMANCE_LEVEL) = 1 THEN '0' || CS_PERFORMANCE_LEVEL ELSE CS_PERFORMANCE_LEVEL END);
COMMIT;
