

GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.TBL_FORM_DTL_AUDIT TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_GRADE_ADVRT TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_NOT_REQ TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_REQ TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_TYPE TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ASSESS_TYPE TO HHS_CMS_HR_RW_ROLE;


GRANT SELECT, INSERT, UPDATE, DELETE ON HHS_CMS_HR.TBL_FORM_DTL_AUDIT TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_GRADE_ADVRT TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_NOT_REQ TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_REQ TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ANNOUNCE_TYPE TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_ASSESS_TYPE TO HHS_CMS_HR_DEV_ROLE;
