--------------------------------------------------------
--  DDL for View VW_LOOKUP
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "HHS_CMS_HR"."VW_LOOKUP" AS 
  SELECT 
   TBL_ID ID
   , TBL_PARENT_ID PARENTID
   , TBL_LTYPE LTYPE
   , TBL_NAME NAME
   , TBL_LABEL LABEL
   , TBL_ACTIVE ACTIVE
   , TBL_DISP_ORDER DISPORDER
   , TBL_CATEGORY CATEGORY
FROM HHS_CMS_HR.TBL_LOOKUP 
ORDER BY TBL_PARENT_ID, TBL_LTYPE, NVL(TBL_DISP_ORDER,0), UPPER(TBL_LABEL)
;
/

GRANT EXECUTE ON HHS_CMS_HR.FN_GET_2ND_SUB_ORG TO HHS_CMS_HR_RW_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_CASE_CATEGORY TO HHS_CMS_HR_RW_ROLE;

GRANT SELECT ON HHS_CMS_HR.VW_ERLR_CNDT_ISSUE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_APPEAL TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_WGI_DNL TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_MEDDOC TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_PERF_ISSUE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_INVESTIGATION TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_INFO_REQUEST TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_3RDPARTY_HEAR TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_PROB_ACTION TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_ULP TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_LABOR_NEGO TO HHS_CMS_HR_RW_ROLE;

GRANT SELECT ON HHS_CMS_HR.ERLR_CASE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_GEN TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_CNDT_ISSUE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_APPEAL TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_WGI_DNL TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_MEDDOC TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_PERF_ISSUE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_INVESTIGATION TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_INFO_REQUEST TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_3RDPARTY_HEAR TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_PROB_ACTION TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_GRIEVANCE TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_ULP TO HHS_CMS_HR_RW_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_LABOR_NEGO TO HHS_CMS_HR_RW_ROLE;


GRANT EXECUTE ON HHS_CMS_HR.FN_GET_2ND_SUB_ORG TO HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.FN_GET_CASE_CATEGORY TO HHS_CMS_HR_DEV_ROLE;

GRANT SELECT ON HHS_CMS_HR.VW_ERLR_CNDT_ISSUE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_APPEAL TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_WGI_DNL TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_MEDDOC TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_PERF_ISSUE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_INVESTIGATION TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_INFO_REQUEST TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_3RDPARTY_HEAR TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_PROB_ACTION TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_GRIEVANCE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_ULP TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.VW_ERLR_LABOR_NEGO TO HHS_CMS_HR_DEV_ROLE;

GRANT SELECT ON HHS_CMS_HR.ERLR_CASE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_GEN TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_CNDT_ISSUE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_APPEAL TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_WGI_DNL TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_MEDDOC TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_PERF_ISSUE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_INVESTIGATION TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_INFO_REQUEST TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_3RDPARTY_HEAR TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_PROB_ACTION TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_GRIEVANCE TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_ULP TO HHS_CMS_HR_DEV_ROLE;
GRANT SELECT ON HHS_CMS_HR.ERLR_LABOR_NEGO TO HHS_CMS_HR_DEV_ROLE;
