
---------------------
-- Grant access to SP_UPDATE_STRATCONHIST_TABLE
---------------------

-- privilege for HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.SP_UPDATE_STRATCONHIST_TABLE TO HHS_CMS_HR_RW_ROLE;

-- privilege for HHS_CMS_HR_DEV_ROLE;
GRANT EXECUTE ON HHS_CMS_HR.SP_UPDATE_STRATCONHIST_TABLE TO HHS_CMS_HR_DEV_ROLE;
