

-------------------------------------
-- STRATCON_GEN table changes
-------------------------------------
ALTER TABLE STRATCON_GEN ADD SG_AT_ID NUMBER(20)
;
COMMENT ON COLUMN STRATCON_GEN.SG_AT_ID IS 'Appointment Type ID'
;
ALTER TABLE STRATCON_GEN ADD SG_VT_ID NUMBER(20)
;
COMMENT ON COLUMN STRATCON_GEN.SG_VT_ID IS 'Volunteer Type ID'
;
ALTER TABLE STRATCON_GEN ADD SG_SAT_ID NUMBER(20)
;
COMMENT ON COLUMN STRATCON_GEN.SG_SAT_ID IS 'Schedule A Type ID'
;



-------------------------------------
-- POSITION table changes
-------------------------------------
ALTER TABLE POSITION ADD POS_CNDT_LAST_NM NVARCHAR2(50)
;
COMMENT ON COLUMN POSITION.POS_CNDT_LAST_NM IS 'Candidate/Selectee Last Name'
;
ALTER TABLE POSITION ADD POS_CNDT_FIRST_NM NVARCHAR2(50)
;
COMMENT ON COLUMN POSITION.POS_CNDT_FIRST_NM IS 'Candidate/Selectee First Name'
;
ALTER TABLE POSITION ADD POS_BGT_APR_OFM CHAR(1)
;
COMMENT ON COLUMN POSITION.POS_BGT_APR_OFM IS 'Budget Approved by OFM?'
;



---------------------
-- ADMIN CODE source change
---------------------

ALTER TABLE CLASSIF_STRATCON ADD CS_ADMIN_CD NVARCHAR2(8)
;
COMMENT ON COLUMN CLASSIF_STRATCON.CS_ADMIN_CD IS 'Admin Code'
;

ALTER TABLE STRATCON_GEN ADD SG_ADMIN_CD NVARCHAR2(8)
;
COMMENT ON COLUMN STRATCON_GEN.SG_ADMIN_CD IS 'Admin Code'
;
