--------------------------------------------------------
--  DDL for VW_ERLR_PROB_ACTION
--------------------------------------------------------
CREATE OR REPLACE VIEW VW_ERLR_PROB_ACTION
AS
SELECT
    PA.ERLR_CASE_NUMBER
    , EC.ERLR_JOB_REQ_NUMBER
    , EC.PROCID    
    , EC.ERLR_CASE_CREATE_DT
    , PPA_ACTION_TYPE
	, PPA_TERMINATION_TYPE
	, PPA_TERM_PROP_ACTION_DT
	, CASE WHEN PPA_TERM_ORAL_PREZ_REQUESTED = '1'  THEN 'Yes' ELSE 'No' END AS PPA_TERM_ORAL_PREZ_REQUESTED
	, PPA_TERM_ORAL_PREZ_DT
	, CASE WHEN PPA_TERM_WRITTEN_RESP = '1'  THEN 'Yes' ELSE 'No' END AS PPA_TERM_WRITTEN_RESP
	, PPA_TERM_WRITTEN_RESP_DUE_DT
	, PPA_TERM_WRITTEN_RESP_DT
	, PPA_TERM_AGENCY_DECISION	
    , (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = PPA_TERM_DECIDING_OFFCL_NAME AND ROWNUM = 1) AS PPA_TERM_DECIDING_OFFCL_NAME
	, PPA_TERM_DECISION_ISSUED_DT
	, PPA_TERM_EFFECTIVE_DECISION_DT
	, PPA_PROB_TERM_DCSN_ISSUED_DT
	, CASE WHEN PPA_PROBATION_CONDUCT = '1'  THEN 'Yes' ELSE 'No' END AS PPA_PROBATION_CONDUCT
	, CASE WHEN PPA_PROBATION_PERFORMANCE = '1'  THEN 'Yes' ELSE 'No' END AS PPA_PROBATION_PERFORMANCE
	, PPA_APPEAL_GRIEVANCE_DEADLINE
	, CASE WHEN PPA_EMP_APPEAL_DECISION = '1'  THEN 'Yes' ELSE 'No' END AS PPA_EMP_APPEAL_DECISION
	, PPA_PROP_ACTION_ISSUED_DT
	, CASE WHEN PPA_ORAL_PREZ_REQUESTED = '1'  THEN 'Yes' ELSE 'No' END AS PPA_ORAL_PREZ_REQUESTED
	, PPA_ORAL_PREZ_DT
	, CASE WHEN PPA_ORAL_RESPONSE_SUBMITTED = '1'  THEN 'Yes' ELSE 'No' END AS PPA_ORAL_RESPONSE_SUBMITTED
	, PPA_RESPONSE_DUE_DT
	, PPA_WRITTEN_RESPONSE_SBMT_DT
	, PPA_POS_TITLE
	, PPA_PPLAN
	, PPA_SERIES
	, PPA_CURRENT_INFO_GRADE
	, PPA_CURRENT_INFO_STEP
	, PPA_PROPOSED_POS_TITLE
	, PPA_PROPOSED_PPLAN
	, PPA_PROPOSED_SERIES
	, PPA_PROPOSED_INFO_GRADE
	, PPA_PROPOSED_INFO_STEP
	, PPA_FINAL_POS_TITLE
	, PPA_FINAL_PPLAN
	, PPA_FINAL_SERIES
	, PPA_FINAL_INFO_GRADE
	, PPA_FINAL_INFO_STEP
	, PPA_NOTICE_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_DECISION
	, (SELECT M.NAME FROM BIZFLOW.MEMBER M WHERE M.MEMBERID = PPA_DECIDING_OFFCL AND ROWNUM = 1) AS PPA_DECIDING_OFFCL
	, PPA_DECISION_ISSUED_DT
	, PPA_DEMO_FINAL_AGENCY_EFF_DT
	, PPA_NUMB_DAYS
	, PPA_EFFECTIVE_DT
	, PPA_CURRENT_ADMIN_CODE
	, PPA_RE_ASSIGNMENT_CURR_ORG
	, PPA_FINAL_ADMIN_CODE
	, PPA_FINAL_ADMIN_CODE_FINAL_ORG
FROM
	ERLR_PROB_ACTION PA
    LEFT OUTER JOIN ERLR_CASE EC ON PA.ERLR_CASE_NUMBER = EC.ERLR_CASE_NUMBER
;
/